Order missing fields first in a desc sort (#2174)
DataBiosphere/azul pull request #2224
Opened 2020-09-02 16:51 UTC by danielsotirhos

Author (before primary review)

- [ ] PR title references issue
- [ ] Title of main commit references issue
- [ ] PR is linked to Zenhub issue
- [ ] Added `HCA` label <sub>or this PR does not target an `hca/*` branch</sub>
- [ ] Created issue to track porting these changes <sub>or this PR does not need porting</sub> 
- [ ] Added `[r]` prefix at start of commit title <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label <sub>or this PR does not require reindexing</sub>
- [ ] Freebies are blocked on this PR <sub>or there are no freebies in this PR</sub>
- [ ] Freebies are referenced in commit titles <sub>or there are no freebies in this PR</sub>
- [ ] This PR is blocked by previous PR in chain <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chain` label to the blocking PR <sub>or this PR is not chained to another PR</sub>
- [ ] Ran `make update_requirements` <sub>or this PR does not change requirements*.txt</sub>
- [ ] Mentioned `make requirements` in UPGRADING.rst <sub>or this PR does not change requirements*.txt</sub>
- [ ] Documented upgrade of personal deployments in UPGRADING.rst <sub>or this PR does not require upgrading</sub>

Primary reviewer (before pushing merge commit)

- [ ] Checked `reindex` label and `[r]` prefix of commit title
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Build passes in `sandbox` <sub>or commented that sandbox will be skipped</sub>
- [ ] Reindexed `sandbox` <sub>or this PR does not require reindexing</sub>
- [ ] Added PR reference to merge commit

Primary reviewer (after pushing merge commit)

- [ ] Moved linked issue to Merged
- [ ] Pushed merge commit to Github
- [ ] Moved freebies to Merged column <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened chain <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [ ] Commented on demo expectations <sub>or labeled as `no demo`</sub>
- [ ] Pushed merge commit to Gitlab
- [ ] Reindexed `dev` <sub>or this PR does not require reindexing</sub>
- [ ] Deleted PR branch from Github and Gitlab
- [ ] Unassign reviewer from PR

2020-09-02 19:31 UTC, amarjandu approved these changes

2020-09-04 19:04 UTC, hannes-ucsc requested changes

2020-09-04 19:04 UTC, hannes-ucsc commented on test/service/test_response.py
> +        def _test(order, expected_values):
same as in other PR.

2020-09-09 06:09 UTC, hannes-ucsc requested changes
Has conflicts. No bump.

2020-09-10 00:44 UTC, hannes-ucsc approved these changes

2020-09-10 00:44 UTC, hannes-ucsc commented on test/service/test_response.py
> +            None,  # that there is a hit however it has no 'cellLineType'.
```suggestion
            None,  # that there is a hit but that it has no 'cellLineType'.
```

Unless your form is grammatically correct. Not sure though.

2020-09-10 03:32 UTC, merged

2020-09-10 03:34 UTC, hannes-ucsc commented
For demo attempt to reproduce #2174.