Log entity ids before querying in TDR plugin (#2265)
DataBiosphere/azul pull request #2272
Opened 2020-09-16 00:48 UTC by noah-aviel-dove

Author (before primary review)

- [ ] PR title references issue
- [ ] Title of main commit references issue
- [ ] PR is linked to Zenhub issue
- [ ] Added `HCA` label <sub>or this PR does not target an `hca/*` branch</sub>
- [ ] Created issue to track porting these changes <sub>or this PR does not need porting</sub> 
- [ ] Added `[r]` prefix at start of commit title <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label <sub>or this PR does not require reindexing</sub>
- [ ] Freebies are blocked on this PR <sub>or there are no freebies in this PR</sub>
- [ ] Freebies are referenced in commit titles <sub>or there are no freebies in this PR</sub>
- [ ] This PR is blocked by previous PR in chain <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chain` label to the blocking PR <sub>or this PR is not chained to another PR</sub>
- [ ] Ran `make requirements_update` <sub>or this PR does not change requirements*.txt</sub>
- [ ] Mentioned `make requirements` in UPGRADING.rst <sub>or this PR does not change requirements*.txt</sub>
- [ ] Documented upgrade of personal deployments in UPGRADING.rst <sub>or this PR does not require upgrading</sub>

Primary reviewer (before pushing merge commit)

- [ ] Checked `reindex` label and `[r]` prefix of commit title
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Build passes in `sandbox` <sub>or commented that sandbox will be skipped</sub>
- [ ] Reindexed `sandbox` <sub>or this PR does not require reindexing</sub>
- [ ] Added PR reference to merge commit

Primary reviewer (after pushing merge commit)

- [ ] Moved linked issue to Merged
- [ ] Pushed merge commit to Github
- [ ] Moved freebies to Merged column <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened chain <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [ ] Commented on demo expectations <sub>or labeled as `no demo`</sub>
- [ ] Pushed merge commit to Gitlab
- [ ] Reindexed `dev` <sub>or this PR does not require reindexing</sub>
- [ ] Deleted PR branch from Github and Gitlab
- [ ] Unassign reviewer from PR

2020-09-16 15:52 UTC, achave11 approved these changes
LGTM!

2020-09-17 04:40 UTC, hannes-ucsc requested changes

2020-09-17 04:40 UTC, hannes-ucsc commented on src/azul/plugins/repository/tdr/__init__.py
> +            log.info('Retrieving %s %s entities...', len(entity_ids), entity_type)
```suggestion
            log.info('Retrieving %i entities of type %r ...', len(entity_ids), entity_type)
```

similarly for the log message at the conclusion of this method.

2020-09-17 09:58 UTC, noah-aviel-dove commented
We could also use [azul.strings.pluralize](https://github.com/DataBiosphere/azul/blob/c99bd3d66559712e2926e6c5853587c03b86c5b1/src/azul/strings.py#L25) here if we want to be strict about grammar. But my feeling is that this isn't importan when the text doesn't end getting displayed in the service.

2020-09-17 17:19 UTC, hannes-ucsc approved these changes

2020-09-17 17:24 UTC, hannes-ucsc commented
I agree.

2020-09-17 19:40 UTC, merged

2020-09-17 19:44 UTC, hannes-ucsc commented
For demo show log message in CloudWatch for `dev` deployment.