Move total_estimated_cells from contents to top level (#2298)
DataBiosphere/azul pull request #2348
Opened 2020-10-13 16:27 UTC by danielsotirhos

Author (before primary review)

- [ ] PR title references issue
- [ ] Title of main commit references issue
- [ ] PR is linked to Zenhub issue
- [ ] Added `DCP/1` label <sub>or this PR does not target an `hca/*` branch</sub>
- [ ] Created issue to track porting these changes <sub>or this PR does not need porting</sub> 
- [ ] Added `[r]` prefix at start of commit title <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label <sub>or this PR does not require reindexing</sub>
- [ ] Freebies are blocked on this PR <sub>or there are no freebies in this PR</sub>
- [ ] Freebies are referenced in commit titles <sub>or there are no freebies in this PR</sub>
- [ ] This PR is blocked by previous PR in chain <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chain` label to the blocking PR <sub>or this PR is not chained to another PR</sub>
- [ ] Ran `make requirements_update` <sub>or this PR does not change requirements*.txt</sub>
- [ ] Mentioned `make requirements` in UPGRADING.rst <sub>or this PR does not change requirements*.txt</sub>
- [ ] Documented upgrade of personal deployments in UPGRADING.rst <sub>or this PR does not require upgrading</sub>
- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>

Primary reviewer (before pushing merge commit)

- [ ] Checked `reindex` label and `[r]` prefix of commit title
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Build passes in `sandbox` <sub>or added `no sandbox` label</sub>
- [ ] Reindexed `sandbox` <sub>or this PR does not require reindexing</sub>
- [ ] Added PR reference to merge commit
- [ ] Moved linked issue to Merged
- [ ] Pushed merge commit to Github

Primary reviewer (after pushing merge commit)

- [ ] Moved freebies to Merged column <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened chain <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [ ] Commented on demo expectations <sub>or labeled as `no demo`</sub>
- [ ] Pushed merge commit to Gitlab <sub>or this changes can be pushed later, together with another PR</sub>
- [ ] Reindexed `dev` <sub>or this PR does not require reindexing</sub>
- [ ] Deleted PR branch from Github and Gitlab
- [ ] Unassign reviewer from PR

2020-10-14 22:34 UTC, jessebrennan approved these changes
This looks good to me :+1:

2020-10-16 06:35 UTC, hannes-ucsc requested changes
We worked so hard on the plug-in abstraction, we're not going to throw that away by reintroducing HCA specifics into the indexer.

2020-10-16 06:35 UTC, hannes-ucsc commented on src/azul/indexer/document.py
> +    total_estimated_cells: int
This is an HCA specific that must be isolated in the plugin.

2020-10-21 01:30 UTC, hannes-ucsc requested changes

2020-10-21 01:30 UTC, hannes-ucsc commented on src/azul/indexer/document_service.py
> +        aggregate_class = self.metadata_plugin(catalog).aggregate_class()
```suggestion
        aggregate_cls = self.metadata_plugin(catalog).aggregate_class()
```

2020-10-21 01:30 UTC, hannes-ucsc commented on src/azul/indexer/index_service.py
> +            aggregate_class = self.metadata_plugin(entity.catalog).aggregate_class()
```suggestion
            aggregate_cls = self.metadata_plugin(entity.catalog).aggregate_class()
```

2020-10-21 01:30 UTC, hannes-ucsc commented on src/azul/indexer/transform.py
> -    def post_process_aggregate(cls, contents: MutableJSON) -> None:
Glad this is gone.

2020-10-21 01:30 UTC, hannes-ucsc commented on src/azul/plugins/__init__.py
> +    def aggregate_class(self) -> Type['Aggregate']:
```suggestion
    def aggregate_class(self) -> Type[Aggregate]:
```

https://www.python.org/dev/peps/pep-0484/#forward-references

2020-10-21 01:30 UTC, hannes-ucsc commented on src/azul/plugins/__init__.py
> +        Returns the MetadataPlugin specific Aggregate class
```suggestion
        Returns the concrete class to use for representing aggregate documents in the indexer.
```

and wrap properly

2020-10-21 01:30 UTC, hannes-ucsc commented on src/azul/plugins/metadata/hca/aggregate.py
> +        self.total_estimated_cells = self._total_estimated_cells()
Seems overly complicated. Can't you use our default mechanism for lazily computed values: @cached_property?

2020-10-21 01:30 UTC, hannes-ucsc commented on test/indexer/test_hca_indexer.py
> +        aggregate_class = self.metadata_plugin().aggregate_class()
```suggestion
        aggregate_cls = self.metadata_plugin().aggregate_class()
```

2020-10-21 01:30 UTC, hannes-ucsc commented on test/indexer/test_hca_indexer.py
> +    @lru_cache(maxsize=None)
It looks like you are uncertain when to use @cached_property and when to use @lru_cache. Feel free to ask after stand-up.

2020-10-27 17:59 UTC, hannes-ucsc requested changes

2020-10-27 17:59 UTC, hannes-ucsc commented on src/azul/indexer/document.py
> +                   coordinates: Optional[DocumentCoordinates[CataloguedEntityReference]] = None) -> 'Document':
```suggestion
                   *,
                   coordinates: Optional[DocumentCoordinates[CataloguedEntityReference]] = None) -> 'Document':
```

2020-10-27 17:59 UTC, hannes-ucsc commented on src/azul/indexer/index_service.py
> +            aggregate_cls = self.metadata_plugin(coordinate.entity.catalog).aggregate_class()
I think we should first collect all catalogs in a set and then iterate over that set to populate mandatory_source_fields. 

We may also want to extract `self.metadata_plugin(catalog).aggregate_class()` into a method and think about applying lru_cache to that method.

2020-10-27 17:59 UTC, hannes-ucsc commented on src/azul/indexer/index_service.py
>          return {
See if this fits into one line.

2020-10-27 17:59 UTC, hannes-ucsc commented on src/azul/plugins/metadata/hca/aggregate.py
> +        return {
Literal …

2020-10-27 17:59 UTC, hannes-ucsc commented on src/azul/plugins/metadata/hca/aggregate.py
> +        return dict(super().to_source(),
or `dict` constructor. Chose one. I think the latter.

2020-10-28 16:13 UTC, danielsotirhos commented
Please advise if you have an idea how this PyCharm warning could be resolved.
`aggregate_class()` is type hinted to return a `Type[Aggregate]` however PyCharm doesn't seem to understand.

![Screen Shot 2020-10-28 at 9 03 40 AM](https://user-images.githubusercontent.com/46407464/97463412-f53a5c80-18fc-11eb-9811-22cb11fc1835.png)

2020-10-28 23:56 UTC, hannes-ucsc approved these changes

2020-10-29 03:32 UTC, merged

2020-10-29 03:33 UTC, hannes-ucsc commented
For demo, show the field in the index, using Kibana, and demonstrate that existing functionality (sorting/filtering) is not impeded.

2020-10-29 17:03 UTC, hannes-ucsc commented
The reindex on dev had some issues caused by PR #2381 for #2330: 600 or so failed tallies. Nevertheless, this can still be demoed and closed.