Fix: nondeterministic parameter validation (#2336)
DataBiosphere/azul pull request #2359
Opened 2020-10-19 18:29 UTC by amarjandu

Author (before primary review)

- [ ] PR title references issue
- [ ] Title of main commit references issue
- [ ] PR is linked to Zenhub issue
- [ ] Added `DCP/1` label <sub>or this PR does not target an `hca/*` branch</sub>
- [ ] Created issue to track porting these changes <sub>or this PR does not need porting</sub> 
- [ ] Added `[r]` prefix at start of commit title <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label <sub>or this PR does not require reindexing</sub>
- [ ] Freebies are blocked on this PR <sub>or there are no freebies in this PR</sub>
- [ ] Freebies are referenced in commit titles <sub>or there are no freebies in this PR</sub>
- [ ] This PR is blocked by previous PR in chain <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chain` label to the blocking PR <sub>or this PR is not chained to another PR</sub>
- [ ] Ran `make requirements_update` <sub>or this PR does not change requirements*.txt</sub>
- [ ] Mentioned `make requirements` in UPGRADING.rst <sub>or this PR does not change requirements*.txt</sub>
- [ ] Documented upgrade of personal deployments in UPGRADING.rst <sub>or this PR does not require upgrading</sub>
- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>

Primary reviewer (before pushing merge commit)

- [ ] Checked `reindex` label and `[r]` prefix of commit title
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Build passes in `sandbox` <sub>or added `no sandbox` label</sub>
- [ ] Reindexed `sandbox` <sub>or this PR does not require reindexing</sub>
- [ ] Added PR reference to merge commit
- [ ] Moved linked issue to Merged
- [ ] Pushed merge commit to Github

Primary reviewer (after pushing merge commit)

- [ ] Moved freebies to Merged column <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened chain <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [ ] Commented on demo expectations <sub>or labeled as `no demo`</sub>
- [ ] Pushed merge commit to Gitlab <sub>or this changes can be pushed later, together with another PR</sub>
- [ ] Reindexed `dev` <sub>or this PR does not require reindexing</sub>
- [ ] Deleted PR branch from Github and Gitlab
- [ ] Unassign reviewer from PR

2020-10-19 18:30 UTC, amarjandu commented
Created this PR to see if the issue can be reproduced on develop within Travis.

2020-10-20 18:20 UTC, amarjandu commented
Was not able to replicate the test failures in the same way that #1465 was failing, but the change in the ordering for the query parameters can be observed when debugging tests.

2020-10-21 06:21 UTC, achave11 approved these changes
Looks good to me!

2020-10-21 22:50 UTC, hannes-ucsc commented on test/service/test_request_validation.py
> -        self.assertTrue(response.json() in [self.facet_message, self.facet_message])
@achave11 FYI

2020-10-21 22:52 UTC, hannes-ucsc reviewed
There was still some non-determinism left. Please review.

2020-10-21 22:53 UTC, hannes-ucsc commented
Review my changes, that is.

2020-10-22 18:23 UTC, amarjandu commented
@hannes-ucsc there are many short-circuits to a BadRequestError that escapes the collection of invalid_params. 

For some query parameters:

```python
        params = {
            'order': 'up',
            'size': '23',
            'sort': 'bad-facet',
            'filters': json.dumps({'organ': {'is': ['fake-val2']}}),
        }
```

In the suggested changes, the invalid `order` parameter would be collected however it will not be returned to the caller because of the validate_size BadRequestError that will occur.

Now if we start catching all the short circuits we could return an error message as seen in [RFC7807](https://tools.ietf.org/html/rfc7807#section-3)

This would allow us to consistently format the output that is sent back to the users, ensure that all the parameters are inspected, and provide insightful responses. 

The response could look something along the lines of: 

```js
{
    'invalid_parameters': [
        {
            'name': 'order',
            'value': 'up',
            'error': 'invalid'
        },
        {
            'name': 'size',
            'value': '23',
            'error': 'type'
        },
        {
            'name': 'sort',
            'value': 'bad-facet',
            'error': 'invalid'
        },
        { 
            'name': 'filter',
            'value': {'organ': {'is': ['fake-val2']}},
            'error': 'unknown relation value'
        },
    ]
}
```

2020-10-29 00:43 UTC, hannes-ucsc requested changes

2020-10-29 00:43 UTC, hannes-ucsc commented on lambdas/service/app.py
> +                raise BadRequestError(msg=f'Invalid input value for `{param_name}`')
```suggestion
                raise BadRequestError(msg=f'Invalid value for `{param_name}`')
```

2020-10-29 00:44 UTC, hannes-ucsc commented
No bump.

2020-10-30 01:07 UTC, hannes-ucsc approved these changes

2020-10-30 20:29 UTC, merged

2020-10-30 20:31 UTC, hannes-ucsc commented
For demo, show that validation still works by making requests with a missing, an extra and an invalid parameter, each. Show that multiples of those work, too.