Log error in IT when non expected hits are present (#2330)
DataBiosphere/azul pull request #2364
Opened 2020-10-19 21:37 UTC by achave11

Author (before primary review)

- [1 ] PR title references issue
- [ ] Title of main commit references issue
- [ ] PR is linked to Zenhub issue
- [ ] Added `DCP/1` label <sub>or this PR does not target an `hca/*` branch</sub>
- [ ] Created issue to track porting these changes <sub>or this PR does not need porting</sub> 
- [ ] Added `[r]` prefix at start of commit title <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label <sub>or this PR does not require reindexing</sub>
- [ ] Freebies are blocked on this PR <sub>or there are no freebies in this PR</sub>
- [ ] Freebies are referenced in commit titles <sub>or there are no freebies in this PR</sub>
- [ ] This PR is blocked by previous PR in chain <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chain` label to the blocking PR <sub>or this PR is not chained to another PR</sub>
- [ ] Ran `make requirements_update` <sub>or this PR does not change requirements*.txt</sub>
- [ ] Mentioned `make requirements` in UPGRADING.rst <sub>or this PR does not change requirements*.txt</sub>
- [ ] Documented upgrade of personal deployments in UPGRADING.rst <sub>or this PR does not require upgrading</sub>
- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>

Primary reviewer (before pushing merge commit)

- [ ] Checked `reindex` label and `[r]` prefix of commit title
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Build passes in `sandbox` <sub>or added `no sandbox` label</sub>
- [ ] Reindexed `sandbox` <sub>or this PR does not require reindexing</sub>
- [ ] Added PR reference to merge commit
- [ ] Moved linked issue to Merged
- [ ] Pushed merge commit to Github

Primary reviewer (after pushing merge commit)

- [ ] Moved freebies to Merged column <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened chain <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [ ] Commented on demo expectations <sub>or labeled as `no demo`</sub>
- [ ] Pushed merge commit to Gitlab <sub>or this changes can be pushed later, together with another PR</sub>
- [ ] Reindexed `dev` <sub>or this PR does not require reindexing</sub>
- [ ] Deleted PR branch from Github and Gitlab
- [ ] Unassign reviewer from PR

2020-10-23 16:58 UTC, danielsotirhos approved these changes
Approved.

2020-10-26 20:58 UTC, hannes-ucsc commented
Since I have taken over #2330 (because I have the fix), you should create a separate issue for this, @achave11. Be sure to link the two issues via comment.

2020-10-26 23:15 UTC, hannes-ucsc requested changes
And see my comment above on creating new issue.

2020-10-26 23:15 UTC, hannes-ucsc commented on test/integration_test.py
> +            hit_counts = {e: len(h) for e, h in entities.items()}
`entity_type` and `hits` respectively.

2020-10-26 23:15 UTC, hannes-ucsc commented on test/integration_test.py
> +            if any(hit_counts.values()):
This is essentially the worst possible way of doing this. `any(hit_counts.values())` is the same as `sum(hit_counts.values())`. Why do essentially the same check twice (inefficient) but in two different ways (confusing)? Exploit that assertEqual can be passed a message.

2020-10-26 23:46 UTC, achave11 commented
@hannes-ucsc this branch can be deleted.

2020-11-02 20:51 UTC, hannes-ucsc commented
> this branch can be deleted

Is there a replacement PR?

2020-11-02 20:59 UTC, hannes-ucsc commented
Never mind. In the future, feel free to close and link yourself, as I will do now,.

2020-11-02 21:00 UTC, hannes-ucsc commented
Continued in #2385.

2020-11-02 21:00 UTC, closed without merging