Reregistering SA with SAM raises error (#2407)
DataBiosphere/azul pull request #2451
Opened 2020-11-11 01:45 UTC by noah-aviel-dove

Author (check before every review)

- [ ] PR title references issue
- [ ] Title of main commit references issue
- [ ] PR is linked to Zenhub issue
- [ ] Added `DCP/1` label                                   <sub>or this PR does not target an `hca/*` branch</sub>
- [ ] Created issue to track porting these changes          <sub>or this PR does not need porting</sub> 
- [ ] Added `r` tag to commit title                         <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label to PR                           <sub>or this PR does not require reindexing</sub>
- [ ] Freebies are blocked on this PR                       <sub>or there are no freebies in this PR</sub>
- [ ] Freebies are referenced in commit titles              <sub>or there are no freebies in this PR</sub>
- [ ] This PR is blocked by previous PR in chain            <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chain` label to the blocking PR                <sub>or this PR is not chained to another PR</sub>
- [ ] Ran `make requirements_update`                        <sub>or this PR leaves requirements*.txt, common.mk and Makefile untouched</sub>
- [ ] Added `R` tag to commit title                         <sub>or this PR leaves requirements*.txt untouched</sub>
- [ ] Added `reqs` label to PR                              <sub>or this PR leaves requirements*.txt untouched</sub>
- [ ] Documented upgrading of deployments in UPGRADING.rst  <sub>or this PR does not require upgrading</sub>
- [ ] Added `u` tag to commit title                         <sub>or this PR does not require upgrading</sub>
- [ ] Added `upgrade` label to PR                           <sub>or this PR does not require upgrading</sub>
- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>
- [ ] Rebased branch on `develop`

Primary reviewer (before pushing merge commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Build passes in `sandbox`                             <sub>or added `no sandbox` label</sub>
- [ ] Reindexed `sandbox`                                   <sub>or this PR does not require reindexing</sub>
- [ ] Added PR reference to merge commit
- [ ] Moved linked issue to Merged
- [ ] Pushed merge commit to Github

Primary reviewer (after pushing merge commit)

- [ ] Moved freebies to Merged column                       <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened chain                                       <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [ ] Commented on demo expectations                        <sub>or labeled as `no demo`</sub>
- [ ] Pushed merge commit to Gitlab                         <sub>or this changes can be pushed later, together with another PR</sub>
- [ ] Reindexed `dev`                                       <sub>or this PR does not require reindexing</sub>
- [ ] Deleted PR branch from Github and Gitlab
- [ ] Unassign reviewer from PR

2020-11-11 01:46 UTC, noah-aviel-dove commented
To be clear, `make sam` did not _succeed_ before this PR, but it was not clear that the failure occurred during SAM registration.

2020-11-12 17:15 UTC, amarjandu requested changes
Very close! Please see the comment attached.

2020-11-12 17:15 UTC, amarjandu commented on src/azul/terra.py
> +            raise RequirementError('Unable to register %s. SAM does not allow '
I like that the script is exited if this is hit, there appears to be a problem with the interpolation of the email into the text.

```
Apply complete! Resources: 3 added, 11 changed, 2 destroyed.
/Applications/Xcode.app/Contents/Developer/usr/bin/make link_health_checks
python /Users/amar/dev/hca/azul/scripts/manage_health_checks.py --link
2020-11-12 09:11:35,375 INFO    MainThread: Found credentials in environment variables.
2020-11-12 09:11:36,323 INFO    MainThread: DCP wide health check does not exist for amar
/Applications/Xcode.app/Contents/Developer/usr/bin/make grafana
python /Users/amar/dev/hca/azul/scripts/update_grafana.py
2020-11-12 09:11:36,655 INFO    MainThread: Skipping publishing of Grafana dashboard
/Applications/Xcode.app/Contents/Developer/usr/bin/make sam
python /Users/amar/dev/hca/azul/scripts/register_sam.py
2020-11-12 09:11:38,591 INFO    MainThread: Found credentials in environment variables.
Traceback (most recent call last):
  File "/Users/amar/dev/hca/azul/scripts/register_sam.py", line 37, in <module>
    main()
  File "/Users/amar/dev/hca/azul/scripts/register_sam.py", line 23, in main
    tdr.register_with_sam()
  File "/Users/amar/dev/hca/azul/src/azul/terra.py", line 153, in register_with_sam
    raise RequirementError('Unable to register %s. SAM does not allow '
azul.RequirementError: ('Unable to register %s. SAM does not allow re-registration of service account emails. Refer to the troubleshooting section of the README.', 'azul-ucsc-2-amar@human-cell-atlas-travis-test.iam.gserviceaccount.com')
make[2]: *** [sam] Error 1
make[1]: *** [apply] Error 2
make: *** [deploy] Error 2
```

2020-11-12 22:47 UTC, amarjandu approved these changes
There is a line length issue, other than that LGTM.

2020-11-12 22:47 UTC, amarjandu commented on src/azul/terra.py
> +            raise RequirementError(f'Unable to register {self.credentials.service_account_email}. '
trimmed line length cannot exceed 81 chars, this line is at 87. 
https://github.com/DataBiosphere/azul/blob/develop/CONTRIBUTING.rst#line-length

2020-11-14 07:47 UTC, hannes-ucsc approved these changes
Could have fixed the line length issue that @amarjandu pointed out.

2020-11-16 18:27 UTC, merged

2020-11-16 18:28 UTC, hannes-ucsc commented
For demo, run `make sam`, delete SA from TDR group tat grants access to the SA, run `make sam`, readd the SA, run `make sam`.

2020-12-01 22:14 UTC, noah-aviel-dove commented
@hannes-ucsc: "[Noah] should come up with [their] own demo plan."