Add matrix stratification values to file contribution (#2603)
DataBiosphere/azul pull request #2613
Opened 2020-12-09 23:44 UTC by danielsotirhos

Author (check before every review)

- [ ] PR title references issue
- [ ] Title of main commit references issue
- [ ] PR is linked to Zenhub issue
- [ ] Added `DCP/1` label                                   <sub>or this PR does not target an `hca/*` branch</sub>
- [ ] Created issue to track porting these changes          <sub>or this PR does not need porting</sub> 
- [ ] Added `r` tag to commit title                         <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label to PR                           <sub>or this PR does not require reindexing</sub>
- [ ] Freebies are blocked on this PR                       <sub>or there are no freebies in this PR</sub>
- [ ] Freebies are referenced in commit titles              <sub>or there are no freebies in this PR</sub>
- [ ] This PR is blocked by previous PR in chain            <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chain` label to the blocking PR                <sub>or this PR is not chained to another PR</sub>
- [ ] Ran `make requirements_update`                        <sub>or this PR leaves requirements*.txt, common.mk and Makefile untouched</sub>
- [ ] Added `R` tag to commit title                         <sub>or this PR leaves requirements*.txt untouched</sub>
- [ ] Added `reqs` label to PR                              <sub>or this PR leaves requirements*.txt untouched</sub>
- [ ] Documented upgrading of deployments in UPGRADING.rst  <sub>or this PR does not require upgrading</sub>
- [ ] Added `u` tag to commit title                         <sub>or this PR does not require upgrading</sub>
- [ ] Added `upgrade` label to PR                           <sub>or this PR does not require upgrading</sub>
- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>
- [ ] Rebased branch on `develop`

Primary reviewer (before pushing merge commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Build passes in `sandbox`                             <sub>or added `no sandbox` label</sub>
- [ ] Reindexed `sandbox`                                   <sub>or this PR does not require reindexing</sub>
- [ ] Added PR reference to merge commit
- [ ] Moved linked issue to Merged
- [ ] Pushed merge commit to Github

Primary reviewer (after pushing merge commit)

- [ ] Moved freebies to Merged column                       <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened chain                                       <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [ ] Commented on demo expectations                        <sub>or labeled as `no demo`</sub>
- [ ] Pushed merge commit to Gitlab                         <sub>or this changes can be pushed later, together with another PR</sub>
- [ ] Reindexed `dev`                                       <sub>or this PR does not require reindexing</sub>
- [ ] Deleted PR branch from Github and Gitlab
- [ ] Unassign reviewer from PR

2020-12-10 16:56 UTC, danielsotirhos commented
A bit hacky, but a proof of concept.
Requesting a preliminary review for suggestions / discussion after stand-up.

2020-12-10 18:02 UTC, hannes-ucsc requested changes

2020-12-10 18:02 UTC, hannes-ucsc commented on src/azul/plugins/metadata/hca/transform.py
> +                       if 'genusSpecies' in points else {}),
Triple lookup. Congrats!

2020-12-22 18:47 UTC, hannes-ucsc requested changes
Please chain this to https://github.com/DataBiosphere/azul/pull/2564

2020-12-22 18:47 UTC, hannes-ucsc commented on src/azul/plugins/metadata/hca/transform.py
> +               if 'genusSpecies' in points else {}),
double lookup, wrapped incorrectly

2020-12-22 18:47 UTC, hannes-ucsc commented on src/azul/plugins/metadata/hca/transform.py
> +        if organ := points.get('organ'):
Conflates None and False-ish

2020-12-22 18:47 UTC, hannes-ucsc commented on src/azul/plugins/metadata/hca/transform.py
> +        if library := points.get('libraryConstructionApproach'):
same

2020-12-22 18:47 UTC, hannes-ucsc commented on src/azul/plugins/metadata/hca/transform.py
> +            **({'development_stage': sorted(points['developmentStage'])}
double lookup, wrapped incorrectly

2020-12-22 18:47 UTC, hannes-ucsc commented on src/azul/plugins/metadata/hca/transform.py
> +                                              contents: JSON,
Consider not passing this but instead **-ing the return value.

2020-12-23 02:47 UTC, hannes-ucsc requested changes

2020-12-23 02:47 UTC, hannes-ucsc commented on src/azul/plugins/metadata/hca/transform.py
> +        if isinstance(genus_species, list):
This looks convoluted.  AFAICT, genus_species is either None or a non-empty list. This looks as if you are expecting it to be other types. Why can't you use `is not None`?

2020-12-23 02:47 UTC, hannes-ucsc commented on src/azul/plugins/metadata/hca/transform.py
> +                    if Submitter.category_for(file) is not None:
This would break if we added a 3rd category for which we don't want this to happen.

2020-12-23 02:47 UTC, hannes-ucsc commented on src/azul/plugins/metadata/hca/transform.py
> +                if isinstance(file, api.SupplementaryFile):
Is this necessary? Note the `require` in `catageory_for`.

2020-12-23 02:47 UTC, hannes-ucsc commented on src/azul/plugins/metadata/hca/transform.py
> +                                      for stratum in file.json['file_description'].split('\n')
Extract `file.json['file_description']` into a variable and move the parsing code into `contributor_matrices.py` for encapsulation. The function signature should be `def parse_stratification(strata:str) -> Mapping[…]` with … reflecting the exact structure of the return value.  Add doctests to that function.

2021-01-04 22:27 UTC, hannes-ucsc commented
@danielsotirhos  I restored the original base branch, reopened the PR and then changed the base branch to develop.

2021-01-12 19:01 UTC, hannes-ucsc requested changes
Consolidate with the parsing code in `make_stratification_tree`.

2021-01-12 19:01 UTC, hannes-ucsc commented on src/azul/plugins/metadata/hca/contributor_matrices.py
> +                if stratum
Don't understand why this condition is necessary.

2021-01-12 19:01 UTC, hannes-ucsc commented on src/azul/plugins/metadata/hca/contributor_matrices.py
> +        if parsed_stratum:
or this one

2021-01-14 03:04 UTC, hannes-ucsc requested changes
Looks pretty good.

2021-01-14 03:04 UTC, hannes-ucsc commented on src/azul/service/hca_response_v5.py
> +            'matrix': ('matrix', lambda x: []),
```suggestion
            'matrix': ('matrix', lambda _: []),
```

But really, this surprises me. To be discussed in parking lot.

2021-01-14 03:04 UTC, hannes-ucsc commented on src/azul/plugins/metadata/hca/contributor_matrices.py
> +def parse_stratification(strata: str) -> JSONs:
Looking at the call sites

```suggestion
def parse_strata(strata: str) -> JSONs:
```

2021-01-14 17:51 UTC, danielsotirhos commented on src/azul/plugins/metadata/hca/contributor_matrices.py
> +            for dimension, values in (point.split('=')
This seemed to be the only format both `make format` and `make pep8` were happy with.
If I start with:
```
        {
            dimension: values.split(',')
            for dimension, values in (
                point.split('=') for point in stratum.split(';')
            )
        }
```
then run `make format` it reformats it to:
```
        {
            dimension: values.split(',')
            for dimension, values in (
            point.split('=') for point in stratum.split(';')
        )
        }
```
which `make pep8` then  complains about:
```
(azul.sc) daniel@Crispin ~/azul.sc $ make pep8
...
/Users/daniel/azul.sc/src/azul/plugins/metadata/hca/contributor_matrices.py:79:13: E122 continuation line missing indentation or outdented
/Users/daniel/azul.sc/src/azul/plugins/metadata/hca/contributor_matrices.py:80:9: E122 continuation line missing indentation or outdented
make: *** [pep8] Error 1
```

2021-01-19 19:15 UTC, hannes-ucsc approved these changes

2021-01-19 20:54 UTC, merged

2021-01-19 20:55 UTC, amarjandu commented
@hannes-ucsc please add demo expectations for this PR.

2021-01-19 21:13 UTC, hannes-ucsc commented
For demo, attempt to reproduce issue. Show changes to service response.

2021-01-20 18:58 UTC, hannes-ucsc commented
@amarjandu, please post results of reindex.

2021-01-20 19:00 UTC, hannes-ucsc commented
@danielsotirhos, it appears that you checked "Added reindex label to PR or this PR does not require reindexing" but did not actually add the label.

2021-01-20 22:18 UTC, amarjandu commented
Reindex was complete without failed notifications in the queues

From my terminal history:
```
(.venv) Specter:azul amar$ python scripts/manage_queues.py list
2021-01-19 16:06:45,443 INFO    MainThread: Listing queues

Queue Name                          Messages Available  Messages In Flight  Messages Delayed

2021-01-19 16:06:45,469 INFO    MainThread: Found credentials in environment variables.
azul-notifications-dev                      0                   0                  0
azul-tallies-dev.fifo                       0                   0                  0
azul-tallies_retry-dev.fifo                 0                   0                  0
azul-tallies_fail-dev.fifo                  0                   0                  0
azul-notifications_fail-dev                 0                   0                  0
```