Prefix filenames in curl format manifest (2403)
DataBiosphere/azul pull request #2642
Opened 2020-12-18 18:16 UTC by danielsotirhos

Author

- [ ] PR title references issue
- [ ] Title of main commit references issue
- [ ] PR is linked to Zenhub issue

Author (reindex)

- [ ] Added `r` tag to commit title                         <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label to PR                           <sub>or this PR does not require reindexing</sub>

Author (freebies & chains)

- [ ] Freebies are blocked on this PR                       <sub>or there are no freebies in this PR</sub>
- [ ] Freebies are referenced in commit titles              <sub>or there are no freebies in this PR</sub>
- [ ] This PR is blocked by previous PR in chain            <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chain` label to the blocking PR                <sub>or this PR is not chained to another PR</sub>

Author (upgrading)

- [ ] Documented upgrading of deployments in UPGRADING.rst  <sub>or this PR does not require upgrading</sub>
- [ ] Added `u` tag to commit title                         <sub>or this PR does not require upgrading</sub>
- [ ] Added `upgrade` label to PR                           <sub>or this PR does not require upgrading</sub>

Author (requirements, before every review)

- [ ] Ran `make requirements_update`                        <sub>or this PR leaves requirements*.txt, common.mk and Makefile untouched</sub>
- [ ] Added `R` tag to commit title                         <sub>or this PR leaves requirements*.txt untouched</sub>
- [ ] Added `reqs` label to PR                              <sub>or this PR leaves requirements*.txt untouched</sub>

Author (before every review)

- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>
- [ ] Rebased branch on `develop`, squashed old fixups

Primary reviewer (before pushing merge commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Build passes in `sandbox`                             <sub>or added `no sandbox` label</sub>
- [ ] Reindexed `sandbox`                                   <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Added PR reference to merge commit
- [ ] Moved linked issue to Merged
- [ ] Pushed merge commit to Github

Primary reviewer (after pushing merge commit)

- [ ] Moved freebies to Merged column                       <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened chain                                       <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [ ] Commented on demo expectations                        <sub>or labeled as `no demo`</sub>
- [ ] Pushed merge commit to Gitlab                         <sub>or this changes can be pushed later, together with another PR</sub>
- [ ] Deleted PR branch from Github and Gitlab

Primary reviewer (reindex) 

- [ ] Started reindex in `dev`                              <sub>or this PR does not require reindexing `dev`</sub>
- [ ] Deleted BQ slot committment in `dev`                  <sub>or this PR does not require reindexing `dev`</sub>
- [ ] Checked for failures in `dev`                         <sub>or this PR does not require reindexing `dev`</sub>
- [ ] Started reindex in `prod`                             <sub>or this PR does not require reindexing `prod`</sub>
- [ ] Deleted BQ slot committment in `prod`                 <sub>or this PR does not require reindexing `prod`</sub>
- [ ] Checked for failures in `prod`                        <sub>or this PR does not require reindexing `prod`</sub>

Primary reviewer

- [ ] Unassign PR from reviewer and assign to PM

2020-12-22 20:53 UTC, theathorn commented
@hannes-ucsc @danielsotirhos If we encode the bundle uuid then how will the user match up the file with the corresponding row in the full manifest (assuming they may download that as well as their selected files)? Maybe we should use the unencoded bundle_uuid value instead?

2020-12-23 06:06 UTC, hannes-ucsc requested changes

2020-12-23 06:06 UTC, hannes-ucsc commented on src/azul/service/manifest_service.py
> +        hex_string = u.hex[:12] + u.hex[13:16] + u.hex[17:18]
Gotta operate on the binary UUID representation, not the hexadecimal one.

2020-12-23 06:06 UTC, hannes-ucsc commented on src/azul/service/manifest_service.py
> +        """
Doctests please.

2020-12-23 06:06 UTC, hannes-ucsc commented on test/service/test_manifest.py
> +                'output="Zjc5MjU3YTdkZmM2NmQ2ZQ_SmartSeq2_sequencing_protocol.pdf"',
The base64 of 64 bits is 11 bytes long (12 bytes with padding).

2020-12-23 06:06 UTC, hannes-ucsc commented on src/azul/service/manifest_service.py
> +        return str(encoded_bytes, 'utf-8')
utf8 is default encoding

2020-12-23 06:06 UTC, hannes-ucsc commented on src/azul/service/manifest_service.py
> +            bundle = one(doc['bundles'])
Many files occur in more than one bundle. Some in thousands.

2020-12-23 19:27 UTC, hannes-ucsc commented
> If we encode the bundle uuid then how will the user match up the file with the corresponding row in the full manifest (assuming they may download that as well as their selected files)? Maybe we should use the unencoded bundle_uuid value instead?

They'd just use the file name minus the prefix to look it up.

2020-12-23 19:54 UTC, hannes-ucsc commented
> They'd just use the file name minus the prefix to look it up

That makes no sense. Different files have the same name in different bundles. One wouldn't know.

We should just use the UUID, no base64-encoded prefix.

@danielsotirhos ^^^

2021-01-08 21:27 UTC, danielsotirhos commented
Taking ticket out of review to be chained on #2682

2021-01-19 19:04 UTC, hannes-ucsc requested changes

2021-01-19 19:04 UTC, hannes-ucsc commented on src/azul/service/manifest_service.py
> +            # To prevent overwriting one file with another of the same name but
```suggestion
            # To prevent overwriting one file with another one of the same name but
```

2021-01-19 19:04 UTC, hannes-ucsc commented on src/azul/service/manifest_service.py
> +            bundle = last(sorted(doc['bundles'], key=lambda b: (b['version'], b['uuid'])))
use `itemgetter` from `operator`

2021-01-19 19:04 UTC, hannes-ucsc commented on src/azul/service/manifest_service.py
> +            bundle = last(sorted(doc['bundles'], key=lambda b: (b['version'], b['uuid'])))
It's inefficient to do a total sort just to find the max or min.

2021-01-20 02:13 UTC, hannes-ucsc requested changes
Typo in commit titles.  Otherwise, LGTM.

2021-01-21 18:37 UTC, merged