Add make `deploy` target dependency on `package` target (#1997)
DataBiosphere/azul pull request #2802
Opened 2021-02-17 19:26 UTC by achave11

Author

- [ ] PR title references issue
- [ ] Title of main commit references issue
- [ ] PR is linked to Zenhub issue

Author (reindex)

- [ ] Added `r` tag to commit title                         <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label to PR                           <sub>or this PR does not require reindexing</sub>

Author (freebies & chains)

- [ ] Freebies are blocked on this PR                       <sub>or there are no freebies in this PR</sub>
- [ ] Freebies are referenced in commit titles              <sub>or there are no freebies in this PR</sub>
- [ ] This PR is blocked by previous PR in the chain        <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chain` label to the blocking PR                <sub>or this PR is not chained to another PR</sub>

Author (upgrading)

- [ ] Documented upgrading of deployments in UPGRADING.rst  <sub>or this PR does not require upgrading</sub>
- [ ] Added `u` tag to commit title                         <sub>or this PR does not require upgrading</sub>
- [ ] Added `upgrade` label to PR                           <sub>or this PR does not require upgrading</sub>

Author (requirements, before every review)

- [ ] Ran `make requirements_update`                        <sub>or this PR leaves requirements*.txt, common.mk and Makefile untouched</sub>
- [ ] Added `R` tag to commit title                         <sub>or this PR leaves requirements*.txt untouched</sub>
- [ ] Added `reqs` label to PR                              <sub>or this PR leaves requirements*.txt untouched</sub>

Author (before every review)

- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>
- [ ] Rebased branch on `develop`, squashed old fixups

Primary reviewer (after approval)

- [ ] Commented on demo expectations                        <sub>or labelled PR as `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] Moved ticket to Approved column
- [ ] Assigned PR to an operator

Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that Demo expectations are clear              <sub>or PR is labeled as `no demo`</sub>
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Pushed PR branch to Github
- [ ] Branch pushed to Gitlab and build passes in `sandbox` <sub>or added `no sandbox` label</sub>
- [ ] Started reindex in `sandbox`                          <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox`                     <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title
- [ ] Moved linked issue to Merged column
- [ ] Pushed merge commit to Github

Operator (after pushing the merge commit)

- [ ] Moved freebies to Merged column                       <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened the PR chain                                <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [ ] Pushed merge commit to Gitlab                         <sub>or this changes can be pushed later, together with another PR</sub>
- [ ] Deleted PR branch from Github and Gitlab

Operator (reindex) 

- [ ] Purchased BQ slot committment in `dev`                <sub>or this PR does not require reindexing `dev`</sub>
- [ ] Started reindex in `dev`                              <sub>or this PR does not require reindexing `dev`</sub>
- [ ] Deleted BQ slot committment in `dev`                  <sub>or this PR does not require reindexing `dev`</sub>
- [ ] Checked for failures in `dev`                         <sub>or this PR does not require reindexing `dev`</sub>
- [ ] Purchased BQ slot committment in `prod`               <sub>or this PR does not require reindexing `prod`</sub>
- [ ] Started reindex in `prod`                             <sub>or this PR does not require reindexing `prod`</sub>
- [ ] Deleted BQ slot committment in `prod`                 <sub>or this PR does not require reindexing `prod`</sub>
- [ ] Checked for failures in `prod`                        <sub>or this PR does not require reindexing `prod`</sub>

Operator

- [ ] Unassigned PR

2021-02-18 19:41 UTC, jessebrennan requested changes
It's not obvious to me why these are separate commits. How come you decided to split them up?

We should probably delete the `package` target in the top level makefile. I can't think of any reason we will need to run it manually. In that case we should remove all references to it. I saw at least one in the README (but there may be more).

2021-02-19 01:02 UTC, achave11 commented
> It's not obvious to me why these are separate commits. How come you decided to split them up?

I though it would be beneficial to separate additions from deletions in separate commits, but that might have been superficial and unnecessary.

2021-02-19 20:57 UTC, jessebrennan approved these changes

2021-02-19 20:57 UTC, jessebrennan commented on UPGRADING.rst
> +
Consider adding a note that `make package` is defunct.

2021-02-23 18:42 UTC, hannes-ucsc requested changes

2021-02-23 18:42 UTC, hannes-ucsc commented on README.md
> +to prepare the lambda functions defined in the `lambdas` directory for
```suggestion
to prepare the Lambda functions defined in the `lambdas` directory for
```

2021-02-23 18:42 UTC, hannes-ucsc commented on README.md
>  cloud infrastructure for the selected deployment.
```suggestion
Some Terraform configuration is generated by `make -C lambdas`, but the rest is
defined in `….tf.json` files which in turn are generated from
`….tf.json.template.py` templates which are simple Python scripts containing the
desired JSON as Python dictionary and list literals and comprehensions. `make deploy` will take care of both, `make -C lambda` as well as expanding the template files. Changes
to either the templates or anything in the `lambdas` directory requires running `make deploy` again in order to update
cloud infrastructure for the selected deployment.
```

2021-02-23 18:42 UTC, hannes-ucsc commented on README.md
> +is deployment specific.
```suggestion
```

That should be obvious now.

2021-02-23 18:42 UTC, hannes-ucsc commented on UPGRADING.rst
> +Run … ::
This sounds like I have to do this to upgrade. I don't think that's the case. If this purely informational, it should be worded that way, or this upgrading entry should be removed.

2021-02-23 18:42 UTC, hannes-ucsc commented on terraform/Makefile
> +config: $(patsubst %.template.py,%,$(wildcard *.tf.json.template.py)) package
```suggestion
config: $(patsubst %.template.py,%,$(wildcard *.tf.json.template.py)) lambdas
```

and below

2021-02-23 18:44 UTC, hannes-ucsc commented
Also,

![image](https://user-images.githubusercontent.com/5143256/108891819-03a33700-75c4-11eb-87f3-99b115d174cb.png)

we squash before every review.

2021-02-26 21:04 UTC, hannes-ucsc requested changes
https://github.com/DataBiosphere/azul/blob/develop/CONTRIBUTING.rst#511review-comments

2021-02-26 22:27 UTC, hannes-ucsc requested changes
Commit and PR titles are 1) inconsistent and 2) make no sense in light of the recent review changes.

2021-03-08 23:56 UTC, hannes-ucsc requested changes
Not much better. Please consult with peer reviewer for better commit and PR titles.

2021-03-11 18:12 UTC, jessebrennan approved these changes
Just a suggestion to adjust the wording.

As for a commit title, maybe "Package lambdas as part of `make deploy`"?

2021-03-13 00:46 UTC, hannes-ucsc requested changes
Back quotes missing in the PR title (I added those) and commit titles.

2021-03-22 15:58 UTC, hannes-ucsc approved these changes

2021-03-22 16:00 UTC, hannes-ucsc commented
No demo, because the `make deploy` target is invoked by CI/CD and frequently by other developers.

2021-03-24 00:03 UTC, merged