[r] Index hca_dev_20201023_ebiv4___20210302 into dcp2ebi on dev (#2851)
DataBiosphere/azul pull request #2853
Opened 2021-03-03 20:24 UTC by amarjandu

Author

- [ ] PR title references issue
- [ ] Title of main commit references issue
- [ ] PR is linked to Zenhub issue

Author (reindex)

- [ ] Added `r` tag to commit title                         <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label to PR                           <sub>or this PR does not require reindexing</sub>

Author (freebies & chains)

- [ ] Freebies are blocked on this PR                       <sub>or there are no freebies in this PR</sub>
- [ ] Freebies are referenced in commit titles              <sub>or there are no freebies in this PR</sub>
- [ ] This PR is blocked by previous PR in the chain        <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chain` label to the blocking PR                <sub>or this PR is not chained to another PR</sub>

Author (upgrading)

- [ ] Documented upgrading of deployments in UPGRADING.rst  <sub>or this PR does not require upgrading</sub>
- [ ] Added `u` tag to commit title                         <sub>or this PR does not require upgrading</sub>
- [ ] Added `upgrade` label to PR                           <sub>or this PR does not require upgrading</sub>

Author (requirements, before every review)

- [ ] Ran `make requirements_update`                        <sub>or this PR leaves requirements*.txt, common.mk and Makefile untouched</sub>
- [ ] Added `R` tag to commit title                         <sub>or this PR leaves requirements*.txt untouched</sub>
- [ ] Added `reqs` label to PR                              <sub>or this PR leaves requirements*.txt untouched</sub>

Author (before every review)

- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>
- [ ] Rebased branch on `develop`, squashed old fixups

Primary reviewer (after approval)

- [ ] Commented on demo expectations                        <sub>or labelled PR as `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] Moved ticket to Approved column
- [ ] Assigned PR to an operator

Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that Demo expectations are clear              <sub>or PR is labeled as `no demo`</sub>
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Pushed PR branch to Github
- [ ] Branch pushed to Gitlab and build passes in `sandbox` <sub>or added `no sandbox` label</sub>
- [ ] Started reindex in `sandbox`                          <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox`                     <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title
- [ ] Moved linked issue to Merged column
- [ ] Pushed merge commit to Github

Operator (after pushing the merge commit)

- [ ] Moved freebies to Merged column                       <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened the PR chain                                <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [ ] Pushed merge commit to Gitlab                         <sub>or this changes can be pushed later, together with another PR</sub>
- [ ] Deleted PR branch from Github and Gitlab

Operator (reindex) 

- [ ] Purchased BQ slot committment in `dev`                <sub>or this PR does not require reindexing `dev`</sub>
- [ ] Started reindex in `dev`                              <sub>or this PR does not require reindexing `dev`</sub>
- [ ] Deleted BQ slot committment in `dev`                  <sub>or this PR does not require reindexing `dev`</sub>
- [ ] Checked for failures in `dev`                         <sub>or this PR does not require reindexing `dev`</sub>
- [ ] Purchased BQ slot committment in `prod`               <sub>or this PR does not require reindexing `prod`</sub>
- [ ] Started reindex in `prod`                             <sub>or this PR does not require reindexing `prod`</sub>
- [ ] Deleted BQ slot committment in `prod`                 <sub>or this PR does not require reindexing `prod`</sub>
- [ ] Checked for failures in `prod`                        <sub>or this PR does not require reindexing `prod`</sub>

Operator

- [ ] Unassigned PR

2021-03-03 23:57 UTC, amarjandu commented
looks like IT fails. https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/11364
Nothing the queues, going to retry IT.

2021-03-04 00:30 UTC, amarjandu commented
IT passed after being ran again, see https://github.com/DataBiosphere/azul/issues/2851#issuecomment-790182938 for information on error.

2021-03-04 00:32 UTC, amarjandu commented
Starting reindex on sandbox, verified that failed queues are empty. 
```
(.venv) Specter:azul amar$ python scripts/manage_queues.py list
2021-03-03 16:29:22,381 INFO    MainThread: Listing queues

Queue Name                          Messages Available  Messages In Flight  Messages Delayed

2021-03-03 16:29:22,424 INFO    MainThread: Found credentials in environment variables.
azul-notifications-sandbox                  0                   0                  0
azul-tallies-sandbox.fifo                   0                   0                  0
azul-tallies_retry-sandbox.fifo             0                   0                  0
azul-tallies_fail-sandbox.fifo              0                   0                  0
azul-notifications_fail-sandbox             0                   0                  0
```

2021-03-04 00:47 UTC, amarjandu commented
reindex on `sandbox` passed without failures.

2021-03-04 01:38 UTC, hannes-ucsc requested changes
We

2021-03-04 01:38 UTC, hannes-ucsc commented on deployments/dev/environment.py
>                  'tdr:broad-jade-dev-data:snapshot/hca_dev_20210211_snaptest3___20210211',
These should be removed. I should have specified that we want just this one snapshot in the catalog.

2021-03-04 01:38 UTC, hannes-ucsc commented on deployments/sandbox/environment.py
>                  'tdr:broad-jade-dev-data:snapshot/hca_dev_20210211_snaptest3___20210211',
Same here

2021-03-04 01:51 UTC, hannes-ucsc approved these changes

2021-03-04 02:48 UTC, merged

2021-03-04 03:47 UTC, amarjandu commented
There are 4 failures notifications in the snapshot hca_dev_20201203___20201210 that were observed in the develop failed queue. These are known failures. https://github.com/DataBiosphere/azul/wiki/Operator-Manual#notes

Going to purge the queues then start the reindex of the `dcp2ebi` catalog.

2021-03-04 05:00 UTC, amarjandu commented
reindex of `dev` is complete, no failed notifications.

reindexed with:
`python scripts/reindex.py --delete --index --purge --partition-prefix-length=2 --catalog dcp2ebi`