Add extended features to CGM Adapter (#3002)
DataBiosphere/azul pull request #3003
Opened 2021-04-22 16:22 UTC by danielsotirhos

Author

- [ ] PR title references issue
- [ ] Title of main commit references issue
- [ ] PR is linked to Zenhub issue

Author (reindex)

- [ ] Added `r` tag to commit title                         <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label to PR                           <sub>or this PR does not require reindexing</sub>

Author (freebies & chains)

- [ ] Freebies are blocked on this PR                       <sub>or there are no freebies in this PR</sub>
- [ ] Freebies are referenced in commit titles              <sub>or there are no freebies in this PR</sub>
- [ ] This PR is blocked by previous PR in the chain        <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chain` label to the blocking PR                <sub>or this PR is not chained to another PR</sub>

Author (upgrading)

- [ ] Documented upgrading of deployments in UPGRADING.rst  <sub>or this PR does not require upgrading</sub>
- [ ] Added `u` tag to commit title                         <sub>or this PR does not require upgrading</sub>
- [ ] Added `upgrade` label to PR                           <sub>or this PR does not require upgrading</sub>

Author (requirements, before every review)

- [ ] Ran `make requirements_update`                        <sub>or this PR leaves requirements*.txt, common.mk and Makefile untouched</sub>
- [ ] Added `R` tag to commit title                         <sub>or this PR leaves requirements*.txt untouched</sub>
- [ ] Added `reqs` label to PR                              <sub>or this PR leaves requirements*.txt untouched</sub>

Author (before every review)

- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>
- [ ] Rebased branch on `develop`, squashed old fixups

Primary reviewer (after approval)

- [ ] Commented on demo expectations                        <sub>or labelled PR as `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] Moved ticket to Approved column
- [ ] Assigned PR to an operator

Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that Demo expectations are clear              <sub>or PR is labeled as `no demo`</sub>
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Pushed PR branch to Github
- [ ] Branch pushed to Gitlab                               <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in sandbox and added `sandbox` label     <sub>or PR is labeled `no sandbox`</sub>
- [ ] Started reindex in `sandbox`                          <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox`                     <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title
- [ ] Moved linked issue to Merged column
- [ ] Pushed merge commit to Github

Operator (after pushing the merge commit)

- [ ] Moved freebies to Merged column                       <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened the PR chain                                <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [ ] Pushed merge commit to Gitlab                         <sub>or this changes can be pushed later, together with another PR</sub>
- [ ] Deleted PR branch from Github and Gitlab

Operator (reindex) 

- [ ] Started reindex in `dev`                              <sub>or this PR does not require reindexing or does not target `dev`</sub>
- [ ] Checked for failures in `dev`                         <sub>or this PR does not require reindexing or does not target `dev`</sub>
- [ ] Started reindex in `prod`                             <sub>or this PR does not require reindexing or does not target `prod`</sub>
- [ ] Checked for failures in `prod`                        <sub>or this PR does not require reindexing or does not target `prod`</sub>

Operator

- [ ] Unassigned PR

2021-04-27 17:20 UTC, danielsotirhos commented
Terminal log from a test run. 
[cgm_adapter_log.txt](https://github.com/DataBiosphere/azul/files/6386400/cgm_adapter_log.txt)

2021-04-27 17:53 UTC, achave11 requested changes
Minor nits. It seems like the logging/log statements are a mix between f-string and %, I am curious if there is a reason for that.

2021-04-27 17:53 UTC, achave11 commented on scripts/cgm_adapter.py
> +                       path=f'/index/projects/{project_id}',
```suggestion
                       path=('index', 'projects', project_id),
```
`furl.path` allows for usage of sequences, that way we don't have to use f-strings to concat.

2021-04-27 17:53 UTC, achave11 commented on scripts/cgm_adapter.py
> +                             f' {date_imported!r} >= {date_added!r}')
Not sure if this logging statement can benefit from [CONTRIBUTING](https://github.com/DataBiosphere/azul/blob/develop/CONTRIBUTING.rst#110logging) -> "We don't use f'' strings or string concatenation when interpolating dynamic values into log messages:"

2021-04-27 18:23 UTC, danielsotirhos commented
> Minor nits. It seems like the logging/log statements are a mix between f-string and %, I am curious if there is a reason for that.

Sloppy code. I will covert the f-strings to `%` formatted strings.

2021-04-28 03:04 UTC, achave11 approved these changes
Looks good. You might want to also consider updating the format of the log messages in `scripts/sha256_gcs_blobs.py`, I think it's appropriate to address it in the same commit as s/logging/log, your call.

2021-04-29 02:23 UTC, hannes-ucsc approved these changes

2021-05-04 17:10 UTC, hannes-ucsc commented
For demo, pick any subset of features you'd like to demo.

2021-05-05 03:52 UTC, merged