Fix: terra.pfb manifest IT fails on prod (#3138)
DataBiosphere/azul pull request #3167
Opened 2021-06-22 17:15 UTC by jessebrennan

How should I address the duplicate test fragment?

Author

- [ ] PR title references issue
- [ ] Title of main commit references issue
- [ ] PR is linked to Zenhub issue

Author (reindex)

- [ ] Added `r` tag to commit title                         <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label to PR                           <sub>or this PR does not require reindexing</sub>

Author (freebies & chains)

- [ ] Freebies are blocked on this PR                       <sub>or there are no freebies in this PR</sub>
- [ ] Freebies are referenced in commit titles              <sub>or there are no freebies in this PR</sub>
- [ ] This PR is blocked by previous PR in the chain        <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chain` label to the blocking PR                <sub>or this PR is not chained to another PR</sub>

Author (upgrading)

- [ ] Documented upgrading of deployments in UPGRADING.rst  <sub>or this PR does not require upgrading</sub>
- [ ] Added `u` tag to commit title                         <sub>or this PR does not require upgrading</sub>
- [ ] Added `upgrade` label to PR                           <sub>or this PR does not require upgrading</sub>

Author (requirements, before every review)

- [ ] Ran `make requirements_update`                        <sub>or this PR leaves requirements*.txt, common.mk and Makefile untouched</sub>
- [ ] Added `R` tag to commit title                         <sub>or this PR leaves requirements*.txt untouched</sub>
- [ ] Added `reqs` label to PR                              <sub>or this PR leaves requirements*.txt untouched</sub>

Author (before every review)

- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>
- [ ] Rebased branch on `develop`, squashed old fixups

Primary reviewer (after approval)

- [ ] Commented in issue about demo expectations            <sub>or labelled issue as `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] Moved ticket to Approved column
- [ ] Assigned PR to an operator

Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear              <sub>or issue is labeled as `no demo`</sub>
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Pushed PR branch to Github
- [ ] Branch pushed to Gitlab                               <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in sandbox and added `sandbox` label     <sub>or PR is labeled `no sandbox`</sub>
- [ ] Started reindex in `sandbox`                          <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox`                     <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title
- [ ] Moved linked issue to Merged column
- [ ] Pushed merge commit to Github

Operator (after pushing the merge commit)

- [ ] Moved freebies to Merged column                       <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened the PR chain                                <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [ ] Pushed merge commit to Gitlab                         <sub>or this changes can be pushed later, together with another PR</sub>
- [ ] Deleted PR branch from Github and Gitlab

Operator (reindex) 

- [ ] Started reindex in `dev`                              <sub>or this PR does not require reindexing or does not target `dev`</sub>
- [ ] Checked for failures in `dev`                         <sub>or this PR does not require reindexing or does not target `dev`</sub>
- [ ] Started reindex in `prod`                             <sub>or this PR does not require reindexing or does not target `prod`</sub>
- [ ] Checked for failures in `prod`                        <sub>or this PR does not require reindexing or does not target `prod`</sub>

Operator

- [ ] Unassigned PR

2021-06-22 17:55 UTC, jessebrennan commented
I have a question about how to reduce redundancy with the test and if it's worth keeping on that I will bring up in PL.

2021-06-25 01:00 UTC, hannes-ucsc requested changes

2021-06-25 01:01 UTC, hannes-ucsc commented on test/indexer/data/587d74b4-1075-4bbf-b96a-4d1ede0481b2.metadata.json
> -                    "242e38d2-c975-47ee-800a-6645b47e92d2"
I mean this big deletion.

2021-06-25 01:03 UTC, hannes-ucsc requested changes
Would also like to see evidence that the added/changed test reproduces the issue.

2021-06-25 18:11 UTC, jessebrennan commented on test/indexer/data/587d74b4-1075-4bbf-b96a-4d1ede0481b2.metadata.json
> -                    "242e38d2-c975-47ee-800a-6645b47e92d2"
Did you read the commit message?

2021-06-25 18:13 UTC, jessebrennan commented
> Would also like to see evidence that the added/changed test reproduces the issue.

The evidence is there in the history. I can explain it in parking lot.

2021-06-26 00:38 UTC, jessebrennan commented
I will redo this with the following commits:

- Use newer bundle for PFB manifest test
- Revert hotfix
- Modify bundle (dynamically) to expose error from prod
- Fix

2021-06-29 23:01 UTC, jessebrennan commented
@hannes-ucsc I'm having trouble finding a new bundle that contains zarrs. Having zarrs is useful for coverage, and to make sure "related_files" make it into the final manifest. There are (as best I can tell) no zarrs in DCP2. The most recent DCP1 zarr I can find is from September 2019. Is this recent enough or should I drop the zarr requirement?

I will bring this up in PL

2021-07-02 18:57 UTC, hannes-ucsc requested changes

2021-07-02 18:57 UTC, hannes-ucsc commented on test/service/test_manifest.py
> +        new_bundle.metadata_files['donor_organism_1.json'] = {
No literal, duplicate the first donor programmatically instead.

2021-07-02 21:29 UTC, hannes-ucsc requested changes
Please squash and push commits individually. No bump.

2021-07-07 23:22 UTC, hannes-ucsc approved these changes

2021-07-08 18:02 UTC, merged