[r] Index hca_dev_20210621_managedaccess_4298b4de92f34cbbbbfe5bc11b8c2422__20210621 into dcp2 on `dev` (#3158)
DataBiosphere/azul pull request #3178
Opened 2021-06-24 00:41 UTC by jessebrennan

Author

- [x] PR title references issue
- [x] Title of main commit references issue
- [x] PR is linked to Zenhub issue

Author (reindex)

- [ ] Added `r` tag to commit title                         <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label to PR                           <sub>or this PR does not require reindexing</sub>

Author (freebies & chains)

- [ ] Freebies are blocked on this PR                       <sub>or there are no freebies in this PR</sub>
- [ ] Freebies are referenced in commit titles              <sub>or there are no freebies in this PR</sub>
- [ ] This PR is blocked by previous PR in the chain        <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chain` label to the blocking PR                <sub>or this PR is not chained to another PR</sub>

Author (upgrading)

- [ ] Documented upgrading of deployments in UPGRADING.rst  <sub>or this PR does not require upgrading</sub>
- [ ] Added `u` tag to commit title                         <sub>or this PR does not require upgrading</sub>
- [ ] Added `upgrade` label to PR                           <sub>or this PR does not require upgrading</sub>

Author (requirements, before every review)

- [ ] Ran `make requirements_update`                        <sub>or this PR leaves requirements*.txt, common.mk and Makefile untouched</sub>
- [ ] Added `R` tag to commit title                         <sub>or this PR leaves requirements*.txt untouched</sub>
- [ ] Added `reqs` label to PR                              <sub>or this PR leaves requirements*.txt untouched</sub>

Author (before every review)

- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>
- [ ] Rebased branch on `develop`, squashed old fixups

Primary reviewer (after approval)

- [ ] Commented in issue about demo expectations            <sub>or labelled issue as `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] Moved ticket to Approved column
- [ ] Assigned PR to an operator

Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear              <sub>or issue is labeled as `no demo`</sub>
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Pushed PR branch to Github
- [ ] Branch pushed to Gitlab                               <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in sandbox and added `sandbox` label     <sub>or PR is labeled `no sandbox`</sub>
- [ ] Started reindex in `sandbox`                          <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox`                     <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title
- [ ] Moved linked issue to Merged column
- [ ] Pushed merge commit to Github

Operator (after pushing the merge commit)

- [ ] Moved freebies to Merged column                       <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened the PR chain                                <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [ ] Pushed merge commit to Gitlab                         <sub>or this changes can be pushed later, together with another PR</sub>
- [ ] Deleted PR branch from Github and Gitlab

Operator (reindex) 

- [ ] Started reindex in `dev`                              <sub>or this PR does not require reindexing or does not target `dev`</sub>
- [ ] Checked for failures in `dev`                         <sub>or this PR does not require reindexing or does not target `dev`</sub>
- [ ] Started reindex in `prod`                             <sub>or this PR does not require reindexing or does not target `prod`</sub>
- [ ] Checked for failures in `prod`                        <sub>or this PR does not require reindexing or does not target `prod`</sub>

Operator

- [ ] Unassigned PR

2021-06-25 01:15 UTC, hannes-ucsc requested changes

2021-06-25 01:15 UTC, hannes-ucsc commented on deployments/dev/environment.py
> -            'tdr:broad-jade-dev-data:snapshot/hca_dev_20201203___20210524_lattice:'
We're adding that snapshot to the catalog, it doesn't replace the existing snapshot. The issue description wasn't clear on this so I won't bump.

2021-06-26 02:27 UTC, hannes-ucsc approved these changes

2021-07-06 17:10 UTC, merged

2021-07-06 22:50 UTC, amarjandu commented
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/pipelines/5622
An early reindex was accidentally kicked off, this occurred before the `deploy` stage was able to finish. Due to the Snapshot change multiple assertion failures occurred:

```
**CloudWatch Logs Insights**  
region: us-east-1  
log-group-names: /aws/lambda/azul-indexer-dev-contribute, /aws/lambda/azul-indexer-dev-aggregate, /aws/lambda/azul-indexer-dev, /aws/lambda/azul-indexer-dev-aggregate_retry, /aws/lambda/azul-indexer-dev-contribute_retry  
start-time: -43200s  
end-time: 0s  
query-string:
```
fields @timestamp, @message
| sort @timestamp desc
|filter @message like 'ERROR'
| limit 20
```
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|       @timestamp        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   @message                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|-------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2021-07-06 17:34:14.077 | [ERROR] AssertionError: (TDRSourceRef(id='fae2ed64-aadc-447a-bee9-ab27598cf45d', spec=TDRSourceSpec(prefix='', project='broad-jade-dev-data', name='hca_dev_20210621_managedaccess_4298b4de92f34cbbbbfe5bc11b8c2422__20210622', is_snapshot=True)), frozenset({TDRSourceSpec(prefix='', project='broad-jade-dev-data', name='hca_dev_20201203___20210524_lattice', is_snapshot=True)})) Traceback (most recent call last):   File "/var/task/app.py", line 118, in new_handler     return old_handler(self, event, context)   File "/var/task/chalice/app.py", line 1459, in __call__     return self.func(event_obj)   File "/var/task/app.py", line 151, in contribute_retry     app.index_controller.contribute(event, retry=True)   File "/var/task/azul/indexer/index_controller.py", line 142, in contribute     AzulClient().remote_reindex_partition(message)   File "/var/task/azul/azulclient.py", line 260, in remote_reindex_partition     bundle_fqids = self.list_bundles(catalog, source, prefix)   File "/var/task/azul/azulclient.py", line 216, in list_bundles     return plugin.list_bundles(source, prefix)   File "/var/task/azul/plugins/repository/tdr/__init__.py", line 207, in list_bundles     self._assert_source(source)   File "/var/task/azul/plugins/repository/tdr/__init__.py", line 201, in _assert_source     assert source.spec in self.sources, (source, self.sources) |
| 2021-07-06 17:34:13.965 | [ERROR] AssertionError: (TDRSourceRef(id='fae2ed64-aadc-447a-bee9-ab27598cf45d', spec=TDRSourceSpec(prefix='', project='broad-jade-dev-data', name='hca_dev_20210621_managedaccess_4298b4de92f34cbbbbfe5bc11b8c2422__20210622', is_snapshot=True)), frozenset({TDRSourceSpec(prefix='', project='broad-jade-dev-data', name='hca_dev_20201203___20210524_lattice', is_snapshot=True)})) Traceback (most recent call last):   File "/var/task/app.py", line 118, in new_handler     return old_handler(self, event, context)   File "/var/task/chalice/app.py", line 1459, in __call__     return self.func(event_obj)   File "/var/task/app.py", line 151, in contribute_retry     app.index_controller.contribute(event, retry=True)   File "/var/task/azul/indexer/index_controller.py", line 142, in contribute     AzulClient().remote_reindex_partition(message)   File "/var/task/azul/azulclient.py", line 260, in remote_reindex_partition     bundle_fqids = self.list_bundles(catalog, source, prefix)   File "/var/task/azul/azulclient.py", line 216, in list_bundles     return plugin.list_bundles(source, prefix)   File "/var/task/azul/plugins/repository/tdr/__init__.py", line 207, in list_bundles     self._assert_source(source)   File "/var/task/azul/plugins/repository/tdr/__init__.py", line 201, in _assert_source     assert source.spec in self.sources, (source, self.sources) |
| 2021-07-06 17:34:13.711 | [ERROR] AssertionError: (TDRSourceRef(id='fae2ed64-aadc-447a-bee9-ab27598cf45d', spec=TDRSourceSpec(prefix='', project='broad-jade-dev-data', name='hca_dev_20210621_managedaccess_4298b4de92f34cbbbbfe5bc11b8c2422__20210622', is_snapshot=True)), frozenset({TDRSourceSpec(prefix='', project='broad-jade-dev-data', name='hca_dev_20201203___20210524_lattice', is_snaps [...]

2021-07-07 00:17 UTC, amarjandu commented
IT passed, starting reindex

2021-07-07 16:02 UTC, amarjandu commented
5 failed notifications in the failed queue:
```
{
  "bundle_uuid": "c12a6ca2-3234-5182-ad0b-f8c2fb881ab5",
  "bundle_version": "2020-12-03T00:00:01.000000Z"
}
{
  "bundle_uuid": "40733888-3b9f-500e-84fd-1a18a64aadbe",
  "bundle_version": "2020-12-03T00:00:01.000000Z"
}
{
  "bundle_uuid": "94565940-7b2f-5fd7-beb1-dc309687fe09",
  "bundle_version": "2021-02-10T17:01:03.177554Z"
}
{
  "bundle_uuid": "9d0f5cd1-0ef6-5eed-8dd7-f15d36a34185",
  "bundle_version": "2020-12-03T00:00:01.000000Z"
}
{
  "bundle_uuid": "ae338c4e-650f-545b-8631-3c8d755aa2f9",
  "bundle_version": "2020-12-03T00:00:01.000000Z"
}
```

2021-07-08 16:21 UTC, hannes-ucsc commented
This should have added the snapshot to the sandbox environment, too. I'll put it back to triage for follow-up PR.