Add contentDescription field to fileTypeSummaries (#3170)
DataBiosphere/azul pull request #3179
Opened 2021-06-24 15:51 UTC by danielsotirhos

Author

- [ ] PR title references issue
- [ ] Title of main commit references issue
- [ ] PR is linked to Zenhub issue

Author (reindex)

- [ ] Added `r` tag to commit title                         <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label to PR                           <sub>or this PR does not require reindexing</sub>

Author (freebies & chains)

- [ ] Freebies are blocked on this PR                       <sub>or there are no freebies in this PR</sub>
- [ ] Freebies are referenced in commit titles              <sub>or there are no freebies in this PR</sub>
- [ ] This PR is blocked by previous PR in the chain        <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chain` label to the blocking PR                <sub>or this PR is not chained to another PR</sub>

Author (upgrading)

- [ ] Documented upgrading of deployments in UPGRADING.rst  <sub>or this PR does not require upgrading</sub>
- [ ] Added `u` tag to commit title                         <sub>or this PR does not require upgrading</sub>
- [ ] Added `upgrade` label to PR                           <sub>or this PR does not require upgrading</sub>

Author (requirements, before every review)

- [ ] Ran `make requirements_update`                        <sub>or this PR leaves requirements*.txt, common.mk and Makefile untouched</sub>
- [ ] Added `R` tag to commit title                         <sub>or this PR leaves requirements*.txt untouched</sub>
- [ ] Added `reqs` label to PR                              <sub>or this PR leaves requirements*.txt untouched</sub>

Author (before every review)

- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>
- [ ] Rebased branch on `develop`, squashed old fixups

Primary reviewer (after approval)

- [ ] Commented in issue about demo expectations            <sub>or labelled issue as `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] Moved ticket to Approved column
- [ ] Assigned PR to an operator

Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear              <sub>or issue is labeled as `no demo`</sub>
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Pushed PR branch to Github
- [ ] Branch pushed to Gitlab                               <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in sandbox and added `sandbox` label     <sub>or PR is labeled `no sandbox`</sub>
- [ ] Started reindex in `sandbox`                          <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox`                     <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title
- [ ] Moved linked issue to Merged column
- [ ] Pushed merge commit to Github

Operator (after pushing the merge commit)

- [ ] Moved freebies to Merged column                       <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened the PR chain                                <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [ ] Pushed merge commit to Gitlab                         <sub>or this changes can be pushed later, together with another PR</sub>
- [ ] Deleted PR branch from Github and Gitlab

Operator (reindex) 

- [ ] Started reindex in `dev`                              <sub>or this PR does not require reindexing or does not target `dev`</sub>
- [ ] Checked for failures in `dev`                         <sub>or this PR does not require reindexing or does not target `dev`</sub>
- [ ] Started reindex in `prod`                             <sub>or this PR does not require reindexing or does not target `prod`</sub>
- [ ] Checked for failures in `prod`                        <sub>or this PR does not require reindexing or does not target `prod`</sub>

Operator

- [ ] Unassigned PR

2021-06-24 17:39 UTC, achave11 approved these changes
LGTM

2021-06-25 01:22 UTC, hannes-ucsc requested changes
Now the big question is if DB wants to group the the fileTypeSummary by content description or not. Could you ask them on Slack and ping me?

2021-06-26 02:29 UTC, hannes-ucsc approved these changes

2021-06-26 02:34 UTC, hannes-ucsc requested changes
This changes the API semantics and is potentially backwards incompatible. Could you ask the DB team how they prefer us to handle the deployment? Last time I requested to be pinged on the conversation, please make sure you do so this time. No bump.

2021-07-01 15:51 UTC, danielsotirhos commented
> Could you ask the DB team how they prefer us to handle the deployment? 

https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1625096980236300?thread_ts=1625096958.236100&cid=C705Y6G9Z

2021-07-02 16:56 UTC, hannes-ucsc requested changes

2021-07-02 16:56 UTC, hannes-ucsc commented on test/indexer/data/fa5be5eb-2d64-49f5-8ed8-bd627ac9bc7a.metadata.json
> +            "content_description": [
The problem is that the [declared schema](http://schema.staging.data.humancellatlas.org/type/file/7.0.2/sequence_file) does not allow this. Can we cover this differently? We should also cover the grouping aspect. There are a few canned bundles that already have `content_description` so maybe we need to bite the bullet and add a test specifically for `fileTypeSummaries`.

2021-07-07 21:05 UTC, hannes-ucsc approved these changes

2021-07-07 23:10 UTC, merged