Apply source filter to /index/summary (#3298)
DataBiosphere/azul pull request #3300
Opened 2021-08-04 23:46 UTC by noah-aviel-dove

Author

- [x] PR title references issue
- [x] Title of main commit references issue
- [ ] PR is linked to Zenhub issue

Author (reindex)

- [x] Added `r` tag to commit title                         <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label to PR                           <sub>or this PR does not require reindexing</sub>

Author (freebies & chains)

- [x] Freebies are blocked on this PR                       <sub>or there are no freebies in this PR</sub>
- [x] Freebies are referenced in commit titles              <sub>or there are no freebies in this PR</sub>
- [ ] This PR is blocked by previous PR in the chain        <sub>or this PR is not chained to another PR</sub>
- [x] Added `chain` label to the blocking PR                <sub>or this PR is not chained to another PR</sub>

Author (upgrading)

- [x] Documented upgrading of deployments in UPGRADING.rst  <sub>or this PR does not require upgrading</sub>
- [x] Added `u` tag to commit title                         <sub>or this PR does not require upgrading</sub>
- [x] Added `upgrade` label to PR                           <sub>or this PR does not require upgrading</sub>

Author (requirements, before every review)

- [x] Ran `make requirements_update`                        <sub>or this PR leaves requirements*.txt, common.mk and Makefile untouched</sub>
- [x] Added `R` tag to commit title                         <sub>or this PR leaves requirements*.txt untouched</sub>
- [x] Added `reqs` label to PR                              <sub>or this PR leaves requirements*.txt untouched</sub>

Author (before every review)

- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>
- [ ] Rebased branch on `develop`, squashed old fixups

Primary reviewer (after approval)

- [ ] Commented in issue about demo expectations            <sub>or labelled issue as `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] Moved ticket to Approved column
- [ ] Assigned PR to an operator

Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear              <sub>or issue is labeled as `no demo`</sub>
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Pushed PR branch to Github
- [ ] Branch pushed to Gitlab and added `sandbox` label     <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passed in sandbox                               <sub>or PR is labeled `no sandbox`</sub>
- [ ] Started reindex in `sandbox`                          <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox`                     <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title
- [ ] Moved linked issue to Merged column
- [ ] Pushed merge commit to Github

Operator (after pushing the merge commit)

- [ ] Moved freebies to Merged column                       <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened the PR chain                                <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [ ] Pushed merge commit to Gitlab                         <sub>or this changes can be pushed later, together with another PR</sub>
- [ ] Deleted PR branch from Github and Gitlab

Operator (reindex) 

- [ ] Started reindex in `dev`                              <sub>or this PR does not require reindexing or does not target `dev`</sub>
- [ ] Checked for failures in `dev`                         <sub>or this PR does not require reindexing or does not target `dev`</sub>
- [ ] Started reindex in `prod`                             <sub>or this PR does not require reindexing or does not target `prod`</sub>
- [ ] Checked for failures in `prod`                        <sub>or this PR does not require reindexing or does not target `prod`</sub>

Operator

- [ ] Unassigned PR

2021-08-07 01:13 UTC, noah-aviel-dove commented
Retracting review because I need to re-think the chain

2021-08-09 16:27 UTC, danielsotirhos approved these changes
LGTM

2021-08-11 09:12 UTC, noah-aviel-dove commented
Re-requesting peer review since the upstream branch has changed and an integration test has been added.

2021-08-11 15:58 UTC, danielsotirhos requested changes
Look good. Just one nitpick about the fixme.

2021-08-11 15:58 UTC, danielsotirhos commented on test/integration_test.py
> +            # FIXME: https://github.com/DataBiosphere/azul/issues/3318
```suggestion
            # FIXME: fileCount doesn't equal the sum of fileTypeSummaries[].count
                     https://github.com/DataBiosphere/azul/issues/3318
```

The FIXME should be placed where `fileCount` and/or `fileTypeSummaries[].count` are calculated.

2021-08-12 16:06 UTC, danielsotirhos requested changes
A practice we started this year when adding FIXMEs is to either include the FIXME ticket number in the commit title, or better yet add the FIXME comment(s) in a separate commit with a title such as "Add FIXME (#3318)"

See: https://github.com/DataBiosphere/azul/pull/3210#pullrequestreview-703039596

```
(.venv) daniel@Crispin ~/repo/azul2 $ git log --pretty=format:"%h %cs %s" --date=short | grep FIXME
5968185f 2021-08-09 FIXME (#3291)
147cfa4f 2021-07-21 Add FIXME (#3152)
5c8e396d 2021-06-17 Add FIXME (#3071)
23cd201b 2021-05-25 FIXME: Consolidate base URL composition in tests (#3008)
a9428a1e 2021-05-10 Fix: FIXME references closed ticket (#2829, PR #3030)
dcae30ea 2021-05-10 Fix: FIXME references closed ticket (#2829)
9c23cb7f 2021-04-30 Add FIXME for prefix tooling (#3027)
4e5d4c37 2021-04-30 Add FIXME to rename SourceName (#2843)
...
```

2021-09-14 17:17 UTC, danielsotirhos requested changes

2021-09-14 17:17 UTC, danielsotirhos commented on test/integration_test.py
> +            response = self._get_url_json(str(url))
The change to `url` seems unnecessary for this PR and doesn't match how `summary_url` is composed and used soon after.

2021-10-01 06:57 UTC, noah-aviel-dove commented
When I rebased, the original fixup commit to adjust the requested changes disappeared during conflict resolution, since that part of the code needed to re-written anyway. The new fixup is unrelated, I just realized after pushing that #3318 had already been fixed.

2021-10-01 18:04 UTC, danielsotirhos approved these changes

2021-10-09 10:31 UTC, noah-aviel-dove commented
The `fixup!` is to address a bug that very rarely caused an IT failure which I found after fixing the conflicts.

2021-11-08 23:44 UTC, hannes-ucsc requested changes

2021-11-08 23:44 UTC, hannes-ucsc commented on src/azul/service/source_controller.py
> +            self._add_implicit_sources_filter(filters, source_ids)
This has nothing to do with parsing. The fact that the parsing of filters is done in close proximity to the application of the source filter is incidental and shouldn't lead to a conflation of the two operations.

2021-11-09 20:22 UTC, noah-aviel-dove commented on src/azul/service/repository_service.py
> +            entity_filters = (original_filters
Decided at parking lot to move `_add_implicit_sources_filter` to service layer (remove from `SourceController`)

2021-11-15 19:22 UTC, hannes-ucsc approved these changes

2021-11-16 03:39 UTC, merged