Fix: Samples don't reflect downstream entities from stitched subgraphs (#3095)
DataBiosphere/azul pull request #3375
Opened 2021-08-26 03:15 UTC by noah-aviel-dove

https://github.com/DataBiosphere/azul/issues/3095

Author

- [x] PR title references issue
- [x] PR title matches issue title (preceded by `Fix: ` for bugs)   <sub>or there is a good reason why they're different</sub>
- [x] Title of main commit references issue
- [x] PR is connected to Zenhub issue and description links to issue

Author (reindex)

- [x] Added `r` tag to commit title                         <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label to PR                           <sub>or this PR does not require reindexing</sub>

Author (freebies & chains)

- [x] Freebies are blocked on this PR                       <sub>or there are no freebies in this PR</sub>
- [x] Freebies are referenced in commit titles              <sub>or there are no freebies in this PR</sub>
- [x] This PR is blocked by previous PR in the chain        <sub>or this PR is not chained to another PR</sub>
- [x] Added `chain` label to the blocking PR                <sub>or this PR is not chained to another PR</sub>

Author (upgrading)

- [x] Documented upgrading of deployments in UPGRADING.rst  <sub>or this PR does not require upgrading</sub>
- [x] Added `u` tag to commit title                         <sub>or this PR does not require upgrading</sub>
- [x] Added `upgrade` label to PR                           <sub>or this PR does not require upgrading</sub>
- [x] Added announcement to PR description                  <sub>or this PR does not require announcement</sub>

Author (requirements, before every review)

- [x] Ran `make requirements_update`                        <sub>or this PR leaves requirements*.txt, common.mk and Makefile untouched</sub>
- [x] Added `R` tag to commit title                         <sub>or this PR leaves requirements*.txt untouched</sub>
- [x] Added `reqs` label to PR                              <sub>or this PR leaves requirements*.txt untouched</sub>

Author (before every review)

- [x] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>
- [x] Rebased branch on `develop`, squashed old fixups

Primary reviewer (after approval)

- [x] Commented in issue about demo expectations            <sub>or labelled issue as `no demo`</sub>
- [x] Decided if PR can be labeled `no sandbox`
- [x] PR title is appropriate as title of merge commit
- [x] Moved ticket to Approved column
- [x] Assigned PR to an operator

Operator (before pushing merge the commit)

- [x] Checked `reindex` label and `r` commit title tag
- [x] Checked that demo expectations are clear              <sub>or issue is labeled as `no demo`</sub>
- [x] Rebased and squashed branch
- [x] Sanity-checked history
- [x] Pushed PR branch to Github
- [x] Branch pushed to Gitlab and added `sandbox` label     <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passed in sandbox                               <sub>or PR is labeled `no sandbox`</sub>
- [x] Started reindex in `sandbox`                          <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Checked for failures in `sandbox`                     <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Added PR reference to merge commit title
- [x] Collected commit title tags in merge commit title
- [x] Moved linked issue to Merged column
- [x] Pushed merge commit to Github

Operator (after pushing the merge commit)

- [ ] Made announcement requested by author                 <sub>or PR description does not contain an announcement</sub>
- [ ] Moved freebies to Merged column                       <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened the PR chain                                <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [ ] Pushed merge commit to Gitlab                         <sub>or this changes can be pushed later, together with another PR</sub>
- [ ] Deleted PR branch from Github and Gitlab

Operator (reindex) 

- [ ] Started reindex in `dev`                              <sub>or this PR does not require reindexing or does not target `dev`</sub>
- [ ] Checked for failures in `dev`                         <sub>or this PR does not require reindexing or does not target `dev`</sub>
- [ ] Started reindex in `prod`                             <sub>or this PR does not require reindexing or does not target `prod`</sub>
- [ ] Checked for failures in `prod`                        <sub>or this PR does not require reindexing or does not target `prod`</sub>

Operator

- [ ] Unassigned PR

2021-10-29 22:26 UTC, noah-aviel-dove commented
Repeat Hannes's patching of the unit tests (https://github.com/DataBiosphere/azul/issues/2868#issuecomment-792501645) and check the actual size of the contributions for the bundle that he analyzed.

2021-11-03 11:06 UTC, noah-aviel-dove commented
I repeated [@hannes-ucsc 's analysis of contribution size] from the issue we're hoping to avoid re-invoking, and the results look good. The largest contribution for the bundle is only 321 KB.

```
$ git show --name-only --oneline
c6adb852 (HEAD -> issues/noah-aviel-dove/3095-missing-samples, github/issues/noah-aviel-dove/3095-missing-samples) Emit contributions for stitched samples (#3095)
src/azul/plugins/metadata/hca/transform.py
$ git diff
diff --git a/test/indexer/test_projects.py b/test/indexer/test_projects.py
index abda96f1..e4ef1c4b 100644
--- a/test/indexer/test_projects.py
+++ b/test/indexer/test_projects.py
@@ -105,6 +105,14 @@ class TestDataExtractorTestCase(IndexerTestCase):
                     self.assertEqual(num_files, len(file_ids))
                     self.assertEqual(num_files, len(set(file_ids)))
 
+    def test_debug_large_bundles(self):
+        import azul.indexer
+        from azul.plugins.repository.local import LocalSourceRef
+        spec = azul.indexer.SimpleSourceSpec.parse('data/:')
+        self._index_canned_bundle(azul.indexer.SourcedBundleFQID(source=LocalSourceRef(id=spec.name, spec=spec),
+                                                                 uuid='9697e762-96f2-5949-af7e-12fb4c4f22d0',
+                                                                 version='2021-02-08T10:30:00.000000Z'))
+
 
 if __name__ == "__main__":
     unittest.main()
```

With a breakpoint in `azul.indexer.index_service.IndexService.Index`:

![Screenshot from 2021-11-03 04-05-09](https://user-images.githubusercontent.com/48401926/140049656-baee6d8b-c7f7-4e1d-a331-2b53960db8a2.png)

2021-11-03 18:09 UTC, danielsotirhos requested changes
With this set in my environment.py
```
        'AZUL_CATALOGS': json.dumps({
            'it0largebundles': dict(atlas='hca',
                                    internal=True,
                                    plugins=dict(metadata=dict(name='hca'),
                                                 repository=dict(name='local')),
                                    sources=[
                                        'data/:'
                                    ]),
        }),
```
my run of IT failed with
```
======================================================================
ERROR: test_indexing (integration_test.IndexingIntegrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/daniel/repo/azul3/test/azul_test_case.py", line 154, in wrapped
    return method(*args, **kwargs)
  File "/Users/daniel/repo/azul3/test/integration_test.py", line 340, in test_indexing
    _wait_for_indexer()
  File "/Users/daniel/repo/azul3/test/integration_test.py", line 319, in _wait_for_indexer
    self.azul_client.wait_for_indexer()
  File "/Users/daniel/repo/azul3/src/azul/azulclient.py", line 481, in wait_for_indexer
    self.queues.wait_to_stabilize()
  File "/Users/daniel/repo/azul3/src/azul/queues.py", line 261, in wait_to_stabilize
    raise Exception('The queues have stalled', final_length)
Exception: ('The queues have stalled', 13)
```
[it-failure-full-log.txt](https://github.com/DataBiosphere/azul/files/7469852/it-failure-full-log.txt)

2021-11-04 02:43 UTC, noah-aviel-dove commented
The stall doesn't happen consistently for me, although I did see it once. The queues do eventually empty for me without errors.

2021-11-04 17:19 UTC, danielsotirhos approved these changes
Approved.

2021-11-04 22:23 UTC, hannes-ucsc requested changes

2021-11-04 22:23 UTC, hannes-ucsc commented on src/azul/plugins/repository/local/__init__.py
> +        files = directory.glob(f'{source_prefix}{prefix}*{self._manifest_ext}')
These files would be included in the Chalice `deployment.zip` and would have to be unpacked every time AWS Lambda initializes a Lambda execution context (a Docker container). Please move this source file and the cans to the attic …

2021-11-04 22:23 UTC, hannes-ucsc commented on test/integration_test.py
> +                self._test_repository_files(catalog.name)
… and remove this …

2021-11-04 22:23 UTC, hannes-ucsc commented on test/integration_test.py
> -            if catalog.is_integration_test_catalog:
... and this, all in a separate commit so the history looks like this:

1) Add local plugin
2) Add cans
3) Move cans and local plugin to attic
4) Main commit

2021-11-05 17:32 UTC, hannes-ucsc requested changes
Let's add a unit test for the smallest of the cans. The commit that adds the test should move the can out of the attic into the test data directory, it should precede the main commit, and pushed independently so I can see the assertion fail and then pass for the main commit.

2021-11-08 22:59 UTC, hannes-ucsc requested changes

2021-11-08 22:59 UTC, hannes-ucsc commented on test/indexer/test_hca_indexer.py
> +            # Stitched downstream samples
```suggestion
            # Stitched upstream samples
```

2021-11-08 22:59 UTC, hannes-ucsc commented on test/indexer/test_hca_indexer.py
> +            'f5d590c5-b307-4b99-af98-8ddba1e2a266'
This only proves that something is contributed to the upstream samples, but not what. The test should assert the expectation from the issue description. And if possible I would like the assertion to be less literal.

2021-11-15 19:32 UTC, hannes-ucsc requested changes
And let's completely remove the other cans in the attic from the history so they don't take up any space in the repo. They're just a little too big compared to the value they add.

2021-11-15 19:32 UTC, hannes-ucsc commented on test/indexer/test_hca_indexer.py
> +        self.assertEqual(len(samples), 15)
expectation should be first argument

2021-11-15 19:32 UTC, hannes-ucsc commented on test/indexer/test_hca_indexer.py
> +            analysis_file_formats = [
```suggestion
            analysis_file_formats = {
```

2021-11-15 19:32 UTC, hannes-ucsc commented on test/indexer/test_hca_indexer.py
> +            ]
```suggestion
            }
```

2021-11-15 19:32 UTC, hannes-ucsc commented on test/indexer/test_hca_indexer.py
> +            self.assertIn('bam', analysis_file_formats)
```suggestion
            self.assertEquals({'bam', 'loom', …} , analysis_file_formats)
```

2021-11-30 05:41 UTC, hannes-ucsc requested changes
The big cans need to be squashed out completely. As long as there is a commit reachable from the develop branch that has those large files (and there would be if we merged this as is), they will take up space in the repository. I wasn't clear about this so no bump. And I would like to see the commit that adds the test and the one that adds the fix to be pushed separately, one more time. Don't need fixups this time.

2021-11-30 17:33 UTC, hannes-ucsc approved these changes

2021-11-30 17:34 UTC, hannes-ucsc requested changes
This does require reindexing to fix the index, so the last commit should carry the `[r]` tag, and the PR the `reindex` label.

2021-12-01 21:42 UTC, hannes-ucsc approved these changes

2021-12-01 21:44 UTC, hannes-ucsc commented
If we promote this today, we would have a genuine reason for reindexing.

2021-12-01 22:59 UTC, merged