Convert datetime values to strings before indexing (#3416)
DataBiosphere/azul pull request #3419
Opened 2021-09-10 17:04 UTC by danielsotirhos

https://github.com/DataBiosphere/azul/issues/3416

Author

- [ ] PR title references issue
- [ ] PR title matches issue title (preceded by `Fix: ` for bugs)   <sub>or there is a good reason why they're different</sub>
- [ ] Title of main commit references issue
- [ ] PR is connected to Zenhub issue and description links to issue

Author (reindex)

- [ ] Added `r` tag to commit title                         <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label to PR                           <sub>or this PR does not require reindexing</sub>

Author (freebies & chains)

- [ ] Freebies are blocked on this PR                       <sub>or there are no freebies in this PR</sub>
- [ ] Freebies are referenced in commit titles              <sub>or there are no freebies in this PR</sub>
- [ ] This PR is blocked by previous PR in the chain        <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chain` label to the blocking PR                <sub>or this PR is not chained to another PR</sub>

Author (upgrading)

- [ ] Documented upgrading of deployments in UPGRADING.rst  <sub>or this PR does not require upgrading</sub>
- [ ] Added `u` tag to commit title                         <sub>or this PR does not require upgrading</sub>
- [ ] Added `upgrade` label to PR                           <sub>or this PR does not require upgrading</sub>
- [ ] Added announcement to PR description                  <sub>or this PR does not require announcement</sub>

Author (requirements, before every review)

- [ ] Ran `make requirements_update`                        <sub>or this PR leaves requirements*.txt, common.mk and Makefile untouched</sub>
- [ ] Added `R` tag to commit title                         <sub>or this PR leaves requirements*.txt untouched</sub>
- [ ] Added `reqs` label to PR                              <sub>or this PR leaves requirements*.txt untouched</sub>

Author (before every review)

- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>
- [ ] Rebased branch on `develop`, squashed old fixups

Primary reviewer (after approval)

- [ ] Commented in issue about demo expectations            <sub>or labelled issue as `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] Moved ticket to Approved column
- [ ] Assigned PR to an operator

Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear              <sub>or issue is labeled as `no demo`</sub>
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Pushed PR branch to Github
- [ ] Branch pushed to Gitlab and added `sandbox` label     <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passed in sandbox                               <sub>or PR is labeled `no sandbox`</sub>
- [ ] Started reindex in `sandbox`                          <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox`                     <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title
- [ ] Moved linked issue to Merged column
- [ ] Pushed merge commit to Github

Operator (after pushing the merge commit)

- [ ] Made announcement requested by author                 <sub>or PR description does not contain an announcement</sub>
- [ ] Moved freebies to Merged column                       <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened the PR chain                                <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [ ] Pushed merge commit to Gitlab                         <sub>or this changes can be pushed later, together with another PR</sub>
- [ ] Deleted PR branch from Github and Gitlab

Operator (reindex) 

- [ ] Started reindex in `dev`                              <sub>or this PR does not require reindexing or does not target `dev`</sub>
- [ ] Checked for failures in `dev`                         <sub>or this PR does not require reindexing or does not target `dev`</sub>
- [ ] Started reindex in `prod`                             <sub>or this PR does not require reindexing or does not target `prod`</sub>
- [ ] Checked for failures in `prod`                        <sub>or this PR does not require reindexing or does not target `prod`</sub>

Operator

- [ ] Unassigned PR

2021-09-14 23:57 UTC, achave11 approved these changes
Looks good. Only made an optional suggestion.

2021-09-14 23:57 UTC, achave11 commented on src/azul/indexer/document.py
> +            parse_dcp2_datetime(value)  # to verify a valid dcp2 datetime string
I am not sure that this comment is necessary. Up to you.

2021-09-17 05:05 UTC, hannes-ucsc requested changes

2021-09-17 05:05 UTC, hannes-ucsc commented on src/azul/time.py
> +    else:
A fixpoint like this is a smell. If None is a fixpoint in one function why is it not a fixpoint of every function? 

Also, format and parse functions should be each other's inverse and this breaks that.

2021-09-17 23:26 UTC, hannes-ucsc requested changes

2021-09-17 23:26 UTC, hannes-ucsc commented on src/azul/plugins/metadata/hca/transform.py
> +            'update_date': update_date,
```suggestion
            'update_date': None
                           if entity.update_date is None else
                           format_dcp2_datetime(entity.update_date),
```

2021-09-17 23:26 UTC, hannes-ucsc commented on src/azul/time.py
> +
```suggestion
```

2021-09-21 23:04 UTC, hannes-ucsc approved these changes

2021-09-22 20:06 UTC, merged

2021-09-23 16:41 UTC, jessebrennan commented
Failures during reindexing in dev:
```
[
  {
    "spec": "tdr:broad-jade-dev-data:snapshot/hca_dev_20201203___20210524_lattice:/2",
    "uuid": "40733888-3b9f-500e-84fd-1a18a64aadbe"
  },
  {
    "spec": "tdr:broad-jade-dev-data:snapshot/hca_dev_20201203___20210524_lattice:/2",
    "uuid": "94565940-7b2f-5fd7-beb1-dc309687fe09"
  },
  {
    "spec": "tdr:broad-jade-dev-data:snapshot/hca_dev_20201203___20210524_lattice:/2",
    "uuid": "9d0f5cd1-0ef6-5eed-8dd7-f15d36a34185"
  },
  {
    "spec": "tdr:broad-jade-dev-data:snapshot/hca_dev_20201203___20210524_lattice:/2",
    "uuid": "ae338c4e-650f-545b-8631-3c8d755aa2f9"
  },
  {
    "spec": "tdr:broad-jade-dev-data:snapshot/hca_dev_20201203___20210524_lattice:/2",
    "uuid": "c12a6ca2-3234-5182-ad0b-f8c2fb881ab5"
  }
]
```
These failure are expected because of:
- https://github.com/DataBiosphere/azul/issues/2870
- https://github.com/DataBiosphere/azul/issues/2873

2021-09-23 16:51 UTC, hannes-ucsc commented
What's `uuid` above?

2021-09-23 18:36 UTC, jessebrennan commented
It's the bundle UUID. To produce this I ran:
```
jq '[.messages[].Body.notification|{"spec": .source.spec, "uuid": .match.bundle_uuid}]' azul-notifications_fail-dev.json 
```