Fix: TDR dev dataset is stale (HumanCellAtlas/dcp2#17)
DataBiosphere/azul pull request #3441
Opened 2021-09-17 18:22 UTC by jessebrennan

https://github.com/HumanCellAtlas/dcp2/issues/17

Author

- [ ] PR title references issue
- [ ] PR title matches issue title (preceded by `Fix: ` for bugs)   <sub>or there is a good reason why they're different</sub>
- [ ] Title of main commit references issue
- [ ] PR is connected to Zenhub issue and description links to issue

Author (reindex)

- [ ] Added `r` tag to commit title                         <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label to PR                           <sub>or this PR does not require reindexing</sub>

Author (freebies & chains)

- [ ] Freebies are blocked on this PR                       <sub>or there are no freebies in this PR</sub>
- [ ] Freebies are referenced in commit titles              <sub>or there are no freebies in this PR</sub>
- [ ] This PR is blocked by previous PR in the chain        <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chain` label to the blocking PR                <sub>or this PR is not chained to another PR</sub>

Author (upgrading)

- [ ] Documented upgrading of deployments in UPGRADING.rst  <sub>or this PR does not require upgrading</sub>
- [ ] Added `u` tag to commit title                         <sub>or this PR does not require upgrading</sub>
- [ ] Added `upgrade` label to PR                           <sub>or this PR does not require upgrading</sub>
- [ ] Added announcement to PR description                  <sub>or this PR does not require announcement</sub>

Author (requirements, before every review)

- [ ] Ran `make requirements_update`                        <sub>or this PR leaves requirements*.txt, common.mk and Makefile untouched</sub>
- [ ] Added `R` tag to commit title                         <sub>or this PR leaves requirements*.txt untouched</sub>
- [ ] Added `reqs` label to PR                              <sub>or this PR leaves requirements*.txt untouched</sub>

Author (before every review)

- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>
- [ ] Rebased branch on `develop`, squashed old fixups

Primary reviewer (after approval)

- [ ] Commented in issue about demo expectations            <sub>or labelled issue as `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] Moved ticket to Approved column
- [ ] Assigned PR to an operator

Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear              <sub>or issue is labeled as `no demo`</sub>
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Pushed PR branch to Github
- [ ] Branch pushed to Gitlab and added `sandbox` label     <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passed in sandbox                               <sub>or PR is labeled `no sandbox`</sub>
- [ ] Started reindex in `sandbox`                          <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox`                     <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title
- [ ] Moved linked issue to Merged column
- [ ] Pushed merge commit to Github

Operator (after pushing the merge commit)

- [ ] Made announcement requested by author                 <sub>or PR description does not contain an announcement</sub>
- [ ] Moved freebies to Merged column                       <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened the PR chain                                <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [ ] Pushed merge commit to Gitlab                         <sub>or this changes can be pushed later, together with another PR</sub>
- [ ] Deleted PR branch from Github and Gitlab

Operator (reindex) 

- [ ] Started reindex in `dev`                              <sub>or this PR does not require reindexing or does not target `dev`</sub>
- [ ] Checked for failures in `dev`                         <sub>or this PR does not require reindexing or does not target `dev`</sub>
- [ ] Started reindex in `prod`                             <sub>or this PR does not require reindexing or does not target `prod`</sub>
- [ ] Checked for failures in `prod`                        <sub>or this PR does not require reindexing or does not target `prod`</sub>

Operator

- [ ] Unassigned PR

2021-09-17 21:20 UTC, amarjandu commented on deployments/sandbox/environment.py
> +            'tdr:datarepo-dev-d4b988d6:snapshot/hca_dev_a004b1501c364af69bbd070c06dbc17d__20210830_20210903:4',
We might want to remove the common prefix.

2021-09-20 18:30 UTC, amarjandu commented on deployments/sandbox/environment.py
> +            'tdr:datarepo-dev-d4b988d6:snapshot/hca_dev_a004b1501c364af69bbd070c06dbc17d__20210830_20210903:4',
for this snapshot, there are 16 total links, and 1 under the uuid 4.

2021-09-20 18:32 UTC, amarjandu commented on deployments/sandbox/environment.py
> +            'tdr:datarepo-dev-02c59b72:snapshot/hca_dev_99101928d9b14aafb759e97958ac7403__20210830_20210903:4',
1190 links total, 84 under the common prefix `4`

2021-09-20 23:46 UTC, jessebrennan commented
Since we can't attach this to its ticket via Zenhub because of a permissions issue @hannes-ucsc mentioned, I'm assigning myself so that it stays on my board.

2021-09-20 23:50 UTC, amarjandu requested changes
Need to update google project id.

2021-09-20 23:50 UTC, amarjandu commented on deployments/sandbox/environment.py
> +            'tdr:datarepo-dev-87beea11:snapshot/hca_dev_ae71be1dddd84feb9bed24c3ddb6e1ad__20210916_20210916:4',
The project name is wrong here. `datarepo-dev-1dce87e5` should be used.
TDR team updated the spreadsheet. 
https://docs.google.com/spreadsheets/d/1yYiB3TrX0wvLCHvtWY1GTZZcAf5MmMREgn52OKCHsqs/edit#gid=1005857707

2021-09-20 23:50 UTC, amarjandu commented on deployments/dev/environment.py
> +            'tdr:datarepo-dev-87beea11:snapshot/hca_dev_ae71be1dddd84feb9bed24c3ddb6e1ad__20210916_20210916:',
here too

2021-09-21 16:40 UTC, amarjandu approved these changes

2021-09-21 17:35 UTC, hannes-ucsc requested changes

2021-09-21 17:35 UTC, hannes-ucsc commented on deployments/dev/environment.py
> +            'tdr:datarepo-dev-02c59b72:snapshot/hca_dev_99101928d9b14aafb759e97958ac7403__20210830_20210903:',
I changed my mind. We should list these in the same order as they occur in the spreadsheet.

Each of the two MA sources should have the comment

```
# Managed access:
```

preceding it.

2021-09-21 18:32 UTC, hannes-ucsc requested changes

2021-09-21 18:32 UTC, hannes-ucsc commented on deployments/dev/environment.py
> +            'tdr:datarepo-dev-02c59b72:snapshot/hca_dev_99101928d9b14aafb759e97958ac7403__20210830_20210903:',
Not consistent with sheet:

![image](https://user-images.githubusercontent.com/5143256/134227530-ca9bcc08-2044-457a-acc8-1609d431fbf1.png)

2021-09-21 22:57 UTC, hannes-ucsc requested changes
Won't review until solution for #3448 lands. Need written assertion that this works in author's personal deployment.

2021-09-30 00:40 UTC, jessebrennan commented
When trying to test this in my personal deployment I encountered this error during the Terraform deploy stage for each lambda function:
```
Error: Error modifying Lambda Function Configuration azul-indexer-jesse1-indexercachehealth: RequestEntityTooLargeException: 
        status code: 413, request id: d202cbf6-19de-4ac3-81ee-93bbead087f7

  on indexer/chalice.tf.json line 74, in resource[0].aws_lambda_function[0].indexercachehealth:
  74:                     }
```

The [AWS docs](https://docs.aws.amazon.com/lambda/latest/dg/troubleshooting-deployment.html#troubleshooting-deployment-InvalidParameterValueException1) explain:
>The maximum size of the variables object that is stored in the function's configuration must not exceed 4096 bytes

Counting the number of characters in the formatted JSON representation of this object I got 15394 bytes. Stripping out whitespace removes only ~1500 bytes.

Removing the `AZUL_TDR_SOURCES` variable but keeping whitespaces give 4088 bytes. Because of this, I assume that whitespace is automatically stripped out before this is uploaded to AWS.

Nonetheless, we need to figure out a new way to store the environment, or perhaps compress it, if we want to index all of these snapshots.

2021-10-01 20:54 UTC, jessebrennan commented
```

Error: Creating CloudWatch Log Group failed: ResourceAlreadyExistsException: The specified log group already exists:  The CloudWatch Log Group '/aws/apigateway/azul-indexer-jesse1' already exists.

  on api_gateway.tf.json line 140, in resource[6].aws_cloudwatch_log_group[0].indexer:
 140:                     }



Error: Creating CloudWatch Log Group failed: ResourceAlreadyExistsException: The specified log group already exists:  The CloudWatch Log Group '/aws/apigateway/azul-service-jesse1' already exists.

  on api_gateway.tf.json line 385, in resource[15].aws_cloudwatch_log_group[0].service:
 385:                     }


make[1]: *** [Makefile:31: apply] Error 1
make[1]: Leaving directory '/home/jesse/gi/azul/terraform'
make: *** [Makefile:81: deploy] Error 2
```
occurred while deploying in personal deployment. Not sure if this is related.

2021-10-02 00:29 UTC, hannes-ucsc approved these changes

2021-10-02 00:30 UTC, hannes-ucsc commented
I'll provide demo instructions later.

2021-10-02 01:29 UTC, noah-aviel-dove commented
Failed in GitLab due to inconsistent snapshot storage locations: https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/30152

The offending snapshots (`location != 'US'`) are 

```
TDRClient.TDRSource(project='datarepo-dev-bdc9f342', id='d5222430-0f7a-4bd1-8706-c58b4397a9b8', location='us-central1')
TDRClient.TDRSource(project='datarepo-dev-12b7a9e1', id='58a0eacf-0caa-449b-9fc8-4fe629e99176', location='us-central1')
TDRClient.TDRSource(project='datarepo-dev-02c59b72', id='cddb722a-4229-47bb-ba86-736b7898406f', location='us-central1')
TDRClient.TDRSource(project='datarepo-dev-71926fdc', id='403ef1b1-7b7f-4e13-bf4a-d898f047310a', location='us-central1')
TDRClient.TDRSource(project='datarepo-dev-dbc582d9', id='79f24905-a9e2-4328-91da-fc18036b77eb', location='us-central1')
TDRClient.TDRSource(project='datarepo-dev-10f0610a', id='2c5901f6-67bf-40cc-aea1-621a60c19baa', location='us-central1')
TDRClient.TDRSource(project='datarepo-dev-71de019e', id='768c4624-c07b-4496-8b7b-76275a149774', location='us-central1')
TDRClient.TDRSource(project='datarepo-dev-78bae095', id='f142a2f7-4c50-458d-a047-27bdb8e0d367', location='us-central1')
TDRClient.TDRSource(project='datarepo-dev-a9252919', id='90c2d68f-a000-4c8d-a493-8be93a71b44d', location='us-central1')
TDRClient.TDRSource(project='datarepo-dev-1c2c69d9', id='c594fc9a-f1c5-4770-acaa-013c2852e660', location='us-central1')
TDRClient.TDRSource(project='datarepo-dev-a198b032', id='38c7e1c4-db48-4cd7-bdf2-36bebc169eac', location='us-central1')
TDRClient.TDRSource(project='datarepo-dev-d4b988d6', id='2c4ec571-f489-4277-b215-da8dedd86803', location='us-central1')
TDRClient.TDRSource(project='datarepo-dev-7b7daff7', id='385eb563-005e-43ed-adb7-d3c9e0a8ae93', location='us-central1')
```

2021-10-02 03:52 UTC, merged

2021-10-04 06:13 UTC, hannes-ucsc commented
Reindex in `dev` resulted in 16 failed notifications, no failed tallies.

Due to the catalog duplication, there are 8 distinct failures.

7 tracked in https://github.com/HumanCellAtlas/dcp2/issues/45
1 tracked in https://github.com/HumanCellAtlas/dcp2/issues/48

2021-10-04 16:14 UTC, hannes-ucsc commented
@jessebrennan, the checklist item "Announce whether reindexing these snapshots succeeded or failed" is lacking the information *where* to announce that.

2021-10-04 16:20 UTC, hannes-ucsc commented
I made the announcement: https://humancellatlas.slack.com/archives/C01360XN04S/p1633364377176400?thread_ts=1631840213.076200&cid=C01360XN04S

2021-10-04 16:52 UTC, hannes-ucsc commented on UPGRADING.rst
> +    python scripts/reindex.py --delete --catalog dcp2ebi
This doesn't delete the corresponding IT catalog `it2ebi` and the flag name is `--catalogs` not `--catalog`.

2021-10-04 17:18 UTC, hannes-ucsc commented
Another announcement: https://humancellatlas.slack.com/archives/C01360XN04S/p1633367887177300?thread_ts=1631635383.071300&cid=C01360XN04S