Document triage of failed merge commits in operator manual
DataBiosphere/azul pull request #3472
Opened 2021-09-28 18:20 UTC by noah-aviel-dove

No issue.

Author

- [ ] ~~PR title references issue~~
- [ ] ~~PR title matches issue title (preceded by `Fix: ` for bugs)   <sub>or there is a good reason why they're different</sub>~~
- [ ] ~~Title of main commit references issue~~
- [ ] ~~PR is connected to Zenhub issue and description links to issue~~

Author (reindex)

- [x] Added `r` tag to commit title                         <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label to PR                           <sub>or this PR does not require reindexing</sub>

Author (freebies & chains)

- [x] Freebies are blocked on this PR                       <sub>or there are no freebies in this PR</sub>
- [x] Freebies are referenced in commit titles              <sub>or there are no freebies in this PR</sub>
- [x] This PR is blocked by previous PR in the chain        <sub>or this PR is not chained to another PR</sub>
- [x] Added `chain` label to the blocking PR                <sub>or this PR is not chained to another PR</sub>

Author (upgrading)

- [x] Documented upgrading of deployments in UPGRADING.rst  <sub>or this PR does not require upgrading</sub>
- [x] Added `u` tag to commit title                         <sub>or this PR does not require upgrading</sub>
- [x] Added `upgrade` label to PR                           <sub>or this PR does not require upgrading</sub>
- [x] Added announcement to PR description                  <sub>or this PR does not require announcement</sub>

Author (requirements, before every review)

- [x] Ran `make requirements_update`                        <sub>or this PR leaves requirements*.txt, common.mk and Makefile untouched</sub>
- [x] Added `R` tag to commit title                         <sub>or this PR leaves requirements*.txt untouched</sub>
- [x] Added `reqs` label to PR                              <sub>or this PR leaves requirements*.txt untouched</sub>

Author (before every review)

- [x] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>
- [x] Rebased branch on `develop`, squashed old fixups

Primary reviewer (after approval)

- [ ] Commented in issue about demo expectations            <sub>or labelled issue as `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] Moved ticket to Approved column
- [ ] Assigned PR to an operator

Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear              <sub>or issue is labeled as `no demo`</sub>
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Pushed PR branch to Github
- [ ] Branch pushed to Gitlab and added `sandbox` label     <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passed in sandbox                               <sub>or PR is labeled `no sandbox`</sub>
- [ ] Started reindex in `sandbox`                          <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox`                     <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title
- [ ] Moved linked issue to Merged column
- [ ] Pushed merge commit to Github

Operator (after pushing the merge commit)

- [ ] Made announcement requested by author                 <sub>or PR description does not contain an announcement</sub>
- [ ] Moved freebies to Merged column                       <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened the PR chain                                <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [ ] Pushed merge commit to Gitlab                         <sub>or this changes can be pushed later, together with another PR</sub>
- [ ] Deleted PR branch from Github and Gitlab

Operator (reindex) 

- [ ] Started reindex in `dev`                              <sub>or this PR does not require reindexing or does not target `dev`</sub>
- [ ] Checked for failures in `dev`                         <sub>or this PR does not require reindexing or does not target `dev`</sub>
- [ ] Started reindex in `prod`                             <sub>or this PR does not require reindexing or does not target `prod`</sub>
- [ ] Checked for failures in `prod`                        <sub>or this PR does not require reindexing or does not target `prod`</sub>

Operator

- [ ] Unassigned PR

2021-09-28 19:17 UTC, amarjandu approved these changes
approved based on conversation https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1632840435386600

2021-09-28 19:44 UTC, noah-aviel-dove commented
@amarjandu I pushed a second commit based on parking lot to avoid opening a second PR.

2021-09-28 19:46 UTC, amarjandu approved these changes
this was agreed on during parking lot.

2021-10-06 21:44 UTC, hannes-ucsc commented
We've decided in last retro that I review even these PR.

2021-10-29 21:36 UTC, noah-aviel-dove commented on OPERATOR.rst
> +If the build for a merge commit fails on a stable deployment, the operator must
I think this belongs in the `Reindexing` section instead, as there may be failed messages in the queues regardless of whether the build passed or not.

2021-10-30 01:39 UTC, hannes-ucsc requested changes

2021-10-30 01:39 UTC, hannes-ucsc commented on OPERATOR.rst
> +- clear the fail queues so they are empty for the next reindex
This can be one step, using `--delete` with dump.

2021-10-30 01:39 UTC, hannes-ucsc commented on OPERATOR.rst
> +- feed the failed messages back into their respective ``_retry`` queues
```suggestion
- feed the failed messages back into their respective ``_retry`` queues, not the non-retry queues (!)
```

or some other, less awkward way to emphasize this.

2021-10-30 01:39 UTC, hannes-ucsc commented on OPERATOR.rst
> +messages. If failed messages are found, use ``python scripts/manage_queues.py``
Should discriminate between notifcations and tallies. I think the best sequence would be notifications until the set of failed messages stabilizes, then repeat with tallies.

2021-10-30 01:39 UTC, hannes-ucsc commented on OPERATOR.rst
> +or no previosuly failed messages succeeded. Finally
Should state the invariant post condition that all queues must be empty and that any permanent failures are tracked in tickets.

2021-11-02 01:06 UTC, noah-aviel-dove commented
@hannes-ucsc  Build is red due to https://github.com/DataBiosphere/azul/issues/3603

2021-11-04 05:46 UTC, hannes-ucsc requested changes
Build must be green.

2021-11-04 22:36 UTC, hannes-ucsc requested changes

2021-11-04 22:36 UTC, hannes-ucsc commented on OPERATOR.rst
> +If a GitLab build fails on a stable deployment, the operator must evaluate the
```suggestion
If a GitLab build fails on a main deployment, the operator must evaluate the
```

2021-11-04 22:36 UTC, hannes-ucsc commented on OPERATOR.rst
> +- force-feed the failed notifications back into the ``notifications_retry``
```suggestion

- force-feed the failed notifications back into the ``notifications_retry``
```

2021-11-05 17:33 UTC, hannes-ucsc approved these changes

2021-11-05 20:22 UTC, merged