Fix: Lambda layer fails to upload to storage bucket (NoSuchBucket) (#3639)
DataBiosphere/azul pull request #3646
Opened 2021-11-18 01:13 UTC by achave11

https://github.com/DataBiosphere/azul/issues/3639

### Author

- [ ] PR title references issue
- [ ] PR title matches issue title (preceded by `Fix: ` for bugs)   <sub>or there is a good reason why they're different</sub>
- [ ] Title of main commit references issue
- [ ] PR is connected to Zenhub issue and description links to issue

### Author (reindex)

- [ ] Added `r` tag to commit title                         <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label to PR                           <sub>or this PR does not require reindexing</sub>

### Author (freebies & chains)

- [ ] Freebies are blocked on this PR                       <sub>or there are no freebies in this PR</sub>
- [ ] Freebies are referenced in commit titles              <sub>or there are no freebies in this PR</sub>
- [ ] This PR is blocked by previous PR in the chain        <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chain` label to the blocking PR                <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [ ] Documented upgrading of deployments in UPGRADING.rst  <sub>or this PR does not require upgrading</sub>
- [ ] Added `u` tag to commit title                         <sub>or this PR does not require upgrading</sub>
- [ ] Added `upgrade` label to PR                           <sub>or this PR does not require upgrading</sub>
- [ ] Added announcement to PR description                  <sub>or this PR does not require announcement</sub>
- [ ] Added checklist items for additional operator tasks   <sub>or this PR does not require additional tasks</sub>

### Author (requirements, before every review)

- [ ] Ran `make requirements_update`                        <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [ ] Added `R` tag to commit title                         <sub>or this PR does not touch requirements*.txt</sub>
- [ ] Added `reqs` label to PR                              <sub>or this PR does not touch requirements*.txt</sub>

### Author (before every review)

- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>
- [ ] Rebased branch on `develop`, squashed old fixups

### Primary reviewer (after approval)

- [ ] Commented in issue about demo expectations            <sub>or labelled issue as `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] Moved ticket to Approved column
- [ ] Assigned PR to an operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear              <sub>or issue is labeled as `no demo`</sub>
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Pushed PR branch to Github
- [ ] Branch pushed to Gitlab and added `sandbox` label     <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passed in sandbox                               <sub>or PR is labeled `no sandbox`</sub>
- [ ] Started reindex in `sandbox`                          <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox`                     <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title
- [ ] Moved linked issue to Merged column
- [ ] Pushed merge commit to Github

### Operator (after pushing the merge commit)

- [ ] Made announcement requested by author                 <sub>or PR description does not contain an announcement</sub>
- [ ] Moved freebies to Merged column                       <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened the PR chain                                <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate       <sub>or this PR is authored by lead</sub>
- [ ] Pushed merge commit to Gitlab                         <sub>or merge commit can be pushed later, with another PR</sub>
- [ ] Deleted PR branch from Github and Gitlab
- [ ] Build passes on Gitlab

### Operator (reindex) 

- [ ] Started reindex in target deployment                  <sub>or this PR does not require reindexing</sub>
- [ ] Checked for and triaged indexing failures             <sub>or this PR does not require reindexing</sub>
- [ ] Emptied fail queues in target deployment              <sub>or this PR does not require reindexing</sub>

### Operator

- [ ] Unassigned PR

2021-11-18 19:15 UTC, achave11 commented
- [ ] I don't this will be a regression from the [previous lambda_layer_bucket](https://github.com/DataBiosphere/azul/pull/3450#discussion_r715035530) change, which addressed issue (https://github.com/DataBiosphere/azul/issues/3330). Just to confirm.
> [Also note that a lambda layer should not be deployed when make -C terraform plan is ran.](https://github.com/DataBiosphere/azul/issues/3639#issuecomment-965740447)
- [ ] Because `make -C terraform config` called by `… terraform plan` has baked in the notion that the lambdas have to be staged when running Terraform, that includes `make package` which deploys the lambdas. Should there be an alternate logic path which doesn't upload the layers to s3, but still produces the lambda resources with chalice-terraform?

2021-11-18 20:53 UTC, achave11 commented
add FIXME for `make -C terraform plan` uploads layers to s3.

```diff
Index: lambdas/Makefile
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lambdas/Makefile b/lambdas/Makefile
--- a/lambdas/Makefile	(revision 39e1643b2804291e611017e5b82b8440aa0b2ead)
+++ b/lambdas/Makefile	(date 1637268693671)
@@ -1,5 +1,5 @@
 .PHONY: all
-all: layer indexer service
+all: indexer service
 
 include ../common.mk
 
Index: terraform/Makefile
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/terraform/Makefile b/terraform/Makefile
--- a/terraform/Makefile	(revision 39e1643b2804291e611017e5b82b8440aa0b2ead)
+++ b/terraform/Makefile	(date 1637268693679)
@@ -27,11 +27,11 @@
 	terraform plan
 
 .PHONY: apply
-apply: validate rename_resources
+apply: validate layer rename_resources
 	terraform apply
 
 .PHONY: auto_apply
-auto_apply: validate rename_resources
+auto_apply: validate layer rename_resources
 	terraform apply -auto-approve
 
 .PHONY: destroy
@@ -67,3 +67,7 @@
 .PHONY: lambdas
 lambdas:
 	$(MAKE) -C $(project_root)/lambdas
+
+.PHONY: layer
+layer:
+	$(MAKE) -C $(project_root)/lambdas/layer
\ No newline at end of file

```

2021-11-18 23:45 UTC, amarjandu approved these changes
✅ Storage bucket is changed
✅ FIXME: added for weird relation between `plan` and layer upload

2021-11-18 23:46 UTC, amarjandu commented
@achave11 might want to make a checklist item for the operator to cleanup the old bucket that was used.

2021-12-02 00:21 UTC, hannes-ucsc requested changes

2021-12-02 00:21 UTC, hannes-ucsc commented on terraform/Makefile
> +# FIXME: lambda layers shouldn't be uploaded when `plan` target is ran
```suggestion
# FIXME: Lambda layers shouldn't be uploaded when `plan` target is run
```

2021-12-08 21:08 UTC, merged