Fix: Transient InternalServerError from BigQuery during IT (#3947)
DataBiosphere/azul pull request #3954
Opened 2022-03-17 16:06 UTC by danielsotirhos

Connected issue: #3947

## Checklist

### Author

- [x] PR title references the connected issue
- [x] PR title matches<sup>1</sup> title of connected issue         <sub>or comment in PR explains why they're different</sub>
- [x] Title of at least one commit references connected issue
- [x] PR is connected to issue via Zenhub 
- [x] PR description links to connected issue

<sup>1</sup> when the issue title describes a problem, the PR title is `Fix: ` followed by the issue title   

### Author (reindex)

- [x] Added `r` tag to commit title                                 <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label to PR                                   <sub>or this PR does not require reindexing</sub>

### Author (chains)

- [x] This PR is blocked by previous PR in the chain                <sub>or this PR is not chained to another PR</sub>
- [x] Added `chain` label to the blocking PR                        <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [x] Documented upgrading of deployments in UPGRADING.rst          <sub>or this PR does not require upgrading</sub>
- [x] Added `u` tag to commit title                                 <sub>or this PR does not require upgrading</sub>
- [x] Added `upgrade` label to PR                                   <sub>or this PR does not require upgrading</sub>
- [x] Added announcement to PR description                          <sub>or this PR does not require announcement</sub>
- [x] Added checklist items for additional operator tasks           <sub>or this PR does not require additional tasks</sub>

## Author (hotfixes)

- [x] Added `h` tag to commit title and PR targets `prod`           <sub>or this PR does not include a temporary hotfix</sub>
- [x] Added `H` tag to commit title                                 <sub>or this PR does not include a permanent hotfix</sub>
- [x] Added `hotfix` label to PR                                    <sub>or this PR does not include a hotfix</sub>
- [x] Reverted the temporary hotfix connected to the issue          <sub>or there is no temporary hotfix for the connected issue on the `prod` branch</sub>

### Author (requirements, before every review)

- [x] Ran `make requirements_update`                                <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [x] Added `R` tag to commit title                                 <sub>or this PR does not touch requirements*.txt</sub>
- [x] Added `reqs` label to PR                                      <sub>or this PR does not touch requirements*.txt</sub>

### Author (before every review)

- [x] `make integration_test` passes in personal deployment         <sub>or this PR does not touch functionality that could break the IT</sub>
- [x] Rebased branch on `develop`, squashed old fixups

### Primary reviewer (after approval)

- [x] Actually approved the PR
- [x] Labeled connected issue as `demo` or `no demo`
- [x] Commented on connected issue about demo expectations          <sub>or labelled connected issue as `no demo`</sub>
- [x] Decided if PR can be labeled `no sandbox`
- [x] PR title is appropriate as title of merge commit
- [x] Moved ticket to Approved column
- [x] Assigned PR to an operator

### Operator (before pushing merge the commit)

- [x] Checked `reindex` label and `r` commit title tag
- [x] Checked that demo expectations are clear                      <sub>or connected issue is labeled as `no demo`</sub>
- [x] Rebased and squashed branch
- [x] Sanity-checked history
- [x] Pushed PR branch to Github
- [x] Branch pushed to Gitlab and added `sandbox` label             <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passed in sandbox                                       <sub>or PR is labeled `no sandbox`</sub>
- [x] Started reindex in `sandbox`                                  <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Checked for failures in `sandbox`                             <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Added PR reference to merge commit title
- [x] Collected commit title tags in merge commit title
- [x] Moved connected issue to Merged column
- [ ] Pushed merge commit to Github

### Operator (after pushing the merge commit)

- [ ] Made announcement requested by author                         <sub>or PR description does not contain an announcement</sub>
- [ ] Shortened the PR chain                                        <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate <sub>or this PR is authored by lead</sub>
- [ ] Pushed merge commit to Gitlab                                 <sub>or merge commit can be pushed later, with another PR</sub>
- [ ] Deleted PR branch from Github and Gitlab
- [ ] Build passes on Gitlab
- [ ] Moved connected issue to `prod` or `Merged prod`              <sub>or this PR does not represent a promotion</sub>

### Operator (reindex) 

- [ ] Started reindex in target deployment                          <sub>or this PR does not require reindexing</sub>
- [ ] Checked for and triaged indexing failures                     <sub>or this PR does not require reindexing</sub>
- [ ] Emptied fail queues in target deployment                      <sub>or this PR does not require reindexing</sub>
- [ ] Filed backport PR                                             <sub>or this PR does not represent a hotfix</sub>

### Operator

- [ ] Unassigned PR

## Shorthand for review comments

- `L` line is too long
- `W` line wrapping is wrong
- `Q` bad quotes
- `F` other formatting problem

2022-03-18 19:36 UTC, noah-aviel-dove approved these changes
LGTM :+1:

2022-03-19 01:15 UTC, hannes-ucsc requested changes

2022-03-19 01:15 UTC, hannes-ucsc commented on src/azul/terra.py
> +                except InternalServerError as e:
Let's also handle 503's this way

```suggestion
                except (InternalServerError, ServiceUnavailable) as e:
```

2022-03-19 01:15 UTC, hannes-ucsc commented on src/azul/terra.py
> +                    sleep(delay)
Too much duplicated code for my taste. Consider a different branching structure for the if 

But most importantly, the condition on `delay is not None` seems to be missing for this branch.

2022-03-21 23:14 UTC, hannes-ucsc requested changes

2022-03-21 23:14 UTC, hannes-ucsc commented on src/azul/terra.py
> +                    handle_exception(e=e,
Still too much duplicated code. Local nested function have access to local variables of the containing function.

2022-03-21 23:14 UTC, hannes-ucsc commented on src/azul/terra.py
> +                    handle_exception(e=e,
I don't like the `match` variable thingy, either. 

Try restructuring the control flow so that you don't need a nested function.

2022-03-21 23:16 UTC, hannes-ucsc commented
Also note that I change the issue title to be less generic, so PR and commit titles need to be updated.

2022-03-24 01:29 UTC, hannes-ucsc requested changes

2022-03-24 01:29 UTC, hannes-ucsc commented on src/azul/terra.py
> +                        type(e).__name__ != 'Forbidden' or 'Exceeded rate limits' in e.message
This is not how one typically checks if an object is an instance of a class. You'd have to use the pythonic way or explain in a comment why you can't.

2022-03-24 17:52 UTC, hannes-ucsc requested changes
```diff
Index: src/azul/terra.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/terra.py b/src/azul/terra.py
--- a/src/azul/terra.py	(revision c4860d56c0520e3e7988c7466c820c84280da00d)
+++ b/src/azul/terra.py	(date 1648144174096)
@@ -462,14 +462,14 @@
                 try:
                     result = job.result()
                 except (Forbidden, InternalServerError, ServiceUnavailable) as e:
-                    if delay and (
-                        not isinstance(e, Forbidden) or 'Exceeded rate limits' in e.message
-                    ):
+                    if delay is None:
+                        raise e
+                    elif isinstance(e, Forbidden) and 'Exceeded rate limits' not in e.message:
+                        raise e
+                    else:
                         log.warning('BigQuery job error during attempt %i/%i. Retrying in %is.',
                                     attempt + 1, len(delays) + 1, delay, exc_info=e)
                         sleep(delay)
-                    else:
-                        raise e
                 else:
                     break
             else:
```

2022-03-24 17:52 UTC, hannes-ucsc commented on src/azul/terra.py
> +                    if delay and (
Conflates `0` and `None`.

2022-03-29 04:24 UTC, hannes-ucsc approved these changes

2022-03-29 23:31 UTC, merged