Prevent automatic ES (OSS) domain software upgrades (#3959)
DataBiosphere/azul pull request #3976
Opened 2022-03-23 18:28 UTC by achave11

Connected issue: #3959

## Checklist

### Author

- [x] PR title references the connected issue
- [x] PR title matches<sup>1</sup> title of connected issue         <sub>or comment in PR explains why they're different</sub>
- [x] Title of at least one commit references connected issue
- [x] PR is connected to issue via Zenhub 
- [x] PR description links to connected issue

<sup>1</sup> when the issue title describes a problem, the PR title is `Fix: ` followed by the issue title   

### Author (reindex)

- [x] Added `r` tag to commit title                                 <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label to PR                                   <sub>or this PR does not require reindexing</sub>

### Author (chains)

- [x] This PR is blocked by previous PR in the chain                <sub>or this PR is not chained to another PR</sub>
- [x] Added `chain` label to the blocking PR                        <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [x] Documented upgrading of deployments in UPGRADING.rst          <sub>or this PR does not require upgrading</sub>
- [x] Added `u` tag to commit title                                 <sub>or this PR does not require upgrading</sub>
- [x] Added `upgrade` label to PR                                   <sub>or this PR does not require upgrading</sub>
- [x] Added announcement to PR description                          <sub>or this PR does not require announcement</sub>
- [x] Added checklist items for additional operator tasks           <sub>or this PR does not require additional tasks</sub>

## Author (hotfixes)

- [x] Added `h` tag to commit title and PR targets `prod`           <sub>or this PR does not include a temporary hotfix</sub>
- [x] Added `H` tag to commit title                                 <sub>or this PR does not include a permanent hotfix</sub>
- [x] Added `hotfix` label to PR                                    <sub>or this PR does not include a hotfix</sub>
- [x] Reverted the temporary hotfix connected to the issue          <sub>or there is no temporary hotfix for the connected issue on the `prod` branch</sub>

### Author (requirements, before every review)

- [x] Ran `make requirements_update`                                <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [x] Added `R` tag to commit title                                 <sub>or this PR does not touch requirements*.txt</sub>
- [x] Added `reqs` label to PR                                      <sub>or this PR does not touch requirements*.txt</sub>

### Author (before every review)

- [x] `make integration_test` passes in personal deployment         <sub>or this PR does not touch functionality that could break the IT</sub>
- [x] Rebased branch on `develop`, squashed old fixups

### Primary reviewer (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issue as `demo` or `no demo`
- [ ] Commented on connected issue about demo expectations          <sub>or labelled connected issue as `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] Ticket is in *Review requested* column
- [ ] Requested review from peer reviewer
- [ ] Assigned PR to peer reviewer

### Peer reviewer (after approval)

- [ ] `N reviews` label on PR reflects prior peer reviews with changes requested
- [ ] Moved ticket to *Approved* column
- [ ] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear                      <sub>or connected issue is labeled as `no demo`</sub>
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Pushed PR branch to Github
- [ ] Branch pushed to Gitlab and added `sandbox` label             <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passed in sandbox                                       <sub>or PR is labeled `no sandbox`</sub>
- [ ] Started reindex in `sandbox`                                  <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox`                             <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title
- [ ] Moved connected issue to Merged column
- [ ] Pushed merge commit to Github

### Operator (after pushing the merge commit)

- [ ] Made announcement requested by author                         <sub>or PR description does not contain an announcement</sub>
- [ ] Shortened the PR chain                                        <sub>or this PR is not the base of another PR</sub>
- [ ] Pushed merge commit to Gitlab                                 <sub>or merge commit can be pushed later, with another PR</sub>
- [ ] Deleted PR branch from Github and Gitlab
- [ ] Build passes on Gitlab
- [ ] Moved connected issue to `prod` or `Merged prod`              <sub>or this PR does not represent a promotion</sub>

### Operator (reindex) 

- [ ] Started reindex in target deployment                          <sub>or this PR does not require reindexing</sub>
- [ ] Checked for and triaged indexing failures                     <sub>or this PR does not require reindexing</sub>
- [ ] Emptied fail queues in target deployment                      <sub>or this PR does not require reindexing</sub>
- [ ] Filed backport PR                                             <sub>or this PR does not represent a hotfix</sub>

### Operator

- [ ] Unassigned PR

## Shorthand for review comments

- `L` line is too long
- `W` line wrapping is wrong
- `Q` bad quotes
- `F` other formatting problem

2022-03-24 00:54 UTC, hannes-ucsc requested changes
You gotta think this thru a bit more with respect to the different ES domains. You gotta take sandbox into account. I don't think we want a ticket for each deployment since I am pretty sure the update notification pretty much arrive at the same time. We should apply the update on `dev` first, then `sandbox` after making sure that no one is using it. Prod should be updated last.

2022-03-24 00:54 UTC, hannes-ucsc commented on OPERATOR.rst
> +   new issue in https://github.com/DataBiosphere/azul/issues/new/choose and
same here re link but everyone knows how to open an issue

2022-03-24 00:54 UTC, hannes-ucsc commented on OPERATOR.rst
> +#. Go to https://us-east-1.console.aws.amazon.com/esv3/home?region=us-east-1#opensearch/notifications
This is not how links are formatted in rst.

Anyways: don't paste deep links to the AWS console. They break in no time. Use English to describe where to go.

2022-03-30 17:02 UTC, achave11 commented on OPERATOR.rst
> +make the update manually as part of a task of an Azul issue.
```suggestion
make the update manually as part of an operator task.
```

2022-03-30 17:03 UTC, achave11 commented on OPERATOR.rst
> +   AWS accounts.
```suggestion
#. Record the severity e.g. ``"Informational", time utc e.g
   ``"3/22/2022, 11:06:14 PM"``, and domain name e.g. ``"azul-index-sandbox"`` of
   these notifications. Collect this information for both ``prod`` and ``dev``
   AWS accounts.
```

2022-03-30 17:08 UTC, achave11 commented on OPERATOR.rst
> +#. Open a new issue in Azul and title it ``Service Software Update {date}``.
```suggestion
#. Open a new issue in Azul and title it ``Apply OpenSearch (ES) Service Software Update before {date}``.
```

2022-03-31 02:03 UTC, hannes-ucsc requested changes

2022-03-31 02:03 UTC, hannes-ucsc commented on OPERATOR.rst
> +   for each domain name recorded in step 2. Be considered of disruptions to
```suggestion
   for each domain name recorded in step 2. Be considerate of disruptions to
```

But discuss in PL.

2022-03-31 02:03 UTC, hannes-ucsc commented on OPERATOR.rst
> +   checklist should reflect a sensible order for performing the upgrades. Always
It's not clear to the reader what this means. Discuss in PL

2022-03-31 02:03 UTC, hannes-ucsc commented on OPERATOR.rst
> +   ``General information`` the ``Service software version`` should have a
```suggestion
   ``General information``, the ``Service software version`` should have a
```

2022-03-31 02:03 UTC, hannes-ucsc commented on OPERATOR.rst
> +#. Once the upgrade process is completed, do a smoke test in the Data Browser to
For `dev` and `prod`. Can't be done for `sandbox`

2022-04-01 18:52 UTC, achave11 commented on OPERATOR.rst
> +[ES]) software updates. Notifications with `High` severity will be subject to an
```suggestion
Check weekly for notifications about Amazon OpenSearch Service
software updates. Notifications with `High` severity will be subject to an
```

2022-04-01 18:52 UTC, achave11 commented on OPERATOR.rst
> +`Amazon notification severities`_ for more info. The operator should avoid any
```suggestion
`Amazon notification severities`_ for more info. The operator should prevent any
```

2022-04-01 18:55 UTC, achave11 commented on OPERATOR.rst
> +   and identify notifications with subject ``'Service Software Update'``.
```suggestion
   and identify notifications with subject ``Service Software Update``.
```
here and elsewhere.

2022-04-01 18:56 UTC, achave11 commented on OPERATOR.rst
> +   AWS accounts.
Remove examples.

2022-04-01 18:56 UTC, achave11 commented on OPERATOR.rst
> +   i.e., a notification of ``High`` severity was recorded.
```suggestion
#. Pin ticket with *High Priority* in ZenHub only if title contains a date.
```

2022-04-01 18:57 UTC, achave11 commented on OPERATOR.rst
> +   for notifying developers of the incoming disruptions to the shared domains.
```suggestion
   for notifying developers of any disruptions to their deployments.
```

2022-04-01 18:58 UTC, achave11 commented on OPERATOR.rst
> +    - [ ] Confirm with Azul devs that their personal deployments are inactive
```suggestion
    - [ ] Confirm with Azul devs that their personal deployments are idle
```

2022-04-04 19:39 UTC, hannes-ucsc requested changes

2022-04-04 21:02 UTC, hannes-ucsc approved these changes

2022-04-05 17:41 UTC, amarjandu approved these changes

2022-04-06 21:18 UTC, merged