Add logging to manifest object tagging (#3982)
DataBiosphere/azul pull request #3991
Opened 2022-03-28 23:44 UTC by danielsotirhos

Connected issue: #3982

## Checklist

### Author

- [ ] PR title references the connected issue
- [ ] PR title matches<sup>1</sup> title of connected issue         <sub>or comment in PR explains why they're different</sub>
- [ ] Title of at least one commit references connected issue
- [ ] PR is connected to issue via Zenhub 
- [ ] PR description links to connected issue

<sup>1</sup> when the issue title describes a problem, the PR title is `Fix: ` followed by the issue title   

### Author (reindex)

- [ ] Added `r` tag to commit title                                 <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label to PR                                   <sub>or this PR does not require reindexing</sub>

### Author (chains)

- [ ] This PR is blocked by previous PR in the chain                <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chain` label to the blocking PR                        <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [ ] Documented upgrading of deployments in UPGRADING.rst          <sub>or this PR does not require upgrading</sub>
- [ ] Added `u` tag to commit title                                 <sub>or this PR does not require upgrading</sub>
- [ ] Added `upgrade` label to PR                                   <sub>or this PR does not require upgrading</sub>
- [ ] Added announcement to PR description                          <sub>or this PR does not require announcement</sub>
- [ ] Added checklist items for additional operator tasks           <sub>or this PR does not require additional tasks</sub>

## Author (hotfixes)

- [ ] Added `h` tag to commit title and PR targets `prod`           <sub>or this PR does not include a temporary hotfix</sub>
- [ ] Added `H` tag to commit title                                 <sub>or this PR does not include a permanent hotfix</sub>
- [ ] Added `hotfix` label to PR                                    <sub>or this PR does not include a hotfix</sub>
- [ ] Reverted the temporary hotfix connected to the issue          <sub>or there is no temporary hotfix for the connected issue on the `prod` branch</sub>

### Author (requirements, before every review)

- [ ] Ran `make requirements_update`                                <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [ ] Added `R` tag to commit title                                 <sub>or this PR does not touch requirements*.txt</sub>
- [ ] Added `reqs` label to PR                                      <sub>or this PR does not touch requirements*.txt</sub>

### Author (before every review)

- [ ] `make integration_test` passes in personal deployment         <sub>or this PR does not touch functionality that could break the IT</sub>
- [ ] Rebased branch on `develop`, squashed old fixups

### Primary reviewer (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issue as `demo` or `no demo`
- [ ] Commented on connected issue about demo expectations          <sub>or labelled connected issue as `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] Ticket is in *Review requested* column
- [ ] Requested review from peer reviewer
- [ ] Assigned PR to peer reviewer

### Peer reviewer (after approval)

- [ ] `N reviews` label on PR reflects prior peer reviews with changes requested
- [ ] Moved ticket to *Approved* column
- [ ] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear                      <sub>or connected issue is labeled as `no demo`</sub>
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Pushed PR branch to Github
- [ ] Branch pushed to Gitlab and added `sandbox` label             <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passed in sandbox                                       <sub>or PR is labeled `no sandbox`</sub>
- [ ] Started reindex in `sandbox`                                  <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox`                             <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title
- [ ] Moved connected issue to Merged column
- [ ] Pushed merge commit to Github

### Operator (after pushing the merge commit)

- [ ] Made announcement requested by author                         <sub>or PR description does not contain an announcement</sub>
- [ ] Shortened the PR chain                                        <sub>or this PR is not the base of another PR</sub>
- [ ] Pushed merge commit to Gitlab                                 <sub>or merge commit can be pushed later, with another PR</sub>
- [ ] Deleted PR branch from Github and Gitlab
- [ ] Build passes on Gitlab
- [ ] Moved connected issue to `prod` or `Merged prod`              <sub>or this PR does not represent a promotion</sub>

### Operator (reindex) 

- [ ] Started reindex in target deployment                          <sub>or this PR does not require reindexing</sub>
- [ ] Checked for and triaged indexing failures                     <sub>or this PR does not require reindexing</sub>
- [ ] Emptied fail queues in target deployment                      <sub>or this PR does not require reindexing</sub>
- [ ] Filed backport PR                                             <sub>or this PR does not represent a hotfix</sub>

### Operator

- [ ] Unassigned PR

## Shorthand for review comments

- `L` line is too long
- `W` line wrapping is wrong
- `Q` bad quotes
- `F` other formatting problem

2022-03-28 23:46 UTC, danielsotirhos commented
Example:

Field | Value
-- | --
@ingestionTime | 1648510342870
@log | 122796619775:/aws/lambda/azul-service-daniel-manifest
@logStream | 2022/03/28/[$LATEST]250af52a04ab4b23bacb1f55edea3744
@message | [INFO] 2022-03-28T23:32:19.036Z fd5b0c7e-6b97-4ffb-86ce-4bab9585d4c1 Putting tag {'TagSet': [{'Key': 'azul_file_name', 'Value': 'HumanMousePancreas 2022-03-28 23.32.tsv'}]} on object manifests/bf34f1d3-2881-5321-a996-a0099788c873.5c957295-df8a-548b-9dd0-f75082d9816d.tsv
@requestId | fd5b0c7e-6b97-4ffb-86ce-4bab9585d4c1
@timestamp | 1648510339036
TagSet.0.Key | azul_file_name
TagSet.0.Value | HumanMousePancreas 2022-03-28 23.32.tsv

2022-03-31 01:49 UTC, hannes-ucsc requested changes
https://github.com/DataBiosphere/azul/blob/develop/CONTRIBUTING.rst#18string-interpolation

2022-03-31 01:49 UTC, hannes-ucsc commented on src/azul/service/storage_service.py
> +        logger.info('Putting tag %s on object %s', tagging, object_key)
```suggestion
        logger.info('Tagging object %r with %r', object_key, tagging)
```

2022-03-31 16:27 UTC, danielsotirhos commented
Example:

Field | Value
-- | --
@ingestionTime | 1648743661731
@log | 122796619775:/aws/lambda/azul-service-daniel-manifest
@logStream | 2022/03/31/[$LATEST]a9c764272f1e482fa135a4ebab1c9dee
@message | [INFO] 2022-03-31T16:20:58.467Z 06fbbc27-5391-422a-b628-4d2ad91cff40 Tagging object 'manifests/ef767aa2-5e05-5c32-ba9e-767d16973e88.5c957295-df8a-548b-9dd0-f75082d9816d.tsv' with {'TagSet': [{'Key': 'azul_file_name', 'Value': 'AcuteSkinInflammation 2022-03-31 16.20.tsv'}]}
@requestId | 06fbbc27-5391-422a-b628-4d2ad91cff40
@timestamp | 1648743658468
TagSet.0.Key | azul_file_name
TagSet.0.Value | AcuteSkinInflammation 2022-03-31 16.20.tsv

2022-04-01 01:01 UTC, hannes-ucsc approved these changes

2022-04-01 01:59 UTC, noah-aviel-dove approved these changes

2022-04-02 00:12 UTC, merged