Put Azul behind AWS WAF (#4000)
DataBiosphere/azul pull request #4084
Opened 2022-04-13 16:48 UTC by danielsotirhos

Connected issue: #4000

## Checklist

### Author

- [x] Target branch is `develop`
- [x] Source branch is `issues/<github-handle>/<issue#>-<slug>`
- [x] PR title references the connected issue
- [x] PR title matches<sup>1</sup> title of connected issue         <sub>or comment in PR explains why they're different</sub>
- [x] Title of at least one commit references connected issue
- [ ] PR is connected to issue via Zenhub 
- [ ] PR description links to connected issue
- [ ] Added `partial` label to PR                                    <sub>or this PR completely resolves the connected issue</sub>

<sup>1</sup> when the issue title describes a problem, the PR title is `Fix: ` followed by the issue title   

### Author (reindex)

- [ ] Added `r` tag to commit title                                 <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label to PR                                   <sub>or this PR does not require reindexing</sub>

### Author (chains)

- [ ] This PR is blocked by previous PR in the chain                <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chain` label to the blocking PR                        <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [ ] Documented upgrading of deployments in UPGRADING.rst          <sub>or this PR does not require upgrading</sub>
- [ ] Added `u` tag to commit title                                 <sub>or this PR does not require upgrading</sub>
- [ ] Added `upgrade` label to PR                                   <sub>or this PR does not require upgrading</sub>

### Author (operator tasks)

- [ ] Added checklist items for additional operator tasks           <sub>or this PR does not require additional tasks</sub>

### Author (hotfixes)

- [ ] Added `F` tag to main commit title                            <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [ ] Reverted the temporary hotfix connected to the issue          <sub>or there is no temporary hotfix for the connected issue on the `prod` branch</sub>

### Author (requirements)

- [ ] Ran `make requirements_update`                                <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [ ] Added `R` tag to commit title                                 <sub>or this PR does not touch requirements*.txt</sub>
- [ ] Added `reqs` label to PR                                      <sub>or this PR does not touch requirements*.txt</sub>

### Author (rebasing, integration test)

- [ ] `make integration_test` passes in personal deployment         <sub>or this PR does not touch functionality that could break the IT</sub>
- [ ] Rebased branch on `develop`, squashed old fixups

### Primary reviewer (after rejection)

Uncheck the *Author (requirements)* and *Author (rebasing, integration test)* 
checklists.

### Primary reviewer (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issue as `demo` or `no demo`
- [ ] Commented on connected issue about demo expectations          <sub>or labelled connected issue as `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] Ticket is in *Review requested* column
- [ ] Requested review from peer reviewer
- [ ] Assigned PR to peer reviewer

### Peer reviewer (after rejection)

Uncheck the *Author (requirements)* and *Author (rebasing, integration test)* 
checklists.

### Peer reviewer (after approval)

- [ ] `N reviews` label on PR reflects prior peer reviews with changes requested
- [ ] Moved ticket to *Approved* column
- [ ] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear                      <sub>or connected issue is labeled as `no demo`</sub>
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Branch pushed to GitLab and added `sandbox` label             <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passed in sandbox                                       <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted unreferenced indices in `sandbox`                     <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices</sub> 
- [ ] Started reindex in `sandbox`                                  <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox`                             <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title
- [ ] Moved connected issue to Merged column
- [ ] Pushed merge commit to GitHub

### Operator (after pushing the merge commit)

- [ ] Shortened the PR chain                                        <sub>or this PR is not labeled `chain`</sub>
- [ ] Pushed merge commit to GitLab                                 <sub>or merge commit can be pushed later, with another PR</sub>
- [ ] Deleted PR branch from GitHub and GitLab
- [ ] Build passes on GitLab

### Operator (reindex) 

- [ ] Deleted unreferenced indices in `dev`                         <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices</sub> 
- [ ] Started reindex in `dev`                                      <sub>or this PR does not require reindexing</sub>
- [ ] Checked for and triaged indexing failures                     <sub>or this PR does not require reindexing</sub>
- [ ] Emptied fail queues in target deployment                      <sub>or this PR does not require reindexing</sub>

### Operator

- [ ] Unassigned PR

## Shorthand for review comments

- `L` line is too long
- `W` line wrapping is wrong
- `Q` bad quotes
- `F` other formatting problem

2022-04-15 18:09 UTC, hannes-ucsc requested changes
Shouldn't this be chained to #4028? I thought a regional gateway was a prerequisite for placing it behind WAF. If my assumption is wrong, I'd like to know. Please also prepare a pre-review demo of this in a PL slot.

2022-04-18 17:50 UTC, danielsotirhos commented
> I thought a regional gateway was a prerequisite for placing it behind WAF. If my assumption is wrong, I'd like to know.

The Web ACLs must themselves be `regional`, however I do not see a limitation that they can only be attached to regional API Gateways.

https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-control-access-aws-waf.html

![Screen Shot 2022-04-18 at 10 45 55 AM](https://user-images.githubusercontent.com/46407464/163850409-08e2be3b-e4ff-4334-b4ae-dd8d4e65ef71.png)

---

As demonstrated here, I have an `Edge` API Gateway:

![Screen Shot 2022-04-18 at 10 38 42 AM](https://user-images.githubusercontent.com/46407464/163849345-ab996578-1810-4e00-8cf1-54eb79de0017.png)

And when creating an ACL...:

![Screen Shot 2022-04-18 at 10 42 59 AM](https://user-images.githubusercontent.com/46407464/163849925-392d0de8-b630-490e-b38e-6cfd312c629b.png)

...I am able to select my `Edge` API Gateway

![Screen Shot 2022-04-18 at 10 44 57 AM](https://user-images.githubusercontent.com/46407464/163850142-b433f5a5-b93a-4bd5-8e54-8d9105fabb8f.png)

![Screen Shot 2022-04-18 at 10 48 16 AM](https://user-images.githubusercontent.com/46407464/163850698-94cac7fb-f93b-4f29-80ab-210d7aaad5b8.png)

2022-04-19 18:08 UTC, hannes-ucsc requested changes
From my previous review

> Please also prepare a pre-review demo of this in a PL slot.

by "this" I meant the entire functionality that this PR adds.

2022-05-09 23:18 UTC, hannes-ucsc requested changes
It appears that the [Fix pep8 warnings](https://github.com/DataBiosphere/azul/pull/4084/commits/0a65ae3a206df4a1dfc68d0c7776c442dcba6b4b) commit is fixing a regression introduced by the previous commit, which you authored. You shouldn't introduce a violation in one commit and fix it in another commit of the same PR. So either squash that commit out or move it to the beginning of the history (in case the pep8 violation is already on develop).

2022-05-09 23:18 UTC, hannes-ucsc commented on terraform/api_gateway.tf.json.template.py
> +                } for lambda_ in ('indexer', 'service')
There already is a comprehension for this. Why did you roll your own? Using the existing comprehension would eliminate the need to convert it to a generator expressions.

2022-05-12 15:41 UTC, hannes-ucsc requested changes
The fact that we can use the same ACL for both WAFs is probably incidental. We should create a separate ACL for each. And don't fix the line length violations in the existing code. I don't particularly like the fixes, and they exaggerate the diff, at least when taking whitespace into account.

2022-05-12 22:22 UTC, hannes-ucsc requested changes

2022-05-12 22:22 UTC, hannes-ucsc commented on terraform/api_gateway.tf.json.template.py
> +                f"azul_{lambda_.name}_waf": {
```suggestion
                lambda_.name: {
```

2022-05-13 18:24 UTC, hannes-ucsc approved these changes

2022-05-13 22:32 UTC, achave11 approved these changes

2022-05-17 05:30 UTC, achave11 commented
PR failed `deploy` job in [sandbox](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/45788).

2022-05-19 00:14 UTC, hannes-ucsc requested changes
Please change title of commit to  `Consolidate CW logs permissions in GitLab boundary` and add a FIXME referring to https://github.com/DataBiosphere/azul/issues/4207

2022-05-19 00:14 UTC, hannes-ucsc commented on terraform/gitlab/gitlab.tf.json.template.py
> +                        'actions': ['logs:*'],
https://github.com/DataBiosphere/azul/issues/4207

2022-05-19 18:12 UTC, hannes-ucsc requested changes

2022-05-19 18:12 UTC, hannes-ucsc commented on terraform/gitlab/gitlab.tf.json.template.py
> +                    # FIXME: Tighten GitLab security boundary
Commit title should reference FIXME.

2022-05-20 16:48 UTC, hannes-ucsc approved these changes

2022-05-25 17:28 UTC, merged