Prefer project estimated cell count for sort order (#4173)
DataBiosphere/azul pull request #4191
Opened 2022-05-13 18:05 UTC by danielsotirhos

Connected issue: #4173

## Checklist

### Author

- [ ] Target branch is `develop`
- [ ] Name of source branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [ ] PR title references the connected issue
- [ ] PR title matches<sup>1</sup> title of connected issue         <sub>or comment in PR explains why they're different</sub>
- [ ] Title of at least one commit references connected issue
- [ ] PR is connected to issue via Zenhub 
- [ ] PR description links to connected issue
- [ ] Added `partial` label to PR                                    <sub>or this PR completely resolves the connected issue</sub>

<sup>1</sup> when the issue title describes a problem, the PR title is `Fix: ` followed by the issue title   

### Author (reindex)

- [ ] Added `r` tag to commit title                                 <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label to PR                                   <sub>or this PR does not require reindexing</sub>

### Author (chains)

- [ ] This PR is blocked by previous PR in the chain               <sub>or this PR is not chained to another PR</sub>
- [ ] Added `base` label to the blocking PR                        <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chained` label to this PR                             <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [ ] Documented upgrading of deployments in UPGRADING.rst          <sub>or this PR does not require upgrading</sub>
- [ ] Added `u` tag to commit title                                 <sub>or this PR does not require upgrading</sub>
- [ ] Added `upgrade` label to PR                                   <sub>or this PR does not require upgrading</sub>

### Author (operator tasks)

- [ ] Added checklist items for additional operator tasks           <sub>or this PR does not require additional tasks</sub>

### Author (hotfixes)

- [ ] Added `F` tag to main commit title                            <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [ ] Reverted the temporary hotfix connected to the issue          <sub>or there is no temporary hotfix for the connected issue on the `prod` branch</sub>

### Author (requirements)

- [ ] Ran `make requirements_update`                                <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [ ] Added `R` tag to commit title                                 <sub>or this PR does not touch requirements*.txt</sub>
- [ ] Added `reqs` label to PR                                      <sub>or this PR does not touch requirements*.txt</sub>

### Author (rebasing, integration test)

- [ ] `make integration_test` passes in personal deployment         <sub>or this PR does not touch functionality that could break the IT</sub>
- [ ] Rebased branch on `develop`, squashed old fixups

### Peer reviewer (after requesting changes)

Uncheck the *Author (requirements)* and *Author (rebasing, integration test)* 
checklists.

### Peer reviewer (after approval)

- [ ] Ticket is in *Review requested* column
- [ ] Requested review from primary reviewer
- [ ] Assigned PR to primary reviewer

### Primary reviewer (after requesting changes)

Uncheck the *Author (requirements)* and *Author (rebasing, integration test)* 
checklists. Update the `N reviews` label. 

### Primary reviewer (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issue as `demo` or `no demo`
- [ ] Commented on connected issue about demo expectations          <sub>or labelled connected issue as `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] `N reviews` label is accurate
- [ ] Moved ticket to *Approved* column
- [ ] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear                      <sub>or connected issue is labeled as `no demo`</sub>
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Branch pushed to GitLab and added `sandbox` label             <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passed in sandbox                                       <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted unreferenced indices in `sandbox`                     <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices</sub> 
- [ ] Started reindex in `sandbox`                                  <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox`                             <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title
- [ ] Moved connected issue to Merged column
- [ ] Pushed merge commit to GitHub

### Operator (after pushing the merge commit)

- [ ] Shortened the PR chain                                        <sub>or this PR is not labeled `base`</sub>
- [ ] Pushed merge commit to GitLab                                 <sub>or merge commit can be pushed later, with another PR</sub>
- [ ] Deleted PR branch from GitHub and GitLab
- [ ] Build passes on GitLab

### Operator (reindex) 

- [ ] Deleted unreferenced indices in `dev`                         <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices</sub> 
- [ ] Started reindex in `dev`                                      <sub>or this PR does not require reindexing</sub>
- [ ] Checked for and triaged indexing failures                     <sub>or this PR does not require reindexing</sub>
- [ ] Emptied fail queues in target deployment                      <sub>or this PR does not require reindexing</sub>

### Operator

- [ ] Unassigned PR

## Shorthand for review comments

- `L` line is too long
- `W` line wrapping is wrong
- `Q` bad quotes
- `F` other formatting problem

2022-05-17 17:58 UTC, achave11 approved these changes

2022-05-18 17:10 UTC, hannes-ucsc requested changes
Explanatory comment requested by me during stand-up is missing.

2022-05-18 17:10 UTC, hannes-ucsc commented on src/azul/plugins/metadata/hca/indexer/aggregate.py
> +            if project_cells is not None:
```suggestion
            if project_cells is None:
```

2022-05-20 16:51 UTC, hannes-ucsc approved these changes

2022-05-24 16:52 UTC, merged

2022-05-25 16:03 UTC, danielsotirhos commented
Changes confirmed working on `dev`.
Sorting projects by `effectiveCellCount` favors the project estimatedCellCount when a project has both project and cell suspension cell counts:

```
$ http 'https://service.dev.singlecell.gi.ucsc.edu/index/projects?filters=%7B%7D&size=200&sort=effectiveCellCount&order=asc&catalog=dcp2' | jq '.hits[] | {"id": .entryId, "pj_cells": .projects[].estimatedCellCount, "cs_cells": ([.cellSuspensions[].totalCells] | add)}'
{
  "id": "0fd8f918-62d6-4b8b-ac35-4c53dd601f71",
  "pj_cells": null,
  "cs_cells": null
}
...
{
  "id": "71436067-ac41-4ace-be1b-2fbcc2cb02fa",
  "pj_cells": null,
  "cs_cells": 4000
}
{
  "id": "df88f39f-01a8-4b5b-92f4-3177d6c0f242",
  "pj_cells": 4438,
  "cs_cells": null
}
{
  "id": "dc1a41f6-9e09-42a6-959e-3be23db6da56",
  "pj_cells": 6083,
  "cs_cells": 161000
}
{
  "id": "8c3c290d-dfff-4553-8868-54ce45f4ba7f",
  "pj_cells": null,
  "cs_cells": 6639
}
{
  "id": "c5f46615-68de-4cf4-bbc2-a0ae10f08243",
  "pj_cells": 7000,
  "cs_cells": null
}
...
```