Fix: IT on prod timeout waiting for queues (#4299)
DataBiosphere/azul pull request #4318
Opened 2022-07-19 18:42 UTC by danielsotirhos

Connected issue: #4299

## Checklist

### Author

- [ ] Target branch is `develop`
- [ ] Name of source branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [ ] PR title references the connected issue
- [ ] PR title matches<sup>1</sup> title of connected issue         <sub>or comment in PR explains why they're different</sub>
- [ ] Title of at least one commit references connected issue
- [ ] PR is connected to issue via Zenhub 
- [ ] PR description links to connected issue
- [ ] Added `partial` label to PR                                    <sub>or this PR completely resolves the connected issue</sub>

<sup>1</sup> when the issue title describes a problem, the PR title is `Fix: ` followed by the issue title   

### Author (reindex)

- [ ] Added `r` tag to commit title                                 <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label to PR                                   <sub>or this PR does not require reindexing</sub>

### Author (chains)

- [ ] This PR is blocked by previous PR in the chain               <sub>or this PR is not chained to another PR</sub>
- [ ] Added `base` label to the blocking PR                        <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chained` label to this PR                             <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [ ] Documented upgrading of deployments in UPGRADING.rst          <sub>or this PR does not require upgrading</sub>
- [ ] Added `u` tag to commit title                                 <sub>or this PR does not require upgrading</sub>
- [ ] Added `upgrade` label to PR                                   <sub>or this PR does not require upgrading</sub>

### Author (operator tasks)

- [ ] Added checklist items for additional operator tasks           <sub>or this PR does not require additional tasks</sub>

### Author (hotfixes)

- [ ] Added `F` tag to main commit title                            <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [ ] Reverted the temporary hotfix connected to the issue          <sub>or there is no temporary hotfix for the connected issue on the `prod` branch</sub>

### Author (requirements)

- [ ] Ran `make requirements_update`                                <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [ ] Added `R` tag to commit title                                 <sub>or this PR does not touch requirements*.txt</sub>
- [ ] Added `reqs` label to PR                                      <sub>or this PR does not touch requirements*.txt</sub>

### Author (rebasing, integration test)

- [ ] `make integration_test` passes in personal deployment         <sub>or this PR does not touch functionality that could break the IT</sub>
- [ ] Rebased branch on `develop`, squashed old fixups

### Peer reviewer (after requesting changes)

Uncheck the *Author (requirements)* and *Author (rebasing, integration test)* 
checklists.

### Peer reviewer (after approval)

- [ ] Ticket is in *Review requested* column
- [ ] Requested review from primary reviewer
- [ ] Assigned PR to primary reviewer

### Primary reviewer (after requesting changes)

Uncheck the *Author (requirements)* and *Author (rebasing, integration test)* 
checklists. Update the `N reviews` label. 

### Primary reviewer (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issue as `demo` or `no demo`
- [ ] Commented on connected issue about demo expectations          <sub>or labelled connected issue as `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] `N reviews` label is accurate
- [ ] Moved ticket to *Approved* column
- [ ] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear                      <sub>or connected issue is labeled as `no demo`</sub>
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Branch pushed to GitLab and added `sandbox` label             <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passed in sandbox                                       <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted unreferenced indices in `sandbox`                     <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices</sub> 
- [ ] Started reindex in `sandbox`                                  <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox`                             <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title
- [ ] Moved connected issue to Merged column
- [ ] Pushed merge commit to GitHub

### Operator (after pushing the merge commit)

- [ ] Shortened the PR chain                                        <sub>or this PR is not labeled `base`</sub>
- [ ] Pushed merge commit to GitLab                                 <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted PR branch from GitHub and GitLab
- [ ] Build passes on GitLab<sup>1</sup>

<sup>1</sup> When pushing the merge commit is skipped due to the PR being
labelled `no sandbox`, the next build triggered by a PR whose merge commit *is* 
pushed determines this checklist item.

### Operator (reindex) 

- [ ] Deleted unreferenced indices in `dev`                         <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices</sub> 
- [ ] Started reindex in `dev`                                      <sub>or this PR does not require reindexing</sub>
- [ ] Checked for and triaged indexing failures                     <sub>or this PR does not require reindexing</sub>
- [ ] Emptied fail queues in target deployment                      <sub>or this PR does not require reindexing</sub>

### Operator

- [ ] Unassigned PR

## Shorthand for review comments

- `L` line is too long
- `W` line wrapping is wrong
- `Q` bad quotes
- `F` other formatting problem

2022-07-21 17:33 UTC, achave11 requested changes
I'd like to suggest the removal of the `A warning sign…` section and query, it seems to lack specificity and not necessarily be helpful in identifying the issue. Additionally, we desire for this manual to be lean, so if is possible to make a determination of the issue more directly from the second query, all the more reason  to only use that. But I differ to your expertise.

2022-07-21 17:33 UTC, achave11 commented on OPERATOR.rst
> +bundle partitions. Run the BigQuery query below against the indexer log groups
```suggestion
bundle partitions. In the CloudWatch console run the query below with the indexer log groups selected
```

2022-07-21 17:33 UTC, achave11 commented on OPERATOR.rst
> +
It feels to me like this is a redundant step, as it is now it implicitly implies any `Dividing partition` messages are a warning sign, is that the case?

2022-07-22 23:04 UTC, achave11 submitted a review, later dismissed
Approved

2022-07-22 23:06 UTC, achave11 reviewed
Missing checklist items.

2022-07-23 00:28 UTC, achave11 approved these changes

2022-07-25 16:34 UTC, hannes-ucsc requested changes

2022-07-25 16:34 UTC, hannes-ucsc commented on OPERATOR.rst
> +entities that need to be divided before they can be indexed. In the AWS console,
Entities aren't being divided. Bundles are.

2022-07-25 16:34 UTC, hannes-ucsc commented on OPERATOR.rst
> +This can happen when IT randomly selects bundles that have a large amount of
```suggestion
This can happen in the rare occasion that the IT's random selection of bundles happens to pick predominantly large bundles
```

2022-07-25 16:34 UTC, hannes-ucsc commented on OPERATOR.rst
> +Note that when partitions are being divided, errors of exceeded rate & quota
Same linguistic inconsistency as above. A whole is divided into parts.

2022-07-26 00:42 UTC, hannes-ucsc requested changes

2022-07-26 00:42 UTC, hannes-ucsc commented on OPERATOR.rst
> +This can happen in the rare occasion that the IT's random selection of bundles
```suggestion
This can happen on the rare occasion that the IT's random selection of bundles
```

2022-07-26 00:42 UTC, hannes-ucsc commented on OPERATOR.rst
> +happens to pick predominantly large bundles that need to be divided before they
```suggestion
happens to pick predominantly large bundles that need to be partitioned before they
```

2022-07-26 00:42 UTC, hannes-ucsc commented on OPERATOR.rst
> +can be indexed. In the AWS console, run the CloudWatch query below with the
```suggestion
can be indexed. In the AWS console, run the CloudWatch Insights query below with the
```

2022-07-26 00:42 UTC, hannes-ucsc commented on OPERATOR.rst
> +Note that when bundles are being divided, errors of exceeded rate & quota
```suggestion
Note that when bundles are being partitioned, errors of exceeded rate & quota
```

2022-07-26 00:42 UTC, hannes-ucsc commented on OPERATOR.rst
> +indexer log groups selected to see how many divisions have occurred::
Add note that not only bundles can be divided into partitions, but also partitions into sub-partitions. Technically, bundles are partitions with an empty prefix.

2022-07-26 00:51 UTC, hannes-ucsc requested changes
Let's also change the titles to `Workaround:` instead of `Fix:`

2022-07-26 19:05 UTC, hannes-ucsc approved these changes

2022-07-26 23:43 UTC, merged