Fix: IT in GitLab dev failed due to empty manifests (#4392)
DataBiosphere/azul pull request #4396
Opened 2022-08-19 22:56 UTC by achave11

Connected issue: #4392

## Checklist

### Author

- [x] Target branch is `develop`
- [x] Name of source branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [x] PR title references the connected issue
- [ ] PR title matches<sup>1</sup> title of connected issue         <sub>or comment in PR explains why they're different</sub>
- [ ] Title of at least one commit references connected issue
- [x] PR is connected to issue via Zenhub 
- [x] PR description links to connected issue
- [x] Added `partial` label to PR                                    <sub>or this PR completely resolves the connected issue</sub>

<sup>1</sup> when the issue title describes a problem, the PR title is `Fix: ` followed by the issue title   

### Author (reindex)

- [ ] Added `r` tag to commit title                                 <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label to PR                                   <sub>or this PR does not require reindexing</sub>

### Author (chains)

- [ ] This PR is blocked by previous PR in the chain               <sub>or this PR is not chained to another PR</sub>
- [ ] Added `base` label to the blocking PR                        <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chained` label to this PR                             <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [ ] Documented upgrading of deployments in UPGRADING.rst          <sub>or this PR does not require upgrading</sub>
- [ ] Added `u` tag to commit title                                 <sub>or this PR does not require upgrading</sub>
- [ ] Added `upgrade` label to PR                                   <sub>or this PR does not require upgrading</sub>

### Author (operator tasks)

- [ ] Added checklist items for additional operator tasks           <sub>or this PR does not require additional tasks</sub>

### Author (hotfixes)

- [ ] Added `F` tag to main commit title                            <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [ ] Reverted the temporary hotfix connected to the issue          <sub>or there is no temporary hotfix for the connected issue on the `prod` branch</sub>

### Author (requirements)

- [ ] Ran `make requirements_update`                                <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [ ] Added `R` tag to commit title                                 <sub>or this PR does not touch requirements*.txt</sub>
- [ ] Added `reqs` label to PR                                      <sub>or this PR does not touch requirements*.txt</sub>

### Author (rebasing, integration test)

- [ ] `make integration_test` passes in personal deployment         <sub>or this PR does not touch functionality that could break the IT</sub>
- [ ] Rebased branch on `develop`, squashed old fixups

### Peer reviewer (after requesting changes)

Uncheck the *Author (requirements)* and *Author (rebasing, integration test)* 
checklists.

### Peer reviewer (after approval)

- [ ] Ticket is in *Review requested* column
- [ ] Requested review from primary reviewer
- [ ] Assigned PR to primary reviewer

### Primary reviewer (after requesting changes)

Uncheck the *Author (requirements)* and *Author (rebasing, integration test)* 
checklists. Update the `N reviews` label. 

### Primary reviewer (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issue as `demo` or `no demo`
- [ ] Commented on connected issue about demo expectations          <sub>or labelled connected issue as `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] `N reviews` label is accurate
- [ ] Moved ticket to *Approved* column
- [ ] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear                      <sub>or connected issue is labeled as `no demo`</sub>
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Branch pushed to GitLab and added `sandbox` label             <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passed in sandbox                                       <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted unreferenced indices in `sandbox`                     <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices</sub> 
- [ ] Started reindex in `sandbox`                                  <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox`                             <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title
- [ ] Moved connected issue to Merged column
- [ ] Pushed merge commit to GitHub

### Operator (after pushing the merge commit)

- [ ] Shortened the PR chain                                        <sub>or this PR is not labeled `base`</sub>
- [ ] Pushed merge commit to GitLab                                 <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted PR branch from GitHub and GitLab
- [ ] Build passes on GitLab<sup>1</sup>

<sup>1</sup> When pushing the merge commit is skipped due to the PR being
labelled `no sandbox`, the next build triggered by a PR whose merge commit *is* 
pushed determines this checklist item.

### Operator (reindex) 

- [ ] Deleted unreferenced indices in `dev`                         <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices</sub> 
- [ ] Started reindex in `dev`                                      <sub>or this PR does not require reindexing</sub>
- [ ] Checked for and triaged indexing failures                     <sub>or this PR does not require reindexing</sub>
- [ ] Emptied fail queues in target deployment                      <sub>or this PR does not require reindexing</sub>

### Operator

- [ ] Unassigned PR

## Shorthand for review comments

- `L` line is too long
- `W` line wrapping is wrong
- `Q` bad quotes
- `F` other formatting problem

2022-08-25 23:30 UTC, achave11 commented
It was pointless to attempt to reproduce this in sandbox because sandbox has a prefix and `dev` doesn't. Reproduce locally, with `dev` selected and pin the seed.

2022-09-01 17:30 UTC, achave11 commented
Repro attained locally with `$_select dev` while running the IT with the pinned seed.
```
======================================================================
ERROR: test_indexing (integration_test.IndexingIntegrationTest) [managed_access_manifest]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/.venv/lib/python3.9/site-packages/more_itertools/more.py", line 138, in first
    return next(iter(iterable))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/test/integration_test.py", line 370, in subTest
    yield
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/test/integration_test.py", line 1027, in _test_managed_access
    first(public_source_ids & indexed_source_ids))
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/.venv/lib/python3.9/site-packages/more_itertools/more.py", line 145, in first
    raise ValueError('first() was called on an empty iterable, and no '
ValueError: first() was called on an empty iterable, and no default value was provided.

======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [manifest] (catalog='dcp2-it', format=None)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/test/integration_test.py", line 370, in subTest
    yield
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/test/integration_test.py", line 535, in _test_manifest
    validator(catalog, response)
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/test/integration_test.py", line 645, in _check_manifest
    self.__check_manifest(BytesIO(response), 'bundle_uuid')
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/test/integration_test.py", line 721, in __check_manifest
    self.assertGreater(len(rows), 0)
AssertionError: 0 not greater than 0

======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [manifest] (catalog='dcp2-it', format=<ManifestFormat.compact: 'compact'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/test/integration_test.py", line 370, in subTest
    yield
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/test/integration_test.py", line 535, in _test_manifest
    validator(catalog, response)
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/test/integration_test.py", line 645, in _check_manifest
    self.__check_manifest(BytesIO(response), 'bundle_uuid')
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/test/integration_test.py", line 721, in __check_manifest
    self.assertGreater(len(rows), 0)
AssertionError: 0 not greater than 0

======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [manifest] (catalog='dcp2-it', format=<ManifestFormat.terra_bdbag: 'terra.bdbag'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/test/integration_test.py", line 370, in subTest
    yield
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/test/integration_test.py", line 535, in _test_manifest
    validator(catalog, response)
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/test/integration_test.py", line 652, in _check_terra_bdbag
    rows = self.__check_manifest(file, 'bundle_uuid')
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/test/integration_test.py", line 721, in __check_manifest
    self.assertGreater(len(rows), 0)
AssertionError: 0 not greater than 0

======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [manifest] (catalog='dcp2-it', format=<ManifestFormat.curl: 'curl'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/test/integration_test.py", line 370, in subTest
    yield
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/test/integration_test.py", line 535, in _test_manifest
    validator(catalog, response)
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/test/integration_test.py", line 745, in _check_curl_manifest
    self.assertGreater(num_files, 0)
AssertionError: 0 not greater than 0

======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [repository_files] (catalog='dcp2-it')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/test/integration_test.py", line 370, in subTest
    yield
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/test/integration_test.py", line 749, in _test_repository_files
    file = self._get_one_file(catalog)
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/test/integration_test.py", line 551, in _get_one_file
    self.fail('No files found')
AssertionError: No files found

----------------------------------------------------------------------
Ran 16 tests in 687.879s

FAILED (failures=5, errors=1, skipped=6)
make: *** [integration_test] Error 1

```

2022-10-17 17:22 UTC, danielsotirhos requested changes
Subjective suggestions on the wording / placement of the comments. Feel free to push back if you think your version reads better.

2022-10-17 17:22 UTC, danielsotirhos commented on test/integration_test.py
> +            # Ensure that at least one public source will be indexed
```suggestion
```

2022-10-17 17:22 UTC, danielsotirhos commented on test/integration_test.py
>          # above to neutralize the bias.
```suggestion
        # This iteration prefers sources occurring first, so we shuffle them
        # above to neutralize the bias, making sure the sequence starts with
        # at least one public source if any exist in the catalog.
```

2022-10-17 23:28 UTC, noah-aviel-dove commented
Decided to take a different approach. Hope this is clearer.

2022-10-18 15:38 UTC, danielsotirhos approved these changes
Approved.

2022-10-21 00:18 UTC, hannes-ucsc requested changes

2022-10-21 00:18 UTC, hannes-ucsc commented on test/integration_test.py
> +        # Ensure that at least one public source will be indexed
This comment seems a little far away from the actual measure that's being taken, which is passing `public_1st=True`. It also should explain why the measure is taken. I usually explain what would happen if I didn't take the measure.

2022-10-26 01:42 UTC, hannes-ucsc requested changes

2022-10-26 01:42 UTC, hannes-ucsc commented on test/integration_test.py
> +        # public and managed access data. `public_first` ensures that at least
```suggestion
        # public and managed access data. `public_1st` ensures that at least
```

2022-11-01 21:06 UTC, merged