Fix: TDR requests are retried on connect (#4381)
DataBiosphere/azul pull request #4422
Opened 2022-08-29 16:21 UTC by danielsotirhos

Connected issue: #4381

## Checklist

### Author

- [ ] Target branch is `develop`
- [ ] Name of source branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [ ] PR title references the connected issue
- [ ] PR title matches<sup>1</sup> title of connected issue         <sub>or comment in PR explains why they're different</sub>
- [ ] Title of at least one commit references connected issue
- [ ] PR is connected to issue via Zenhub 
- [ ] PR description links to connected issue
- [ ] Added `partial` label to PR                                    <sub>or this PR completely resolves the connected issue</sub>

<sup>1</sup> when the issue title describes a problem, the PR title is `Fix: ` followed by the issue title   

### Author (reindex)

- [ ] Added `r` tag to commit title                                 <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label to PR                                   <sub>or this PR does not require reindexing</sub>

### Author (chains)

- [ ] This PR is blocked by previous PR in the chain               <sub>or this PR is not chained to another PR</sub>
- [ ] Added `base` label to the blocking PR                        <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chained` label to this PR                             <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [ ] Documented upgrading of deployments in UPGRADING.rst          <sub>or this PR does not require upgrading</sub>
- [ ] Added `u` tag to commit title                                 <sub>or this PR does not require upgrading</sub>
- [ ] Added `upgrade` label to PR                                   <sub>or this PR does not require upgrading</sub>

### Author (operator tasks)

- [ ] Added checklist items for additional operator tasks           <sub>or this PR does not require additional tasks</sub>

### Author (hotfixes)

- [ ] Added `F` tag to main commit title                            <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [ ] Reverted the temporary hotfix connected to the issue          <sub>or there is no temporary hotfix for the connected issue on the `prod` branch</sub>

### Author (requirements)

- [ ] Ran `make requirements_update`                                <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [ ] Added `R` tag to commit title                                 <sub>or this PR does not touch requirements*.txt</sub>
- [ ] Added `reqs` label to PR                                      <sub>or this PR does not touch requirements*.txt</sub>

### Author (rebasing, integration test)

- [ ] `make integration_test` passes in personal deployment         <sub>or this PR does not touch functionality that could break the IT</sub>
- [ ] Rebased branch on `develop`, squashed old fixups

### Peer reviewer (after requesting changes)

Uncheck the *Author (requirements)* and *Author (rebasing, integration test)* 
checklists.

### Peer reviewer (after approval)

- [ ] Ticket is in *Review requested* column
- [ ] Requested review from primary reviewer
- [ ] Assigned PR to primary reviewer

### Primary reviewer (after requesting changes)

Uncheck the *Author (requirements)* and *Author (rebasing, integration test)* 
checklists. Update the `N reviews` label. 

### Primary reviewer (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issue as `demo` or `no demo`
- [ ] Commented on connected issue about demo expectations          <sub>or labelled connected issue as `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] `N reviews` label is accurate
- [ ] Moved ticket to *Approved* column
- [ ] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear                      <sub>or connected issue is labeled as `no demo`</sub>
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Branch pushed to GitLab and added `sandbox` label             <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passed in sandbox                                       <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted unreferenced indices in `sandbox`                     <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices</sub> 
- [ ] Started reindex in `sandbox`                                  <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox`                             <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title
- [ ] Moved connected issue to Merged column
- [ ] Pushed merge commit to GitHub

### Operator (after pushing the merge commit)

- [ ] Shortened the PR chain                                        <sub>or this PR is not labeled `base`</sub>
- [ ] Pushed merge commit to GitLab                                 <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted PR branch from GitHub and GitLab
- [ ] Build passes on GitLab<sup>1</sup>

<sup>1</sup> When pushing the merge commit is skipped due to the PR being
labelled `no sandbox`, the next build triggered by a PR whose merge commit *is* 
pushed determines this checklist item.

### Operator (reindex) 

- [ ] Deleted unreferenced indices in `dev`                         <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices</sub> 
- [ ] Started reindex in `dev`                                      <sub>or this PR does not require reindexing</sub>
- [ ] Checked for and triaged indexing failures                     <sub>or this PR does not require reindexing</sub>
- [ ] Emptied fail queues in target deployment                      <sub>or this PR does not require reindexing</sub>

### Operator

- [ ] Unassigned PR

## Shorthand for review comments

- `L` line is too long
- `W` line wrapping is wrong
- `Q` bad quotes
- `F` other formatting problem

2022-08-31 17:31 UTC, danielsotirhos commented
Repeating the case shown in the ticket description (download of a file from `/repository/files/...`) the apigateway and lambda logs only show the 1 request and do not have the repeat request.

**CloudWatch Logs Insights**  
region: us-east-1  
log-group-names: /aws/apigateway/azul-service-daniel, /aws/lambda/azul-service-daniel  
start-time: -1800s  
end-time: 0s  
query-string:
```
fields @timestamp, @message
| filter @message like '13472277-c704-46fd-8aca-a9928c6d2d7b'  # file UUID
| sort @timestamp asc
| limit 200
```
| @timestamp | @message |
|---|---|
| 2022-08-31 17:06:40.896 | {"accountId": "122796619775", "apiId": "071n66awdf", "authorizer_claims_property": "-", "authorizer_error": "-", "authorizer_principalId": "-", "authorizer_property": "-", "awsEndpointRequestId": "e8e2d03d-99bf-43ef-b427-ac75f01ad00e", "awsEndpointRequestId2": "-", "customDomain_basePathMatched": "(none)", "dataProcessed": "-", "domainName": "service.daniel.dev.singlecell.gi.ucsc.edu", "domainPrefix": "service", "error_message": "-", "error_messageString": "-", "error_responseType": "-", "extendedRequestId": "XvQ9KEj0IAMFTWg=", "httpMethod": "GET", "identity_accountId": "-", "identity_caller": "-", "identity_cognitoAuthenticationProvider": "-", "identity_cognitoAuthenticationType": "-", "identity_cognitoIdentityId": "-", "identity_cognitoIdentityPoolId": "-", "identity_principalOrgId": "-", "identity_clientCert_clientCertPem": "-", "identity_clientCert_subjectDN": "-", "identity_clientCert_issuerDN": "-", "identity_clientCert_serialNumber": "-", "identity_clientCert_validity_notBefore": "-", "identity_clientCert_validity_notAfter": "-", "identity_sourceIp": "73.222.193.39", "identity_user": "-", "identity_userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36", "identity_userArn": "-", "integration_error": "-", "integration_integrationStatus": "200", "integration_latency": "2372", "integration_requestId": "e8e2d03d-99bf-43ef-b427-ac75f01ad00e", "integration_status": "302", "integrationErrorMessage": "-", "integrationLatency": "2372", "integrationStatus": "200", "path": "/repository/files/13472277-c704-46fd-8aca-a9928c6d2d7b", "protocol": "HTTP/1.1", "requestId": "6cec1bdd-a85e-41ac-9d14-c6f1a5d7072d", "requestTime": "31/Aug/2022:17:06:40 +0000", "requestTimeEpoch": "1661965600896", "responseLatency": "2383", "responseLength": "0", "routeKey": "-", "stage": "daniel", "status": "302"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 2022-08-31 17:06:40.927 | [INFO] 2022-08-31T17:06:40.927Z e8e2d03d-99bf-43ef-b427-ac75f01ad00e azul.chalice Received GET request for '/repository/files/13472277-c704-46fd-8aca-a9928c6d2d7b', with query {"catalog": "dcp2", "version": "2021-05-14T13:44:33.938000Z"} and headers {"accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9", "accept-encoding": "gzip, deflate, br", "accept-language": "en-US,en;q=0.9", "cloudfront-forwarded-proto": "https", "cloudfront-is-desktop-viewer": "true", "cloudfront-is-mobile-viewer": "false", "cloudfront-is-smarttv-viewer": "false", "cloudfront-is-tablet-viewer": "false", "cloudfront-viewer-asn": "7922", "cloudfront-viewer-country": "US", "cookie": "G_ENABLED_IDPS=google; cs9-prd-web-8-1810-PORTAL-PSJSESSIONID=gjCUbg0fXxUA-dMJybbzUQoSxc9Xrogq!1567185761; experimentation_subject_id=IjA2OTQ1NGZmLTUzYmQtNGFlMi05ZTA1LTRiY2RkZTg1ZGFmYiI%3D--98287bfbd2c1c6ba94965fee0bb034b6d1f8677e; hguid=1093029397_YWSQPQ01F29qhTjG1BBAlcHqKUtd; lcsrftoken=exfsf+JnH1Vkp/DKx6PJPO8ZCV6/Ntwr4h1w8RY+y7w=", "host": "service.daniel.dev.singlecell.gi.ucsc.edu", "referer": "https://service.daniel.dev.singlecell.gi.ucsc.edu/index/files?catalog=dcp2&filters=%7B%22fileSize%22%3A%20%7B%22within%22%3A%20%5B%5B0%2C%2010000000%5D%5D%7D%7D&size=10", "sec-ch-ua": "\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"104\"", "sec-ch-ua-mobile": "?0", "sec-ch-ua-platform": "\"macOS\"", "sec-fetch-dest": "document", "sec-fetch-mode": "navigate", "sec-fetch-site": "same-origin", "sec-fetch-user": "?1", "sec-gpc": "1", "upgrade-insecure-requests": "1", "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36", "via": "2.0 ee1357dac478fcfacce91819c1cc9482.cloudfront.net (CloudFront)", "x-amz-cf-id": "8s_uGtuKrhdJjbllAGkGJtHJTo56xXJ8GjiPPcl5WbYq6CLHljZ7cA==", "x-amzn-trace-id": "Root=1-630f9520-1efb8649138976f53b481b65", "x-forwarded-for": "73.222.193.39, 70.132.61.103", "x-forwarded-port": "443", "x-forwarded-proto": "https"}.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2022-08-31 17:06:42.238 | [INFO] 2022-08-31T17:06:42.237Z e8e2d03d-99bf-43ef-b427-ac75f01ad00e azul.drs -> 200 b'{"id":"v1_b1083e8b-4de9-467a-97de-18179c4e6bd1_a7271c25-c9f6-493a-bea4-5a6427be2168","name":"10BTreg94_S382_L001_R1_001.fastq.gz","self_uri":"drs://jade.datarepo-dev.broadinstitute.org/v1_b1083e8b-4de9-467a-97de-18179c4e6bd1_a7271c25-c9f6-493a-bea4-5a6427be2168","size":2783000,"created_time":"2021-09-07T18:36:56.102Z","updated_time":"2021-09-07T18:36:56.102Z","version":"0","mime_type":null,"checksums":[{"checksum":"68e974bb","type":"crc32c"},{"checksum":"4388a94fd1d164e3d0ce8d3a8fb2b878","type":"md5"}],"access_methods":[{"type":"gs","access_url":{"url":"gs://datarepo-dev-a970b701-bucket/917777d2-b9f9-4b4a-990e-5a80d7a5a728/a7271c25-c9f6-493a-bea4-5a6427be2168/10BTreg94_S382_L001_ [...]

2022-08-31 21:49 UTC, noah-aviel-dove requested changes
Checklist is incomplete

2022-08-31 21:49 UTC, noah-aviel-dove commented on src/azul/__init__.py
> +    def _timing_is_restricted(self):
Would benefit from a return type annotation

```suggestion
    def _timing_is_restricted(self) -> bool:
```

2022-09-01 18:32 UTC, noah-aviel-dove approved these changes

2022-09-02 00:09 UTC, hannes-ucsc approved these changes

2022-09-02 01:31 UTC, merged