[Snyk] Security upgrade wheel from 0.37.1 to 0.38.0
DataBiosphere/azul pull request #4672
Opened 2022-11-01 21:08 UTC by azul-group

<p>This PR was automatically created by Snyk using the credentials of a real user.</p><br /><h3>Snyk has created this PR to fix one or more vulnerable packages in the `pip` dependencies of this project.</h3>

#### Changes included in this PR

- Changes to the following files to upgrade the vulnerable dependencies to a fixed version:
    - requirements.all.txt

<details>
<summary>⚠️ <b>Warning</b></summary>

```
httplib2 0.20.4 requires pyparsing, which is not installed.
google-auth 2.13.0 requires rsa, which is not installed.
bdbag 1.6.3 requires requests, which is not installed.
bagit-profile 1.3.1 requires requests, which is not installed.
aws-requests-auth 0.4.3 requires requests, which is not installed.

```
</details>

#### Vulnerabilities that will be fixed

##### By pinning:
Severity                   |  Issue                   | Upgrade                   | Breaking Change                   | Exploit Maturity
:-------------------------:|:-------------------------|:-------------------------|:-------------------------|:-------------------------
![medium severity](https://res.cloudinary.com/snyk/image/upload/w_20,h_20/v1561977819/icon/m.png "medium severity") | Regular Expression Denial of Service (ReDoS) <br/>[SNYK-PYTHON-WHEEL-3092128](https://snyk.io/vuln/SNYK-PYTHON-WHEEL-3092128) |  `wheel:` <br> `0.37.1 -> 0.38.0` <br>  |  No  | No Known Exploit 

Some vulnerabilities couldn't be fully fixed and so Snyk will still find them when the project is tested again. This may be because the vulnerability existed within more than one direct dependency, but not all of the affected dependencies could be upgraded.

Check the changes in this PR to ensure they won't cause issues with your project.

------------

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open fix PRs.*

For more information:  <img src="https://api.segment.io/v1/pixel/track?data=eyJ3cml0ZUtleSI6InJyWmxZcEdHY2RyTHZsb0lYd0dUcVg4WkFRTnNCOUEwIiwiYW5vbnltb3VzSWQiOiIwMjlkYTQ4My01YmY2LTQwNGItYWVhMS04Y2Q5YmM3YjlmYjkiLCJldmVudCI6IlBSIHZpZXdlZCIsInByb3BlcnRpZXMiOnsicHJJZCI6IjAyOWRhNDgzLTViZjYtNDA0Yi1hZWExLThjZDliYzdiOWZiOSJ9fQ==" width="0" height="0"/>
🧐 [View latest project report](https://app.snyk.io/org/azul/project/4d953c91-4fea-4446-b721-274d58c08bb9?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;fix-pr)

🛠 [Adjust project settings](https://app.snyk.io/org/azul/project/4d953c91-4fea-4446-b721-274d58c08bb9?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;fix-pr/settings)

📚 [Read more about Snyk's upgrade and patch logic](https://support.snyk.io/hc/en-us/articles/360003891078-Snyk-patches-to-fix-vulnerabilities)

[//]: # (snyk:metadata:{"prId":"029da483-5bf6-404b-aea1-8cd9bc7b9fb9","prPublicId":"029da483-5bf6-404b-aea1-8cd9bc7b9fb9","dependencies":[{"name":"wheel","from":"0.37.1","to":"0.38.0"}],"packageManager":"pip","projectPublicId":"4d953c91-4fea-4446-b721-274d58c08bb9","projectUrl":"https://app.snyk.io/org/azul/project/4d953c91-4fea-4446-b721-274d58c08bb9?utm_source=github&utm_medium=referral&page=fix-pr","type":"auto","patch":[],"vulns":["SNYK-PYTHON-WHEEL-3092128"],"upgrade":[],"isBreakingChange":false,"env":"prod","prType":"fix","templateVariants":["updated-fix-title","pr-warning-shown"],"priorityScoreList":[null]})

---

**Learn how to fix vulnerabilities with free interactive lessons:**

 🦉 [Regular Expression Denial of Service (ReDoS)](https://learn.snyk.io/lessons/redos/javascript//?loc&#x3D;fix-pr)

2022-11-03 21:26 UTC, achave11 approved these changes
LGTM.

2022-11-03 21:33 UTC, achave11 commented
Felt compelled to add PR checklist.

2022-11-03 22:17 UTC, hannes-ucsc approved these changes

2022-11-03 22:21 UTC, hannes-ucsc requested changes
Need R tag on at least one of the commits. Or a PR checklist item to add that tag to the merge commit.

2022-11-07 18:06 UTC, hannes-ucsc approved these changes

2022-11-07 22:43 UTC, merged