Update to AnVIL schema v4 (#4617)
DataBiosphere/azul pull request #4741
Opened 2022-11-15 04:14 UTC by noah-aviel-dove

Connected issues: #4617 

## Checklist

### Author

- [x] Target branch is `develop`
- [x] Name of PR branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [x] PR title references all connected issues
- [x] PR title matches<sup>1</sup> that of a connected issue        <sub>or comment in PR explains why they're different</sub>
- [x] For each connected issue, there is at least one commit whose title references that issue
- [x] PR is connected to all connected issues via Zenhub 
- [x] PR description links to connected issues
- [x] Added `partial` label to PR                                   <sub>or this PR completely resolves all connected issues</sub>

<sup>1</sup> when the issue title describes a problem, the corresponding PR title is `Fix: ` followed by the issue title   

### Author (reindex)

- [x] Added `r` tag to commit title                                 <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label to PR                                   <sub>or this PR does not require reindexing</sub>

### Author (chains)

- [x] This PR is blocked by previous PR in the chain               <sub>or this PR is not chained to another PR</sub>
- [x] Added `base` label to the blocking PR                        <sub>or this PR is not chained to another PR</sub>
- [x] Added `chained` label to this PR                             <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [x] Documented upgrading of deployments in UPGRADING.rst          <sub>or this PR does not require upgrading</sub>
- [x] Added `u` tag to commit title                                 <sub>or this PR does not require upgrading</sub>
- [x] Added `upgrade` label to PR                                   <sub>or this PR does not require upgrading</sub>

### Author (operator tasks)

- [x] Added checklist items for additional operator tasks           <sub>or this PR does not require additional tasks</sub>

### Author (hotfixes)

- [x] Added `F` tag to main commit title                            <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [x] Reverted the temporary hotfixes for any connected issues      <sub>or the `prod` branch has no temporary hotfixes for any connected issues</sub>

### Author (requirements, before every review)

- [x] Ran `make requirements_update`                                <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [x] Added `R` tag to commit title                                 <sub>or this PR does not touch requirements*.txt</sub>
- [x] Added `reqs` label to PR                                      <sub>or this PR does not touch requirements*.txt</sub>

### Author (rebasing, integration test)

- [ ] `make integration_test` passes in personal deployment         <sub>or this PR does not touch functionality that could break the IT</sub>
- [x] Rebased PR branch on `develop`, squashed old fixups

### Peer reviewer (after requesting changes)

Uncheck the *Author (requirements)* and *Author (rebasing, integration test)* 
checklists.

### Peer reviewer (after approval)

- [ ] Ticket is in *Review requested* column
- [ ] Requested review from primary reviewer
- [ ] Assigned PR to primary reviewer

### Primary reviewer (after requesting changes)

Uncheck the *Author (requirements)* and *Author (rebasing, integration test)* 
checklists. Update the `N reviews` label. 

### Primary reviewer (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issues as `demo` or `no demo`
- [ ] Commented on connected issues about demo expectations         <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] `N reviews` label is accurate
- [ ] Moved ticket to *Approved* column
- [ ] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear                      <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Rebased and squashed PR branch
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Pushed PR branch to GitLab `dev` and added `sandbox` label    <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `sandbox` deployment                          <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build log for anomalies in `sandbox` deployment      <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted unreferenced indices in `sandbox`                     <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices</sub> 
- [ ] Started reindex in `sandbox`                                  <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox`                             <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvildev`                         <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `anvilbox` deployment                         <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build log for anomalies in `anvilbox` deployment     <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted unreferenced indices in `anvilbox`                    <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices</sub> 
- [ ] Started reindex in `anvilbox`                                 <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `anvilbox`                            <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title
- [ ] Moved connected issues to Merged column
- [ ] Pushed merge commit to GitHub

### Operator (after pushing the merge commit)

- [ ] Shortened the PR chain                                        <sub>or this PR is not labeled `base`</sub>
- [ ] Pushed merge commit to GitLab `dev`                           <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed merge commit to GitLab `anvildev`                      <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes on GitLab `dev`<sup>1</sup>
- [ ] Reviewed build log for anomalies on GitLab `dev`<sup>1</sup>
- [ ] Build passes on GitLab `anvildev`<sup>1</sup>
- [ ] Reviewed build log for anomalies on GitLab `anvildev`<sup>1</sup>
- [ ] Deleted PR branch from GitHub
- [ ] Deleted PR branch from GitLab `dev`
- [ ] Deleted PR branch from GitLab `anvildev`

<sup>1</sup> When pushing the merge commit is skipped due to the PR being
labelled `no sandbox`, the next build triggered by a PR whose merge commit *is* 
pushed determines this checklist item.

### Operator (reindex) 

- [ ] Deleted unreferenced indices in `dev`                         <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices</sub> 
- [ ] Deleted unreferenced indices in `anvildev`                    <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices</sub> 
- [ ] Started reindex in `dev`                                      <sub>or this PR does not require reindexing</sub>
- [ ] Started reindex in `anvildev`                                 <sub>or this PR does not require reindexing</sub>
- [ ] Checked for and triaged indexing failures in `dev`            <sub>or this PR does not require reindexing</sub>
- [ ] Checked for and triaged indexing failures in `anvildev`       <sub>or this PR does not require reindexing</sub>
- [ ] Emptied fail queues in `dev` deployment                       <sub>or this PR does not require reindexing</sub>
- [ ] Emptied fail queues in `anvildev` deployment                  <sub>or this PR does not require reindexing</sub>

### Operator

- [ ] Unassigned PR

## Shorthand for review comments

- `L` line is too long
- `W` lin [...]

2022-12-01 07:20 UTC, achave11-ucsc approved these changes
LGTM 👌🏽

2022-12-05 18:35 UTC, hannes-ucsc requested changes
I am confused about the files names and provenance of the cans. 

This comment sounds wrong to me: https://github.com/DataBiosphere/azul/blob/64ae91b57af6a0f6fd2001fc2bf2a73aa4e53618/scripts/recan_bundle_tdr.py#L358

The deletion of .manifest.json and .metadata.json should be an early, separate commit if they are truly redundant.

The `.result` and `.results` in the file names are confusing, very similar but different semantics. I am also confused as to what purpose the `.tables` file has.

And there's a smell with https://github.com/DataBiosphere/azul/blob/64ae91b57af6a0f6fd2001fc2bf2a73aa4e53618/scripts/recan_bundle_tdr.py#L77

I think the code to create it is longer than a literal of the result, even though there is no advantage to making it dynamic since the references are very static.

Please request a PL slot for this.

2022-12-05 18:35 UTC, hannes-ucsc commented on scripts/can_bundle.py
> +                        help='Provide a key to redact personally senstive information from the output files')
```suggestion
                        help='Provide a key to redact confidential or sensitive information from the output files')
```

2022-12-05 18:35 UTC, hannes-ucsc commented on scripts/can_bundle.py
> +    >>> redact_json('sensitive', key + b'plit')
Empty line between test cases.

2022-12-05 18:35 UTC, hannes-ucsc commented on scripts/can_bundle.py
> +        o[:] = sorted(redact_json(item, key) for item in o)
A comment should explain the need for sorting.

2022-12-05 18:35 UTC, hannes-ucsc commented on scripts/can_bundle.py
> +def redact_json(o: AnyMutableJSON, key: bytes) -> AnyMutableJSON:
Either return or mutate in place, never both. If a mix is needed for recursion, a wrapper should hide that. I personally find pure functions easier to write and reason about. I only resort non-pure for performance reasons, or when that is easier to understand, for example, when a surgical change is made. This is more of a transformation so I would write a pure function.

FYI  @achave11

2022-12-06 00:23 UTC, hannes-ucsc requested changes

2022-12-06 00:23 UTC, hannes-ucsc commented on scripts/can_bundle.py
> +    >>> key = b'bananas'
```suggestion
    >>> key = b'bananas'
    
```

2022-12-06 00:23 UTC, hannes-ucsc commented on scripts/can_bundle.py
> +                        help='Provide a key to redact personally senstive information from the output files')
Please address https://github.com/DataBiosphere/azul/pull/4741/files#r1038456379

2022-12-06 00:23 UTC, hannes-ucsc commented on scripts/can_bundle.py
> +    >>> key = b'bananas'
This script should be included in `test_doctests.py`

2022-12-06 00:23 UTC, hannes-ucsc commented on scripts/can_bundle.py
> +    ['redacted-AVm0tjOw', 42027752232213208]
These can't be passing since Python can't sort heterogeneous iterables.

2022-12-06 00:23 UTC, hannes-ucsc commented on scripts/can_bundle.py
> +    {'foo': ['redacted-AVm0tjOw', {'bar': 42027752232213208}]}
These can't be passing since Python can't sort heterogeneous iterables.

2022-12-06 19:00 UTC, hannes-ucsc requested changes

2022-12-06 19:00 UTC, hannes-ucsc commented on scripts/can_bundle.py
> +                        help='Provide a key to redact confidential or senstive information from the output files')
```suggestion
                        help='Provide a key to redact confidential or sensitive information from the output files')
```

2022-12-07 01:23 UTC, hannes-ucsc approved these changes

2022-12-07 21:31 UTC, merged