Ensure IAM password policies have strong configurations (#4692)
DataBiosphere/azul pull request #4803
Opened 2022-12-08 00:45 UTC by danielsotirhos

Connected issues: #4692

## Checklist

### Author

- [x] Target branch is `develop`
- [x] Name of PR branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [x] PR title references all connected issues
- [x] PR title matches<sup>1</sup> that of a connected issue        <sub>or comment in PR explains why they're different</sub>
- [x] For each connected issue, there is at least one commit whose title references that issue
- [x] PR is connected to all connected issues via Zenhub 
- [x] PR description links to connected issues
- [x] Added `partial` label to PR                                   <sub>or this PR completely resolves all connected issues</sub>

<sup>1</sup> when the issue title describes a problem, the corresponding PR title is `Fix: ` followed by the issue title   

### Author (reindex)

- [ ] Added `r` tag to commit title                                 <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label to PR                                   <sub>or this PR does not require reindexing</sub>

### Author (chains)

- [ ] This PR is blocked by previous PR in the chain               <sub>or this PR is not chained to another PR</sub>
- [ ] Added `base` label to the blocking PR                        <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chained` label to this PR                             <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [ ] Documented upgrading of deployments in UPGRADING.rst          <sub>or this PR does not require upgrading</sub>
- [ ] Added `u` tag to commit title                                 <sub>or this PR does not require upgrading</sub>
- [ ] Added `upgrade` label to PR                                   <sub>or this PR does not require upgrading</sub>

### Author (operator tasks)

- [ ] Added checklist items for additional operator tasks           <sub>or this PR does not require additional tasks</sub>

### Author (hotfixes)

- [ ] Added `F` tag to main commit title                            <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [ ] Reverted the temporary hotfixes for any connected issues      <sub>or the `prod` branch has no temporary hotfixes for any connected issues</sub>

### Author (requirements, before every review)

- [ ] Ran `make requirements_update`                                <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [ ] Added `R` tag to commit title                                 <sub>or this PR does not touch requirements*.txt</sub>
- [ ] Added `reqs` label to PR                                      <sub>or this PR does not touch requirements*.txt</sub>

### Author (rebasing, integration test)

- [ ] `make integration_test` passes in personal deployment         <sub>or this PR does not touch functionality that could break the IT</sub>
- [ ] Rebased PR branch on `develop`, squashed old fixups

### Peer reviewer (after requesting changes)

Uncheck the *Author (requirements)* and *Author (rebasing, integration test)* 
checklists.

### Peer reviewer (after approval)

- [ ] Ticket is in *Review requested* column
- [ ] Requested review from primary reviewer
- [ ] Assigned PR to primary reviewer

### Primary reviewer (after requesting changes)

Uncheck the *Author (requirements)* and *Author (rebasing, integration test)* 
checklists. Update the `N reviews` label. 

### Primary reviewer (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issues as `demo` or `no demo`
- [ ] Commented on connected issues about demo expectations         <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] `N reviews` label is accurate
- [ ] Moved ticket to *Approved* column
- [ ] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear                      <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Rebased and squashed PR branch
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Pushed PR branch to GitLab `dev` and added `sandbox` label    <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `sandbox` deployment                          <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build log for anomalies in `sandbox` deployment      <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted unreferenced indices in `sandbox`                     <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices</sub> 
- [ ] Started reindex in `sandbox`                                  <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox`                             <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvildev`                         <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `anvilbox` deployment                         <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build log for anomalies in `anvilbox` deployment     <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted unreferenced indices in `anvilbox`                    <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices</sub> 
- [ ] Started reindex in `anvilbox`                                 <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `anvilbox`                            <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title
- [ ] Moved connected issues to Merged column
- [ ] Pushed merge commit to GitHub

### Operator (after pushing the merge commit)

- [ ] Shortened the PR chain                                        <sub>or this PR is not labeled `base`</sub>
- [ ] Pushed merge commit to GitLab `dev`                           <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed merge commit to GitLab `anvildev`                      <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes on GitLab `dev`<sup>1</sup>
- [ ] Reviewed build log for anomalies on GitLab `dev`<sup>1</sup>
- [ ] Build passes on GitLab `anvildev`<sup>1</sup>
- [ ] Reviewed build log for anomalies on GitLab `anvildev`<sup>1</sup>
- [ ] Deleted PR branch from GitHub
- [ ] Deleted PR branch from GitLab `dev`
- [ ] Deleted PR branch from GitLab `anvildev`

<sup>1</sup> When pushing the merge commit is skipped due to the PR being
labelled `no sandbox`, the next build triggered by a PR whose merge commit *is* 
pushed determines this checklist item.

### Operator (reindex) 

- [ ] Deleted unreferenced indices in `dev`                         <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices</sub> 
- [ ] Deleted unreferenced indices in `anvildev`                    <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices</sub> 
- [ ] Started reindex in `dev`                                      <sub>or this PR does not require reindexing</sub>
- [ ] Started reindex in `anvildev`                                 <sub>or this PR does not require reindexing</sub>
- [ ] Checked for and triaged indexing failures in `dev`            <sub>or this PR does not require reindexing</sub>
- [ ] Checked for and triaged indexing failures in `anvildev`       <sub>or this PR does not require reindexing</sub>
- [ ] Emptied fail queues in `dev` deployment                       <sub>or this PR does not require reindexing</sub>
- [ ] Emptied fail queues in `anvildev` deployment                  <sub>or this PR does not require reindexing</sub>

### Operator

- [ ] Unassigned PR

## Shorthand for review comments

- `L` line is too long
- `W` line [...]

2022-12-09 17:31 UTC, danielsotirhos commented
Output from `make plan`:

```
Terraform will perform the following actions:

  # aws_iam_account_password_policy.cis_compliant will be created
  + resource "aws_iam_account_password_policy" "cis_compliant" {
      + allow_users_to_change_password = true
      + expire_passwords               = (known after apply)
      + hard_expiry                    = (known after apply)
      + id                             = (known after apply)
      + max_password_age               = 90
      + minimum_password_length        = 14
      + password_reuse_prevention      = 24
      + require_lowercase_characters   = true
      + require_numbers                = true
      + require_symbols                = true
      + require_uppercase_characters   = true
    }
```

2022-12-09 23:34 UTC, danielsotirhos commented
Unable to test on anvildev:
> Error: Error updating IAM Password Policy: AccessDenied: User: arn:aws:sts::289950828509:assumed-role/developer/botocore-session-1670627408 is not authorized to perform: iam:UpdateAccountPasswordPolicy on resource: * because no identity-based policy allows the iam:UpdateAccountPasswordPolicy action

2022-12-10 00:11 UTC, achave11 approved these changes

2022-12-10 07:31 UTC, hannes-ucsc requested changes

2022-12-10 07:31 UTC, hannes-ucsc commented on terraform/shared/shared.tf.json.template.py
> +            'cis_compliant': {
```suggestion
            'cis': {
```

2022-12-12 19:06 UTC, hannes-ucsc requested changes
Timing of checklist item is inconsistent with upgrade instructions.

You [indicate](https://github.com/DataBiosphere/azul/pull/4803#issuecomment-1344888308) that there is a problem with permissions but appear to not have taken any steps to address or accommodate that problem.

2022-12-13 17:44 UTC, danielsotirhos commented
Tested deploying changes to anvildev:

![Screen Shot 2022-12-13 at 9 42 56 AM](https://user-images.githubusercontent.com/46407464/207406484-0ad994f0-c30a-47b9-8577-76f3fcb2e128.png)

2022-12-14 01:32 UTC, hannes-ucsc approved these changes

2022-12-14 17:26 UTC, merged