Enable VPC flow logs (#4176)
DataBiosphere/azul pull request #5036
Opened 2023-03-09 01:34 UTC by achave11

Connected issues: #4176 

## Checklist

### Author

- [x] PR is a draft
- [ ] Target branch is `develop`
- [ ] Name of PR branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [ ] PR title references all connected issues
- [ ] PR title matches<sup>1</sup> that of a connected issue <sub>or comment in PR explains why they're different</sub>
- [ ] For each connected issue, there is at least one commit whose title references that issue
- [ ] PR is connected to all connected issues via ZenHub
- [ ] PR description links to connected issues
- [ ] Added `partial` label to PR <sub>or this PR completely resolves all connected issues</sub>

<sup>1</sup> when the issue title describes a problem, the corresponding PR
title is `Fix: ` followed by the issue title

### Author (reindex, API changes)

- [ ] Added `r` tag to commit title <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label to PR <sub>or this PR does not require reindexing</sub>
- [ ] Added `a` (compatible changes) or `A` (incompatible ones) tag to commit title <sub>or this PR does not modify the Azul service API</sub>
- [ ] Added `API` label to connected issues <sub>or this PR does not modify the Azul service API</sub>

### Author (chains)

- [ ] This PR is blocked by previous PR in the chain <sub>or this PR is not chained to another PR</sub>
- [ ] Added `base` label to the blocking PR <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chained` label to this PR <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [ ] Documented upgrading of deployments in UPGRADING.rst <sub>or this PR does not require upgrading</sub>
- [ ] Added `u` tag to commit title <sub>or this PR does not require upgrading</sub>
- [ ] Added `upgrade` label to PR <sub>or this PR does not require upgrading</sub>

### Author (operator tasks)

- [ ] Added checklist items for additional operator tasks <sub>or this PR does not require additional tasks</sub>

### Author (hotfixes)

- [ ] Added `F` tag to main commit title <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [ ] Reverted the temporary hotfixes for any connected issues <sub>or the `prod` branch has no temporary hotfixes for any connected issues</sub>

### Author (before every review)

- [ ] Rebased PR branch on `develop`, squashed old fixups
- [ ] Ran `make requirements_update` <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [ ] Added `R` tag to commit title <sub>or this PR does not touch requirements*.txt</sub>
- [ ] Added `reqs` label to PR <sub>or this PR does not touch requirements*.txt</sub>
- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>

### Peer reviewer (after requesting changes)

Uncheck the *Author (before every review)* checklists.

### Peer reviewer (after approval)

- [ ] PR is not a draft
- [ ] Ticket is in *Review requested* column
- [ ] Requested review from primary reviewer
- [ ] Assigned PR to primary reviewer

### Primary reviewer (after requesting changes)

Uncheck the *before every review* checklists. Update the `N reviews` label.

### Primary reviewer (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issues as `demo` or `no demo`
- [ ] Commented on connected issues about demo expectations <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] `N reviews` label is accurate
- [ ] Moved ticket to *Approved* column
- [ ] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Squashed PR branch and rebased onto `develop`
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Pushed PR branch to GitLab `dev` and added `sandbox` label <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted unreferenced indices in `sandbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Deleted unreferenced indices in `anvilbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Started reindex in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Started reindex in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title
- [ ] Moved connected issues to Merged column in ZenHub
- [ ] Pushed merge commit to GitHub

### Operator (after pushing the merge commit)

- [ ] Shortened the PR chain <sub>or this PR is not labeled `base`</sub>
- [ ] Pushed merge commit to GitLab `dev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed merge commit to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes on GitLab `dev`<sup>1</sup>
- [ ] Reviewed build logs for anomalies on GitLab `dev`<sup>1</sup>
- [ ] Build passes on GitLab `anvildev`<sup>1</sup>
- [ ] Reviewed build logs for anomalies on GitLab `anvildev`<sup>1</sup>
- [ ] Deleted PR branch from GitHub
- [ ] Deleted PR branch from GitLab `dev`
- [ ] Deleted PR branch from GitLab `anvildev`

<sup>1</sup> When pushing the merge commit is skipped due to the PR being
labelled `no sandbox`, the next build triggered by a PR whose merge commit *is*
pushed determines this checklist item.

### Operator (reindex)

- [ ] Deleted unreferenced indices in `dev` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Deleted unreferenced indices in `anvildev` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Started reindex in `dev` <sub>or this PR does not require reindexing</sub>
- [ ] Started reindex in `anvildev` <sub>or this PR does not require reindexing</sub>
- [ ] Checked for and triaged indexing failures in `dev` <sub>or this PR does not require reindexing</sub>
- [ ] Checked for and triaged indexing failures in `anvildev` <sub>or this PR does not require reindexing</sub>
- [ ] Emptied fail queues in `dev` deployment <sub>or this PR does not require reindexing</sub>
- [ ] Emptied fail queues in `anvildev` deployment <sub>or this PR does not require reindexing</sub>

### Operator

- [ ] Unassigned PR

## Shorthand for review comments

- `L` line is too long
- `W` line wrapping is wrong
- `Q` bad quotes
- `F` other formatting problem

2023-03-09 19:17 UTC, achave11 commented
The following is the TF plan output for the newly added resources.
```
Terraform will perform the following actions:

  # aws_cloudwatch_log_group.gitlab_vpc-flow-logs will be created
  + resource "aws_cloudwatch_log_group" "gitlab_vpc-flow-logs" {
      + arn               = (known after apply)
      + id                = (known after apply)
      + name              = "/aws/vpc/azul-gitlab-flow-logs"
      + retention_in_days = 180
      + tags              = {
          + "Name"                = "azul-gitlab_vpc-flow-logs"
          + "billing"             = "hca"
          + "component"           = "azul-gitlab_vpc-flow-logs"
          + "deployment"          = "dev"
          + "owner"               = "hannes@ucsc.edu"
          + "service"             = "azul"
          + "terraform_component" = "gitlab"
        }
      + tags_all          = {
          + "Name"                = "azul-gitlab_vpc-flow-logs"
          + "billing"             = "hca"
          + "component"           = "azul-gitlab_vpc-flow-logs"
          + "deployment"          = "dev"
          + "owner"               = "hannes@ucsc.edu"
          + "service"             = "azul"
          + "terraform_component" = "gitlab"
        }
    }

  # aws_flow_log.gitlab_vpc-flow-logs will be created
  + resource "aws_flow_log" "gitlab_vpc-flow-logs" {
      + arn                      = (known after apply)
      + iam_role_arn             = (known after apply)
      + id                       = (known after apply)
      + log_destination          = (known after apply)
      + log_destination_type     = "cloud-watch-logs"
      + log_format               = (known after apply)
      + log_group_name           = (known after apply)
      + max_aggregation_interval = 600
      + tags                     = {
          + "Name"                = "azul-gitlab_vpc-flow-logs"
          + "billing"             = "hca"
          + "component"           = "azul-gitlab_vpc-flow-logs"
          + "deployment"          = "dev"
          + "owner"               = "hannes@ucsc.edu"
          + "service"             = "azul"
          + "terraform_component" = "gitlab"
        }
      + tags_all                 = {
          + "Name"                = "azul-gitlab_vpc-flow-logs"
          + "billing"             = "hca"
          + "component"           = "azul-gitlab_vpc-flow-logs"
          + "deployment"          = "dev"
          + "owner"               = "hannes@ucsc.edu"
          + "service"             = "azul"
          + "terraform_component" = "gitlab"
        }
      + traffic_type             = "ALL"
      + vpc_id                   = "vpc-03aeb4a3542c7a5d3"
    }

  # aws_iam_policy.gitlab_vpc-flow-logs will be created
  + resource "aws_iam_policy" "gitlab_vpc-flow-logs" {
      + arn       = (known after apply)
      + id        = (known after apply)
      + name      = "azul-gitlab_vpc-flow-logs"
      + path      = "/"
      + policy    = jsonencode(
            {
              + Statement = [
                  + {
                      + Action   = [
                          + "logs:CreateLogGroup",
                          + "logs:CreateLogStream",
                          + "logs:PutLogEvents",
                          + "logs:DescribeLogGroups",
                          + "logs:DescribeLogStreams",
                        ]
                      + Effect   = "Allow"
                      + Resource = "*"
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + policy_id = (known after apply)
      + tags      = {
          + "Name"                = "azul-gitlab_vpc-flow-logs"
          + "billing"             = "hca"
          + "component"           = "azul-gitlab_vpc-flow-logs"
          + "deployment"          = "dev"
          + "owner"               = "hannes@ucsc.edu"
          + "service"             = "azul"
          + "terraform_component" = "gitlab"
        }
      + tags_all  = {
          + "Name"                = "azul-gitlab_vpc-flow-logs"
          + "billing"             = "hca"
          + "component"           = "azul-gitlab_vpc-flow-logs"
          + "deployment"          = "dev"
          + "owner"               = "hannes@ucsc.edu"
          + "service"             = "azul"
          + "terraform_component" = "gitlab"
        }
    }

  # aws_iam_role.gitlab_vpc-flow-logs will be created
  + resource "aws_iam_role" "gitlab_vpc-flow-logs" {
      + arn                   = (known after apply)
      + assume_role_policy    = jsonencode(
            {
              + Statement = [
                  + {
                      + Action    = "sts:AssumeRole"
                      + Effect    = "Allow"
                      + Principal = {
                          + Service = "vpc-flow-logs.amazonaws.com"
                        }
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + create_date           = (known after apply)
      + force_detach_policies = false
      + id                    = (known after apply)
      + managed_policy_arns   = (known after apply)
      + max_session_duration  = 3600
      + name                  = "azul-gitlab_vpc-flow-logs"
      + name_prefix           = (known after apply)
      + path                  = "/"
      + tags                  = {
          + "Name"                = "azul-gitlab_vpc-flow-logs"
          + "billing"             = "hca"
          + "component"           = "azul-gitlab_vpc-flow-logs"
          + "deployment"          = "dev"
          + "owner"               = "hannes@ucsc.edu"
          + "service"             = "azul"
          + "terraform_component" = "gitlab"
        }
      + tags_all              = {
          + "Name"                = "azul-gitlab_vpc-flow-logs"
          + "billing"             = "hca"
          + "component"           = "azul-gitlab_vpc-flow-logs"
          + "deployment"          = "dev"
          + "owner"               = "hannes@ucsc.edu"
          + "service"             = "azul"
          + "terraform_component" = "gitlab"
        }
      + unique_id             = (known after apply)

      + inline_policy {
          + name   = (known after apply)
          + policy = (known after apply)
        }
    }

  # aws_iam_role_policy_attachment.gitlab_vpc-flow-logs will be created
  + resource "aws_iam_role_policy_attachment" "gitlab_vpc-flow-logs" {
      + id         = (known after apply)
      + policy_arn = (known after apply)
      + role       = "azul-gitlab_vpc-flow-logs"
    }

Plan: 5 to add, 0 to change, 0 to destroy.

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions
if you run "terraform apply" now.

```

2023-03-09 20:21 UTC, achave11 commented on terraform/gitlab/gitlab.tf.json.template.py
> +            'gitlab_vpc': {
```suggestion
            'gitlab': {
```

2023-03-09 20:27 UTC, achave11 commented on terraform/gitlab/gitlab.tf.json.template.py
> +                'name': 'azul-gitlab-vpc',
```suggestion
                'name': 'azul-gitlab_vpc',
```

2023-03-10 19:24 UTC, achave11 commented
Enabling flow logs for the default VPC in the `shared` component produced a valid TF plan.
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  + create

Terraform will perform the following actions:

  # aws_cloudwatch_log_group.default will be created
  + resource "aws_cloudwatch_log_group" "default" {
      + arn               = (known after apply)
      + id                = (known after apply)
      + name              = "/aws/vpc/azul-default-dev"
      + retention_in_days = 180
      + tags              = {
          + "Name"                = "azul-default"
          + "billing"             = "hca"
          + "component"           = "azul-default"
          + "deployment"          = "dev"
          + "owner"               = "hannes@ucsc.edu"
          + "service"             = "azul"
          + "terraform_component" = "shared"
        }
      + tags_all          = {
          + "Name"                = "azul-default"
          + "billing"             = "hca"
          + "component"           = "azul-default"
          + "deployment"          = "dev"
          + "owner"               = "hannes@ucsc.edu"
          + "service"             = "azul"
          + "terraform_component" = "shared"
        }
    }

  # aws_flow_log.default will be created
  + resource "aws_flow_log" "default" {
      + arn                      = (known after apply)
      + iam_role_arn             = (known after apply)
      + id                       = (known after apply)
      + log_destination          = (known after apply)
      + log_destination_type     = "cloud-watch-logs"
      + log_format               = (known after apply)
      + log_group_name           = (known after apply)
      + max_aggregation_interval = 600
      + tags                     = {
          + "Name"                = "azul-default"
          + "billing"             = "hca"
          + "component"           = "azul-default"
          + "deployment"          = "dev"
          + "owner"               = "hannes@ucsc.edu"
          + "service"             = "azul"
          + "terraform_component" = "shared"
        }
      + tags_all                 = {
          + "Name"                = "azul-default"
          + "billing"             = "hca"
          + "component"           = "azul-default"
          + "deployment"          = "dev"
          + "owner"               = "hannes@ucsc.edu"
          + "service"             = "azul"
          + "terraform_component" = "shared"
        }
      + traffic_type             = "ALL"
      + vpc_id                   = "vpc-aadf0dd0"
    }

  # aws_iam_role.default will be created
  + resource "aws_iam_role" "default" {
      + arn                   = (known after apply)
      + assume_role_policy    = jsonencode(
            {
              + Statement = [
                  + {
                      + Action    = "sts:AssumeRole"
                      + Effect    = "Allow"
                      + Principal = {
                          + Service = "vpc-flow-logs.amazonaws.com"
                        }
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + create_date           = (known after apply)
      + force_detach_policies = false
      + id                    = (known after apply)
      + managed_policy_arns   = (known after apply)
      + max_session_duration  = 3600
      + name                  = "azul-default_vpc-dev"
      + name_prefix           = (known after apply)
      + path                  = "/"
      + tags                  = {
          + "Name"                = "azul-default"
          + "billing"             = "hca"
          + "component"           = "azul-default"
          + "deployment"          = "dev"
          + "owner"               = "hannes@ucsc.edu"
          + "service"             = "azul"
          + "terraform_component" = "shared"
        }
      + tags_all              = {
          + "Name"                = "azul-default"
          + "billing"             = "hca"
          + "component"           = "azul-default"
          + "deployment"          = "dev"
          + "owner"               = "hannes@ucsc.edu"
          + "service"             = "azul"
          + "terraform_component" = "shared"
        }
      + unique_id             = (known after apply)

      + inline_policy {
          + name   = (known after apply)
          + policy = (known after apply)
        }
    }

  # aws_iam_role_policy.default will be created
  + resource "aws_iam_role_policy" "default" {
      + id     = (known after apply)
      + name   = "azul-default_vpc-dev"
      + policy = jsonencode(
            {
              + Statement = [
                  + {
                      + Action   = [
                          + "logs:CreateLogGroup",
                          + "logs:CreateLogStream",
                          + "logs:PutLogEvents",
                          + "logs:DescribeLogGroups",
                          + "logs:DescribeLogStreams",
                        ]
                      + Effect   = "Allow"
                      + Resource = "*"
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + role   = (known after apply)
    }

Plan: 4 to add, 0 to change, 0 to destroy.

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run
"terraform apply" now.


```

2023-03-10 22:31 UTC, noah-aviel-dove requested changes
Just a few small things

2023-03-10 22:31 UTC, noah-aviel-dove commented on UPGRADING.rst
> +Manually deploy the ``gitlab`` as well as the ``shared`` component of any main
```suggestion
Manually deploy the ``gitlab`` and  ``shared`` components of any main
```

2023-03-10 22:31 UTC, noah-aviel-dove commented on terraform/shared/shared.tf.json.template.py
> +        # attribute in the docs, its usage is valid.
I would move this comment to where the `.id` attribute is accessed

2023-03-10 23:28 UTC, noah-aviel-dove submitted a review, later dismissed

2023-03-11 21:11 UTC, hannes-ucsc submitted a review, later dismissed

2023-03-11 21:11 UTC, hannes-ucsc approved these changes

2023-03-11 22:14 UTC, merged