Invalid JSON for search_after or …before should cause 4xx (#4996)
DataBiosphere/azul pull request #5163
Opened 2023-04-26 18:12 UTC by dsotirho-ucsc

Connected issues: #4996

## Checklist

### Author

- [ ] PR is a draft
- [ ] Target branch is `develop`
- [ ] Name of PR branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [ ] PR title references all connected issues
- [ ] PR title matches<sup>1</sup> that of a connected issue <sub>or comment in PR explains why they're different</sub>
- [ ] For each connected issue, there is at least one commit whose title references that issue
- [ ] PR is connected to all connected issues via ZenHub
- [ ] PR description links to connected issues
- [ ] Added `partial` label to PR <sub>or this PR completely resolves all connected issues</sub>

<sup>1</sup> when the issue title describes a problem, the corresponding PR
title is `Fix: ` followed by the issue title

### Author (reindex, API changes)

- [ ] Added `r` tag to commit title <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label to PR <sub>or this PR does not require reindexing</sub>
- [ ] Added `a` (compatible changes) or `A` (incompatible ones) tag to commit title <sub>or this PR does not modify the Azul service API</sub>
- [ ] Added `API` label to connected issues <sub>or this PR does not modify the Azul service API</sub>

### Author (chains)

- [ ] This PR is blocked by previous PR in the chain <sub>or this PR is not chained to another PR</sub>
- [ ] Added `base` label to the blocking PR <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chained` label to this PR <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [ ] Documented upgrading of deployments in UPGRADING.rst <sub>or this PR does not require upgrading</sub>
- [ ] Added `u` tag to commit title <sub>or this PR does not require upgrading</sub>
- [ ] Added `upgrade` label to PR <sub>or this PR does not require upgrading</sub>

### Author (operator tasks)

- [ ] Added checklist items for additional operator tasks <sub>or this PR does not require additional tasks</sub>

### Author (hotfixes)

- [ ] Added `F` tag to main commit title <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [ ] Reverted the temporary hotfixes for any connected issues <sub>or the `prod` branch has no temporary hotfixes for any connected issues</sub>

### Author (before every review)

- [ ] Rebased PR branch on `develop`, squashed old fixups
- [ ] Ran `make requirements_update` <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [ ] Added `R` tag to commit title <sub>or this PR does not touch requirements*.txt</sub>
- [ ] Added `reqs` label to PR <sub>or this PR does not touch requirements*.txt</sub>
- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>

### Peer reviewer (after requesting changes)

Uncheck the *Author (before every review)* checklists.

### Peer reviewer (after approval)

- [ ] PR is not a draft
- [ ] Ticket is in *Review requested* column
- [ ] Requested review from primary reviewer
- [ ] Assigned PR to primary reviewer

### Primary reviewer (after requesting changes)

Uncheck the *before every review* checklists. Update the `N reviews` label.

### Primary reviewer (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issues as `demo` or `no demo`
- [ ] Commented on connected issues about demo expectations <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] `N reviews` label is accurate
- [ ] Moved ticket to *Approved* column
- [ ] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Squashed PR branch and rebased onto `develop`
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Pushed PR branch to GitLab `dev` and added `sandbox` label <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted unreferenced indices in `sandbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Deleted unreferenced indices in `anvilbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Started reindex in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Started reindex in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title
- [ ] Moved connected issues to Merged column in ZenHub
- [ ] Pushed merge commit to GitHub

### Operator (after pushing the merge commit)

- [ ] Shortened the PR chain <sub>or this PR is not labeled `base`</sub>
- [ ] Pushed merge commit to GitLab `dev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed merge commit to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes on GitLab `dev`<sup>1</sup>
- [ ] Reviewed build logs for anomalies on GitLab `dev`<sup>1</sup>
- [ ] Build passes on GitLab `anvildev`<sup>1</sup>
- [ ] Reviewed build logs for anomalies on GitLab `anvildev`<sup>1</sup>
- [ ] Deleted PR branch from GitHub
- [ ] Deleted PR branch from GitLab `dev`
- [ ] Deleted PR branch from GitLab `anvildev`

<sup>1</sup> When pushing the merge commit is skipped due to the PR being
labelled `no sandbox`, the next build triggered by a PR whose merge commit *is*
pushed determines this checklist item.

### Operator (reindex)

- [ ] Deleted unreferenced indices in `dev` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Deleted unreferenced indices in `anvildev` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Started reindex in `dev` <sub>or this PR does not require reindexing</sub>
- [ ] Started reindex in `anvildev` <sub>or this PR does not require reindexing</sub>
- [ ] Checked for and triaged indexing failures in `dev` <sub>or this PR does not require reindexing</sub>
- [ ] Checked for and triaged indexing failures in `anvildev` <sub>or this PR does not require reindexing</sub>
- [ ] Emptied fail queues in `dev` deployment <sub>or this PR does not require reindexing</sub>
- [ ] Emptied fail queues in `anvildev` deployment <sub>or this PR does not require reindexing</sub>

### Operator

- [ ] Unassigned PR

## Shorthand for review comments

- `L` line is too long
- `W` line wrapping is wrong
- `Q` bad quotes
- `F` other formatting problem

2023-04-27 19:32 UTC, nadove-ucsc requested changes
Consider consolidating with the filters validation:

```diff
Subject: [PATCH] fixup!
---
Index: lambdas/service/app.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lambdas/service/app.py b/lambdas/service/app.py
--- a/lambdas/service/app.py	(revision 335e08fe20bb3a94f51f065271bc3b13663fb7dd)
+++ b/lambdas/service/app.py	(date 1682623858598)
@@ -698,10 +698,7 @@
 
 
 def validate_filters(filters):
-    try:
-        filters = json.loads(filters)
-    except Exception:
-        raise BRE('The `filters` parameter is not valid JSON')
+    filters = validate_json(filters)
     if type(filters) is not dict:
         raise BRE('The `filters` parameter must be a dictionary')
     field_types = app.repository_controller.field_types(app.catalog)
@@ -783,9 +780,9 @@
         raise BRE(f'Unknown order `{order}`. Must be one of {supported_orders}')
 
 
-def validate_json(json_: str):
+def validate_json(json_: str) -> MutableJSON:
     try:
-        json.loads(json_)
+        return json.loads(json_)
     except json.decoder.JSONDecodeError:
         raise BRE(f'Invalid JSON string: {json_!r}')
 
```

2023-04-28 17:47 UTC, dsotirho-ucsc commented
> Consider consolidating with the filters validation:

Implemented your suggestion with some tweaks to preserve the existing error message:
```
The `filters` parameter is not valid JSON
```
and produce a similar error message if `search_after` or `search_before` contain invalid JSON.

2023-04-28 19:38 UTC, nadove-ucsc requested changes
Nice work with the error messages. I think the test can be written more succinctly: 

```diff
Subject: [PATCH] fixup!
---
Index: test/service/test_response.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/service/test_response.py b/test/service/test_response.py
--- a/test/service/test_response.py	(revision 78588bade4a710e52eb19af4b97c52aef4383feb)
+++ b/test/service/test_response.py	(date 1682710468719)
@@ -2070,18 +2070,15 @@
             'search_before': response_json['pagination']['previous'],
             'search_after': response_json['pagination']['next']
         }
-        for pagination_key, url in test_cases.items():
+        for pagination_key, good_url in test_cases.items():
             with self.subTest(pagination_key=pagination_key):
-                query_params = parse_url_qs(url)
-                url_ = furl(url)
                 # Verify URL works before modifying
-                good_url = furl(origin=url_.origin, path=url_.path, query=query_params)
-                response = requests.get(str(good_url))
+                response = requests.get(good_url)
                 response.raise_for_status()
                 # Modify search_… param in URL and verify expected error occurs
-                self.assertIn('"', query_params[pagination_key])
-                query_params[pagination_key] = query_params[pagination_key].replace('"', '')
-                bad_url = furl(origin=url_.origin, path=url_.path, query=query_params)
+                bad_url = furl(good_url)
+                self.assertIn('"', bad_url.args[pagination_key])
+                bad_url.args[pagination_key] = bad_url.args[pagination_key].replace('"', '')
                 response = requests.get(str(bad_url))
                 error_msg = f'The `{pagination_key}` parameter is not valid JSON'
                 expected_text = f'{{"Code":"BadRequestError","Message":"{error_msg}"}}'
```

2023-04-28 23:33 UTC, nadove-ucsc submitted a review, later dismissed

2023-05-01 19:03 UTC, hannes-ucsc requested changes

2023-05-01 19:03 UTC, hannes-ucsc commented on lambdas/service/app.py
> +        'search_after': validate_search_after,
```suggestion
        'search_after': partial(validate_json_param, 'search_before')
```

using `functools.partial`

2023-05-01 19:03 UTC, hannes-ucsc commented on lambdas/service/app.py
> +def validate_json_param(name: str, json_: str) -> MutableJSON:
```suggestion
def validate_json_param(name: str, value: str) -> MutableJSON:
```

Underscore should be a last resort.

2023-05-01 19:03 UTC, hannes-ucsc commented on lambdas/service/app.py
> +        raise BRE(f'The `{name}` parameter is not valid JSON')
```suggestion
        raise BRE(f'The {name!r} parameter is not valid JSON')
```

We're moving away from backquotes and there is precedent in this module that shows that we already started, so I'm OK with having a mix of single quotes and backquotes.

2023-05-01 22:25 UTC, hannes-ucsc approved these changes

2023-05-01 22:33 UTC, hannes-ucsc requested changes
PR and commit title should start with `Fix: `. I unchecked the corresponding CL item.

2023-05-03 02:14 UTC, hannes-ucsc approved these changes

2023-05-04 20:45 UTC, merged