Track Replica hub IDs (#5360)
DataBiosphere/azul pull request #5490
Opened 2023-08-30 02:44 UTC by nadove-ucsc

Connected issues: #5360

## Checklist

### Author

- [x] PR is a draft
- [ ] Target branch is `develop`
- [x] Name of PR branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [x] PR title references all connected issues
- [x] PR title matches<sup>1</sup> that of a connected issue <sub>or comment in PR explains why they're different</sub>
- [x] For each connected issue, there is at least one commit whose title references that issue
- [ ] PR is connected to all connected issues via ZenHub
- [x] PR description links to connected issues
- [x] Added `partial` label to PR <sub>or this PR completely resolves all connected issues</sub>

<sup>1</sup> when the issue title describes a problem, the corresponding PR
title is `Fix: ` followed by the issue title

### Author (reindex, API changes)

- [x] Added `r` tag to commit title <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label to PR <sub>or this PR does not require reindexing</sub>
- [x] PR and connected issue are labeled `API` <sub>or this PR does not modify a REST API</sub>
- [x] Added `a` (`A`) tag to commit title for backwards (in)compatible changes <sub>or this PR does not modify a REST API</sub>
- [x] Updated REST API version number in `app.py` <sub>or this PR does not modify a REST API</sub>

### Author (chains)

- [ ] This PR is blocked by previous PR in the chain <sub>or this PR is not chained to another PR</sub>
- [ ] Added `base` label to the blocking PR <sub>or this PR is not chained to another PR</sub>
- [x] Added `chained` label to this PR <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [x] Documented upgrading of deployments in UPGRADING.rst <sub>or this PR does not require upgrading</sub>
- [x] Added `u` tag to commit title <sub>or this PR does not require upgrading</sub>
- [x] Added `upgrade` label to PR <sub>or this PR does not require upgrading</sub>

### Author (operator tasks)

- [x] Added checklist items for additional operator tasks <sub>or this PR does not require additional tasks</sub>

### Author (hotfixes)

- [x] Added `F` tag to main commit title <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [x] Reverted the temporary hotfixes for any connected issues <sub>or the `prod` branch has no temporary hotfixes for any connected issues</sub>

### Author (before every review)

- [x] Rebased PR branch on `develop`, squashed old fixups
- [x] Ran `make requirements_update` <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [x] Added `R` tag to commit title <sub>or this PR does not touch requirements*.txt</sub>
- [x] Added `reqs` label to PR <sub>or this PR does not touch requirements*.txt</sub>
- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>

### Peer reviewer (after requesting changes)

Uncheck the *Author (before every review)* checklists.

### Peer reviewer (after approval)

- [ ] PR is not a draft
- [ ] Ticket is in *Review requested* column
- [ ] Requested review from primary reviewer
- [ ] Assigned PR to primary reviewer

### Primary reviewer (after requesting changes)

Uncheck the *before every review* checklists. Update the `N reviews` label.

### Primary reviewer (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issues as `demo` or `no demo`
- [ ] Commented on connected issues about demo expectations <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] `N reviews` label is accurate
- [ ] Moved ticket to *Approved* column
- [ ] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear <sub>or all connected issues are labeled `no demo`</sub>
- [ ] PR has checklist items for upgrading instructions <sub>or PR is not labeled `upgrade`</sub>
- [ ] Squashed PR branch and rebased onto `develop`
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Pushed PR branch to GitLab `dev` and added `sandbox` label <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvilprod` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `hammerbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `hammerbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted unreferenced indices in `sandbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Deleted unreferenced indices in `anvilbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Deleted unreferenced indices in `hammerbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Started reindex in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Started reindex in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Started reindex in `hammerbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `hammerbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Title of merge commit starts with title from this PR
- [ ] Added PR reference to merge commit title
- [ ] Added commit title tags to merge commit title
- [ ] Moved connected issues to Merged column in ZenHub
- [ ] Pushed merge commit to GitHub

### Operator (chain shortening)

- [ ] Changed the target branch of the blocked PR to `develop` <sub>or this PR is not labeled `base`</sub>
- [ ] Removed the `chained` label from the blocked PR <sub>or this PR is not labeled `base`</sub>
- [ ] Removed the blocking relationship from the blocked PR <sub>or this PR is not labeled `base`</sub>
- [ ] Removed the `base` label from this PR <sub>or this PR is not labeled `base`</sub>

### Operator (after pushing the merge commit)

- [ ] Pushed merge commit to GitLab `dev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed merge commit to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed merge commit to GitLab `anvilprod` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes on GitLab `dev`<sup>1</sup>
- [ ] Reviewed build logs for anomalies on GitLab `dev`<sup>1</sup>
- [ ] Build passes on GitLab `anvildev`<sup>1</sup>
- [ ] Reviewed build logs for anomalies on GitLab `anvildev`<sup>1</sup>
- [ ] Build passes on GitLab `anvilprod`<sup>1</sup>
- [ ] Reviewed build logs for anomalies on GitLab `anvilprod`<sup>1</sup>
- [ ] Deleted PR branch from GitHub
- [ ] Deleted PR branch from GitLab `dev`
- [ ] Deleted PR branch from GitLab `anvildev`
- [ ] Deleted PR branch from GitLab `anvilprod`

<sup>1</sup> When pushing the merge commit is skipped due to the PR being
labelled `no sandbox`, the next build triggered by a PR whose merge commit *is*
pushed determines this checklist item.

### Operator (reindex)

- [ ] Deleted unreferenced indices in `dev` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Deleted unreferenced indices in `anvildev` <sub>or this PR does not remove catalogs o [...]

2023-10-14 04:54 UTC, nadove-ucsc commented
For WIP review, please look at the refactoring in the 1st commit. The intent is to facilitate the addition of scripted updates in the 2nd commit. I'd like feedback on the overall approach and the division of labor between the methods in the `Document` class.

2023-10-19 16:23 UTC, hannes-ucsc reviewed
Replacing the boolean combinations with an enum makes sense. The code touched by that refactoring is rather complex and prone to breaking. I think we should do the refactoring as a separate PR and test it with a reindex in `prod`, without any other changes that would require a reindex.

2023-10-19 16:23 UTC, hannes-ucsc commented on src/azul/indexer/document.py
> +                if bulk else
Probably easier to just `if …: result['_op_type'] = ` afterwards

2023-10-19 16:23 UTC, hannes-ucsc commented on src/azul/indexer/index_service.py
> +            assert op_type in OpType.__members__, op_type
Isn't there a non-dunder way to do this?

2023-10-19 16:23 UTC, hannes-ucsc commented on test/indexer/test_indexer.py
> +                                    fr'.*_aggregate/_create/{doc_id}.*')
This looks odd to me. `_doc` is what ES calls a `doctype`, the default one. They are deprecated, so maybe this is ok.

2024-01-22 17:28 UTC, dsotirho-ucsc requested changes
Nicely done. Just a couple minor cleanup suggestions.

2024-01-22 17:28 UTC, dsotirho-ucsc commented on src/azul/indexer/document.py
> +    update = auto()
`update` should get a description comment like the other OpTypes

2024-01-22 17:28 UTC, dsotirho-ucsc commented on src/azul/plugins/metadata/anvil/indexer/transform.py
>              files=self._entities(self._file, linked['file']),
```suggestion
            files=self._entities(self._file, files),
```

2024-01-22 22:15 UTC, dsotirho-ucsc approved these changes, later dismissed
Approved.

2024-01-22 23:54 UTC, dsotirho-ucsc commented
My force-push was to fix an accidental click of the `Update branch` button and remove the rebase commit added by GitHub.

2024-01-23 02:30 UTC, dsotirho-ucsc approved these changes, later dismissed
Approved.

2024-02-05 16:12 UTC, hannes-ucsc requested changes
Conflicts.

2024-02-07 17:36 UTC, hannes-ucsc requested changes
```diff
Subject: [PATCH] Add support for referencing images by digest
---
Index: src/azul/indexer/document.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/indexer/document.py b/src/azul/indexer/document.py
--- a/src/azul/indexer/document.py	(revision 91311a0e8c8f32c3db8ab29fd57138aae14e8173)
+++ b/src/azul/indexer/document.py	(date 1707327246928)
@@ -1103,8 +1103,8 @@
     delete = auto()
 
     #: Modify a document in the index via a scripted update or fail if it does
-    #: not exist.
-    update = auto()
+    #: not exist
+    scripted_update = auto()
 
 
 C = TypeVar('C', bound=DocumentCoordinates)
@@ -1311,7 +1311,8 @@
                 {}
                 if op_type is OpType.delete else
                 {
-                    '_source' if bulk else 'body': self._body(field_types[coordinates.entity.catalog])
+                    '_source' if bulk else 'body':
+                        self._body(field_types[coordinates.entity.catalog])
                 }
             ),
             '_id' if bulk else 'id': self.coordinates.document_id
@@ -1343,6 +1344,7 @@
         raise NotImplementedError
 
     def _body(self, field_types: FieldTypes) -> JSON:
+        # REVIEW: this should assert that optype is not update
         body = self.to_json()
         if self.needs_translation:
             body = self.translate_fields(doc=body,
@@ -1536,6 +1538,7 @@
         assert isinstance(self.coordinates, ReplicaCoordinates)
         assert self.coordinates.doc_type is DocumentType.replica
         assert self.entity.entity_type == 'replica', self.entity
+        # REVIEW: A comment should explain this
         self.hub_ids.sort()
 
     @classmethod
@@ -1570,6 +1573,8 @@
                     Collections.sort(ctx._source.hub_ids);
                 ''',
                     'params': {
+                        # REVIEW: Might be better to sort here but I'd still
+                        #         would like to know why sorting is necessary
                         'hub_ids': self.hub_ids
                     }
                 }
Index: src/azul/plugins/metadata/anvil/indexer/transform.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/plugins/metadata/anvil/indexer/transform.py b/src/azul/plugins/metadata/anvil/indexer/transform.py
--- a/src/azul/plugins/metadata/anvil/indexer/transform.py	(revision 91311a0e8c8f32c3db8ab29fd57138aae14e8173)
+++ b/src/azul/plugins/metadata/anvil/indexer/transform.py	(date 1707326964531)
@@ -488,7 +488,8 @@
             donors=self._entities(self._donor, self._entities_by_type['donor']),
             files=self._entities(self._file, files)
         )
-        return self._add_replica(contents, entity, [f.entity_id for f in files])
+        hub_ids = [f.entity_id for f in files]  # REVIEW: and elsewhere
+        return self._add_replica(contents, entity, hub_ids)
 
     @classmethod
     def field_types(cls) -> FieldTypes:
Index: src/azul/indexer/index_service.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/indexer/index_service.py b/src/azul/indexer/index_service.py
--- a/src/azul/indexer/index_service.py	(revision 91311a0e8c8f32c3db8ab29fd57138aae14e8173)
+++ b/src/azul/indexer/index_service.py	(date 1707326964540)
@@ -513,6 +513,11 @@
             retry_replicas = []
             for r in replicas:
                 if r.coordinates in writer.retries:
+                    # REVIEW: It feels like there is an assumption here about
+                    #         what the version type is. An assert could be added,
+                    #         but I think it would be better to rewrite the `if`
+                    #         to solely look at the version type first and then
+                    #         nest the `if` below
                     conflicts = writer.conflicts[r.coordinates]
                     if conflicts in (0, 1):
                         retry_replicas.append(r)
@@ -914,6 +919,9 @@
             log.debug('Successfully wrote %s with %i contribution(s).',
                       coordinates, doc.num_contributions)
         elif isinstance(doc, Replica) and doc.version_type is VersionType.none:
+            # REVIEW: Before this change, there would always be a log message.
+            # Now, there is a condition in which nothing is logged. If that is
+            # intentional, we should make that more clear (comments, asserts, …)
             log.debug('Successfully updated %s.', coordinates)
         else:
             log.debug('Successfully wrote %s.', coordinates)
```

2024-02-08 03:24 UTC, nadove-ucsc commented
> \+    scripted_update = auto()

This will break because [the member name determines which method to call on the ES client](https://github.com/DataBiosphere/azul/blob/5f7406dd84eb9602e48dfc9f5aed72a1d200f1fe/src/azul/indexer/index_service.py#L856)

> \+            # REVIEW: Before this change, there would always be a log message.
\+            # Now, there is a condition in which nothing is logged. If that is
\+            # intentional, we should make that more clear (comments, asserts, …)

I don't believe that this is the case. What condition do you think will result in nothing being logged?

> \+                        # REVIEW: Might be better to sort here but I'd still
\+                        #         would like to know why sorting is necessary

I can remove all references to sorting from the indexer code at the low cost of adding some sorting to the unit tests. I don't entirely remember why I chose to sort them, but at minimum it would help with manually inspecting/debugging the index contents. I guess I just figured it was better for the contents to be deterministic than nondeterministic, as future-proofing against unforeseen complications.

2024-02-08 09:03 UTC, nadove-ucsc commented
> \+                        # REVIEW: Might be better to sort here but I'd still
\+                        #         would like to know why sorting is necessary

If hub ID's are only sorted during updates, then they will be unsorted when a replica is first written to the index and remain so until if/when a scripted update occurs. This breaks the unit tests.

2024-02-11 02:25 UTC, hannes-ucsc commented
> > +    scripted_update = auto()
> 
> This will break because [the member name determines which method to call on the ES client](https://github.com/DataBiosphere/azul/blob/5f7406dd84eb9602e48dfc9f5aed72a1d200f1fe/src/azul/indexer/index_service.py#L856)
> 

Makes sense. OK to leave it as is.

> > +            # REVIEW: Before this change, there would always be a log message.
> > +            # Now, there is a condition in which nothing is logged. If that is
> > +            # intentional, we should make that more clear (comments, asserts, …)
> 
> I don't believe that this is the case. What condition do you think will result in nothing being logged?

None. I was mistaken.

2024-02-11 02:38 UTC, hannes-ucsc requested changes

2024-02-11 02:38 UTC, hannes-ucsc commented on src/azul/indexer/document.py
> +        self.hub_ids.sort()
Since `hub_ids` isn't immutable, please sort as late as possible, just before writing.

2024-02-11 02:38 UTC, hannes-ucsc commented on test/indexer/test_indexer.py
> +                                # Indexing the same contribution twice does not
Please request PL slot to discuss this.

2024-02-11 02:38 UTC, hannes-ucsc commented on src/azul/plugins/metadata/hca/indexer/transform.py
> +        return self._add_replica(contents, self._singleton_entity(), list(map(str, visitor.files)))
L 

Please extract variable as requested in previous review, for all calls to _add_replica

2024-02-13 22:57 UTC, nadove-ucsc commented on test/indexer/test_indexer.py
> +                                # Indexing the same contribution twice does not
Feedback assimilated at PL.

2024-02-14 18:35 UTC, hannes-ucsc requested changes

2024-02-14 18:35 UTC, hannes-ucsc commented on src/azul/indexer/document.py
> +                        'hub_ids': sorted(self.hub_ids)
Why do you sort here? I don't think `params` manifests anywhere in test code or cans.

2024-02-14 18:35 UTC, hannes-ucsc commented on src/azul/indexer/document.py
> +                    hub_ids=sorted(self.hub_ids))
A comment should explain why, just like in the previous version.

2024-02-14 18:35 UTC, hannes-ucsc commented on src/azul/indexer/document.py
> +                    ctx._source.hub_ids.addAll(params.hub_ids);
```suggestion
                    Stream stream = Stream.concat(ctx._source.hub_ids.stream(), params.hub_ids.stream());
                    ctx._source.hub_ids = stream.sorted().distinct().collect(Collectors.toList());
```

https://stackoverflow.com/questions/43806467/java-streams-how-to-do-an-efficient-distinct-and-sort

2024-02-14 18:35 UTC, hannes-ucsc commented on test/indexer/test_indexer.py
> +            ('New replica', ['1'], ['1']),
Should also test duplicate hub ids in new replicas.

2024-02-14 18:35 UTC, hannes-ucsc commented on test/indexer/test_indexer.py
> +            ('Additional hub IDs', ['1', '2', '3'], ['1', '2', '3']),
Reverse the order of the hub_ids to make this stronger.

2024-02-16 06:27 UTC, hannes-ucsc approved these changes

2024-02-21 00:21 UTC, merged