Fix: Lambda azul-service-anvilprod-servicecachehealth failed due to a timeout (partial #5467)
DataBiosphere/azul pull request #5564
Opened 2023-09-22 18:07 UTC by achave11-ucsc

Connected issues: #5467 

## Checklist

### Author

- [x] PR is a draft
- [x] Target branch is `develop`
- [x] Name of PR branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [x] PR title references all connected issues
- [x] PR title matches<sup>1</sup> that of a connected issue <sub>or comment in PR explains why they're different</sub>
- [x] For each connected issue, there is at least one commit whose title references that issue
- [x] PR is connected to all connected issues via ZenHub
- [x] PR description links to connected issues
- [x] Added `partial` label to PR <sub>or this PR completely resolves all connected issues</sub>

<sup>1</sup> when the issue title describes a problem, the corresponding PR
title is `Fix: ` followed by the issue title

### Author (reindex, API changes)

- [ ] Added `r` tag to commit title <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label to PR <sub>or this PR does not require reindexing</sub>
- [ ] PR and connected issue are labeled `API` <sub>or this PR does not modify a REST API</sub>
- [ ] Added `a` (`A`) tag to commit title for backwards (in)compatible changes <sub>or this PR does not modify a REST API</sub>
- [ ] Updated REST API version number in `app.py` <sub>or this PR does not modify a REST API</sub>

### Author (chains)

- [ ] This PR is blocked by previous PR in the chain <sub>or this PR is not chained to another PR</sub>
- [ ] Added `base` label to the blocking PR <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chained` label to this PR <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [ ] Documented upgrading of deployments in UPGRADING.rst <sub>or this PR does not require upgrading</sub>
- [ ] Added `u` tag to commit title <sub>or this PR does not require upgrading</sub>
- [ ] Added `upgrade` label to PR <sub>or this PR does not require upgrading</sub>

### Author (operator tasks)

- [ ] Added checklist items for additional operator tasks <sub>or this PR does not require additional tasks</sub>

### Author (hotfixes)

- [ ] Added `F` tag to main commit title <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [ ] Reverted the temporary hotfixes for any connected issues <sub>or the `prod` branch has no temporary hotfixes for any connected issues</sub>

### Author (before every review)

- [ ] Rebased PR branch on `develop`, squashed old fixups
- [ ] Ran `make requirements_update` <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [ ] Added `R` tag to commit title <sub>or this PR does not touch requirements*.txt</sub>
- [ ] Added `reqs` label to PR <sub>or this PR does not touch requirements*.txt</sub>
- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>

### Peer reviewer (after requesting changes)

Uncheck the *Author (before every review)* checklists.

### Peer reviewer (after approval)

- [ ] PR is not a draft
- [ ] Ticket is in *Review requested* column
- [ ] Requested review from primary reviewer
- [ ] Assigned PR to primary reviewer

### Primary reviewer (after requesting changes)

Uncheck the *before every review* checklists. Update the `N reviews` label.

### Primary reviewer (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issues as `demo` or `no demo`
- [ ] Commented on connected issues about demo expectations <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] `N reviews` label is accurate
- [ ] Moved ticket to *Approved* column
- [ ] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear <sub>or all connected issues are labeled `no demo`</sub>
- [ ] PR has checklist items for upgrading instructions <sub>or PR is not labeled `upgrade`</sub>
- [ ] Squashed PR branch and rebased onto `develop`
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Pushed PR branch to GitLab `dev` and added `sandbox` label <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvilprod` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `hammerbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `hammerbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted unreferenced indices in `sandbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Deleted unreferenced indices in `anvilbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Deleted unreferenced indices in `hammerbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Started reindex in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Started reindex in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Started reindex in `hammerbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `hammerbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Title of merge commit starts with title from this PR
- [ ] Added PR reference to merge commit title
- [ ] Added commit title tags to merge commit title
- [ ] Moved connected issues to Merged column in ZenHub
- [ ] Pushed merge commit to GitHub

### Operator (chain shortening)

- [ ] Changed the target branch of the blocked PR to `develop` <sub>or this PR is not labeled `base`</sub>
- [ ] Removed the `chained` label from the blocked PR <sub>or this PR is not labeled `base`</sub>
- [ ] Removed the blocking relationship from the blocked PR <sub>or this PR is not labeled `base`</sub>
- [ ] Removed the `base` label from this PR <sub>or this PR is not labeled `base`</sub>

### Operator (after pushing the merge commit)

- [ ] Pushed merge commit to GitLab `dev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed merge commit to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed merge commit to GitLab `anvilprod` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes on GitLab `dev`<sup>1</sup>
- [ ] Reviewed build logs for anomalies on GitLab `dev`<sup>1</sup>
- [ ] Build passes on GitLab `anvildev`<sup>1</sup>
- [ ] Reviewed build logs for anomalies on GitLab `anvildev`<sup>1</sup>
- [ ] Build passes on GitLab `anvilprod`<sup>1</sup>
- [ ] Reviewed build logs for anomalies on GitLab `anvilprod`<sup>1</sup>
- [ ] Deleted PR branch from GitHub
- [ ] Deleted PR branch from GitLab `dev`
- [ ] Deleted PR branch from GitLab `anvildev`
- [ ] Deleted PR branch from GitLab `anvilprod`

<sup>1</sup> When pushing the merge commit is skipped due to the PR being
labelled `no sandbox`, the next build triggered by a PR whose merge commit *is*
pushed determines this checklist item.

### Operator (reindex)

- [ ] Deleted unreferenced indices in `dev` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Deleted unreferenced indices in `anvildev` <sub>or this PR does not remove catalogs  [...]

2023-09-22 18:08 UTC, achave11-ucsc commented on src/azul/health.py
> +        endpoint = random.choice([
WIP: Q1

2023-09-22 18:08 UTC, achave11-ucsc commented on src/azul/health.py
> +        log.info('%s %s [request: %.3fs]',
WIP: Q2

2023-09-22 19:13 UTC, achave11-ucsc commented on src/azul/health.py
> +        log.info('Requesting %r', endpoint)
Replicate format from Terra requests.

2023-09-29 18:26 UTC, achave11-ucsc commented on src/azul/health.py
> +        log.debug('_request(HEAD, %s)', endpoint)
```python
log.debug('_request(HEAD, %s) …', endpoint)

```

2023-10-03 15:31 UTC, dsotirho-ucsc requested changes

2023-10-03 15:31 UTC, dsotirho-ucsc commented on src/azul/health.py
> +        # Select any single entity index endpoint from the ones available
This comment should tell the reader _why_ one endpoint is being randomly selected.

2023-10-03 15:31 UTC, dsotirho-ucsc commented on src/azul/health.py
> +        random.seed(a=1695859751)
```suggestion
```

I'm guessing this was put in to temporarily turn off the randomness while this was being developed?

2023-10-03 15:31 UTC, dsotirho-ucsc commented on src/azul/health.py
> +                  time.time() - start, response.status_code)
```suggestion
        log.debug('_request(…) -> %.3fs %r',
                  time.time() - start, response.status_code)
```
If this log format was discussed or requested then it's ok, however personally something more readable would be my preference, e.g.

DEBUG: Requesting https://www.example.com/index/files 
DEBUG: Received a 200 response in 0.405 seconds

2023-10-03 15:31 UTC, dsotirho-ucsc commented on test/service/test_health_check.py
> +        self.assertEqual(self._expected_health(endpoint_states), actual_health)
How about renaming this method from `test_all_api_endpoints_down` to `test_api_endpoints_down` since it is getting the status of one random endpoint at a time.

2023-10-03 16:27 UTC, hannes-ucsc commented on test/service/test_health_check.py
> +        self.assertEqual(self._expected_health(endpoint_states), actual_health)
Minimize the renames for now, please.

2023-10-03 16:32 UTC, hannes-ucsc commented on src/azul/health.py
> +        # Select any single entity index endpoint from the ones available
Comment is fine. It is obvious why a health check only tests a subset of available functionality (performance). It is also obvious why a random choice is used (increase coverage).

2023-10-03 16:34 UTC, hannes-ucsc commented on src/azul/health.py
> +        endpoint = random.choice([
Pick a random entity type first, then derive the endpoint URL.

2023-10-03 17:55 UTC, achave11-ucsc commented on src/azul/health.py
> +                  time.time() - start, response.status_code)
Yeah, this is more or less how we log a requests' execution time. Checkout [src/azul/terra.py#L368](https://github.com/DataBiosphere/azul/blob/042165077853fe341cd0d4e96677ad9140bd4170/src/azul/terra.py#L343-#L368).

2023-10-04 04:34 UTC, dsotirho-ucsc approved these changes, later dismissed
Approved.

2023-10-06 00:27 UTC, hannes-ucsc requested changes

2023-10-06 00:27 UTC, hannes-ucsc commented on test/service/test_health_check.py
> +            e: u for e, u in endpoint_states.items() if e in actual_health['api_endpoints']['error']
L

2023-10-06 00:27 UTC, hannes-ucsc commented on test/service/test_health_check.py
> +        self.assertEqual(self._expected_health(endpoint_states), actual_health)
This is convoluted. You're deriving the expectation from the actual outcome, which is a smell. You've simplified the response, so the expectation should be simpler, too. It seems like the only variability is in the URL in the `error` property of the response. I see two ways to deal with that: fingerprinting or a pattern match.

2023-10-06 00:34 UTC, hannes-ucsc requested changes
Forgot to add my changes to the code under test:

```diff
Index: src/azul/health.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/health.py b/src/azul/health.py
--- a/src/azul/health.py	(revision a1449855dde565e8e68a4bf096df49db01e41073)
+++ b/src/azul/health.py	(date 1696552352692)
@@ -236,24 +236,14 @@
             ))
         }
 
-    @cached_property
-    def entity_types(self):
-        return self.controller.metadata_plugin(self.catalog).exposed_indices.keys()
-
-    @health_property
-    def api_endpoints(self):
-        """
-        Indicates whether important service API endpoints are operational.
-        """
-        # Select any single entity index from the ones available
-        entity_type = random.choice([*self.entity_types])
-        endpoint = furl(path=('index', entity_type), args={'size': '1'})
-        endpoint = str(config.service_endpoint.join(endpoint))
-        log.debug('_request(HEAD, %s) …', endpoint)
+    def _api_endpoint(self, entity_type: str) -> tuple[str, JSON]:
+        relative_url = furl(path=('index', entity_type), args={'size': '1'})
+        url = str(config.service_endpoint.join(relative_url))
+        log.info('Making HEAD request to %s', url)
         start = time.time()
-        response = requests.head(endpoint)
-        log.debug('_request(…) -> %.3fs %r',
-                  time.time() - start, response.status_code)
+        response = requests.head(url)
+        log.info('Got %s response after %.3fs from HEAD request to %s',
+                 response.status_code, time.time() - start, url)
         try:
             response.raise_for_status()
         except requests.exceptions.HTTPError as e:
@@ -261,6 +251,18 @@
         else:
             return {'up': True}
 
+    @cached_property
+    def entity_types(self):
+        return self.controller.metadata_plugin(self.catalog).exposed_indices.keys()
+
+    @health_property
+    def api_endpoints(self):
+        """
+        Indicates whether important service API endpoints are operational.
+        """
+        entity_type = random.choice(list(self.entity_types))
+        return self._api_endpoint(entity_type)
+
     @health_property
     def elasticsearch(self):
         """
```

2023-10-06 22:48 UTC, achave11-ucsc commented
The suggested patch (https://github.com/DataBiosphere/azul/pull/5564#pullrequestreview-1660955732) did not require additional test modifications, so it retained authorship as part of a split commit.

2023-10-07 05:43 UTC, hannes-ucsc requested changes
Let's try a different approach. Let's patch the random generator used by the app during the test so that its seed is pinned. Note that you may need to have a dedicated generator for the health code, instead of using the global, default generator. That way the patch would only affect the health code. Once you pin the seed during the test, you can know which endpoint will be picked and what the response is going to be.

2023-10-07 05:43 UTC, hannes-ucsc commented on src/azul/health.py
> +    def _api_endpoint(self, entity_type: str) -> tuple[str, JSON]:
Return type hint is wrong.

2023-10-07 05:43 UTC, hannes-ucsc commented on test/health_check_test_case.py
> +                    "Service Unavailable for url: ")
`)` in the wrong place

2023-10-07 05:43 UTC, hannes-ucsc commented on test/health_check_test_case.py
> +                'up': False,
I can change this to `True` and the tests still pass.

2023-10-25 05:32 UTC, hannes-ucsc requested changes
I added a few commits that I would like to retain as mine, and another one that I would like to be squashed into on of yours.

2023-10-25 05:33 UTC, hannes-ucsc reviewed
Oh, and not "partial" anymore in commit titles.

2023-10-26 00:17 UTC, hannes-ucsc approved these changes

2023-10-26 17:39 UTC, merged