Fix: Index anvil3 in anvilprod (#5616)
DataBiosphere/azul pull request #5664
Opened 2023-10-30 21:53 UTC by dsotirho-ucsc

Connected issues: #5616

## Checklist

### Author

- [x] PR is a draft
- [x] Target branch is `develop`
- [x] Name of PR branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [x] PR title references all connected issues
- [x] PR title matches<sup>1</sup> that of a connected issue <sub>or comment in PR explains why they're different</sub>
- [x] For each connected issue, there is at least one commit whose title references that issue
- [x] PR is connected to all connected issues via ZenHub
- [x] PR description links to connected issues
- [x] Added `p` tag to titles of partial commits
- [x] Added `partial` label to PR <sub>or this PR completely resolves all connected issues</sub>
- [x] All connected issues are resolved partially <sub>or this PR does not have the `partial` label</sub>

<sup>1</sup> when the issue title describes a problem, the corresponding PR
title is `Fix: ` followed by the issue title

### Author (reindex, API changes)

- [x] Added `r` tag to commit title <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label to PR <sub>or this PR does not require reindexing</sub>
    - no reindex necessary, snapshot to be removed with `reindex.py --deindex`
- [x] PR and connected issue are labeled `API` <sub>or this PR does not modify a REST API</sub>
- [x] Added `a` (`A`) tag to commit title for backwards (in)compatible changes <sub>or this PR does not modify a REST API</sub>
- [x] Updated REST API version number in `app.py` <sub>or this PR does not modify a REST API</sub>

### Author (chains)

- [x] This PR is blocked by previous PR in the chain <sub>or this PR is not chained to another PR</sub>
- [x] Added `base` label to the blocking PR <sub>or this PR is not chained to another PR</sub>
- [x] Added `chained` label to this PR <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [x] Documented upgrading of deployments in UPGRADING.rst <sub>or this PR does not require upgrading</sub>
- [x] Added `u` tag to commit title <sub>or this PR does not require upgrading</sub>
- [x] Added `upgrade` label to PR <sub>or this PR does not require upgrading</sub>

### Author (operator tasks)

- [x] Added checklist items for additional operator tasks <sub>or this PR does not require additional tasks</sub>

### Author (hotfixes)

- [x] Added `F` tag to main commit title <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [x] Reverted the temporary hotfixes for any connected issues <sub>or the `prod` branch has no temporary hotfixes for any connected issues</sub>

### Author (before every review)

- [x] Rebased PR branch on `develop`, squashed old fixups
- [x] Ran `make requirements_update` <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [x] Added `R` tag to commit title <sub>or this PR does not touch requirements*.txt</sub>
- [x] Added `reqs` label to PR <sub>or this PR does not touch requirements*.txt</sub>
- [x] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>

### Peer reviewer (after requesting changes)

Uncheck the *Author (before every review)* checklists.

### Peer reviewer (after approval)

- [ ] PR is not a draft
- [ ] Ticket is in *Review requested* column
- [ ] Requested review from primary reviewer
- [ ] Assigned PR to primary reviewer

### Primary reviewer (after requesting changes)

Uncheck the *before every review* checklists. Update the `N reviews` label.

### Primary reviewer (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issues as `demo` or `no demo`
- [ ] Commented on connected issues about demo expectations <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] `N reviews` label is accurate
- [ ] Moved ticket to *Approved* column
- [ ] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear <sub>or all connected issues are labeled `no demo`</sub>
- [ ] PR has checklist items for upgrading instructions <sub>or PR is not labeled `upgrade`</sub>
- [ ] Squashed PR branch and rebased onto `develop`
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Pushed PR branch to GitLab `dev` and added `sandbox` label <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvilprod` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `hammerbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `hammerbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted unreferenced indices in `sandbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Deleted unreferenced indices in `anvilbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Deleted unreferenced indices in `hammerbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Started reindex in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Started reindex in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Started reindex in `hammerbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `hammerbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Title of merge commit starts with title from this PR
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title <sub>but only include `p` if the PR is labeled `partial`</sub>
- [ ] Moved connected issues to Merged column in ZenHub
- [ ] Pushed merge commit to GitHub

### Operator (chain shortening)

- [ ] Changed the target branch of the blocked PR to `develop` <sub>or this PR is not labeled `base`</sub>
- [ ] Removed the `chained` label from the blocked PR <sub>or this PR is not labeled `base`</sub>
- [ ] Removed the blocking relationship from the blocked PR <sub>or this PR is not labeled `base`</sub>
- [ ] Removed the `base` label from this PR <sub>or this PR is not labeled `base`</sub>

### Operator (after pushing the merge commit)

- [ ] Pushed merge commit to GitLab `dev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed merge commit to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed merge commit to GitLab `anvilprod` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes on GitLab `dev`<sup>1</sup>
- [ ] Reviewed build logs for anomalies on GitLab `dev`<sup>1</sup>
- [ ] Build passes on GitLab `anvildev`<sup>1</sup>
- [ ] Reviewed build logs for anomalies on GitLab `anvildev`<sup>1</sup>
- [ ] Build passes on GitLab `anvilprod`<sup>1</sup>
- [ ] Reviewed build logs for anomalies on GitLab `anvilprod`<sup>1</sup>
- [ ] Deleted PR branch from GitHub
- [ ] Deleted PR branch from GitLab `dev`
- [ ] Deleted PR branch from GitLab `anvildev`
- [ ] Deleted PR branch from GitLab `anvilprod`

<sup>1</sup> When pushing the merge commit is skipped due to the PR being
labelled `no sandbox`, the next build triggered by a PR whose merge [...]

2023-10-30 22:10 UTC, dsotirho-ucsc commented
> Ran the following with `anvilprod` selected to deindex the snapshot from anvil3:

```
(.venv) daniel@Crispin ~/repo/azul3 $ _select
lrwxr-xr-x  1 daniel  staff  9 Oct 30 15:08 .active -> anvilprod
(.venv) daniel@Crispin ~/repo/azul3 $
(.venv) daniel@Crispin ~/repo/azul3 $ python scripts/reindex.py --catalogs anvil3 --deindex --sources tdr:datarepo-828e5175:snapshot/ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242:/2
2023-10-30 15:08:42,743   DEBUG MainThread __main__: Source glob 'tdr:datarepo-828e5175:snapshot/ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242:/2' matched sources ['tdr:datarepo-828e5175:snapshot/ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242:/2'] in catalog 'anvil3'
2023-10-30 15:08:42,744   DEBUG MainThread azul.terra: _request('GET', https://data.terra.bio/api/repository/v1/snapshots?filter=ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242&limit=2, headers=None, timeout=20.0, body=None)
2023-10-30 15:08:42,755    INFO MainThread botocore.credentials: Found credentials in environment variables.
2023-10-30 15:08:44,319   DEBUG MainThread azul.terra: _request(…) -> 1.575s 200 b'{"total":1354,"filteredTotal":1,"items":[{"id":"f918ddde-889c-49a3-8881-e7bbdebd0e56","name":"ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242","description":"Full view snapshot of ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024","createdDa...'
2023-10-30 15:08:44,320   DEBUG MainThread azul.terra: _request('GET', https://data.terra.bio/api/repository/v1/snapshots/f918ddde-889c-49a3-8881-e7bbdebd0e56, headers=None, timeout=20.0, body=None)
2023-10-30 15:08:46,642   DEBUG MainThread azul.terra: _request(…) -> 2.321s 200 b'{"id":"f918ddde-889c-49a3-8881-e7bbdebd0e56","name":"ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242","description":"Full view snapshot of ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024","createdDate":"2023-10-10T12:42:57.728118Z","consen...'
2023-10-30 15:08:47,201   DEBUG MainThread azul.es: Creating ES client [vpc-azul-index-anvilprod-ggipah4skn2ftt47u4xgvydzqm.us-east-1.es.amazonaws.com:443]
2023-10-30 15:08:47,243    INFO MainThread botocore.credentials: Found credentials in environment variables.
2023-10-30 15:08:47,243    INFO MainThread azul.azulclient: Deindexing sources {'tdr:datarepo-828e5175:snapshot/ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242:/2'} from catalog 'anvil3'
2023-10-30 15:08:47,244   DEBUG MainThread azul.azulclient: Using query: {'query': {'bool': {'should': [{'terms': {'sources.id.keyword': ['f918ddde-889c-49a3-8881-e7bbdebd0e56']}}, {'terms': {'source.id.keyword': ['f918ddde-889c-49a3-8881-e7bbdebd0e56']}}]}}}
2023-10-30 15:08:47,244    INFO MainThread elasticsearch: Making POST request to https://vpc-azul-index-anvilprod-ggipah4skn2ftt47u4xgvydzqm.us-east-1.es.amazonaws.com:443/azul_v2_anvilprod_anvil3_activities,azul_v2_anvilprod_anvil3_activities_aggregate,azul_v2_anvilprod_anvil3_biosamples,azul_v2_anvilprod_anvil3_biosamples_aggregate,azul_v2_anvilprod_anvil3_datasets,azul_v2_anvilprod_anvil3_datasets_aggregate,azul_v2_anvilprod_anvil3_donors,azul_v2_anvilprod_anvil3_donors_aggregate,azul_v2_anvilprod_anvil3_files,azul_v2_anvilprod_anvil3_files_aggregate/_delete_by_query?slices=auto
2023-10-30 15:08:47,244    INFO MainThread elasticsearch: … with request body b'{"query":{"bool":{"should":[{"terms":{"sources.id.keyword":["f918ddde-889c-49a3-8881-e7bbdebd0e56"]}},{"terms":{"source.id.ke...'
2023-10-30 15:08:50,314    INFO MainThread elasticsearch: Got 200 response after 3.070s from POST to https://vpc-azul-index-anvilprod-ggipah4skn2ftt47u4xgvydzqm.us-east-1.es.amazonaws.com:443/azul_v2_anvilprod_anvil3_activities,azul_v2_anvilprod_anvil3_activities_aggregate,azul_v2_anvilprod_anvil3_biosamples,azul_v2_anvilprod_anvil3_biosamples_aggregate,azul_v2_anvilprod_anvil3_datasets,azul_v2_anvilprod_anvil3_datasets_aggregate,azul_v2_anvilprod_anvil3_donors,azul_v2_anvilprod_anvil3_donors_aggregate,azul_v2_anvilprod_anvil3_files,azul_v2_anvilprod_anvil3_files_aggregate/_delete_by_query?slices=auto
2023-10-30 15:08:50,314    INFO MainThread elasticsearch: … with response body '{"took":2625,"timed_out":false,"total":19501,"deleted":19501,"batches":20,"version_conflicts":0,"noops":0,"retries":{"bulk":0,"…'
(.venv) daniel@Crispin ~/repo/azul3 $
(.venv) daniel@Crispin ~/repo/azul3 $
(.venv) daniel@Crispin ~/repo/azul3 $ python scripts/reindex.py --catalogs anvil3 --deindex --sources tdr:datarepo-828e5175:snapshot/ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242:/2
2023-10-30 15:09:44,191   DEBUG MainThread __main__: Source glob 'tdr:datarepo-828e5175:snapshot/ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242:/2' matched sources ['tdr:datarepo-828e5175:snapshot/ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242:/2'] in catalog 'anvil3'
2023-10-30 15:09:44,191   DEBUG MainThread azul.terra: _request('GET', https://data.terra.bio/api/repository/v1/snapshots?filter=ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242&limit=2, headers=None, timeout=20.0, body=None)
2023-10-30 15:09:44,202    INFO MainThread botocore.credentials: Found credentials in environment variables.
2023-10-30 15:09:45,567   DEBUG MainThread azul.terra: _request(…) -> 1.376s 200 b'{"total":1354,"filteredTotal":1,"items":[{"id":"f918ddde-889c-49a3-8881-e7bbdebd0e56","name":"ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242","description":"Full view snapshot of ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024","createdDa...'
2023-10-30 15:09:45,568   DEBUG MainThread azul.terra: _request('GET', https://data.terra.bio/api/repository/v1/snapshots/f918ddde-889c-49a3-8881-e7bbdebd0e56, headers=None, timeout=20.0, body=None)
2023-10-30 15:09:47,873   DEBUG MainThread azul.terra: _request(…) -> 2.305s 200 b'{"id":"f918ddde-889c-49a3-8881-e7bbdebd0e56","name":"ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242","description":"Full view snapshot of ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024","createdDate":"2023-10-10T12:42:57.728118Z","consen...'
2023-10-30 15:09:48,331   DEBUG MainThread azul.es: Creating ES client [vpc-azul-index-anvilprod-ggipah4skn2ftt47u4xgvydzqm.us-east-1.es.amazonaws.com:443]
2023-10-30 15:09:48,372    INFO MainThread botocore.credentials: Found credentials in environment variables.
2023-10-30 15:09:48,372    INFO MainThread azul.azulclient: Deindexing sources {'tdr:datarepo-828e5175:snapshot/ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242:/2'} from catalog 'anvil3'
2023-10-30 15:09:48,373   DEBUG MainThread azul.azulclient: Using query: {'query': {'bool': {'should': [{'terms': {'sources.id.keyword': ['f918ddde-889c-49a3-8881-e7bbdebd0e56']}}, {'terms': {'source.id.keyword': ['f918ddde-889c-49a3-8881-e7bbdebd0e56']}}]}}}
2023-10-30 15:09:48,373    INFO MainThread elasticsearch: Making POST request to https://vpc-azul-index-anvilprod-ggipah4skn2ftt47u4xgvydzqm.us-east-1.es.amazonaws.com:443/azul_v2_anvilprod_anvil3_activities,azul_v2_anvilprod_anvil3_activities_aggregate,azul_v2_anvilprod_anvil3_biosamples,azul_v2_anvilprod_anvil3_biosamples_aggregate,azul_v2_anvilprod_anvil3_datasets,azul_v2_anvilprod_anvil3_datasets_aggregate,azul_v2_anvilprod_anvil3_donors,azul_v2_anvilprod_anvil3_donors_aggregate,azul_v2_anvilprod_anvil3_files,azul_v2_anvilprod_anvil3_files_aggregate/_delete_by_query?slices=auto
2023-10-30 15:09:48,373    INFO MainThread elasticsearch: … with request body b'{"query":{"bool":{"should":[{"terms":{"sources.id.keyword":["f918ddde-889c-49a3-8881-e7bbdebd0e56"]}},{"terms":{"source.id.ke...'
2023-10-30 15:09:48,799    INFO MainThread elasticsearch: Got 200 response after 0.426s from POST to https://vpc-azul-index-anvilprod-ggipah4skn2ftt47u4xgvydzqm.us-east-1.es.amazonaws.com:443/azul_v2_anvilprod_anvil3_activities,azul_v2_anvilprod_anvil3_activities_aggregate,azul_v2_anvilprod_anvil3_biosamples,azul_v2_anvilprod_anvil3_biosamples_ [...]

2023-10-30 22:44 UTC, dsotirho-ucsc commented
Contacted Nathan about the snasphot
https://ucsc-gi.slack.com/archives/C03TPJS54DC/p1698705739796969?thread_ts=1697034911.133969&cid=C03TPJS54DC

2023-10-31 16:50 UTC, achave11-ucsc requested changes
Changes look good.

In your transcript, https://github.com/DataBiosphere/azul/pull/5664#issuecomment-1786124870, it looks like you only delete the project from the `anvil3` catalog, twice. This needs to happen for the `anvil3-it` catalog in the `anvilprod` deployment, as well as in both catalogs (`anvil3`, and `anvil3-it`) for the `hammerbox` deployment.

2023-10-31 17:09 UTC, dsotirho-ucsc commented
anvilprod anvil3-it

```
(.venv) daniel@Crispin ~/repo/azul3 $ python scripts/reindex.py --catalogs anvil3-it --deindex --sources tdr:datarepo-828e5175:snapshot/ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242:/2
2023-10-31 09:06:40,658   DEBUG MainThread __main__: Source glob 'tdr:datarepo-828e5175:snapshot/ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242:/2' matched sources ['tdr:datarepo-828e5175:snapshot/ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242:/2'] in catalog 'anvil3-it'
2023-10-31 09:06:40,659   DEBUG MainThread azul.terra: _request('GET', https://data.terra.bio/api/repository/v1/snapshots?filter=ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242&limit=2, headers=None, timeout=20.0, body=None)
2023-10-31 09:06:40,670    INFO MainThread botocore.credentials: Found credentials in environment variables.
2023-10-31 09:06:41,932   DEBUG MainThread azul.terra: _request(…) -> 1.273s 200 b'{"total":1354,"filteredTotal":1,"items":[{"id":"f918ddde-889c-49a3-8881-e7bbdebd0e56","name":"ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242","description":"Full view snapshot of ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024","createdDa...'
2023-10-31 09:06:41,933   DEBUG MainThread azul.terra: _request('GET', https://data.terra.bio/api/repository/v1/snapshots/f918ddde-889c-49a3-8881-e7bbdebd0e56, headers=None, timeout=20.0, body=None)
2023-10-31 09:06:44,861   DEBUG MainThread azul.terra: _request(…) -> 2.929s 200 b'{"id":"f918ddde-889c-49a3-8881-e7bbdebd0e56","name":"ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242","description":"Full view snapshot of ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024","createdDate":"2023-10-10T12:42:57.728118Z","consen...'
2023-10-31 09:06:45,333   DEBUG MainThread azul.es: Creating ES client [vpc-azul-index-anvilprod-ggipah4skn2ftt47u4xgvydzqm.us-east-1.es.amazonaws.com:443]
2023-10-31 09:06:45,353    INFO MainThread botocore.credentials: Found credentials in environment variables.
2023-10-31 09:06:45,354    INFO MainThread azul.azulclient: Deindexing sources {'tdr:datarepo-828e5175:snapshot/ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242:/2'} from catalog 'anvil3-it'
2023-10-31 09:06:45,354   DEBUG MainThread azul.azulclient: Using query: {'query': {'bool': {'should': [{'terms': {'sources.id.keyword': ['f918ddde-889c-49a3-8881-e7bbdebd0e56']}}, {'terms': {'source.id.keyword': ['f918ddde-889c-49a3-8881-e7bbdebd0e56']}}]}}}
2023-10-31 09:06:45,354    INFO MainThread elasticsearch: Making POST request to https://vpc-azul-index-anvilprod-ggipah4skn2ftt47u4xgvydzqm.us-east-1.es.amazonaws.com:443/azul_v2_anvilprod_anvil3-it_activities,azul_v2_anvilprod_anvil3-it_activities_aggregate,azul_v2_anvilprod_anvil3-it_biosamples,azul_v2_anvilprod_anvil3-it_biosamples_aggregate,azul_v2_anvilprod_anvil3-it_datasets,azul_v2_anvilprod_anvil3-it_datasets_aggregate,azul_v2_anvilprod_anvil3-it_donors,azul_v2_anvilprod_anvil3-it_donors_aggregate,azul_v2_anvilprod_anvil3-it_files,azul_v2_anvilprod_anvil3-it_files_aggregate/_delete_by_query?slices=auto
2023-10-31 09:06:45,354    INFO MainThread elasticsearch: … with request body b'{"query":{"bool":{"should":[{"terms":{"sources.id.keyword":["f918ddde-889c-49a3-8881-e7bbdebd0e56"]}},{"terms":{"source.id.ke...'
2023-10-31 09:06:45,731    INFO MainThread elasticsearch: Got 200 response after 0.377s from POST to https://vpc-azul-index-anvilprod-ggipah4skn2ftt47u4xgvydzqm.us-east-1.es.amazonaws.com:443/azul_v2_anvilprod_anvil3-it_activities,azul_v2_anvilprod_anvil3-it_activities_aggregate,azul_v2_anvilprod_anvil3-it_biosamples,azul_v2_anvilprod_anvil3-it_biosamples_aggregate,azul_v2_anvilprod_anvil3-it_datasets,azul_v2_anvilprod_anvil3-it_datasets_aggregate,azul_v2_anvilprod_anvil3-it_donors,azul_v2_anvilprod_anvil3-it_donors_aggregate,azul_v2_anvilprod_anvil3-it_files,azul_v2_anvilprod_anvil3-it_files_aggregate/_delete_by_query?slices=auto
2023-10-31 09:06:45,731    INFO MainThread elasticsearch: … with response body '{"took":10,"timed_out":false,"total":4,"deleted":4,"batches":1,"version_conflicts":0,"noops":0,"retries":{"bulk":0,"search":0},…'
```

hammerbox anvil3

```
(.venv) daniel@Crispin ~/repo/azul3 $ python scripts/reindex.py --catalogs anvil3 --deindex --sources tdr:datarepo-828e5175:snapshot/ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242*
2023-10-31 09:08:25,548   DEBUG MainThread __main__: Source glob 'tdr:datarepo-828e5175:snapshot/ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242*' matched sources ['tdr:datarepo-828e5175:snapshot/ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242:3d1/0'] in catalog 'anvil3'
2023-10-31 09:08:25,549   DEBUG MainThread azul.terra: _request('GET', https://data.terra.bio/api/repository/v1/snapshots?filter=ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242&limit=2, headers=None, timeout=20.0, body=None)
2023-10-31 09:08:25,559    INFO MainThread botocore.credentials: Found credentials in environment variables.
2023-10-31 09:08:26,822   DEBUG MainThread azul.terra: _request(…) -> 1.274s 200 b'{"total":1354,"filteredTotal":1,"items":[{"id":"f918ddde-889c-49a3-8881-e7bbdebd0e56","name":"ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242","description":"Full view snapshot of ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024","createdDa...'
2023-10-31 09:08:26,823   DEBUG MainThread azul.terra: _request('GET', https://data.terra.bio/api/repository/v1/snapshots/f918ddde-889c-49a3-8881-e7bbdebd0e56, headers=None, timeout=20.0, body=None)
2023-10-31 09:08:29,418   DEBUG MainThread azul.terra: _request(…) -> 2.594s 200 b'{"id":"f918ddde-889c-49a3-8881-e7bbdebd0e56","name":"ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242","description":"Full view snapshot of ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024","createdDate":"2023-10-10T12:42:57.728118Z","consen...'
2023-10-31 09:08:29,900   DEBUG MainThread azul.es: Creating ES client [vpc-azul-index-hammerbox-srwikb4z42wnpzxq2f56y36icu.us-east-1.es.amazonaws.com:443]
2023-10-31 09:08:29,961    INFO MainThread botocore.credentials: Found credentials in environment variables.
2023-10-31 09:08:29,962    INFO MainThread azul.azulclient: Deindexing sources {'tdr:datarepo-828e5175:snapshot/ANVIL_CCDG_Broad_CVD_EOCAD_VIRGO_WGS_20221024_ANV5_202310101242:3d1/0'} from catalog 'anvil3'
2023-10-31 09:08:29,962   DEBUG MainThread azul.azulclient: Using query: {'query': {'bool': {'should': [{'terms': {'sources.id.keyword': ['f918ddde-889c-49a3-8881-e7bbdebd0e56']}}, {'terms': {'source.id.keyword': ['f918ddde-889c-49a3-8881-e7bbdebd0e56']}}]}}}
2023-10-31 09:08:29,962    INFO MainThread elasticsearch: Making POST request to https://vpc-azul-index-hammerbox-srwikb4z42wnpzxq2f56y36icu.us-east-1.es.amazonaws.com:443/azul_v2_hammerbox_anvil3_activities,azul_v2_hammerbox_anvil3_activities_aggregate,azul_v2_hammerbox_anvil3_biosamples,azul_v2_hammerbox_anvil3_biosamples_aggregate,azul_v2_hammerbox_anvil3_datasets,azul_v2_hammerbox_anvil3_datasets_aggregate,azul_v2_hammerbox_anvil3_donors,azul_v2_hammerbox_anvil3_donors_aggregate,azul_v2_hammerbox_anvil3_files,azul_v2_hammerbox_anvil3_files_aggregate/_delete_by_query?slices=auto
2023-10-31 09:08:29,962    INFO MainThread elasticsearch: … with request body b'{"query":{"bool":{"should":[{"terms":{"sources.id.keyword":["f918ddde-889c-49a3-8881-e7bbdebd0e56"]}},{"terms":{"source.id.ke...'
2023-10-31 09:08:30,442    INFO MainThread elasticsearch: Got 200 response after 0.480s from POST to https://vpc-azul-index-hammerbox-srwikb4z42wnpzxq2f56y36icu.us-east-1.es.amazonaws.com:443/azul_v2_hammerbox_anvil3_activities,azul_v2_hammerbox_anvil3_activities_aggregate,azul_v2_hammerbox_anvil3_biosamples,azul_v2_hammerbox_anvil3_biosamples_aggregate,azul_v2_hammerbox_anvil3_datasets,azul_v2_hammerbox_anvil3_datasets_aggregate,azul_v2_hammerbox_anvil3_donors,azul_v2_hammerbox_anvil3_donors_aggregate,azul_v2_hammerbox_anvil3_fil [...]

2023-10-31 17:15 UTC, achave11-ucsc approved these changes

2023-10-31 17:21 UTC, hannes-ucsc requested changes
Title is non-sensical. This is a fix bit "Index anvil3 in anvilprod" isn't a description of a defect. What's we've done in the past is make the PR title (and therefore the title of the merge commit) the same as that of previous PR to which this is a follow-up but use "Fix: {description of defect}" as the commit title.

2023-11-01 06:07 UTC, hannes-ucsc approved these changes

2023-11-01 17:22 UTC, merged