Upgrade dependencies 2023-11-27 (#5723)
DataBiosphere/azul pull request #5735
Opened 2023-11-29 19:18 UTC by dsotirho-ucsc

Connected issues: #5723

## Checklist

### Author

- [ ] PR is a draft
- [ ] Target branch is `develop`
- [ ] Name of PR branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [ ] PR title references all connected issues
- [ ] PR title matches<sup>1</sup> that of a connected issue <sub>or comment in PR explains why they're different</sub>
- [ ] For each connected issue, there is at least one commit whose title references that issue
- [ ] PR is connected to all connected issues via ZenHub
- [ ] PR description links to connected issues
- [ ] Added `p` tag to titles of partial commits
- [ ] Added `partial` label to PR <sub>or this PR completely resolves all connected issues</sub>
- [ ] All connected issues are resolved partially <sub>or this PR does not have the `partial` label</sub>

<sup>1</sup> when the issue title describes a problem, the corresponding PR
title is `Fix: ` followed by the issue title

### Author (reindex, API changes)

- [ ] Added `r` tag to commit title <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label to PR <sub>or this PR does not require reindexing</sub>
- [ ] PR and connected issue are labeled `API` <sub>or this PR does not modify a REST API</sub>
- [ ] Added `a` (`A`) tag to commit title for backwards (in)compatible changes <sub>or this PR does not modify a REST API</sub>
- [ ] Updated REST API version number in `app.py` <sub>or this PR does not modify a REST API</sub>

### Author (chains)

- [ ] This PR is blocked by previous PR in the chain <sub>or this PR is not chained to another PR</sub>
- [ ] Added `base` label to the blocking PR <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chained` label to this PR <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [ ] Documented upgrading of deployments in UPGRADING.rst <sub>or this PR does not require upgrading</sub>
- [ ] Added `u` tag to commit title <sub>or this PR does not require upgrading</sub>
- [ ] Added `upgrade` label to PR <sub>or this PR does not require upgrading</sub>

### Author (operator tasks)

- [ ] Added checklist items for additional operator tasks <sub>or this PR does not require additional tasks</sub>

### Author (hotfixes)

- [ ] Added `F` tag to main commit title <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [ ] Reverted the temporary hotfixes for any connected issues <sub>or the `prod` branch has no temporary hotfixes for any connected issues</sub>

### Author (before every review)

- [ ] Rebased PR branch on `develop`, squashed old fixups
- [ ] Ran `make requirements_update` <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [ ] Added `R` tag to commit title <sub>or this PR does not touch requirements*.txt</sub>
- [ ] Added `reqs` label to PR <sub>or this PR does not touch requirements*.txt</sub>
- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>

### Peer reviewer (after requesting changes)

Uncheck the *Author (before every review)* checklists.

### Peer reviewer (after approval)

- [ ] PR is not a draft
- [ ] Ticket is in *Review requested* column
- [ ] Requested review from primary reviewer
- [ ] Assigned PR to primary reviewer

### Primary reviewer (after requesting changes)

Uncheck the *before every review* checklists. Update the `N reviews` label.

### Primary reviewer (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issues as `demo` or `no demo`
- [ ] Commented on connected issues about demo expectations <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] `N reviews` label is accurate
- [ ] Moved ticket to *Approved* column
- [ ] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear <sub>or all connected issues are labeled `no demo`</sub>
- [ ] PR has checklist items for upgrading instructions <sub>or PR is not labeled `upgrade`</sub>
- [ ] Squashed PR branch and rebased onto `develop`
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Pushed PR branch to GitLab `dev` and added `sandbox` label <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvilprod` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `hammerbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `hammerbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted unreferenced indices in `sandbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Deleted unreferenced indices in `anvilbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Deleted unreferenced indices in `hammerbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Started reindex in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Started reindex in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Started reindex in `hammerbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `hammerbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Title of merge commit starts with title from this PR
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title <sub>but only include `p` if the PR is labeled `partial`</sub>
- [ ] Moved connected issues to Merged column in ZenHub
- [ ] Pushed merge commit to GitHub

### Operator (chain shortening)

- [ ] Changed the target branch of the blocked PR to `develop` <sub>or this PR is not labeled `base`</sub>
- [ ] Removed the `chained` label from the blocked PR <sub>or this PR is not labeled `base`</sub>
- [ ] Removed the blocking relationship from the blocked PR <sub>or this PR is not labeled `base`</sub>
- [ ] Removed the `base` label from this PR <sub>or this PR is not labeled `base`</sub>

### Operator (after pushing the merge commit)

- [ ] Pushed merge commit to GitLab `dev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed merge commit to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed merge commit to GitLab `anvilprod` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes on GitLab `dev`<sup>1</sup>
- [ ] Reviewed build logs for anomalies on GitLab `dev`<sup>1</sup>
- [ ] Build passes on GitLab `anvildev`<sup>1</sup>
- [ ] Reviewed build logs for anomalies on GitLab `anvildev`<sup>1</sup>
- [ ] Build passes on GitLab `anvilprod`<sup>1</sup>
- [ ] Reviewed build logs for anomalies on GitLab `anvilprod`<sup>1</sup>
- [ ] Deleted PR branch from GitHub
- [ ] Deleted PR branch from GitLab `dev`
- [ ] Deleted PR branch from GitLab `anvildev`
- [ ] Deleted PR branch from GitLab `anvilprod`

<sup>1</sup> When pushing the merge commit is skipped due to the PR being
labelled `no sandbox`, the next build triggered by a PR whose merge commit *is*
pushed determines this checklist item.

### Operator (reindex)

-  [...]

2023-12-01 03:56 UTC, dsotirho-ucsc commented
PR was deployed to personal deployment & passed tests including IT.
PR was deployed to GitLab `dev` (for the GitLab update) and pushed to sandbox. [Pipeline 28706](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/pipelines/28706) successfully.

2023-12-01 19:20 UTC, achave11-ucsc requested changes
Changes look good, nicely done. A few nits.
Also consider doing another pass over your Inspector script, it might benefit from having more type hints and other misc formatting changes.

2023-12-01 19:20 UTC, achave11-ucsc commented on .github/ISSUE_TEMPLATE/upgrade.md
> +  - [ ] … Updates to [Terraform](https://hub.docker.com/r/hashicorp/terraform/tags) (only patch versions)
`U…` might be a typo here.

2023-12-01 19:20 UTC, achave11-ucsc commented on scripts/inspector-findings.py
> +                                 'Choices: ' + ','.join(cls.all_severities))
Consider adhering to a single format, whether it be f-strings or concatenation, I think it might improve consistency.

2023-12-01 19:20 UTC, achave11-ucsc commented on scripts/inspector-findings.py
> +                                 'Choices: ' + ','.join(cls.all_severities))
Also consider a space character after the comma in the join command, to improve readability.

2023-12-01 19:20 UTC, achave11-ucsc commented on scripts/inspector-findings.py
> +        client = aws.client('inspector2')  # Note inspector2 not inspector
The comment might be redundant, I think it's protocol (has been enforced during review process) to use the most recent client or resource API version available.

2023-12-01 19:20 UTC, achave11-ucsc commented on scripts/inspector-findings.py
> +        log.info(f'Fetched a total of {len(self.findings)} findings from AWS Inspector')
Reference the fourth bulleted item in https://github.com/DataBiosphere/azul/blob/develop/CONTRIBUTING.rst#logging.

2023-12-01 19:20 UTC, achave11-ucsc commented on scripts/inspector-findings.py
> +        log.info(f'Grouped findings by {len(findings)} unique vulnerabilities')
Same here.

2023-12-01 19:20 UTC, achave11-ucsc commented on scripts/inspector-findings.py
> +        log.info(f'Writing file {output_file_name!r}')
Also here.

2023-12-01 19:20 UTC, achave11-ucsc commented on scripts/inspector-findings.py
> +                continue
This looks to me like what the first bulleted item in https://github.com/DataBiosphere/azul/blob/develop/CONTRIBUTING.rst#control-flow describes.

2023-12-01 19:20 UTC, achave11-ucsc commented on scripts/inspector-findings.py
> +        log.info(f'Found {finding_count} vulnerabilities with a severity '
Would `len(findings)` not achieve the same here?
The counter might be unnecessary.

2023-12-01 19:20 UTC, achave11-ucsc commented on scripts/inspector-findings.py
> +    def parse_findings_for_csv(self) -> tuple[dict, set, set]:
The definition of this method seems a bit complicated. Consider doing another pass over this method to see if it might do with a bit of de-duplication or simplification.

2023-12-01 19:20 UTC, achave11-ucsc commented on scripts/inspector-findings.py
> +    def parse_findings_for_csv(self) -> tuple[dict, set, set]:
Additionally, a bit of preprocessing might help cleanup and address what looks like a bail-out.

2023-12-01 21:44 UTC, dsotirho-ucsc commented on scripts/inspector-findings.py
> +        log.info(f'Found {finding_count} vulnerabilities with a severity '
`finding_count` is the total number of findings (that matched the specified severity), while `len(findings)` gives the number of unique vulnerabilities (e.g.  CVE-1234), which can have one or more finding associated with it. While not entirely necessary I thought it'd be info nice to see. I renamed the counter variable to make it less confusing.

2023-12-02 01:34 UTC, dsotirho-ucsc commented
Note: I amended the `Update GitLab…` commit (instead of adding a fixup) to change the new version from 6.16.0 to 6.16.1.

PR was redeployed to `dev.gitlab` to test GitLab 6.16.1, and the PR passed on sandbox (Pipeline [28731](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/pipelines/28731))

2023-12-02 04:05 UTC, achave11-ucsc approved these changes, later dismissed
🦭✅

2023-12-05 00:59 UTC, hannes-ucsc approved these changes, later dismissed

2023-12-05 01:02 UTC, hannes-ucsc commented
When I rebased, some of the commits were squashed out. I also ran `make requirements_update` again.

2023-12-06 21:36 UTC, hannes-ucsc approved these changes

2023-12-06 21:56 UTC, merged