Explicitly set no lifecycle rule in TF for buckets without one (#5561)
DataBiosphere/azul pull request #5756
Opened 2023-12-05 01:38 UTC by nadove-ucsc

Connected issues: #5561

## Checklist

### Author

- [x] PR is a draft
- [x] Target branch is `develop`
- [x] Name of PR branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [x] PR title references all connected issues
- [x] PR title matches<sup>1</sup> that of a connected issue <sub>or comment in PR explains why they're different</sub>
- [x] For each connected issue, there is at least one commit whose title references that issue
- [ ] PR is connected to all connected issues via ZenHub
- [x] PR description links to connected issues
- [x] Added `p` tag to titles of partial commits
- [x] Added `partial` label to PR <sub>or this PR completely resolves all connected issues</sub>
- [x] All connected issues are resolved partially <sub>or this PR does not have the `partial` label</sub>

<sup>1</sup> when the issue title describes a problem, the corresponding PR
title is `Fix: ` followed by the issue title

### Author (reindex, API changes)

- [x] Added `r` tag to commit title <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label to PR <sub>or this PR does not require reindexing</sub>
- [x] PR and connected issue are labeled `API` <sub>or this PR does not modify a REST API</sub>
- [x] Added `a` (`A`) tag to commit title for backwards (in)compatible changes <sub>or this PR does not modify a REST API</sub>
- [x] Updated REST API version number in `app.py` <sub>or this PR does not modify a REST API</sub>

### Author (chains)

- [x] This PR is blocked by previous PR in the chain <sub>or this PR is not chained to another PR</sub>
- [x] Added `base` label to the blocking PR <sub>or this PR is not chained to another PR</sub>
- [x] Added `chained` label to this PR <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [x] Documented upgrading of deployments in UPGRADING.rst <sub>or this PR does not require upgrading</sub>
- [x] Added `u` tag to commit title <sub>or this PR does not require upgrading</sub>
- [x] Added `upgrade` label to PR <sub>or this PR does not require upgrading</sub>

### Author (operator tasks)

- [ ] Added checklist items for additional operator tasks <sub>or this PR does not require additional tasks</sub>

### Author (hotfixes)

- [x] Added `F` tag to main commit title <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [x] Reverted the temporary hotfixes for any connected issues <sub>or the `prod` branch has no temporary hotfixes for any connected issues</sub>

### Author (before every review)

- [x] Rebased PR branch on `develop`, squashed old fixups
- [x] Ran `make requirements_update` <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [x] Added `R` tag to commit title <sub>or this PR does not touch requirements*.txt</sub>
- [x] Added `reqs` label to PR <sub>or this PR does not touch requirements*.txt</sub>
- [x] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>

### Peer reviewer (after requesting changes)

Uncheck the *Author (before every review)* checklists.

### Peer reviewer (after approval)

- [ ] PR is not a draft
- [ ] Ticket is in *Review requested* column
- [ ] Requested review from primary reviewer
- [ ] Assigned PR to primary reviewer

### Primary reviewer (after requesting changes)

Uncheck the *before every review* checklists. Update the `N reviews` label.

### Primary reviewer (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issues as `demo` or `no demo`
- [ ] Commented on connected issues about demo expectations <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] `N reviews` label is accurate
- [ ] Moved ticket to *Approved* column
- [ ] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear <sub>or all connected issues are labeled `no demo`</sub>
- [ ] PR has checklist items for upgrading instructions <sub>or PR is not labeled `upgrade`</sub>
- [ ] Squashed PR branch and rebased onto `develop`
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Pushed PR branch to GitLab `dev` and added `sandbox` label <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvilprod` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `hammerbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `hammerbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted unreferenced indices in `sandbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Deleted unreferenced indices in `anvilbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Deleted unreferenced indices in `hammerbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Started reindex in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Started reindex in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Started reindex in `hammerbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `hammerbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Title of merge commit starts with title from this PR
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title <sub>but only include `p` if the PR is labeled `partial`</sub>
- [ ] Moved connected issues to Merged column in ZenHub
- [ ] Pushed merge commit to GitHub

### Operator (chain shortening)

- [ ] Changed the target branch of the blocked PR to `develop` <sub>or this PR is not labeled `base`</sub>
- [ ] Removed the `chained` label from the blocked PR <sub>or this PR is not labeled `base`</sub>
- [ ] Removed the blocking relationship from the blocked PR <sub>or this PR is not labeled `base`</sub>
- [ ] Removed the `base` label from this PR <sub>or this PR is not labeled `base`</sub>

### Operator (after pushing the merge commit)

- [ ] Pushed merge commit to GitLab `dev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed merge commit to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed merge commit to GitLab `anvilprod` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes on GitLab `dev`<sup>1</sup>
- [ ] Reviewed build logs for anomalies on GitLab `dev`<sup>1</sup>
- [ ] Build passes on GitLab `anvildev`<sup>1</sup>
- [ ] Reviewed build logs for anomalies on GitLab `anvildev`<sup>1</sup>
- [ ] Build passes on GitLab `anvilprod`<sup>1</sup>
- [ ] Reviewed build logs for anomalies on GitLab `anvilprod`<sup>1</sup>
- [ ] Deleted PR branch from GitHub
- [ ] Deleted PR branch from GitLab `dev`
- [ ] Deleted PR branch from GitLab `anvildev`
- [ ] Deleted PR branch from GitLab `anvilprod`

<sup>1</sup> When pushing the merge commit is skipped due to the PR being
labelled `no sandbox`, the next build triggered by a PR whose merge commit *is*
pushed determines this checklist item.

### Operator (reindex)

-  [...]

2023-12-06 01:58 UTC, nadove-ucsc commented
@dsotirho-ucsc Please ignore the CodeQL warning for now.

2023-12-06 18:21 UTC, dsotirho-ucsc requested changes
I get a terraform validation failure when trying to build the `shared` component:

```
Creating shared.tf.json
terraform validate
╷
│ Error: Missing required argument
│
│   on shared.tf.json line 254, in resource[7].aws_s3_bucket_lifecycle_configuration[2].trail.rule:
│  254:                         "rule": {}
│
│ The argument "status" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│
│   on shared.tf.json line 254, in resource[7].aws_s3_bucket_lifecycle_configuration[2].trail.rule:
│  254:                         "rule": {}
│
│ The argument "id" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│
│   on shared.tf.json line 260, in resource[7].aws_s3_bucket_lifecycle_configuration[3].aws_config.rule:
│  260:                         "rule": {}
│
│ The argument "status" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│
│   on shared.tf.json line 260, in resource[7].aws_s3_bucket_lifecycle_configuration[3].aws_config.rule:
│  260:                         "rule": {}
│
│ The argument "id" is required, but no definition was found.
╵
make: *** [validate] Error 1
```

2023-12-06 23:40 UTC, nadove-ucsc commented
Unfortunately, creating these empty policies does not appear to have the desired effect of removing the existing policies. 
```
$ (cd terraform/shared/ && CI_COMMIT_REF_NAME=develop make plan)
...

  # aws_s3_bucket_lifecycle_configuration.aws_config will be created
  + resource "aws_s3_bucket_lifecycle_configuration" "aws_config" {
      + bucket = "edu-ucsc-gi-platform-hca-dev-awsconfig.us-east-1"
      + id     = (known after apply)

      + rule {
          + id     = "aws_config_default_lifecycle_policy"
          + status = "Enabled"
        }
    }

  # aws_s3_bucket_lifecycle_configuration.trail will be created
  + resource "aws_s3_bucket_lifecycle_configuration" "trail" {
      + bucket = "edu-ucsc-gi-platform-hca-dev-trail.us-east-1"
      + id     = (known after apply)

      + rule {
          + id     = "trail_default_lifecycle_policy"
          + status = "Enabled"
        }
    }

Plan: 2 to add, 0 to change, 0 to destroy.
````

Presumably, Terraform does not consider the rules in the configuration to be incompatible with the preexisting ones, because we are forced to specify an `id` to distinguish them.

2023-12-07 01:59 UTC, nadove-ucsc commented
Hannes found an alternative approach that appears to achieve the desired effect at the cost of some deprecation warnings:

```
Terraform will perform the following actions:

  # aws_s3_bucket.aws_config will be updated in-place
  ~ resource "aws_s3_bucket" "aws_config" {
        id                          = "edu-ucsc-gi-platform-hca-dev-awsconfig.us-east-1"
        tags                        = {
            "Name"                = "azul-aws_config"
            "billing"             = "hca"
            "component"           = "azul-aws_config"
            "deployment"          = "dev"
            "owner"               = "hannes@ucsc.edu"
            "service"             = "azul"
            "terraform_component" = "shared"
        }
        # (11 unchanged attributes hidden)

      ~ lifecycle_rule {
          ~ enabled                                = true -> false
            id                                     = "mandatory_tag_enforcer_lifecycle_s3"
            tags                                   = {}
            # (1 unchanged attribute hidden)

          + expiration {
              + days = 36500
            }

          - transition {
              - days          = 1 -> null
              - storage_class = "INTELLIGENT_TIERING" -> null
            }
        }

        # (4 unchanged blocks hidden)
    }

  # aws_s3_bucket.trail will be updated in-place
  ~ resource "aws_s3_bucket" "trail" {
        id                          = "edu-ucsc-gi-platform-hca-dev-trail.us-east-1"
        tags                        = {
            "Name"                = "azul-trail"
            "billing"             = "hca"
            "component"           = "azul-trail"
            "deployment"          = "dev"
            "owner"               = "hannes@ucsc.edu"
            "service"             = "azul"
            "terraform_component" = "shared"
        }
        # (11 unchanged attributes hidden)

      ~ lifecycle_rule {
          ~ enabled                                = true -> false
            id                                     = "mandatory_tag_enforcer_lifecycle_s3"
            tags                                   = {}
            # (1 unchanged attribute hidden)

          + expiration {
              + days = 36500
            }

          - transition {
              - days          = 1 -> null
              - storage_class = "INTELLIGENT_TIERING" -> null
            }
        }

        # (4 unchanged blocks hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.

Warnings:

- Argument is deprecated
  on shared.tf.json line 95 (and 3 more)

To see the full warning notes, run Terraform without -compact-warnings.
```

2023-12-07 18:20 UTC, dsotirho-ucsc submitted a review, later dismissed
Approved.

2023-12-12 00:56 UTC, hannes-ucsc requested changes

2023-12-12 00:56 UTC, hannes-ucsc commented on environment.py
> +        'TF_CLI_ARGS_apply': '-compact-warnings',
Let's `**` a dict comprehension here.

2023-12-12 05:36 UTC, hannes-ucsc requested changes

2023-12-12 05:36 UTC, hannes-ucsc commented on environment.py
> +            for stage in ['validate', 'plan', 'apply']
```suggestion
            'TF_CLI_ARGS_' + command: '-compact-warnings'
            for command in ['validate', 'plan', 'apply']
```

"stage" is already taken and `terraform --help` refers to them as "commands".

2023-12-12 17:59 UTC, hannes-ucsc approved these changes

2023-12-14 05:28 UTC, merged