Update Terraform to 1.6.x (#5687)
DataBiosphere/azul pull request #5780
Opened 2023-12-12 17:19 UTC by dsotirho-ucsc

Connected issues: #5687

## Checklist

### Author

- [x] PR is a draft
- [x] Target branch is `develop`
- [x] Name of PR branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [x] PR title references all connected issues
- [x] PR title matches<sup>1</sup> that of a connected issue <sub>or comment in PR explains why they're different</sub>
- [x] For each connected issue, there is at least one commit whose title references that issue
- [x] PR is connected to all connected issues via ZenHub
- [x] PR description links to connected issues
- [x] Added `p` tag to titles of partial commits
- [x] Added `partial` label to PR <sub>or this PR completely resolves all connected issues</sub>
- [x] All connected issues are resolved partially <sub>or this PR does not have the `partial` label</sub>

<sup>1</sup> when the issue title describes a problem, the corresponding PR
title is `Fix: ` followed by the issue title

### Author (reindex, API changes)

- [x] Added `r` tag to commit title <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label to PR <sub>or this PR does not require reindexing</sub>
- [x] PR and connected issue are labeled `API` <sub>or this PR does not modify a REST API</sub>
- [x] Added `a` (`A`) tag to commit title for backwards (in)compatible changes <sub>or this PR does not modify a REST API</sub>
- [x] Updated REST API version number in `app.py` <sub>or this PR does not modify a REST API</sub>

### Author (chains)

- [x] This PR is blocked by previous PR in the chain <sub>or this PR is not chained to another PR</sub>
- [x] Added `base` label to the blocking PR <sub>or this PR is not chained to another PR</sub>
- [x] Added `chained` label to this PR <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [x] Documented upgrading of deployments in UPGRADING.rst <sub>or this PR does not require upgrading</sub>
- [x] Added `u` tag to commit title <sub>or this PR does not require upgrading</sub>
- [x] Added `upgrade` label to PR <sub>or this PR does not require upgrading</sub>

### Author (operator tasks)

- [ ] Added checklist items for additional operator tasks <sub>or this PR does not require additional tasks</sub>

### Author (hotfixes)

- [ ] Added `F` tag to main commit title <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [ ] Reverted the temporary hotfixes for any connected issues <sub>or the `prod` branch has no temporary hotfixes for any connected issues</sub>

### Author (before every review)

- [ ] Rebased PR branch on `develop`, squashed old fixups
- [ ] Ran `make requirements_update` <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [ ] Added `R` tag to commit title <sub>or this PR does not touch requirements*.txt</sub>
- [ ] Added `reqs` label to PR <sub>or this PR does not touch requirements*.txt</sub>
- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>

### Peer reviewer (after requesting changes)

Uncheck the *Author (before every review)* checklists.

### Peer reviewer (after approval)

- [ ] PR is not a draft
- [ ] Ticket is in *Review requested* column
- [ ] Requested review from primary reviewer
- [ ] Assigned PR to primary reviewer

### Primary reviewer (after requesting changes)

Uncheck the *before every review* checklists. Update the `N reviews` label.

### Primary reviewer (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issues as `demo` or `no demo`
- [ ] Commented on connected issues about demo expectations <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] `N reviews` label is accurate
- [ ] Moved ticket to *Approved* column
- [ ] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear <sub>or all connected issues are labeled `no demo`</sub>
- [ ] PR has checklist items for upgrading instructions <sub>or PR is not labeled `upgrade`</sub>
- [ ] Squashed PR branch and rebased onto `develop`
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Pushed PR branch to GitLab `dev` and added `sandbox` label <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvilprod` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `hammerbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `hammerbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted unreferenced indices in `sandbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Deleted unreferenced indices in `anvilbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Deleted unreferenced indices in `hammerbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [ ] Started reindex in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Started reindex in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Started reindex in `hammerbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `hammerbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Title of merge commit starts with title from this PR
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title <sub>but only include `p` if the PR is labeled `partial`</sub>
- [ ] Moved connected issues to Merged column in ZenHub
- [ ] Pushed merge commit to GitHub

### Operator (chain shortening)

- [ ] Changed the target branch of the blocked PR to `develop` <sub>or this PR is not labeled `base`</sub>
- [ ] Removed the `chained` label from the blocked PR <sub>or this PR is not labeled `base`</sub>
- [ ] Removed the blocking relationship from the blocked PR <sub>or this PR is not labeled `base`</sub>
- [ ] Removed the `base` label from this PR <sub>or this PR is not labeled `base`</sub>

### Operator (after pushing the merge commit)

- [ ] Pushed merge commit to GitLab `dev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed merge commit to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed merge commit to GitLab `anvilprod` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes on GitLab `dev`<sup>1</sup>
- [ ] Reviewed build logs for anomalies on GitLab `dev`<sup>1</sup>
- [ ] Build passes on GitLab `anvildev`<sup>1</sup>
- [ ] Reviewed build logs for anomalies on GitLab `anvildev`<sup>1</sup>
- [ ] Build passes on GitLab `anvilprod`<sup>1</sup>
- [ ] Reviewed build logs for anomalies on GitLab `anvilprod`<sup>1</sup>
- [ ] Deleted PR branch from GitHub
- [ ] Deleted PR branch from GitLab `dev`
- [ ] Deleted PR branch from GitLab `anvildev`
- [ ] Deleted PR branch from GitLab `anvilprod`

<sup>1</sup> When pushing the merge commit is skipped due to the PR being
labelled `no sandbox`, the next build triggered by a PR whose merge commit *is*
pushed determines this checklist item.

### Operator (reindex)

-  [...]

2023-12-18 18:32 UTC, achave11-ucsc requested changes
Some author CL items are missing.
Also, would you care to enhance the CL with an item to notify developers when this gets merged into develop.

2023-12-18 23:58 UTC, achave11-ucsc approved these changes, later dismissed

2023-12-21 21:39 UTC, hannes-ucsc requested changes
There is more to this. Look for references to `azul_terraform_version` and consider what else needs to be done.

Edit: This may be a little obscure but since you are changing an input to the Dockerfile, this requires `make requirements_update` as it invalidates the layer cache and would lead to dirty requirements files during the sandbox builds.

2024-01-05 00:55 UTC, hannes-ucsc commented on UPGRADING.rst
> +pushing the merge commit to the GitLab instance in that deployment.
Why is this necessary?

2024-01-10 19:08 UTC, hannes-ucsc approved these changes

2024-01-10 19:11 UTC, hannes-ucsc requested changes
There is a suspected freebie mentioned in the issue description. Please tend to that.

2024-01-12 17:35 UTC, dsotirho-ucsc commented
> There is a suspected freebie mentioned in the issue description. Please tend to that.

Confirmed the update to Terraform resolved issue #5656 and allowed a private API deployment without errorr.

<details>
<summary>`make deploy` log with TF 1.6.5 and private API</summary>

```
(.venv) daniel@Crispin ~/repo/azul2 $ tfenv list
* 1.6.5 (set by /Users/daniel/repo/azul2/.terraform-version)
  1.3.10
  1.3.4
  0.12.31
(.venv) daniel@Crispin ~/repo/azul2 $
(.venv) daniel@Crispin ~/repo/azul2 $ env | grep PRIVATE_API=
AZUL_PRIVATE_API=1
(.venv) daniel@Crispin ~/repo/azul2 $
(.venv) daniel@Crispin ~/repo/azul2 $ make deploy
/Library/Developer/CommandLineTools/usr/bin/make -C lambdas
/Library/Developer/CommandLineTools/usr/bin/make -C layer layer
python /Users/daniel/repo/azul2/scripts/check_branch.py
python .chalice/config.json.template.py .chalice/config.json
Creating .chalice/config.json
python /Users/daniel/repo/azul2/scripts/stage_layer.py
2024-01-11 14:55:56,549    INFO MainThread botocore.credentials: Found credentials in shared credentials file: ~/.aws/credentials
2024-01-11 14:55:57,156    INFO MainThread azul.lambda_layer: Checking for dependencies layer package at s3://edu-ucsc-gi-platform-hca-dev-shared.us-east-1/azul/daniel2/lambda_layers/23940d1fcb83c5f1f3729e5d04934aeec4a629bd.zip.
2024-01-11 14:55:57,335    INFO MainThread azul.boto3: s3.HeadObject:	Making HEAD request to https://s3.amazonaws.com/edu-ucsc-gi-platform-hca-dev-shared.us-east-1/azul/daniel2/lambda_layers/23940d1fcb83c5f1f3729e5d04934aeec4a629bd.zip
2024-01-11 14:55:57,335    INFO MainThread azul.boto3: s3.HeadObject:	… without request body
2024-01-11 14:55:57,766    INFO MainThread azul.boto3: s3.HeadObject:	Got 200 response
2024-01-11 14:55:57,766    INFO MainThread azul.boto3: s3.HeadObject:	… with response body b''
2024-01-11 14:55:57,767    INFO MainThread azul.lambda_layer: Layer package already up-to-date.
/Library/Developer/CommandLineTools/usr/bin/make -C indexer package
python /Users/daniel/repo/azul2/scripts/check_branch.py
python .chalice/config.json.template.py .chalice/config.json
[INFO]	2024-01-11T14:56:01.854Z	00010ca1-b0ba-466f-8c58-dabbad000000	botocore.credentials	Found credentials in shared credentials file: ~/.aws/credentials
Creating .chalice/config.json
python vendor/resources/environ.json.template.py vendor/resources/environ.json
Creating vendor/resources/environ.json
PYTHONHASHSEED=0 python -m compileall \
		-f -q --invalidation-mode checked-hash \
		vendor vendor/humancellatlas vendor/azul
python -m azul.changelog vendor
chalice package --stage daniel2 --pkg-format terraform .chalice/terraform
/Users/daniel/repo/azul2/.venv/lib/python3.11/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
[INFO]	2024-01-11T14:56:05.257Z	00010ca1-b0ba-466f-8c58-dabbad000000	botocore.credentials	Found credentials in shared credentials file: ~/.aws/credentials
Creating deployment package.
Reusing existing deployment package.
[INFO]	2024-01-11T14:56:05.805Z	00010ca1-b0ba-466f-8c58-dabbad000000	botocore.credentials	Found credentials in environment variables.
/Library/Developer/CommandLineTools/usr/bin/make -C service package
python /Users/daniel/repo/azul2/scripts/check_branch.py
python .chalice/config.json.template.py .chalice/config.json
[INFO]	2024-01-11T14:56:10.195Z	00010ca1-b0ba-466f-8c58-dabbad000000	botocore.credentials	Found credentials in shared credentials file: ~/.aws/credentials
Creating .chalice/config.json
python vendor/resources/environ.json.template.py vendor/resources/environ.json
Creating vendor/resources/environ.json
PYTHONHASHSEED=0 python -m compileall \
		-f -q --invalidation-mode checked-hash \
		vendor vendor/humancellatlas vendor/azul
python -m azul.changelog vendor
chalice package --stage daniel2 --pkg-format terraform .chalice/terraform
/Users/daniel/repo/azul2/.venv/lib/python3.11/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Creating deployment package.
Reusing existing deployment package.
[INFO]	2024-01-11T14:56:13.861Z	00010ca1-b0ba-466f-8c58-dabbad000000	botocore.credentials	Found credentials in environment variables.
/Library/Developer/CommandLineTools/usr/bin/make -C terraform apply
set -o pipefail && git ls-files --ignored --others --directory --exclude-standard | (grep -v '/[^/]' || test $? -eq 1) | xargs -r rm -rv
api_gateway.tf.json
authentication.tf.json
backend.tf.json
cloudwatch.tf.json
common.tf.json
dynamo.tf.json
lambda_layer.tf.json
providers.tf.json
s3.tf.json
sqs.tf.json
step_function.tf.json
python /Users/daniel/repo/azul2/scripts/check_branch.py
python providers.tf.json.template.py providers.tf.json
Creating providers.tf.json
python backend.tf.json.template.py backend.tf.json
Creating backend.tf.json
terraform init -reconfigure

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Reusing previous version of hashicorp/google from the dependency lock file
- Reusing previous version of hashicorp/aws from the dependency lock file
- Reusing previous version of hashicorp/external from the dependency lock file
- Reusing previous version of hashicorp/null from the dependency lock file
- Using previously-installed hashicorp/aws v5.11.0
- Using previously-installed hashicorp/external v2.2.0
- Using previously-installed hashicorp/null v3.2.0
- Using previously-installed hashicorp/google v4.58.0

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
/Library/Developer/CommandLineTools/usr/bin/make check_providers_clean
git diff --exit-code --name-only .terraform.lock.hcl \
	&& git diff --cached --exit-code --name-only .terraform.lock.hcl
python /Users/daniel/repo/azul2/scripts/terraform_schema.py check \
	|| (echo "Schema is stale. Run 'make update_schema' and commit." ; false)
2024-01-11 14:56:28,630    INFO MainThread azul.terraform: Running ['terraform', 'version', '-json']
2024-01-11 14:56:28,703    INFO MainThread azul.terraform: Terraform output:
{
  "terraform_version": "1.6.5",
  "platform": "darwin_amd64",
  "provider_selections": {
    "registry.terraform.io/hashicorp/aws": "5.11.0",
    "registry.terraform.io/hashicorp/external": "2.2.0",
    "registry.terraform.io/hashicorp/google": "4.58.0",
    "registry.terraform.io/hashicorp/null": "3.2.0"
  },
  "terraform_outdated": true
}

python api_gateway.tf.json.template.py api_gateway.tf.json
Creating api_gateway.tf.json
python authentication.tf.json.template.py authentication.tf.json
Creating authentication.tf.json
python cloudwatch.tf.json.template.py cloudwatch.tf.json
Creating cloudwatch.tf.json
python common.tf.json.template.py common.tf.json
Creating common.tf.json
python dynamo.tf.json.template.py dynamo.tf.json
Creating dynamo.tf.json
python elasticsearch.tf.json.template.py elasticsearch.tf.json
python lambda_layer.tf.json.template.py lambda_layer.tf.json
Creating lambda_layer.tf.json
python s3.tf.json.template.py s3.tf.json
Creating s3.tf.json
python sqs.tf.json.template.py sqs.tf.json
Creating sqs.tf.json
python step_function.tf.json.template.py step_function.tf.json
[INFO]	2024-01-11T14:56:44.365Z	00010ca1-b0ba-466f-8c58-dabbad000000	botocore.credentials	Found credentials in shared credentials file: ~/.aws/credentials
Creating step_function.tf.json
terraform validate
Success! The configuration is valid.

python /Users/daniel/repo/azul2/scripts/rename_resource [...]

2024-01-16 17:34 UTC, hannes-ucsc submitted a review, later dismissed

2024-01-19 19:19 UTC, achave11-ucsc approved these changes

2024-01-19 21:24 UTC, hannes-ucsc approved these changes

2024-01-20 00:33 UTC, merged