Upgrade dependencies 2023-12-11 (#5772)
DataBiosphere/azul pull request #5795
Opened 2023-12-14 19:10 UTC by achave11-ucsc

Connected issue: #5772

## Checklist

### Author

- [ ] Target branch is `develop`
- [ ] Name of PR branch matches `gitlab/yyyy-mm-dd/<GitLab version>`
- [ ] PR title matches `Update GitLab to <GitLab version> (#4014)`
- [ ] Disconnected any other PRs currently connected to #4014 via ZenHub
- [ ] PR is connected to issue #4014 via ZenHub

### Author (deploy)

- [ ] Deployed changes to `dev.gitlab`
- [ ] Deployed changes to `anvildev.gitlab`
- [ ] Deployed changes to `anvilprod.gitlab`
- [ ] Deployed changes to `prod.gitlab`

### Primary reviewer (after approval)

- [ ] Verified background migrations for `dev.gitlab` are complete
- [ ] Verified background migrations for `anvildev.gitlab` are complete
- [ ] Verified background migrations for `anvilprod.gitlab` are complete
- [ ] Verified background migrations for `prod.gitlab` are complete
- [ ] Actually approved the PR
- [ ] Labeled connected issue as `no demo`
- [ ] Labeled PR as `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] Moved ticket to *Approved* column
- [ ] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [ ] Squashed PR branch and rebased onto `develop`
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Title of merge commit starts with title from this PR
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title <sub>but exclude any `p` tags</sub>
- [ ] Moved connected issue to Merged column in ZenHub
- [ ] Pushed merge commit to GitHub

### Operator (chain shortening)

- [ ] Changed the target branch of the blocked PR to `develop` <sub>or this PR is not labeled `base`</sub>
- [ ] Removed the `chained` label from the blocked PR <sub>or this PR is not labeled `base`</sub>
- [ ] Removed the blocking relationship from the blocked PR <sub>or this PR is not labeled `base`</sub>
- [ ] Removed the `base` label from this PR <sub>or this PR is not labeled `base`</sub>

### Operator (after pushing the merge commit)

- [ ] Deleted PR branch from GitHub

### Operator

- [ ] Unassigned PR

## Shorthand for review comments

- `L` line is too long
- `W` line wrapping is wrong
- `Q` bad quotes
- `F` other formatting problem

2023-12-15 23:11 UTC, achave11-ucsc commented
The checklist of upgrades issue, #5772 has been updated to reflect the changes introduced in this PR.

2023-12-16 00:39 UTC, dsotirho-ucsc submitted a review, later dismissed
Nit: My preference would be to use the standard PR template for these `upgrade dependencies` PRs, unless/until we create a new template specific for these upgrades. 

With that said, it appears the current PR checklist covers all the key items, so approved.

2023-12-16 06:12 UTC, hannes-ucsc requested changes
I think we should merge this PR before we merge my https://github.com/DataBiosphere/azul/pull/5806. One thing you should steal from that PR though is the "split" deployment of the `shared` component so that personal deployments don't break while this PR is being merged. Look for `apply_keep_unused` in `.github/PULL_REQUEST_TEMPLATE/upgrade.md`.

2023-12-16 06:12 UTC, hannes-ucsc commented on README.md
>  version listed in [environment.boot](environment.boot).
Please revert changes to this file. If we were to update it in every upgrade PR, the very sentence you're modifying here would be redundant.

2023-12-20 04:34 UTC, hannes-ucsc submitted a review, later dismissed

2023-12-20 05:47 UTC, achave11-ucsc commented
@hannes-ucsc, perhaps we could add the following patch, make it less of a 'figure it out' thing for deploying the GitLab component. That's because we're deploying from the feature branch, as the CL currently stands. Or this might be a new improvisations issue.

```
Subject: [PATCH] fixup! Fix: CL item for running IT in personal deployments missing from upgrade PR template
---
Index: .github/PULL_REQUEST_TEMPLATE/upgrade.md
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/.github/PULL_REQUEST_TEMPLATE/upgrade.md b/.github/PULL_REQUEST_TEMPLATE/upgrade.md
--- a/.github/PULL_REQUEST_TEMPLATE/upgrade.md	(revision 5bb85c1fc013d5303bb028e0b38b09ca389d791e)
+++ b/.github/PULL_REQUEST_TEMPLATE/upgrade.md	(date 1703050587410)
@@ -48,9 +48,9 @@
 - [ ] Squashed PR branch and rebased onto `develop`
 - [ ] Sanity-checked history
 - [ ] Pushed PR branch to GitHub
-- [ ] Selected `dev.gitlab` and ran `make -C terraform/gitlab apply` <sub>or this PR does not change the GitLab version</sub>
-- [ ] Selected `anvildev.gitlab` and ran `make -C terraform/gitlab apply` <sub>or this PR does not change the GitLab version</sub>
-- [ ] Selected `anvilprod.gitlab` and ran `make -C terraform/gitlab apply` <sub>or this PR does not change the GitLab version</sub>
+- [ ] Selected `CI_COMMIT_REF_NAME=develop dev.gitlab` and ran `make -C terraform/gitlab apply` <sub>or this PR does not change the GitLab version</sub>
+- [ ] Selected `CI_COMMIT_REF_NAME=develop anvildev.gitlab` and ran `make -C terraform/gitlab apply` <sub>or this PR does not change the GitLab version</sub>
+- [ ] Selected `CI_COMMIT_REF_NAME=develop anvilprod.gitlab` and ran `make -C terraform/gitlab apply` <sub>or this PR does not change the GitLab version</sub>
 - [ ] Assigned system administrator <sub>or this PR does not change the GitLab version</sub>
 - [ ] Checked the items in the next section <sub>or this PR changes the GitLab version</sub>
 
Index: .github/pull_request_template.md.template.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/.github/pull_request_template.md.template.py b/.github/pull_request_template.md.template.py
--- a/.github/pull_request_template.md.template.py	(revision 5bb85c1fc013d5303bb028e0b38b09ca389d791e)
+++ b/.github/pull_request_template.md.template.py	(date 1703050581046)
@@ -548,7 +548,8 @@
                 *[
                     {
                         'type': 'cli',
-                        'content': f'Selected `{deployment}.gitlab` and '
+                        'content': f'Selected `{"CI_COMMIT_REF_NAME=develop " if t == T.upgrade else ""}'
+                                   f'{deployment}.gitlab` and '
                                    f'ran `make -C terraform/gitlab apply`',
                         'alt': 'or this PR does not change the GitLab version'
                     }

```

2023-12-20 17:13 UTC, hannes-ucsc approved these changes

2023-12-20 17:22 UTC, merged

2023-12-20 20:39 UTC, achave11-ucsc commented
![Screen Shot 2023-12-20 at 12 38 44 PM](https://github.com/DataBiosphere/azul/assets/19215510/2fd39a98-cfc0-40f5-a6f3-4d6e7f858cdb)

2023-12-21 06:24 UTC, hannes-ucsc commented
@achave11-ucsc, skipping the sandbox builds after the `botocore-stubs` dependency bump  caused issues with the next PR.