Upgrade dependencies 2024-01-22 (#5876)
DataBiosphere/azul pull request #5897
Opened 2024-01-25 22:05 UTC by dsotirho-ucsc

Connected issue: #5876

## Checklist

### Author

- [x] Target branch is `develop`
- [x] Name of PR branch matches `upgrades/yyyy-mm-dd`
- [x] On ZenHub, PR is connected to the upgrade issue it resolves
- [x] PR title matches `Upgrade dependencies yyyy-mm-dd`
- [x] PR title references the connected issue

### Author (upgrading deployments)

- [ ] Added `upgrade` label to PR <sub>or this PR does not require upgrading deployments</sub>

### Author (before every review)

- [ ] Rebased PR branch on `develop`, squashed old fixups
- [ ] Ran `make requirements_update` <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [ ] Added `R` tag to commit title <sub>or this PR does not touch requirements*.txt</sub>
- [ ] Added `reqs` label to PR <sub>or this PR does not touch requirements*.txt</sub>
- [ ] Selected `dev.shared` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR does not change any Docker image versions</sub>
- [ ] Selected `anvildev.shared` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR does not change any Docker image versions</sub>
- [ ] Selected `anvilprod.shared` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR does not change any Docker image versions</sub>
- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>

### System administrator (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issue as `no demo`
- [ ] PR title is appropriate as title of merge commit
- [ ] Moved ticket to *Approved* column
- [ ] PR is assigned to current operator

### Operator (before pushing merge the commit)

- [ ] Squashed PR branch and rebased onto `develop`
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Selected `dev.gitlab` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR does not include any changes to files in terraform/gitlab</sub>
- [ ] Selected `anvildev.gitlab` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR does not include any changes to files in terraform/gitlab</sub>
- [ ] Selected `anvilprod.gitlab` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR does not include any changes to files in terraform/gitlab</sub>
- [ ] Assigned system administrator <sub>or this PR does not include any changes to files in terraform/gitlab</sub>
- [ ] Checked the items in the next section <sub>or this PR includes changes to files in terraform/gitlab</sub>

### System administrator

- [ ] Background migrations for `dev.gitlab` are complete <sub>or this PR does not include any changes to files in terraform/gitlab</sub>
- [ ] Background migrations for `anvildev.gitlab` are complete <sub>or this PR does not include any changes to files in terraform/gitlab</sub>
- [ ] Background migrations for `anvilprod.gitlab` are complete <sub>or this PR does not include any changes to files in terraform/gitlab</sub>
- [ ] PR is assigned to operator

### Operator (before pushing merge the commit)

- [ ] Selected `dev.gitlab` and ran `make -C terraform/gitlab/runner` <sub>or this PR does not change `azul_docker_version`</sub>
- [ ] Selected `anvildev.gitlab` and ran `make -C terraform/gitlab/runner` <sub>or this PR does not change `azul_docker_version`</sub>
- [ ] Selected `anvilprod.gitlab` and ran `make -C terraform/gitlab/runner` <sub>or this PR does not change `azul_docker_version`</sub>
- [ ] Added `sandbox` label
- [ ] Pushed PR branch to GitLab `dev`
- [ ] Pushed PR branch to GitLab `anvildev`
- [ ] Pushed PR branch to GitLab `anvilprod`
- [ ] Build passes in `sandbox` deployment
- [ ] Build passes in `anvilbox` deployment
- [ ] Build passes in `hammerbox` deployment
- [ ] Reviewed build logs for anomalies in `sandbox` deployment
- [ ] Reviewed build logs for anomalies in `anvilbox` deployment
- [ ] Reviewed build logs for anomalies in `hammerbox` deployment
- [ ] Title of merge commit starts with title from this PR
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title <sub>but exclude any `p` tags</sub>
- [ ] Moved connected issue to Merged column in ZenHub
- [ ] Pushed merge commit to GitHub

### Operator (after pushing the merge commit)

- [ ] Pushed merge commit to GitLab `dev`
- [ ] Pushed merge commit to GitLab `anvildev`
- [ ] Pushed merge commit to GitLab `anvilprod`
- [ ] Build passes on GitLab `dev`
- [ ] Reviewed build logs for anomalies on GitLab `dev`
- [ ] Build passes on GitLab `anvildev`
- [ ] Reviewed build logs for anomalies on GitLab `anvildev`
- [ ] Build passes on GitLab `anvilprod`
- [ ] Reviewed build logs for anomalies on GitLab `anvilprod`
- [ ] Selected `dev.shared` and ran `make -C terraform/shared apply` <sub>or this PR does not change any Docker image versions</sub>
- [ ] Selected `anvildev.shared` and ran `make -C terraform/shared apply` <sub>or this PR does not change any Docker image versions</sub>
- [ ] Selected `anvilprod.shared` and ran `make -C terraform/shared apply` <sub>or this PR does not change any Docker image versions</sub>
- [ ] Deleted PR branch from GitHub
- [ ] Deleted PR branch from GitLab `dev`
- [ ] Deleted PR branch from GitLab `anvildev`
- [ ] Deleted PR branch from GitLab `anvilprod`

### Operator

- [ ] Ran `script/export_inspector_findings.py` against `anvilprod`, imported results to [Google Sheet](https://docs.google.com/spreadsheets/d/1RWF7g5wRKWPGovLw4jpJGX_XMi8aWLXLOvvE5rxqgH8) and posted screenshot of relevant<sup>1</sup> findings as a comment on the connected issue.
- [ ] PR is assigned to system administrator

<sup>1</sup>A relevant finding is a high or critical vulnerability in an image
that is used within the security boundary. Images not used within the boundary
are tracked in `azul.docker_images` under a key starting with `_`.

### System administrator

- [ ] No currently reported vulnerability requires immediate attention
- [ ] PR is assigned to no one

## Shorthand for review comments

- `L` line is too long
- `W` line wrapping is wrong
- `Q` bad quotes
- `F` other formatting problem

2024-01-26 20:37 UTC, dsotirho-ucsc commented
Run a test:
- disable docker
- deploy & run integration_test in personal deployment
- if successful, move `shared (apply_keep_unused)` checkboxes just before deploy `gitlab` checkboxes & file a ticket to update PR template.

2024-01-29 18:56 UTC, dsotirho-ucsc commented
> Run a test:
> 
> * disable docker
> * deploy & run integration_test in personal deployment
> * if successful, move `shared (apply_keep_unused)` checkboxes just before deploy `gitlab` checkboxes & file a ticket to update PR template.

Test was successful.
```
(.venv) daniel@Crispin ~/repo/azul2 $ git s
On branch upgrades/2024-01-22
Your branch is up to date with 'github/upgrades/2024-01-22'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.terraform-version

nothing added to commit but untracked files present (use "git add" to track)
(.venv) daniel@Crispin ~/repo/azul2 $
(.venv) daniel@Crispin ~/repo/azul2 $ make deploy
/Library/Developer/CommandLineTools/usr/bin/make -C lambdas
/Library/Developer/CommandLineTools/usr/bin/make -C layer layer
python /Users/daniel/repo/azul2/scripts/check_branch.py
python .chalice/config.json.template.py .chalice/config.json
Creating .chalice/config.json
python /Users/daniel/repo/azul2/scripts/stage_layer.py
2024-01-29 10:09:41,042    INFO MainThread botocore.credentials: Found credentials in shared credentials file: ~/.aws/credentials
2024-01-29 10:09:41,583    INFO MainThread azul.lambda_layer: Checking for dependencies layer package at s3://edu-ucsc-gi-platform-hca-dev-shared.us-east-1/azul/daniel/lambda_layers/e43d09c184c6d18ddb69a0eaf56a9986846c406f.zip.
…
Plan: 8 to add, 11 to change, 39 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_api_gateway_base_path_mapping.service_1: Destroying... [id=drs.daniel.dev.singlecell.gi.ucsc.edu/]
aws_api_gateway_method_settings.service_0: Destroying... [id=071n66awdf-daniel-*/*]
aws_cloudwatch_metric_alarm.service_throttles: Destroying... [id=azul-service_throttles-daniel.alarm]
…
Apply complete! Resources: 8 added, 11 changed, 39 destroyed.
python /Users/daniel/repo/azul2/scripts/post_deploy_tdr.py
2024-01-29 10:16:22,364    INFO MainThread botocore.credentials: Found credentials in shared credentials file: ~/.aws/credentials
2024-01-29 10:16:23,038    INFO MainThread azul.terra: Making POST request to 'https://sam.dsde-dev.broadinstitute.org/register/user/v1'
2024-01-29 10:16:23,038   DEBUG MainThread azul.terra: … with request body ''
…

(.venv) daniel@Crispin ~/repo/azul2 $ 
(.venv) daniel@Crispin ~/repo/azul2 $ docker ps
Cannot connect to the Docker daemon at unix:///Users/daniel/.docker/run/docker.sock. Is the docker daemon running?
(.venv) daniel@Crispin ~/repo/azul2 $ 
(.venv) daniel@Crispin ~/repo/azul2 $ make integration_test
python /Users/daniel/repo/azul2/scripts/check_branch.py
python /Users/daniel/repo/azul2/lambdas/service/.chalice/config.json.template.py /Users/daniel/repo/azul2/lambdas/service/.chalice/config.json
[INFO]	2024-01-29T10:27:54.458Z	00010ca1-b0ba-466f-8c58-dabbad000000	botocore.credentials	Found credentials in shared credentials file: ~/.aws/credentials
Creating /Users/daniel/repo/azul2/lambdas/service/.chalice/config.json
python -m unittest -v integration_test
2024-01-29 10:27:56,616    INFO MainThread botocore.credentials: Found credentials in shared credentials file: ~/.aws/credentials
2024-01-29 10:27:57,178   DEBUG MainThread azul.es: Creating ES client [vpc-azul-index-sandbox-mcwjphhhdivigzrsrdmxm2uude.us-east-1.es.amazonaws.com:443]
2024-01-29 10:27:57,221    INFO MainThread botocore.credentials: Found credentials in environment variables.
…
2024-01-29 10:45:32,979   DEBUG MainThread test.integration_test: … with response body b'{"message":"Forbidden"}'
2024-01-29 10:45:32,979    INFO MainThread test.integration_test: Making GET request to 'https://indexer.daniel.dev.singlecell.gi.ucsc.edu/static/..%2Fdoes-not-exist'
2024-01-29 10:45:32,979   DEBUG MainThread test.integration_test: … without request body
2024-01-29 10:45:33,184    INFO MainThread test.integration_test: Got 403 response after 0.204s from GET to https://indexer.daniel.dev.singlecell.gi.ucsc.edu/static/..%2Fdoes-not-exist
2024-01-29 10:45:33,184   DEBUG MainThread test.integration_test: … with response headers HTTPHeaderDict({'Content-Type': 'application/json', 'Content-Length': '23', 'Connection': 'keep-alive', 'Date': 'Mon, 29 Jan 2024 18:45:33 GMT', 'x-amzn-RequestId': '90be3a7f-6742-40fb-b8c8-ad880b61166b', 'x-amzn-ErrorType': 'ForbiddenException', 'x-amz-apigw-id': 'SULMHGfVoAMEclQ=', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 e61b74b41588d9216f1bb35848394554.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'SFO20-C1', 'X-Amz-Cf-Id': 'MfNQFHfw2hXRkOotBAPcHVumo2apx8eEGyAfOFsxUmjJggNioLfaQA=='})
2024-01-29 10:45:33,184   DEBUG MainThread test.integration_test: … with response body b'{"message":"Forbidden"}'
ok

----------------------------------------------------------------------
Ran 15 tests in 1056.592s

OK (skipped=3)
(.venv) daniel@Crispin ~/repo/azul2 $
```

2024-01-29 22:33 UTC, dsotirho-ucsc commented
[5897_IT_2024-01-29.txt](https://github.com/DataBiosphere/azul/files/14090388/5897_IT_2024-01-29.txt)

2024-01-29 23:23 UTC, dsotirho-ucsc commented
[5897_integration-test_2024-01-29.txt](https://github.com/DataBiosphere/azul/files/14090834/5897_integration-test_2024-01-29.txt)

2024-01-29 23:55 UTC, hannes-ucsc requested changes
There's an unchecked item in the CL in the issue.

2024-01-30 01:00 UTC, dsotirho-ucsc commented
[5897_integration-test_2024-01-29.txt](https://github.com/DataBiosphere/azul/files/14091526/5897_integration-test_2024-01-29.txt)

2024-01-30 01:37 UTC, hannes-ucsc approved these changes

2024-01-30 01:37 UTC, hannes-ucsc commented on UPGRADING.rst
> +the merge commit to the GitLab instance in that deployment.
The second sentence is in the wrong commit.

2024-01-30 01:38 UTC, hannes-ucsc requested changes
The previous review should have requested changes.

2024-01-30 01:40 UTC, hannes-ucsc commented
Please set tfenv version with environment variables so you can have a different version per deployment and don't have a working copy that's permanently dirtied by a file called `.terraform-version`.

2024-01-30 02:09 UTC, hannes-ucsc submitted a review, later dismissed
I think I can live with the wrong commit structure.

2024-01-31 21:21 UTC, hannes-ucsc approved these changes

2024-01-31 21:29 UTC, merged

2024-02-01 01:28 UTC, dsotirho-ucsc commented
https://docs.google.com/spreadsheets/d/1RWF7g5wRKWPGovLw4jpJGX_XMi8aWLXLOvvE5rxqgH8/edit#gid=1432851400

![Screenshot 2024-01-31 at 5 26 40 PM](https://github.com/DataBiosphere/azul/assets/46407464/cef7400b-d96a-4f50-ab81-f06feb95862e)

2024-02-01 19:01 UTC, hannes-ucsc commented
CVE-2018-12976: From https://groups.google.com/g/golang-announce/c/4rpTbfzYB1k/m/no6MEwlQAwAJ

> [godoc.org](http://godoc.org/) is patched, and this only affects you if you run your own instance of gddo.

While the vulnerable version of the `gddo` module is included in the `dockerd` binary (it is [vendored](https://github.com/moby/moby/blob/master/vendor.mod#L47)), and dockerd is running as a daemon, it does not represent an instance of `gddo`, and is therefore not vulnerable, according to the above announcement.

2024-02-01 19:17 UTC, hannes-ucsc commented
Please post screenshot to issue, not PR. See CL item.