Upgrade dependencies 2024-02-19 (#5970)
DataBiosphere/azul pull request #5996
Opened 2024-02-28 01:28 UTC by dsotirho-ucsc

Connected issue: #5970

## Checklist

### Author

- [x] Target branch is `develop`
- [x] Name of PR branch matches `upgrades/yyyy-mm-dd`
- [x] On ZenHub, PR is connected to the upgrade issue it resolves
- [x] PR title matches `Upgrade dependencies yyyy-mm-dd`
- [x ] PR title references the connected issue

### Author (upgrading deployments)

- [ ] Ran `make image_manifests.json` and committed any resulting changes <sub>or this PR does not modify `azul_docker_images` or any other variables referenced in the definition of that variable</sub>
- [ ] Documented upgrading of deployments in UPGRADING.rst <sub>or this PR does not require upgrading deployments</sub>
- [ ] Added `u` tag to commit title <sub>or this PR does not require upgrading deployments</sub>
- [ ] Added `upgrade` label to PR <sub>or this PR does not require upgrading deployments</sub>

### Author (before every review)

- [ ] Rebased PR branch on `develop`, squashed old fixups
- [ ] Ran `make requirements_update` <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [ ] Added `R` tag to commit title <sub>or this PR does not touch requirements*.txt</sub>
- [ ] Added `reqs` label to PR <sub>or this PR does not touch requirements*.txt</sub>
- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>

### System administrator (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issue as `no demo`
- [ ] PR title is appropriate as title of merge commit
- [ ] Moved ticket to *Approved* column
- [ ] PR is assigned to current operator

### Operator (before pushing merge the commit)

- [ ] Squashed PR branch and rebased onto `develop`
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Selected `dev.shared` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR does not change any Docker image versions</sub>
- [ ] Selected `dev.gitlab` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR does not include any changes to files in terraform/gitlab</sub>
- [ ] Selected `anvildev.shared` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR does not change any Docker image versions</sub>
- [ ] Selected `anvildev.gitlab` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR does not include any changes to files in terraform/gitlab</sub>
- [ ] Selected `anvilprod.shared` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR does not change any Docker image versions</sub>
- [ ] Selected `anvilprod.gitlab` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR does not include any changes to files in terraform/gitlab</sub>
- [ ] Assigned system administrator <sub>or this PR does not include any changes to files in terraform/gitlab</sub>
- [ ] Checked the items in the next section <sub>or this PR includes changes to files in terraform/gitlab</sub>

### System administrator

- [ ] Background migrations for `dev.gitlab` are complete <sub>or this PR does not include any changes to files in terraform/gitlab</sub>
- [ ] Background migrations for `anvildev.gitlab` are complete <sub>or this PR does not include any changes to files in terraform/gitlab</sub>
- [ ] Background migrations for `anvilprod.gitlab` are complete <sub>or this PR does not include any changes to files in terraform/gitlab</sub>
- [ ] PR is assigned to operator

### Operator (before pushing merge the commit)

- [ ] Selected `dev.gitlab` and ran `make -C terraform/gitlab/runner` <sub>or this PR does not change `azul_docker_version`</sub>
- [ ] Selected `anvildev.gitlab` and ran `make -C terraform/gitlab/runner` <sub>or this PR does not change `azul_docker_version`</sub>
- [ ] Selected `anvilprod.gitlab` and ran `make -C terraform/gitlab/runner` <sub>or this PR does not change `azul_docker_version`</sub>
- [ ] Added `sandbox` label
- [ ] Pushed PR branch to GitLab `dev`
- [ ] Pushed PR branch to GitLab `anvildev`
- [ ] Pushed PR branch to GitLab `anvilprod`
- [ ] Build passes in `sandbox` deployment
- [ ] Build passes in `anvilbox` deployment
- [ ] Build passes in `hammerbox` deployment
- [ ] Reviewed build logs for anomalies in `sandbox` deployment
- [ ] Reviewed build logs for anomalies in `anvilbox` deployment
- [ ] Reviewed build logs for anomalies in `hammerbox` deployment
- [ ] Title of merge commit starts with title from this PR
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title <sub>but exclude any `p` tags</sub>
- [ ] Moved connected issue to Merged column in ZenHub
- [ ] Pushed merge commit to GitHub

### Operator (after pushing the merge commit)

- [ ] Pushed merge commit to GitLab `dev`
- [ ] Pushed merge commit to GitLab `anvildev`
- [ ] Pushed merge commit to GitLab `anvilprod`
- [ ] Build passes on GitLab `dev`
- [ ] Reviewed build logs for anomalies on GitLab `dev`
- [ ] Build passes on GitLab `anvildev`
- [ ] Reviewed build logs for anomalies on GitLab `anvildev`
- [ ] Build passes on GitLab `anvilprod`
- [ ] Reviewed build logs for anomalies on GitLab `anvilprod`
- [ ] Selected `dev.shared` and ran `make -C terraform/shared apply` <sub>or this PR does not change any Docker image versions</sub>
- [ ] Selected `anvildev.shared` and ran `make -C terraform/shared apply` <sub>or this PR does not change any Docker image versions</sub>
- [ ] Selected `anvilprod.shared` and ran `make -C terraform/shared apply` <sub>or this PR does not change any Docker image versions</sub>
- [ ] Deleted PR branch from GitHub
- [ ] Deleted PR branch from GitLab `dev`
- [ ] Deleted PR branch from GitLab `anvildev`
- [ ] Deleted PR branch from GitLab `anvilprod`

### Operator

- [ ] Ran `script/export_inspector_findings.py` against `anvilprod`, imported results to [Google Sheet](https://docs.google.com/spreadsheets/d/1RWF7g5wRKWPGovLw4jpJGX_XMi8aWLXLOvvE5rxqgH8) and posted screenshot of relevant<sup>1</sup> findings as a comment on the connected issue.
- [ ] PR is assigned to system administrator

<sup>1</sup>A relevant finding is a high or critical vulnerability in an image
that is used within the security boundary. Images not used within the boundary
are tracked in `azul.docker_images` under a key starting with `_`.

### System administrator

- [ ] No currently reported vulnerability requires immediate attention
- [ ] PR is assigned to no one

## Shorthand for review comments

- `L` line is too long
- `W` line wrapping is wrong
- `Q` bad quotes
- `F` other formatting problem

2024-02-28 23:22 UTC, dsotirho-ucsc commented
[5996_IT_2024-02-28.txt](https://github.com/DataBiosphere/azul/files/14440863/5996_IT_2024-02-28.txt)

2024-03-01 00:32 UTC, hannes-ucsc requested changes
Please update the PR checklist to the one from the recently updated template.

2024-03-01 07:29 UTC, hannes-ucsc reviewed
Conflicts.

2024-03-01 20:10 UTC, dsotirho-ucsc commented
[5996_IT_2024-03-01.txt](https://github.com/DataBiosphere/azul/files/14465502/5996_IT_2024-03-01.txt)

2024-03-02 00:04 UTC, hannes-ucsc approved these changes, later dismissed

2024-03-02 00:04 UTC, hannes-ucsc commented on UPGRADING.rst
> +the merge commit to the GitLab instance in that deployment.
The checklist changes make this unnecessary.

2024-03-02 00:05 UTC, hannes-ucsc commented
### Security design review

- [x] Security design review completed; this PR does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with Terra 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

2024-03-02 19:30 UTC, hannes-ucsc commented
https://github.com/DataBiosphere/azul/issues/4890 has occurred on `anvildev.gitlab`. Please apply the workaround. Remember to check whether GitLab is functional after deploying it.

2024-03-04 17:58 UTC, hannes-ucsc approved these changes

2024-03-04 22:36 UTC, merged