Parameterize reindex job in GitLab with catalog to reindex (#5336)
DataBiosphere/azul pull request #6000
Opened 2024-02-28 18:44 UTC by achave11-ucsc

Connected issues: #5336

## Checklist

### Author

- [ ] PR is a draft
- [ ] Target branch is `develop`
- [ ] Name of PR branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [ ] On ZenHub, PR is connected to all issues it (partially) resolves
- [ ] PR description links to connected issues
- [ ] PR title matches<sup>1</sup> that of a connected issue <sub>or comment in PR explains why they're different</sub>
- [ ] PR title references all connected issues
- [ ] For each connected issue, there is at least one commit whose title references that issue

### Author (partiality)

- [ ] Added `p` tag to titles of partial commits
- [ ] Added `partial` label to PR <sub>or this PR completely resolves all connected issues</sub>
- [ ] All connected issues are resolved partially <sub>or this PR does not have the `partial` label</sub>

<sup>1</sup> when the issue title describes a problem, the corresponding PR
title is `Fix: ` followed by the issue title

### Author (reindex, API changes)

- [ ] Added `r` tag to commit title <sub>or this PR does not require reindexing</sub>
- [ ] Added `reindex` label to PR <sub>or this PR does not require reindexing</sub>
- [ ] PR and connected issue are labeled `API` <sub>or this PR does not modify a REST API</sub>
- [ ] Added `a` (`A`) tag to commit title for backwards (in)compatible changes <sub>or this PR does not modify a REST API</sub>
- [ ] Updated REST API version number in `app.py` <sub>or this PR does not modify a REST API</sub>

### Author (chains)

- [ ] This PR is blocked by previous PR in the chain <sub>or this PR is not chained to another PR</sub>
- [ ] Added `base` label to the blocking PR <sub>or this PR is not chained to another PR</sub>
- [ ] Added `chained` label to this PR <sub>or this PR is not chained to another PR</sub>

### Author (upgrading deployments)

- [ ] Ran `make image_manifests.json` and committed any resulting changes <sub>or this PR does not modify `azul_docker_images` or any other variables referenced in the definition of that variable</sub>
- [ ] Documented upgrading of deployments in UPGRADING.rst <sub>or this PR does not require upgrading deployments</sub>
- [ ] Added `u` tag to commit title <sub>or this PR does not require upgrading deployments</sub>
- [ ] Added `upgrade` label to PR <sub>or this PR does not require upgrading deployments</sub>

### Author (operator tasks)

- [ ] Added checklist items for additional operator tasks <sub>or this PR does not require additional tasks</sub>

### Author (hotfixes)

- [ ] Added `F` tag to main commit title <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [ ] Reverted the temporary hotfixes for any connected issues <sub>or the `prod` branch has no temporary hotfixes for any connected issues</sub>

### Author (before every review)

- [ ] Rebased PR branch on `develop`, squashed old fixups
- [ ] Ran `make requirements_update` <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [ ] Added `R` tag to commit title <sub>or this PR does not touch requirements*.txt</sub>
- [ ] Added `reqs` label to PR <sub>or this PR does not touch requirements*.txt</sub>
- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>

### Peer reviewer (after requesting changes)

Uncheck the *Author (before every review)* checklists.

### Peer reviewer (after approval)

- [ ] PR is not a draft
- [ ] Ticket is in *Review requested* column
- [ ] Requested review from system administrator
- [ ] PR is assigned to system administrator

### System administrator (after requesting changes)

Uncheck the *before every review* checklists. Update the `N reviews` label.

### System administrator (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issues as `demo` or `no demo`
- [ ] Commented on connected issues about demo expectations <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] PR title is appropriate as title of merge commit
- [ ] `N reviews` label is accurate
- [ ] Moved ticket to *Approved* column
- [ ] PR is assigned to current operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear <sub>or all connected issues are labeled `no demo`</sub>
- [ ] PR has checklist items for upgrading instructions <sub>or PR is not labeled `upgrade`</sub>
- [ ] Squashed PR branch and rebased onto `develop`
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Added `sandbox` label <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `dev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvilprod` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `hammerbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `hammerbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted unreferenced indices in `sandbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices in `dev`</sub>
- [ ] Deleted unreferenced indices in `anvilbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices in `anvildev`</sub>
- [ ] Deleted unreferenced indices in `hammerbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices in `anvilprod`</sub>
- [ ] Started reindex in `sandbox` <sub>or this PR does not require reindexing `dev`</sub>
- [ ] Started reindex in `anvilbox` <sub>or this PR does not require reindexing `anvildev`</sub>
- [ ] Started reindex in `hammerbox` <sub>or this PR does not require reindexing `anvilprod`</sub>
- [ ] Checked for failures in `sandbox` <sub>or this PR does not require reindexing `dev`</sub>
- [ ] Checked for failures in `anvilbox` <sub>or this PR does not require reindexing `anvildev`</sub>
- [ ] Checked for failures in `hammerbox` <sub>or this PR does not require reindexing `anvilprod`</sub>
- [ ] Title of merge commit starts with title from this PR
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title <sub>but only include `p` if the PR is labeled `partial`</sub>
- [ ] Moved connected issues to Merged column in ZenHub
- [ ] Pushed merge commit to GitHub

### Operator (chain shortening)

- [ ] Changed the target branch of the blocked PR to `develop` <sub>or this PR is not labeled `base`</sub>
- [ ] Removed the `chained` label from the blocked PR <sub>or this PR is not labeled `base`</sub>
- [ ] Removed the blocking relationship from the blocked PR <sub>or this PR is not labeled `base`</sub>
- [ ] Removed the `base` label from this PR <sub>or this PR is not labeled `base`</sub>

### Operator (after pushing the merge commit)

- [ ] Pushed merge commit to GitLab `dev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed merge commit to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed merge commit to GitLab `anvilprod` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes on GitLab `dev`<sup>1</sup>
- [ ] Reviewed build logs for anomalies on GitLab `dev`<sup>1</sup>
- [ ] Build passes on GitLab `anvildev`<sup>1</sup>
- [ ] Reviewed build logs for anomalies on GitLab `anvildev`<sup>1</sup>
- [ ] Build passes on GitLab `anvilprod`<sup>1</sup>
- [ ] Reviewed build logs for anomalies on GitLab `anvilprod`<sup>1</sup>
- [ ]  [...]

2024-02-28 22:03 UTC, achave11-ucsc commented
Catalog specific re-index succeeded in `sandbox` build, https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/87300.

A single catalog was indexed in job.

Comparing the last `sandbox` re-index, all catalogs in `sandbox` would have been indexed if this changes were invalid.
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/86803

2024-02-29 17:49 UTC, dsotirho-ucsc requested changes
The description in the operator guide implies more than one catalog can be specified for reindex. This should be clarified a bit since only one catalog can be set to the `azul_current_catalog` variable at a time.

![Screenshot 2024-02-29 at 9 49 14 AM](https://github.com/DataBiosphere/azul/assets/46407464/a0d390f4-01fa-4670-9cf8-eb87c28050c5)

2024-02-29 17:49 UTC, dsotirho-ucsc commented on OPERATOR.rst
> +reindexing of any targeted catalog/s. From there, you should see an option for
```suggestion
reindexing of a targeted catalog. From there, you should see an option for
```

2024-02-29 17:49 UTC, dsotirho-ucsc commented on OPERATOR.rst
> +index, for example, if we want to only index ``dcp3``, then set ``Value=dcp3``.
```suggestion
Set ``Key`` to ``azul_current_catalog``, and ``Value`` to the desired catalog to be
indexed, for example, ``dcp3``.
```

2024-02-29 17:49 UTC, dsotirho-ucsc commented on OPERATOR.rst
> +
```suggestion

Repeat these steps to index any additional catalogs.
```

2024-02-29 20:01 UTC, dsotirho-ucsc requested changes

2024-02-29 20:01 UTC, dsotirho-ucsc commented on OPERATOR.rst
> +indexed, for example, ``dcp3``. Once you've confirm this is the desired
```suggestion
Set ``Key`` to ``azul_current_catalog``, and ``Value`` to the desired catalog to
be indexed, for example, ``dcp3``. Once you've confirm this is the desired

```

2024-02-29 20:01 UTC, dsotirho-ucsc commented on OPERATOR.rst
> +indexed, for example, ``dcp3``. Once you've confirm this is the desired
Sorry, my previous suggestion wasn't properly formatted for an 80 character line.

2024-02-29 22:16 UTC, dsotirho-ucsc approved these changes, later dismissed
Approved.

2024-03-01 01:11 UTC, hannes-ucsc requested changes

2024-03-01 01:11 UTC, hannes-ucsc commented on OPERATOR.rst
> +Repeat these steps to index any additional catalogs.
```suggestion
From the GitLab web app, select the ``reindex`` job for the pipeline that needs
reindexing of a specific catalog. From there, you should see an option for
defining the key and value of additional variables to parameterize the job with.

Set ``Key`` to ``azul_current_catalog``, and ``Value`` to the name of the catalog
to be reindexed, for example, ``dcp3``. Check the inputs you just made. Start the ``reindex`` job by clicking on ``Run job``. Wait until the job has completed.

Repeat these steps to reindex any additional catalogs.
```

2024-03-01 01:11 UTC, hannes-ucsc commented on OPERATOR.rst
> +Repeat these steps to index any additional catalogs.
We should also add a note that this applies to the `reindex_early` job as well.

2024-03-02 00:15 UTC, hannes-ucsc approved these changes

2024-03-05 23:05 UTC, merged