Fix: test_replica_update fails in prod (#6062)
DataBiosphere/azul pull request #6080
Opened 2024-03-21 01:16 UTC by nadove-ucsc

Connected issues: #6062

## Checklist

### Author

- [x] PR is a draft
- [x] Target branch is `develop`
- [x] Name of PR branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [ ] On ZenHub, PR is connected to all issues it (partially) resolves
- [x] PR description links to connected issues
- [x] PR title matches<sup>1</sup> that of a connected issue <sub>or comment in PR explains why they're different</sub>
- [x] PR title references all connected issues
- [x] For each connected issue, there is at least one commit whose title references that issue

### Author (partiality)

- [x] Added `p` tag to titles of partial commits
- [x] This PR is labeled `partial` <sub>or completely resolves all connected issues</sub>
- [x] This PR partially resolves each of the connected issues <sub>or does not have the `partial` label</sub>

<sup>1</sup> when the issue title describes a problem, the corresponding PR
title is `Fix: ` followed by the issue title

### Author (chains)

- [x] This PR is blocked by previous PR in the chain <sub>or is not chained to another PR</sub>
- [x] The blocking PR is labeled `base` <sub>or this PR is not chained to another PR</sub>
- [x] This PR is labeled `chained` <sub>or is not chained to another PR</sub>

### Author (reindex, API changes)

- [x] Added `r` tag to commit title <sub>or this PR does not require reindexing</sub>
- [x] This PR is labeled `reindex:dev` <sub>or does not require reindexing `dev`</sub>
- [x] This PR is labeled `reindex:anvildev` <sub>or does not require reindexing `anvildev`</sub>
- [x] This PR is labeled `reindex:anvilprod` <sub>or does not require reindexing `anvilprod`</sub>
- [x] This PR is labeled `reindex:partial` and its description documents the specific reindexing procedure for `dev`, `anvildev`, `anvilprod` and `prod` <sub>or requires a full reindex or carries none of the labels `reindex:dev`, `reindex:anvildev`, `reindex:anvilprod` and `reindex:prod`</sub>
- [x] This PR and its connected issues are labeled `API` <sub>or this PR does not modify a REST API</sub>
- [x] Added `a` (`A`) tag to commit title for backwards (in)compatible changes <sub>or this PR does not modify a REST API</sub>
- [x] Updated REST API version number in `app.py` <sub>or this PR does not modify a REST API</sub>

### Author (upgrading deployments)

- [x] Documented upgrading of deployments in UPGRADING.rst <sub>or this PR does not require upgrading deployments</sub>
- [x] Added `u` tag to commit title <sub>or this PR does not require upgrading deployments</sub>
- [x] Ran `make image_manifests.json` and committed the resulting changes <sub>or this PR does not modify `azul_docker_images`, or any other variables referenced in the definition of that variable</sub>
- [x] This PR is labeled `upgrade` <sub>or does not require upgrading deployments</sub>
- [x] This PR is labeled `deploy:shared` <sub>or does not modify `image_manifests.json`, and does not require deploying the `shared` component for any other reason</sub>
- [x] This PR is labeled `deploy:gitlab` <sub>or does not require deploying the `gitlab` component</sub>
- [x] This PR is labeled `deploy:runner` <sub>or does not require deploying the `runner` image</sub>

### Author (operator tasks)

- [x] Added checklist items for additional operator tasks <sub>or this PR does not require additional tasks</sub>

### Author (hotfixes)

- [x] Added `F` tag to main commit title <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [x] Reverted the temporary hotfixes for any connected issues <sub>or the `prod` branch has no temporary hotfixes for any connected issues</sub>

### Author (before every review)

- [x] Rebased PR branch on `develop`, squashed old fixups
- [x] Ran `make requirements_update` <sub>or this PR does not modify `requirements*.txt`, `common.mk`, `Makefile` and `Dockerfile`</sub>
- [x] Added `R` tag to commit title <sub>or this PR does not modify `requirements*.txt`</sub>
- [x] This PR is labeled `reqs` <sub>or does not modify `requirements*.txt`</sub>
- [x] `make integration_test` passes in personal deployment <sub>or this PR does not modify functionality that could affect the IT outcome</sub>

### Peer reviewer (after requesting changes)

Uncheck the *Author (before every review)* checklists.

### Peer reviewer (after approval)

- [ ] PR is not a draft
- [ ] Ticket is in *Review requested* column
- [ ] Requested review from system administrator
- [ ] PR is assigned to only the system administrator

### System administrator (after requesting changes)

Uncheck the *before every review* checklists. Update the `N reviews` label.

### System administrator (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issues as `demo` or `no demo`
- [ ] Commented on connected issues about demo expectations <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] A comment to this PR details the completed security design review <sub>or this PR is a promotion or a backport</sub>
- [ ] PR title is appropriate as title of merge commit
- [ ] `N reviews` label is accurate
- [ ] Moved ticket to *Approved* column
- [ ] PR is assigned to only the operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex:…` labels and `r` commit title tag
- [ ] Checked that demo expectations are clear <sub>or all connected issues are labeled `no demo`</sub>
- [ ] PR has checklist items for upgrading instructions <sub>or PR is not labeled `upgrade`</sub>
- [ ] Squashed PR branch and rebased onto `develop`
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Ran `_select dev.shared && CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR is not labeled `deploy:shared`</sub>
- [ ] Ran `_select dev.gitlab && CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] Ran `_select anvildev.shared && CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR is not labeled `deploy:shared`</sub>
- [ ] Ran `_select anvildev.gitlab && CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] Ran `_select anvilprod.shared && CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR is not labeled `deploy:shared`</sub>
- [ ] Ran `_select anvilprod.gitlab && CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] Checked the items in the next section <sub>or this PR is labeled `deploy:gitlab`</sub>
- [ ] Assigned system administrator <sub>or this PR is not labeled `deploy:gitlab`</sub>

### System administrator

- [ ] Background migrations for `dev.gitlab` are complete <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] Background migrations for `anvildev.gitlab` are complete <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] Background migrations for `anvilprod.gitlab` are complete <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] PR is assigned to only the operator

### Operator (before pushing merge the commit)

- [ ] Ran `_select dev.gitlab && make -C terraform/gitlab/runner` <sub>or this PR is not labeled `deploy:runner`</sub>
- [ ] Ran `_select anvildev.gitlab && make -C terraform/gitlab/runner` <sub>or this PR is not labeled `deploy:runner`</sub>
- [ ] Ran `_select anvilprod.gitlab && make -C terraform/gitlab/runner` <sub>or this PR is not labeled `deploy:runner`</sub>
- [ ] Added `sandbox` label <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `dev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvilprod` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build pas [...]

2024-03-25 18:29 UTC, dsotirho-ucsc approved these changes, later dismissed
Approved

2024-03-25 23:23 UTC, hannes-ucsc requested changes
Please remove the `skipIf` and provide a test fixture that fixes `config.enable_replicas` to `True`. Remove all other usages of `skipIf` and `skipUnless` that use this config property.

There are tests that would benefit (in terms of code coverage) from covering the two possible values for that fixture. Identify those tests and either modify the tests to loop over the two values or add a FIXME referring to a newly created issue. 

The goal is to maximize coverage and to desensitize tests to configuration.

2024-05-08 00:55 UTC, nadove-ucsc commented
> There are tests that would benefit (in terms of code coverage) from covering the two possible values for that fixture. Identify those tests and either modify the tests to loop over the two values or add a FIXME referring to a newly created issue.

I am having difficulty identifying such a test. We already cover both pathways in `TestDCP1Indexer.test_indexing` and I can't find any areas of the code that 1. are effected by this fixture and 2. are not covered either by that test or an existing manifest test.

2024-05-08 01:38 UTC, hannes-ucsc requested changes

2024-05-08 01:38 UTC, hannes-ucsc commented on test/service/test_manifest.py
> +        super().tearDownClass()
We recently started doing this differently. Look for `addClassPatch`.

2024-05-08 01:38 UTC, hannes-ucsc commented on test/service/test_manifest.py
> +class ReplicaBasedManifestTestCase(ManifestTestCase, metaclass=ABCMeta):
I think we can provide this fixture at a higher level in the class hierarchy, in an existing `…TestCase` class without complicating the class hierarchy with this mixin.

2024-05-08 01:38 UTC, hannes-ucsc commented
> > There are tests that would benefit (in terms of code coverage) from covering the two possible values for that fixture. Identify those tests and either modify the tests to loop over the two values or add a FIXME referring to a newly created issue.
> 
> I am having difficulty identifying such a test. We already cover both pathways in `TestDCP1Indexer.test_indexing` and I can't find any areas of the code that 1. are effected by this fixture and 2. are not covered either by that test or an existing manifest test.

Sounds good.

2024-05-10 01:32 UTC, hannes-ucsc requested changes
This as a separate commit, please:

```diff
Index: test/indexer/test_indexer.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/indexer/test_indexer.py b/test/indexer/test_indexer.py
--- a/test/indexer/test_indexer.py	(revision e7c137cda692a08a5ccc84417c9fa21bd0c795ca)
+++ b/test/indexer/test_indexer.py	(date 1715303995980)
@@ -207,60 +207,66 @@
         for max_partition_size in [BundlePartition.max_partition_size, 1]:
             for page_size in (config.contribution_page_size, 1):
                 for enable_replicas in True, False:
-                    with self.subTest(page_size=page_size,
-                                      max_partition_size=max_partition_size,
-                                      enable_replicas=enable_replicas):
-                        with patch.object(target=type(config),
-                                          attribute='enable_replicas',
-                                          new_callable=PropertyMock,
-                                          return_value=enable_replicas):
-                            with patch.object(BundlePartition, 'max_partition_size', new=max_partition_size):
-                                with patch.object(type(config), 'contribution_page_size', new=page_size):
-                                    self.index_service.create_indices(self.catalog)
-                                    try:
-                                        self._index_bundle(bundle, delete=False)
-                                        hits = self._get_all_hits()
-                                        if enable_replicas:
-                                            expected_hits = canned_hits
-                                        else:
-                                            expected_hits = [
-                                                h
-                                                for h in canned_hits
-                                                if self._parse_index_name(h)[1] is not DocumentType.replica
-                                            ]
-                                        self.assertElasticEqual(expected_hits, hits)
-                                        contributions = []
-                                        replicas = []
-                                        for hit in hits:
-                                            qualifier, doc_type = self._parse_index_name(hit)
-                                            if doc_type is DocumentType.replica:
-                                                entity_id = ReplicaCoordinates.from_hit(hit).entity.entity_id
-                                                replicas.append(entity_id)
-                                                if entity_id == bundle.uuid:
-                                                    expected = bundle.metadata_files['links.json']
-                                                else:
-                                                    expected = one(
-                                                        m
-                                                        for m in bundle.metadata_files.values()
-                                                        if (
-                                                            m['schema_type'] != 'link_bundle'
-                                                            and m['provenance']['document_id'] == entity_id
-                                                        )
-                                                    )
-                                                # Replica contents should match the entity
-                                                # metadata as supplied by the repository
-                                                # plugin, verbatim
-                                                actual = hit['_source']['contents']
-                                                self.assertEqual(expected, actual)
-                                            elif doc_type is DocumentType.contribution:
-                                                entity_id = ContributionCoordinates.from_hit(hit).entity.entity_id
-                                                contributions.append(entity_id)
-                                        contributions.sort()
-                                        replicas.sort()
-                                        # Every contribution should be replicated
-                                        self.assertEqual(contributions if enable_replicas else [], replicas)
-                                    finally:
-                                        self.index_service.delete_indices(self.catalog)
+                    with (
+                        self.subTest(page_size=page_size,
+                                     max_partition_size=max_partition_size,
+                                     enable_replicas=enable_replicas),
+                        patch.object(target=type(config),
+                                     attribute='enable_replicas',
+                                     new_callable=PropertyMock,
+                                     return_value=enable_replicas),
+                        patch.object(BundlePartition,
+                                     'max_partition_size',
+                                     new=max_partition_size),
+                        patch.object(type(config),
+                                     'contribution_page_size',
+                                     new=page_size)
+                    ):
+                        self.index_service.create_indices(self.catalog)
+                        try:
+                            self._index_bundle(bundle, delete=False)
+                            hits = self._get_all_hits()
+                            if enable_replicas:
+                                expected_hits = canned_hits
+                            else:
+                                expected_hits = [
+                                    h
+                                    for h in canned_hits
+                                    if self._parse_index_name(h)[1] is not DocumentType.replica
+                                ]
+                            self.assertElasticEqual(expected_hits, hits)
+                            contributions = []
+                            replicas = []
+                            for hit in hits:
+                                qualifier, doc_type = self._parse_index_name(hit)
+                                if doc_type is DocumentType.replica:
+                                    entity_id = ReplicaCoordinates.from_hit(hit).entity.entity_id
+                                    replicas.append(entity_id)
+                                    if entity_id == bundle.uuid:
+                                        expected = bundle.metadata_files['links.json']
+                                    else:
+                                        expected = one(
+                                            m
+                                            for m in bundle.metadata_files.values()
+                                            if (
+                                                m['schema_type'] != 'link_bundle'
+                                                and m['provenance']['document_id'] == entity_id
+                                            )
+                                        )
+                                    # Replica contents should match the entity
+                                    # metadata as supplied by the repository
+                                    # plugin, verbatim
+                                    actual = hit['_source']['contents']
+                                    self.assertEqual(expected, actual)
+                                elif doc_type is DocumentType.contribution:
+                  [...]

2024-05-10 01:32 UTC, hannes-ucsc commented on test/service/test_manifest.py
> +    @classmethod
Let's pull this up even higher.

```diff
Index: test/azul_test_case.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/azul_test_case.py b/test/azul_test_case.py
--- a/test/azul_test_case.py	(revision e7c137cda692a08a5ccc84417c9fa21bd0c795ca)
+++ b/test/azul_test_case.py	(date 1715304615691)
@@ -359,6 +359,7 @@
     def setUpClass(cls) -> None:
         super().setUpClass()
         cls._patch_catalogs()
+        cls._patch_replicas_enabled()
 
     @classmethod
     def _patch_catalogs(cls):
@@ -388,6 +389,12 @@
         assert config.default_catalog == cls.catalog
         assert config.integration_test_catalogs == {}
 
+    @classmethod
+    def _patch_replicas_enabled(cls):
+        cls.addClassPatch(patch.object(type(config),
+                                       'enable_replicas',
+                                       return_value=True))
+
 
 class DSSTestCase(CatalogTestCase, metaclass=ABCMeta):
     """
Index: test/service/test_manifest.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/service/test_manifest.py b/test/service/test_manifest.py
--- a/test/service/test_manifest.py	(revision e7c137cda692a08a5ccc84417c9fa21bd0c795ca)
+++ b/test/service/test_manifest.py	(date 1715303518462)
@@ -141,17 +141,6 @@
                        StorageServiceTestMixin,
                        metaclass=ABCMeta):
 
-    @classmethod
-    def setUpClass(cls):
-        super().setUpClass()
-        cls._patch_replicas_enabled()
-
-    @classmethod
-    def _patch_replicas_enabled(cls):
-        cls.addClassPatch(patch.object(type(config),
-                                       'enable_replicas',
-                                       return_value=True))
-
     def setUp(self):
         super().setUp()
         self._setup_indices()
```

2024-05-10 18:02 UTC, hannes-ucsc approved these changes

2024-05-10 18:09 UTC, hannes-ucsc commented
### Security design review

- [x] Security design review completed; this PR does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with Terra 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

2024-05-10 22:07 UTC, merged