Fix: Log messages from docker exec are not prefixed with container name (#6015)
DataBiosphere/azul pull request #6088
Opened 2024-03-25 16:53 UTC by dsotirho-ucsc

Connected issues: #6015

## Checklist

### Author

- [x] PR is a draft
- [x] Target branch is `develop`
- [x] Name of PR branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [x] On ZenHub, PR is connected to all issues it (partially) resolves
- [x] PR description links to connected issues
- [x] PR title matches<sup>1</sup> that of a connected issue <sub>or comment in PR explains why they're different</sub>
- [x] PR title references all connected issues
- [x] For each connected issue, there is at least one commit whose title references that issue

### Author (partiality)

- [x] Added `p` tag to titles of partial commits
- [x] This PR is labeled `partial` <sub>or completely resolves all connected issues</sub>
- [x] This PR partially resolves each of the connected issues <sub>or does not have the `partial` label</sub>

<sup>1</sup> when the issue title describes a problem, the corresponding PR
title is `Fix: ` followed by the issue title

### Author (chains)

- [x] This PR is blocked by previous PR in the chain <sub>or is not chained to another PR</sub>
- [x] The blocking PR is labeled `base` <sub>or this PR is not chained to another PR</sub>
- [x] This PR is labeled `chained` <sub>or is not chained to another PR</sub>

### Author (reindex, API changes)

- [x] Added `r` tag to commit title <sub>or this PR does not require reindexing</sub>
- [x] This PR is labeled `reindex:dev` <sub>or does not require reindexing `dev`</sub>
- [x] This PR is labeled `reindex:anvildev` <sub>or does not require reindexing `anvildev`</sub>
- [x] This PR is labeled `reindex:anvilprod` <sub>or does not require reindexing `anvilprod`</sub>
- [x] This PR is labeled `reindex:partial` and its description documents the specific reindexing procedure for `dev`, `anvildev`, `anvilprod` and `prod` <sub>or requires a full reindex or carries none of the labels `reindex:dev`, `reindex:anvildev`, `reindex:anvilprod` and `reindex:prod`</sub>
- [x] This PR and its connected issues are labeled `API` <sub>or this PR does not modify a REST API</sub>
- [x] Added `a` (`A`) tag to commit title for backwards (in)compatible changes <sub>or this PR does not modify a REST API</sub>
- [x] Updated REST API version number in `app.py` <sub>or this PR does not modify a REST API</sub>

### Author (upgrading deployments)

- [x] Documented upgrading of deployments in UPGRADING.rst <sub>or this PR does not require upgrading deployments</sub>
- [x] Added `u` tag to commit title <sub>or this PR does not require upgrading deployments</sub>
- [x] Ran `make image_manifests.json` and committed the resulting changes <sub>or this PR does not modify `azul_docker_images`, or any other variables referenced in the definition of that variable</sub>
- [x] This PR is labeled `upgrade` <sub>or does not require upgrading deployments</sub>
- [ ] This PR is labeled `deploy:shared` <sub>or does not modify `image_manifests.json`, and does not require deploying the `shared` component for any other reason</sub>
- [ ] This PR is labeled `deploy:gitlab` <sub>or does not require deploying the `gitlab` component</sub>
- [ ] This PR is labeled `deploy:runner` <sub>or does not require deploying the `runner` image</sub>

### Author (operator tasks)

- [ ] Added checklist items for additional operator tasks <sub>or this PR does not require additional tasks</sub>

### Author (hotfixes)

- [ ] Added `F` tag to main commit title <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [ ] Reverted the temporary hotfixes for any connected issues <sub>or the `prod` branch has no temporary hotfixes for any connected issues</sub>

### Author (before every review)

- [ ] Rebased PR branch on `develop`, squashed old fixups
- [ ] Ran `make requirements_update` <sub>or this PR does not modify `requirements*.txt`, `common.mk`, `Makefile` and `Dockerfile`</sub>
- [ ] Added `R` tag to commit title <sub>or this PR does not modify `requirements*.txt`</sub>
- [ ] This PR is labeled `reqs` <sub>or does not modify `requirements*.txt`</sub>
- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not modify functionality that could affect the IT outcome</sub>

### Peer reviewer (after requesting changes)

Uncheck the *Author (before every review)* checklists.

### Peer reviewer (after approval)

- [ ] PR is not a draft
- [ ] Ticket is in *Review requested* column
- [ ] Requested review from system administrator
- [ ] PR is assigned to only the system administrator

### System administrator (after requesting changes)

Uncheck the *before every review* checklists. Update the `N reviews` label.

### System administrator (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issues as `demo` or `no demo`
- [ ] Commented on connected issues about demo expectations <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] A comment to this PR details the completed security design review <sub>or this PR is a promotion or a backport</sub>
- [ ] PR title is appropriate as title of merge commit
- [ ] `N reviews` label is accurate
- [ ] Moved ticket to *Approved* column
- [ ] PR is assigned to only the operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex:…` labels and `r` commit title tag
- [ ] Checked that demo expectations are clear <sub>or all connected issues are labeled `no demo`</sub>
- [ ] PR has checklist items for upgrading instructions <sub>or PR is not labeled `upgrade`</sub>
- [ ] Squashed PR branch and rebased onto `develop`
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Ran `_select dev.shared && CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR is not labeled `deploy:shared`</sub>
- [ ] Ran `_select dev.gitlab && CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] Ran `_select anvildev.shared && CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR is not labeled `deploy:shared`</sub>
- [ ] Ran `_select anvildev.gitlab && CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] Ran `_select anvilprod.shared && CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR is not labeled `deploy:shared`</sub>
- [ ] Ran `_select anvilprod.gitlab && CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] Checked the items in the next section <sub>or this PR is labeled `deploy:gitlab`</sub>
- [ ] Assigned system administrator <sub>or this PR is not labeled `deploy:gitlab`</sub>

### System administrator

- [ ] Background migrations for `dev.gitlab` are complete <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] Background migrations for `anvildev.gitlab` are complete <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] Background migrations for `anvilprod.gitlab` are complete <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] PR is assigned to only the operator

### Operator (before pushing merge the commit)

- [ ] Ran `_select dev.gitlab && make -C terraform/gitlab/runner` <sub>or this PR is not labeled `deploy:runner`</sub>
- [ ] Ran `_select anvildev.gitlab && make -C terraform/gitlab/runner` <sub>or this PR is not labeled `deploy:runner`</sub>
- [ ] Ran `_select anvilprod.gitlab && make -C terraform/gitlab/runner` <sub>or this PR is not labeled `deploy:runner`</sub>
- [ ] Added `sandbox` label <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `dev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvilprod` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build pas [...]

2024-04-01 23:09 UTC, dsotirho-ucsc commented
[6088_IT_2024-04-01.txt](https://github.com/DataBiosphere/azul/files/14829333/6088_IT_2024-04-01.txt)

2024-04-01 23:11 UTC, dsotirho-ucsc commented
PR deployed to and verified on `dev.gitlab`

## Manually running prune-images:

```
[ec2-user@ip-172-21-0-99 ~]$ sudo grep exec /etc/systemd/system/*.service
/etc/systemd/system/prune-images.service:ExecStart=/usr/bin/docker exec gitlab-dind sh -c 'docker image prune --force --all --filter "until=2160h" > /proc/1/fd/1'
/etc/systemd/system/prune-images.service:ExecStart=/usr/bin/docker exec gitlab-dind sh -c 'docker buildx prune --force --all --filter "until=2160h" > /proc/1/fd/1'
/etc/systemd/system/registry-garbage-collect.service:ExecStart=/usr/bin/docker exec gitlab sh -c '/opt/gitlab/bin/gitlab-ctl registry-garbage-collect -m > /proc/1/fd/1'
[ec2-user@ip-172-21-0-99 ~]$
[ec2-user@ip-172-21-0-99 ~]$ sudo systemctl status prune-images
● prune-images.service - Pruning of stale docker images
   Loaded: loaded (/etc/systemd/system/prune-images.service; static; vendor preset: disabled)
   Active: inactive (dead)
[ec2-user@ip-172-21-0-99 ~]$
[ec2-user@ip-172-21-0-99 ~]$ sudo systemctl start prune-images
[ec2-user@ip-172-21-0-99 ~]$
[ec2-user@ip-172-21-0-99 ~]$ sudo systemctl status prune-images
● prune-images.service - Pruning of stale docker images
   Loaded: loaded (/etc/systemd/system/prune-images.service; static; vendor preset: disabled)
   Active: inactive (dead) since Mon 2024-04-01 22:17:43 UTC; 2s ago
  Process: 14006 ExecStart=/usr/bin/docker exec gitlab-dind sh -c docker buildx prune --force --all --filter "until=2160h" > /proc/1/fd/1 (code=exited, status=0/SUCCESS)
  Process: 13974 ExecStart=/usr/bin/docker exec gitlab-dind sh -c docker image prune --force --all --filter "until=2160h" > /proc/1/fd/1 (code=exited, status=0/SUCCESS)
  Process: 13955 ExecStartPre=/usr/bin/docker pull 122796619775.dkr.ecr.us-east-1.amazonaws.com/docker.io/library/docker:25.0.5-dind (code=exited, status=0/SUCCESS)
  Process: 13945 ExecStartPre=/usr/bin/docker rm prune-images (code=exited, status=1/FAILURE)
  Process: 13915 ExecStartPre=/usr/bin/docker stop prune-images (code=exited, status=1/FAILURE)
 Main PID: 14006 (code=exited, status=0/SUCCESS)

Apr 01 22:17:37 ip-172-21-0-99.ec2.internal systemd[1]: Starting Pruning of stale docker images...
Apr 01 22:17:37 ip-172-21-0-99.ec2.internal docker[13915]: Error response from daemon: No such container: prune-images
Apr 01 22:17:37 ip-172-21-0-99.ec2.internal docker[13945]: Error: No such container: prune-images
Apr 01 22:17:37 ip-172-21-0-99.ec2.internal docker[13955]: 25.0.5-dind: Pulling from docker
Apr 01 22:17:37 ip-172-21-0-99.ec2.internal docker[13955]: Digest: sha256:92bcad604ec2aa6243ba5d3a1cf4cfc06cc505cd383de58a4f5ae67f17b4a87c
Apr 01 22:17:37 ip-172-21-0-99.ec2.internal docker[13955]: Status: Image is up to date for 122796619775.dkr.ecr.us-east-1.amazonaws.com/docker.io/library/docker:25.0.5-dind
Apr 01 22:17:37 ip-172-21-0-99.ec2.internal docker[13955]: 122796619775.dkr.ecr.us-east-1.amazonaws.com/docker.io/library/docker:25.0.5-dind
Apr 01 22:17:43 ip-172-21-0-99.ec2.internal systemd[1]: Started Pruning of stale docker images.
[ec2-user@ip-172-21-0-99 ~]$
```

## Prune-images logs:

```
Apr  1 22:17:37 ip-172-21-0-99 systemd: Starting Pruning of stale docker images...
Apr  1 22:17:37 ip-172-21-0-99 docker: Error response from daemon: No such container: prune-images
Apr  1 22:17:37 ip-172-21-0-99 docker: Error: No such container: prune-images
Apr  1 22:17:37 ip-172-21-0-99 docker: 25.0.5-dind: Pulling from docker
Apr  1 22:17:37 ip-172-21-0-99 docker: Digest: sha256:92bcad604ec2aa6243ba5d3a1cf4cfc06cc505cd383de58a4f5ae67f17b4a87c
Apr  1 22:17:37 ip-172-21-0-99 docker: Status: Image is up to date for 122796619775.dkr.ecr.us-east-1.amazonaws.com/docker.io/library/docker:25.0.5-dind
Apr  1 22:17:37 ip-172-21-0-99 docker: 122796619775.dkr.ecr.us-east-1.amazonaws.com/docker.io/library/docker:25.0.5-dind
Apr  1 22:17:38 ip-172-21-0-99 docker: gitlab-dind: Total reclaimed space: 0B
Apr  1 22:17:40 ip-172-21-0-99 docker: gitlab-dind: ID#011#011#011#011#011#011RECLAIMABLE#011SIZE#011#011LAST ACCESSED
Apr  1 22:17:40 ip-172-21-0-99 docker: gitlab-dind: zmupug4d886812oxw7q8060rq*              #011true #011#0112.709kB   #0113 months ago
Apr  1 22:17:40 ip-172-21-0-99 docker: gitlab-dind: c778x611g7ir1bqljsz0bhd6l*              #011true #0112.709kB   #0113 months ago
Apr  1 22:17:40 ip-172-21-0-99 docker: gitlab-dind: x3ulmrypx6lig6icax6fknua0*              #011true #01119.5kB    #0113 months ago
Apr  1 22:17:40 ip-172-21-0-99 docker: gitlab-dind: dqf9qm9l1kk32med2bdl975yn*              #011true #01119.5kB    #0113 months ago
Apr  1 22:17:40 ip-172-21-0-99 docker: gitlab-dind: xzt409sxlxoo4fzloog19xadx*              #011true #01196B       #0113 months ago
Apr  1 22:17:40 ip-172-21-0-99 docker: gitlab-dind: fbxjn36hr1us78bkplz3te60x*              #011true #0112.709kB   #0113 months ago
Apr  1 22:17:40 ip-172-21-0-99 docker: gitlab-dind: w508pyhkwx6cfjekw9h0sunmn*              #011true #01196B       #0113 months ago
…
```

## Manually running registry-garbage-collect:

```
[ec2-user@ip-172-21-0-99 ~]$
[ec2-user@ip-172-21-0-99 ~]$ sudo grep exec /etc/systemd/system/*.service
/etc/systemd/system/prune-images.service:ExecStart=/usr/bin/docker exec gitlab-dind sh -c 'docker image prune --force --all --filter "until=2160h" > /proc/1/fd/1'
/etc/systemd/system/prune-images.service:ExecStart=/usr/bin/docker exec gitlab-dind sh -c 'docker buildx prune --force --all --filter "until=2160h" > /proc/1/fd/1'
/etc/systemd/system/registry-garbage-collect.service:ExecStart=/usr/bin/docker exec gitlab sh -c '/opt/gitlab/bin/gitlab-ctl registry-garbage-collect -m > /proc/1/fd/1'
[ec2-user@ip-172-21-0-99 ~]$
[ec2-user@ip-172-21-0-99 ~]$ sudo systemctl status registry-garbage-collect
● registry-garbage-collect.service - GitLab container registry garbage collection
   Loaded: loaded (/etc/systemd/system/registry-garbage-collect.service; static; vendor preset: disabled)
   Active: inactive (dead)
[ec2-user@ip-172-21-0-99 ~]$
[ec2-user@ip-172-21-0-99 ~]$ sudo systemctl start registry-garbage-collect
[ec2-user@ip-172-21-0-99 ~]$
[ec2-user@ip-172-21-0-99 ~]$ sudo systemctl status registry-garbage-collect
● registry-garbage-collect.service - GitLab container registry garbage collection
   Loaded: loaded (/etc/systemd/system/registry-garbage-collect.service; static; vendor preset: disabled)
   Active: active (running) since Mon 2024-04-01 22:38:02 UTC; 1s ago
  Process: 23006 ExecStartPre=/usr/bin/docker pull 122796619775.dkr.ecr.us-east-1.amazonaws.com/docker.io/gitlab/gitlab-ce:16.10.0-ce.0 (code=exited, status=0/SUCCESS)
  Process: 22996 ExecStartPre=/usr/bin/docker rm registry-garbage-collect (code=exited, status=1/FAILURE)
  Process: 22967 ExecStartPre=/usr/bin/docker stop registry-garbage-collect (code=exited, status=1/FAILURE)
 Main PID: 23025 (docker)
    Tasks: 8
   Memory: 10.4M
   CGroup: /system.slice/registry-garbage-collect.service
           └─23025 /usr/bin/docker exec gitlab sh -c /opt/gitlab/bin/gitlab-ctl registry-garbage-collect -m > /proc/1/fd/1

Apr 01 22:38:02 ip-172-21-0-99.ec2.internal systemd[1]: Starting GitLab container registry garbage collection...
Apr 01 22:38:02 ip-172-21-0-99.ec2.internal docker[22967]: Error response from daemon: No such container: registry-garbage-collect
Apr 01 22:38:02 ip-172-21-0-99.ec2.internal docker[22996]: Error: No such container: registry-garbage-collect
Apr 01 22:38:02 ip-172-21-0-99.ec2.internal docker[23006]: 16.10.0-ce.0: Pulling from gitlab/gitlab-ce
Apr 01 22:38:02 ip-172-21-0-99.ec2.internal docker[23006]: Digest: sha256:bf67edce97f03c5584d5ad3f1681c2817b9f80b3da4b1a930a3c4aecb3c4a950
Apr 01 22:38:02 ip-172-21-0-99.ec2.internal docker[23006]: Status: Image is up to date for 122796619775.dkr.ecr.us-east-1.amazonaws.com/docker.io/gitlab/gitlab-ce:16.10.0-ce.0
Apr 01 22:38:02 ip-172-21-0-99.ec2.internal docker[23006]: 122796619775.dkr.ecr.us-east-1.amazonaws.com/docker.io/gitlab/gitlab-ce:16.10.0-ce.0
Apr 01 22:38:02 ip-172-21-0-99.ec2.internal systemd[1]: Started GitLab container [...]

2024-04-02 19:02 UTC, achave11-ucsc approved these changes, later dismissed
Approved ✅

2024-04-04 18:39 UTC, hannes-ucsc requested changes

2024-04-04 18:39 UTC, hannes-ucsc commented on terraform/gitlab/gitlab.tf.json.template.py
> +                                    'sh -c',  # … a command passed as a string to the shell.
```suggestion
                                    'sh -c',  # … via the shell so we can redirect stdout
```

2024-04-04 18:39 UTC, hannes-ucsc commented on terraform/gitlab/gitlab.tf.json.template.py
> +                                        '> /proc/1/fd/1',  # … with output sent to the container's STDOUT.
Explain why. Attribute source.

2024-04-17 17:38 UTC, dsotirho-ucsc commented
Tested on `dev.gitlab` (by manually running `sudo systemctl start registry-garbage-collect`)

---
| @timestamp | @message |
| --- | --- |
| 2024-04-17 16:58:30.625 | Apr 17 16:58:30 ip-172-21-0-99 sudo: ec2-user : TTY=pts/0 ; PWD=/home/ec2-user ; USER=root ; COMMAND=/bin/systemctl#040status#040registry-garbage-collect |
| 2024-04-17 16:58:41.905 | Apr 17 16:58:41 ip-172-21-0-99 sudo: ec2-user : TTY=pts/0 ; PWD=/home/ec2-user ; USER=root ; COMMAND=/bin/systemctl#040start#040registry-garbage-collect |
| 2024-04-17 16:58:42.330 | Apr 17 16:58:41 ip-172-21-0-99 systemd: Starting GitLab container registry garbage collection... |
| 2024-04-17 16:58:42.368 | type=SERVICE_START msg=audit(1713373122.187:50436): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=registry-garbage-collect comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success' |
| 2024-04-17 16:58:44.086 | Apr 17 16:58:42 ip-172-21-0-99 systemd: Started GitLab container registry garbage collection. |
| 2024-04-17 16:58:44.087 | Apr 17 16:58:43 ip-172-21-0-99 docker: gitlab: Running garbage-collect using configuration ["/opt/gitlab/embedded/bin/registry", "garbage-collect", "/var/opt/gitlab/registry/config.yml", "-m"], this might take a while... |
| 2024-04-17 16:58:44.087 | Apr 17 16:58:43 ip-172-21-0-99 docker: gitlab: time="2024-04-17T16:58:43.953Z" level=info msg="starting mark stage" driver=filesystem dry_run=false environment=production go_version=go1.21.7 instance_id=f53d349c-26e4-47c5-9e5d-bcc23760b2ef service=registry stage=mark version=v3.90.0-gitlab |
|   | … |
| 2024-04-17 16:58:45.844 | Apr 17 16:58:45 ip-172-21-0-99 docker: gitlab: time="2024-04-17T16:58:44.726Z" level=info msg="finding blobs eligible for deletion. This may take some time..." driver=filesystem dry_run=false environment=production go_version=go1.21.7 instance_id=f53d349c-26e4-47c5-9e5d-bcc23760b2ef service=registry stage=mark version=v3.90.0-gitlab |
| 2024-04-17 16:58:45.844 | Apr 17 16:58:45 ip-172-21-0-99 docker: gitlab: time="2024-04-17T16:58:44.756Z" level=info msg="mark stage complete" blobs_marked=366 blobs_to_delete=0 driver=filesystem dry_run=false duration_s=0.80284426 environment=production go_version=go1.21.7 instance_id=f53d349c-26e4-47c5-9e5d-bcc23760b2ef manifests_to_delete=0 service=registry stage=mark storage_use_estimate_bytes=0 version=v3.90.0-gitlab |
| 2024-04-17 16:58:45.844 | Apr 17 16:58:45 ip-172-21-0-99 docker: gitlab: time="2024-04-17T16:58:44.756Z" level=info msg="starting sweep stage" driver=filesystem dry_run=false environment=production go_version=go1.21.7 instance_id=f53d349c-26e4-47c5-9e5d-bcc23760b2ef service=registry stage=sweep version=v3.90.0-gitlab |
| 2024-04-17 16:58:45.844 | Apr 17 16:58:45 ip-172-21-0-99 docker: gitlab: time="2024-04-17T16:58:44.756Z" level=info msg="sweep stage complete" driver=filesystem dry_run=false duration_s=2.974e-05 environment=production go_version=go1.21.7 instance_id=f53d349c-26e4-47c5-9e5d-bcc23760b2ef service=registry stage=sweep version=v3.90.0-gitlab |
| 2024-04-17 16:58:45.844 | Apr 17 16:58:45 ip-172-21-0-99 docker: gitlab: time="2024-04-17T16:58:44.756Z" level=info msg="zero-downtime continuous garbage collection is now available as part of a beta feature. Please see the feedback issue for more information: https://gitlab.com/gitlab-org/gitlab/-/issues/423459" driver=filesystem dry_run=false environment=production go_version=go1.21.7 instance_id=f53d349c-26e4-47c5-9e5d-bcc23760b2ef service=registry stage=mark version=v3.90.0-gitlab |
| 2024-04-17 16:58:48.956 | type=SERVICE_STOP msg=audit(1713373124.779:50442): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=registry-garbage-collect comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success' |
---

2024-04-18 05:20 UTC, hannes-ucsc commented
### Security design review

- [x] Security design review completed; this PR does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with Terra 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

2024-04-18 05:21 UTC, hannes-ucsc commented
Security design review: This PR improves the monitoring and audit logging capabilities by added a crucial, but missing piece of information to the logs.

2024-04-19 22:58 UTC, hannes-ucsc approved these changes

2024-04-19 23:08 UTC, merged