Fix: update_subgraph_counts.py fails for ANVIL_T2T_CHRY dataset (#6206)
DataBiosphere/azul pull request #6221
Opened 2024-05-01 05:01 UTC by nadove-ucsc

Connected issues: #6206

## Checklist

### Author

- [x] PR is a draft
- [x] Target branch is `develop`
- [x] Name of PR branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [ ] On ZenHub, PR is connected to all issues it (partially) resolves
- [x] PR description links to connected issues
- [x] PR title matches<sup>1</sup> that of a connected issue <sub>or comment in PR explains why they're different</sub>
- [x] PR title references all connected issues
- [x] For each connected issue, there is at least one commit whose title references that issue

<sup>1</sup> when the issue title describes a problem, the corresponding PR
title is `Fix: ` followed by the issue title

### Author (partiality)

- [x] Added `p` tag to titles of partial commits
- [x] This PR is labeled `partial` <sub>or completely resolves all connected issues</sub>
- [x] This PR partially resolves each of the connected issues <sub>or does not have the `partial` label</sub>

### Author (chains)

- [ ] This PR is blocked by previous PR in the chain <sub>or is not chained to another PR</sub>
- [ ] The blocking PR is labeled `base` <sub>or this PR is not chained to another PR</sub>
- [ ] This PR is labeled `chained` <sub>or is not chained to another PR</sub>

### Author (reindex, API changes)

- [x] Added `r` tag to commit title <sub>or the changes introduced by this PR will not require reindexing of any deployment</sub>
- [x] This PR is labeled `reindex:dev` <sub>or the changes introduced by it will not require reindexing of `dev`</sub>
- [x] This PR is labeled `reindex:anvildev` <sub>or the changes introduced by it will not require reindexing of `anvildev`</sub>
- [x] This PR is labeled `reindex:anvilprod` <sub>or the changes introduced by it will not require reindexing of `anvilprod`</sub>
- [x] This PR is labeled `reindex:prod` <sub>or the changes introduced by it will not require reindexing of `prod`</sub>
- [ ] This PR is labeled `reindex:partial` and its description documents the specific reindexing procedure for `dev`, `anvildev`, `anvilprod` and `prod` <sub>or requires a full reindex or carries none of the labels `reindex:dev`, `reindex:anvildev`, `reindex:anvilprod` and `reindex:prod`</sub>
- [x] This PR and its connected issues are labeled `API` <sub>or this PR does not modify a REST API</sub>
- [x] Added `a` (`A`) tag to commit title for backwards (in)compatible changes <sub>or this PR does not modify a REST API</sub>
- [x] Updated REST API version number in `app.py` <sub>or this PR does not modify a REST API</sub>

### Author (upgrading deployments)

- [x] Ran `make image_manifests.json` and committed the resulting changes <sub>or this PR does not modify `azul_docker_images`, or any other variables referenced in the definition of that variable</sub>
- [x] Documented upgrading of deployments in UPGRADING.rst <sub>or this PR does not require upgrading deployments</sub>
- [x] Added `u` tag to commit title <sub>or this PR does not require upgrading deployments</sub>
- [x] This PR is labeled `upgrade` <sub>or does not require upgrading deployments</sub>
- [x] This PR is labeled `deploy:shared` <sub>or does not modify `image_manifests.json`, and does not require deploying the `shared` component for any other reason</sub>
- [x] This PR is labeled `deploy:gitlab` <sub>or does not require deploying the `gitlab` component</sub>
- [x] This PR is labeled `deploy:runner` <sub>or does not require deploying the `runner` image</sub>

### Author (hotfixes)

- [x] Added `F` tag to main commit title <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [x] Reverted the temporary hotfixes for any connected issues <sub>or the none of the stable branches (`anvilprod` and `prod`) have temporary hotfixes for any of the issues connected to this PR</sub>

### Author (before every review)

- [x] Rebased PR branch on `develop`, squashed old fixups
- [x] Ran `make requirements_update` <sub>or this PR does not modify `requirements*.txt`, `common.mk`, `Makefile` and `Dockerfile`</sub>
- [x] Added `R` tag to commit title <sub>or this PR does not modify `requirements*.txt`</sub>
- [x] This PR is labeled `reqs` <sub>or does not modify `requirements*.txt`</sub>
- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not modify functionality that could affect the IT outcome</sub>

### Peer reviewer (after approval)

- [ ] PR is not a draft
- [ ] Ticket is in *Review requested* column
- [ ] PR is awaiting requested review from system administrator
- [ ] PR is assigned to only the system administrator

### System administrator (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issues as `demo` or `no demo`
- [ ] Commented on connected issues about demo expectations <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] A comment to this PR details the completed security design review
- [ ] PR title is appropriate as title of merge commit
- [ ] `N reviews` label is accurate
- [ ] Moved ticket to *Approved* column
- [ ] PR is assigned to only the operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex:…` labels and `r` commit title tag
- [ ] Checked that demo expectations are clear <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Squashed PR branch and rebased onto `develop`
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Ran `_select dev.shared && CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR is not labeled `deploy:shared`</sub>
- [ ] Ran `_select dev.gitlab && CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] Ran `_select anvildev.shared && CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR is not labeled `deploy:shared`</sub>
- [ ] Ran `_select anvildev.gitlab && CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] Checked the items in the next section <sub>or this PR is labeled `deploy:gitlab`</sub>
- [ ] PR is assigned to only the system administrator <sub>or this PR is not labeled `deploy:gitlab`</sub>

### System administrator

- [ ] Background migrations for `dev.gitlab` are complete <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] Background migrations for `anvildev.gitlab` are complete <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] PR is assigned to only the operator

### Operator (before pushing merge the commit)

- [ ] Ran `_select dev.gitlab && make -C terraform/gitlab/runner` <sub>or this PR is not labeled `deploy:runner`</sub>
- [ ] Ran `_select anvildev.gitlab && make -C terraform/gitlab/runner` <sub>or this PR is not labeled `deploy:runner`</sub>
- [ ] Added `sandbox` label <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `dev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted unreferenced indices in `sandbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices in `dev`</sub>
- [ ] Deleted unreferenced indices in `anvilbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices in `anvildev`</sub>
- [ ] Started reindex in `sandbox` <sub>or this PR is not labeled `reindex:dev`</sub>
- [ ] Started reindex in `anvilbox` <sub>or this PR is not labeled `reindex:anvildev`</sub>
- [ ] Checked for failures in `sandbox` <sub>or this PR is not  [...]

2024-05-01 22:34 UTC, achave11-ucsc submitted a review, later dismissed
Nicely done! ✅

2024-05-02 04:46 UTC, hannes-ucsc requested changes
```diff
Index: src/azul/plugins/__init__.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/plugins/__init__.py b/src/azul/plugins/__init__.py
--- a/src/azul/plugins/__init__.py	(revision ccae3f3e1e6a1d3dd0d95ad779021a445459b608)
+++ b/src/azul/plugins/__init__.py	(date 1714625127176)
@@ -594,11 +594,14 @@
 
     def list_partitions(self, source: SOURCE_REF) -> Optional[Mapping[str, int]]:
         """
-        Return the number of bundles in each partition of the given source, or
-        return None if that information cannot be retrieved inexpensively. Each
-        key in the returned mapping is the full prefix of a partition, including
-        the common prefix if one is configured. Implementations are allowed to
-        omit empty partitions from the result.
+        Return the number of bundles in each non-empty partition of the given
+        source, or return None if that information cannot be retrieved
+        inexpensively. Each key in the returned mapping is the full prefix of a
+        partition, including the common prefix if one is configured.
+
+        REVIEW: Ambiguity is to be avoided as it complicates the calling code.
+                Each implementation must assert the post-condition (no result 
+                entries with 0 as the value).
 
         Subclasses may optionally implement this method to facilitate
         integration test coverage of the partition sizes of their sources.
Index: test/integration_test.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/integration_test.py b/test/integration_test.py
--- a/test/integration_test.py	(revision ccae3f3e1e6a1d3dd0d95ad779021a445459b608)
+++ b/test/integration_test.py	(date 1714624568010)
@@ -300,7 +300,8 @@
         partition_prefix = self.random.choice(partition_prefixes)
         effective_prefix = prefix.common + partition_prefix
         fqids = self.azul_client.list_bundles(catalog, source, partition_prefix)
-        bundle_count = len(fqids)
+        # REVIEW: Separate commit for this rename
+        num_bundles = len(fqids)
         partition = f'Partition {effective_prefix!r} of source {source.spec}'
         if not config.is_sandbox_or_personal_deployment:
             # For sources that use partitioning, 512 is the desired partition
@@ -325,7 +326,7 @@
                         # across all partitions simultaneously, we can check
                         # whether the chosen partition is an outlier by
                         # determining the *average* partition size.
-                        bundle_count = sum(counts.values()) / prefix.partition_count()
+                        num_bundles = sum(counts.values()) / prefix.num_partitions
             else:
                 # Sources too small to be split into more than one partition may
                 # have as few as one bundle in total
@@ -340,8 +341,8 @@
             upper = 64
             lower = 1
 
-        self.assertLessEqual(bundle_count, upper, partition + ' is too large')
-        self.assertGreaterEqual(bundle_count, lower, partition + ' is too small')
+        self.assertLessEqual(num_bundles, upper, partition + ' is too large')
+        self.assertGreaterEqual(num_bundles, lower, partition + ' is too small')
 
         return source, partition_prefix, fqids
 
Index: deployments/anvilprod/environment.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/deployments/anvilprod/environment.py b/deployments/anvilprod/environment.py
--- a/deployments/anvilprod/environment.py	(revision ccae3f3e1e6a1d3dd0d95ad779021a445459b608)
+++ b/deployments/anvilprod/environment.py	(date 1714624872270)
@@ -383,6 +383,7 @@
     # @formatter:on
 ]))
 
+# REVIEW: This should be a separate, second commit
 anvil6_sources = mkdict(anvil5_sources, 256, mkdelta([
     # @formatter:off
     mksrc('datarepo-38af6304', 'ANVIL_1000G_PRIMED_data_model_20240410_ANV5_202404101419', 14695),
@@ -616,6 +617,7 @@
     mksrc('datarepo-4a4eec27', 'ANVIL_PAGE_SoL_HMB_WGS_20221220_ANV5_202403040445', 234, pop),
     mksrc('datarepo-a1f917db', 'ANVIL_PAGE_Stanford_Global_Reference_Panel_GRU_WGS_20221128_ANV5_202403040453', 78, pop), # noqa E501
     mksrc('datarepo-6264931f', 'ANVIL_PAGE_WHI_HMB_IRB_WGS_20221019_ANV5_202403040500', 235, pop),
+    # REVIEW: This should be a separate, second commit
     mksrc('datarepo-e5b16a5a', 'ANVIL_T2T_CHRY_20240301_ANV5_202403040508', 309979),
     mksrc('datarepo-f3817357', 'ANVIL_ccdg_asc_ndd_daly_talkowski_AGRE_asd_exome_20221102_ANV5_202403040528', 850),
     mksrc('datarepo-23635d1c', 'ANVIL_ccdg_asc_ndd_daly_talkowski_IBIS_asd_exome_20221024_ANV5_202403040537', 241),
Index: src/azul/indexer/__init__.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/indexer/__init__.py b/src/azul/indexer/__init__.py
--- a/src/azul/indexer/__init__.py	(revision ccae3f3e1e6a1d3dd0d95ad779021a445459b608)
+++ b/src/azul/indexer/__init__.py	(date 1714624363096)
@@ -160,10 +160,12 @@
             validate_uuid_prefix(self.common + partition_prefix)
             yield partition_prefix
 
-    def partition_count(self) -> int:
+    @property
+    def num_partitions(self) -> int:
         """
-        Efficient computation of `len(self.partition_prefixes())`
+        Equivalent to `len(self.partition_prefixes())`, but more efficient.
         """
+        # REVIEW: Not covered by doctests
         return len(self.digits) ** self.partition
 
     def __str__(self):
@@ -175,6 +177,7 @@
         return f'{self.common}/{self.partition}'
 
     def __len__(self):
+        # REVIEW: Not covered by doctests
         return len(self.common) + self.partition
 
 
Index: deployments/hammerbox/environment.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/deployments/hammerbox/environment.py b/deployments/hammerbox/environment.py
--- a/deployments/hammerbox/environment.py	(revision ccae3f3e1e6a1d3dd0d95ad779021a445459b608)
+++ b/deployments/hammerbox/environment.py	(date 1714624872284)
@@ -396,6 +396,7 @@
     # @formatter:on
 ]))
 
+# REVIEW: This should be a separate, second commit
 anvil6_sources = mkdict(anvil5_sources, 256, mkdelta([
     # @formatter:off
     mksrc('datarepo-38af6304', 'ANVIL_1000G_PRIMED_data_model_20240410_ANV5_202404101419', 14695),
@@ -629,6 +630,7 @@
     mksrc('datarepo-4a4eec27', 'ANVIL_PAGE_SoL_HMB_WGS_20221220_ANV5_202403040445', 234, pop),
     mksrc('datarepo-a1f917db', 'ANVIL_PAGE_Stanford_Global_Reference_Panel_GRU_WGS_20221128_ANV5_202403040453', 78, pop), # noqa E501
     mksrc('datarepo-6264931f', 'ANVIL_PAGE_WHI_HMB_IRB_WGS_20221019_ANV5_202403040500', 235, pop),
+    # REVIEW: This should be a separate, second commit
     mksrc('datarepo-e5b16a5a', 'ANVIL_T2T_CHRY_20240301_ANV5_202403040508', 309979),
     mksrc('datarepo-f3817357', 'ANVIL_ccdg_asc_ndd_daly_talkowski_AGRE_asd_exome_20221102_ANV5_202403040528', 850),
     mksrc('datarepo-23635d1c', 'ANVIL_ccdg_asc_ndd_daly_talkowski_IBIS_asd_exome_20221024_ANV5_202403040537', 241),
```

2024-05-02 16:49 UTC, hannes-ucsc requested changes
> ```
> +                Each implementation must assert the post-condition (no result 
> +                entries with 0 as the value).
> ```

from my previous review seems to be missing.

2024-05-03 04:37 UTC, hannes-ucsc reviewed
This version doesn't require the intermediate list.

```diff
Index: src/azul/plugins/repository/tdr_anvil/__init__.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/plugins/repository/tdr_anvil/__init__.py b/src/azul/plugins/repository/tdr_anvil/__init__.py
--- a/src/azul/plugins/repository/tdr_anvil/__init__.py	(revision 72359b52d08a79f1270405f29ed6f9ce4070b1a0)
+++ b/src/azul/plugins/repository/tdr_anvil/__init__.py	(date 1714710740201)
@@ -244,7 +244,7 @@
         prefix = source.spec.prefix
         primary = BundleEntityType.primary.value
         supplementary = BundleEntityType.supplementary.value
-        rows = list(self._run_sql(f'''
+        rows = self._run_sql(f'''
             SELECT prefix, COUNT(*) AS subgraph_count
             FROM (
                 SELECT SUBSTR(datarepo_row_id, 1, {len(prefix)}) AS prefix
@@ -257,9 +257,10 @@
             )
             WHERE STARTS_WITH(prefix, {prefix.common!r})
             GROUP BY prefix
-        '''))
-        assert all(row['subgraph_count'] > 0 for row in rows)
-        return {row['prefix']: row['subgraph_count'] for row in rows}
+        ''')
+        partitions = {row['prefix']: row['subgraph_count'] for row in rows}
+        assert all(v > 0 for v in partitions.values())
+        return partitions
 
     def resolve_bundle(self, fqid: SourcedBundleFQIDJSON) -> TDRAnvilBundleFQID:
         if 'entity_type' not in fqid:

```

More on pre- and postconditions: https://en.wikipedia.org/wiki/Hoare_logic

2024-05-03 04:38 UTC, hannes-ucsc requested changes
https://github.com/DataBiosphere/azul/pull/6221#pullrequestreview-2037312108

2024-05-03 16:23 UTC, hannes-ucsc approved these changes

2024-05-03 16:24 UTC, hannes-ucsc approved these changes

2024-05-03 16:25 UTC, hannes-ucsc commented
### Security design review

- [x] Security design review completed; this PR does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with Terra 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

2024-05-03 22:14 UTC, merged