Fix: Execution of untrusted code when cloning Git submodule (CVE-2024-32002) (#6352)
DataBiosphere/azul pull request #6467
Opened 2024-08-02 16:51 UTC by dsotirho-ucsc

Connected issues: #6352

## Checklist

### Author

- [x] PR is a draft
- [x] Target branch is `develop`
- [x] Name of PR branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [x] On ZenHub, PR is connected to all issues it (partially) resolves
- [x] PR description links to connected issues
- [x] PR title matches<sup>1</sup> that of a connected issue <sub>or comment in PR explains why they're different</sub>
- [x] PR title references all connected issues
- [x] For each connected issue, there is at least one commit whose title references that issue

<sup>1</sup> when the issue title describes a problem, the corresponding PR
title is `Fix: ` followed by the issue title

### Author (partiality)

- [x] Added `p` tag to titles of partial commits
- [x] This PR is labeled `partial` <sub>or completely resolves all connected issues</sub>
- [x] This PR partially resolves each of the connected issues <sub>or does not have the `partial` label</sub>

### Author (chains)

- [x] This PR is blocked by previous PR in the chain <sub>or is not chained to another PR</sub>
- [x] The blocking PR is labeled `base` <sub>or this PR is not chained to another PR</sub>
- [x] This PR is labeled `chained` <sub>or is not chained to another PR</sub>

### Author (reindex, API changes)

- [x] Added `r` tag to commit title <sub>or the changes introduced by this PR will not require reindexing of any deployment</sub>
- [x] This PR is labeled `reindex:dev` <sub>or the changes introduced by it will not require reindexing of `dev`</sub>
- [x] This PR is labeled `reindex:anvildev` <sub>or the changes introduced by it will not require reindexing of `anvildev`</sub>
- [x] This PR is labeled `reindex:anvilprod` <sub>or the changes introduced by it will not require reindexing of `anvilprod`</sub>
- [x] This PR is labeled `reindex:prod` <sub>or the changes introduced by it will not require reindexing of `prod`</sub>
- [x] This PR is labeled `reindex:partial` and its description documents the specific reindexing procedure for `dev`, `anvildev`, `anvilprod` and `prod` <sub>or requires a full reindex or carries none of the labels `reindex:dev`, `reindex:anvildev`, `reindex:anvilprod` and `reindex:prod`</sub>
- [x] This PR and its connected issues are labeled `API` <sub>or this PR does not modify a REST API</sub>
- [x] Added `a` (`A`) tag to commit title for backwards (in)compatible changes <sub>or this PR does not modify a REST API</sub>
- [x] Updated REST API version number in `app.py` <sub>or this PR does not modify a REST API</sub>

### Author (upgrading deployments)

- [x] Ran `make image_manifests.json` and committed the resulting changes <sub>or this PR does not modify `azul_docker_images`, or any other variables referenced in the definition of that variable</sub>
- [x] Documented upgrading of deployments in UPGRADING.rst <sub>or this PR does not require upgrading deployments</sub>
- [x] Added `u` tag to commit title <sub>or this PR does not require upgrading deployments</sub>
- [x] This PR is labeled `upgrade` <sub>or does not require upgrading deployments</sub>
- [x] This PR is labeled `deploy:shared` <sub>or does not modify `image_manifests.json`, and does not require deploying the `shared` component for any other reason</sub>
- [x] This PR is labeled `deploy:gitlab` <sub>or does not require deploying the `gitlab` component</sub>
- [x] This PR is labeled `deploy:runner` <sub>or does not require deploying the `runner` image</sub>

### Author (hotfixes)

- [x] Added `F` tag to main commit title <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [x] Reverted the temporary hotfixes for any connected issues <sub>or the none of the stable branches (`anvilprod` and `prod`) have temporary hotfixes for any of the issues connected to this PR</sub>

### Author (before every review)

- [ ] Rebased PR branch on `develop`, squashed old fixups
- [ ] Ran `make requirements_update` <sub>or this PR does not modify `requirements*.txt`, `common.mk`, `Makefile` and `Dockerfile`</sub>
- [ ] Added `R` tag to commit title <sub>or this PR does not modify `requirements*.txt`</sub>
- [ ] This PR is labeled `reqs` <sub>or does not modify `requirements*.txt`</sub>
- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not modify functionality that could affect the IT outcome</sub>

### Peer reviewer (after approval)

- [ ] PR is not a draft
- [ ] Ticket is in *Review requested* column
- [ ] PR is awaiting requested review from system administrator
- [ ] PR is assigned to only the system administrator

### System administrator (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issues as `demo` or `no demo`
- [ ] Commented on connected issues about demo expectations <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] A comment to this PR details the completed security design review
- [ ] PR title is appropriate as title of merge commit
- [ ] `N reviews` label is accurate
- [ ] Moved ticket to *Approved* column
- [ ] PR is assigned to only the operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex:…` labels and `r` commit title tag
- [ ] Checked that demo expectations are clear <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Squashed PR branch and rebased onto `develop`
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Ran `_select dev.shared && CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR is not labeled `deploy:shared`</sub>
- [ ] Ran `_select dev.gitlab && CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] Ran `_select anvildev.shared && CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR is not labeled `deploy:shared`</sub>
- [ ] Ran `_select anvildev.gitlab && CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] Checked the items in the next section <sub>or this PR is labeled `deploy:gitlab`</sub>
- [ ] PR is assigned to only the system administrator <sub>or this PR is not labeled `deploy:gitlab`</sub>

### System administrator

- [ ] Background migrations for `dev.gitlab` are complete <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] Background migrations for `anvildev.gitlab` are complete <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] PR is assigned to only the operator

### Operator (before pushing merge the commit)

- [ ] Ran `_select dev.gitlab && make -C terraform/gitlab/runner` <sub>or this PR is not labeled `deploy:runner`</sub>
- [ ] Ran `_select anvildev.gitlab && make -C terraform/gitlab/runner` <sub>or this PR is not labeled `deploy:runner`</sub>
- [ ] Added `sandbox` label <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `dev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted unreferenced indices in `sandbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices in `dev`</sub>
- [ ] Deleted unreferenced indices in `anvilbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices in `anvildev`</sub>
- [ ] Started reindex in `sandbox` <sub>or this PR is not labeled `reindex:dev`</sub>
- [ ] Started reindex in `anvilbox` <sub>or this PR is not labeled `reindex:anvildev`</sub>
- [ ] Checked for failures in `sandbox` <sub>or this PR is not  [...]

2024-08-02 17:19 UTC, dsotirho-ucsc commented
[6467_IT_2024-08-02.txt](https://github.com/user-attachments/files/16473361/6467_IT_2024-08-02.txt)

Test of the new PyCharm image by running `make format`:
```
$ git log -n 1 -c
commit 61011d863dc18638a1eec706cd5c0d434b812cde (HEAD -> issues/dsotirho-ucsc/6352-pycharm-image, github/issues/dsotirho-ucsc/6352-pycharm-image)
Author: Daniel Sotirhos <dsotirho@ucsc.edu>
Date:   Fri Aug 2 09:48:32 2024 -0700

    [p] Remove Git from the PyCharm Docker image (#6352)

diff --git a/environment.py b/environment.py
index a1ff3cc8a..c5d141bb2 100644
--- a/environment.py
+++ b/environment.py
@@ -281,7 +281,7 @@ def env() -> Mapping[str, Optional[str]]:
                 'url': 'https://hub.docker.com/_/python',
             },
             'pycharm': {
-                'ref': 'docker.io/ucscgi/azul-pycharm:2024.1.4-27',
+                'ref': 'docker.io/ucscgi/azul-pycharm:2024.1.4-29',
                 'url': 'https://hub.docker.com/repository/docker/ucscgi/azul-pycharm',
                 'is_custom': True
             },
diff --git a/image_manifests.json b/image_manifests.json
index 5cb8d702c..9f4e4e567 100644
--- a/image_manifests.json
+++ b/image_manifests.json
@@ -29,17 +29,17 @@
             }
         }
     },
-    "docker.io/ucscgi/azul-pycharm:2024.1.4-27": {
-        "digest": "sha256:9d7673b74e23b2d1b85b677cad8aaf3afec8dd9dae1e4062df451ca7df98419c",
+    "docker.io/ucscgi/azul-pycharm:2024.1.4-29": {
+        "digest": "sha256:0d64cc3083f225af1a8e8f87532ea39f8679e3d27db9383debe4ddfd3a3971c3",
         "manifests": {
             "linux/amd64": {
-                "digest": "sha256:94cadca4ee4134a54207c444dd8985140e2dc90fff4ddd9fc90f39a60bd79b61",
-                "id": "sha256:5bed946b8e710d30311dfb13e97bc252b32552c0aab661091bae7c233a6f5645",
+                "digest": "sha256:03481106395a2ea9c8c5574a8e31302ada32f096441ac83759969ab666caacd7",
+                "id": "sha256:57294c18ca720658a8a4a64c09463010f82d8929a4e7512f49e98c958c2eb584",
                 "platform": "linux/amd64"
             },
             "linux/arm64": {
-                "digest": "sha256:8e7e55aad6ed7ba066a4d9e4f172a74d09f639fc2466b2823c106b1612229a86",
-                "id": "sha256:bac165e26f2db8619c64f7bedc0f96948c0f51a99b32e853102f6f205cc9261e",
+                "digest": "sha256:cc9fc7231e12730158c2128a8b80e190efea765e33ecc491235d3883bfebbbe1",
+                "id": "sha256:382798ed46630ef3b5b23dc11f8d1a741fb477afcd3cbce2ef34ad76b1c3a7f6",
                 "platform": "linux/arm64"
             }
         }

$ azul_docker_registry="" make format
docker run \
        --rm \
        --volume $(python scripts/resolve_container_path.py /Users/daniel/repo/azul2):/home/developer/azul \
        --workdir /home/developer/azul \
        $(AZUL_DEBUG=0 python -m azul 'docker.resolve_docker_image_for_launch("pycharm")') \
        /opt/pycharm/bin/format.sh -r -settings .pycharm.style.xml -mask '*.py' src scripts test lambdas/layer/app.py lambdas/indexer/app.py lambdas/service/app.py .flake8/azul_flake8.py environment.py deployments/anvilbox/environment.py deployments/anvildev.browser/environment.py deployments/anvildev.gitlab/environment.py deployments/anvildev.shared/environment.py deployments/anvildev/environment.py deployments/anvilprod.browser/environment.py deployments/anvilprod.gitlab/environment.py deployments/anvilprod.shared/environment.py deployments/anvilprod/environment.py deployments/daniel.local/environment.py deployments/dev.gitlab/environment.py deployments/dev.shared/environment.py deployments/dev/environment.py deployments/hammerbox/environment.py deployments/prod.gitlab/environment.py deployments/prod.shared/environment.py deployments/prod/environment.py deployments/sandbox/environment.py deployments/tempdev.browser/environment.py deployments/tempdev.gitlab/environment.py deployments/tempdev.shared/environment.py deployments/tempdev/environment.py .github/workflows/schedule.py terraform/backend.tf.json.template.py terraform/common.tf.json.template.py terraform/step_function.tf.json.template.py terraform/lambda_layer.tf.json.template.py terraform/dynamo.tf.json.template.py terraform/cloudwatch.tf.json.template.py terraform/elasticsearch.tf.json.template.py terraform/api_gateway.tf.json.template.py terraform/providers.tf.json.template.py terraform/authentication.tf.json.template.py terraform/sqs.tf.json.template.py terraform/s3.tf.json.template.py terraform/gitlab/gitlab.tf.json.template.py terraform/shared/shared.tf.json.template.py terraform/browser/browser.tf.json.template.py lambdas/indexer/.chalice/config.json.template.py lambdas/service/.chalice/config.json.template.py .github/pull_request_template.md.template.py
envhook.py: Warning: AZUL_DEBUG is '0' but should be '1', you must run `source environment`
2024-08-02 09:49:18,222    INFO MainThread azul.docker: Resolving image 'pycharm' TagImageRef(registry='docker.io', username='ucscgi', repository=('azul-pycharm',), tag='2024.1.4-29') …
2024-08-02 09:49:18,222    INFO MainThread azul.docker: Pulling image DigestImageRef(registry='docker.io', username='ucscgi', repository=('azul-pycharm',), digest='sha256:0d64cc3083f225af1a8e8f87532ea39f8679e3d27db9383debe4ddfd3a3971c3') …
2024-08-02 09:49:19,005    INFO MainThread azul.docker: Pulled image DigestImageRef(registry='docker.io', username='ucscgi', repository=('azul-pycharm',), digest='sha256:0d64cc3083f225af1a8e8f87532ea39f8679e3d27db9383debe4ddfd3a3971c3')
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true
Aug 02, 2024 4:49:19 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
PyCharm 2024.1.4, build PC-241.18034.82 Formatter
2024-08-02 16:49:19,808 [    333]   WARN - #c.i.s.ComponentManagerImpl - com.intellij.formatting.commandLine.FormatterStarterKt <clinit> requests com.intellij.openapi.application.ApplicationInfo instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
…
Formatting /home/developer/azul/lambdas/indexer/.chalice/config.json.template.py...OK
Formatting /home/developer/azul/lambdas/service/.chalice/config.json.template.py...OK
Formatting /home/developer/azul/.github/pull_request_template.md.template.py...OK

253 file(s) scanned.
253 file(s) formatted.
2024-08-02 16:49:28,538 [   9063] SEVERE - #c.i.o.v.n.RefreshQueue - null
org.jetbrains.concurrency.AsyncPromise$Companion$CANCELED$1
2024-08-02 16:49:28,539 [   9064] SEVERE - #c.i.o.v.n.RefreshQueue - PyCharm 2024.1.4  Build #PC-241.18034.82
2024-08-02 16:49:28,539 [   9064] SEVERE - #c.i.o.v.n.RefreshQueue - JDK: 17.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-08-02 16:49:28,539 [   9064] SEVERE - #c.i.o.v.n.RefreshQueue - OS: Linux
```

2024-08-02 17:22 UTC, dsotirho-ucsc commented
Previous image (azul-pycharm:2024.1.4-28)
<img width="1685" alt="Screenshot 2024-08-01 at 7 51 13 PM" src="https://github.com/user-attachments/assets/769d87bb-5973-4b5a-a704-52e45fc35bf2">

This image (azul-pycharm:2024.1.4-29)
<img width="1687" alt="Screenshot 2024-08-01 at 8 35 34 PM" src="https://github.com/user-attachments/assets/5fb95729-ed0e-41f5-914a-cd081e00ac20">

https://hub.docker.com/repository/docker/ucscgi/azul-pycharm/general
![Screenshot 2024-08-02 at 9 38 09 AM](https://github.com/user-attachments/assets/b079e175-c33a-4794-8fcd-b5a27ea920df)

2024-08-02 17:23 UTC, dsotirho-ucsc commented
[6467_IT_2024-08-02.txt](https://github.com/user-attachments/files/16473402/6467_IT_2024-08-02.txt)

Test of the new PyCharm image with `make format`
```
$ git log -n 1 -c
commit 61011d863dc18638a1eec706cd5c0d434b812cde (HEAD -> issues/dsotirho-ucsc/6352-pycharm-image, github/issues/dsotirho-ucsc/6352-pycharm-image)
Author: Daniel Sotirhos <dsotirho@ucsc.edu>
Date:   Fri Aug 2 09:48:32 2024 -0700

    [p] Remove Git from the PyCharm Docker image (#6352)

diff --git a/environment.py b/environment.py
index a1ff3cc8a..c5d141bb2 100644
--- a/environment.py
+++ b/environment.py
@@ -281,7 +281,7 @@ def env() -> Mapping[str, Optional[str]]:
                 'url': 'https://hub.docker.com/_/python',
             },
             'pycharm': {
-                'ref': 'docker.io/ucscgi/azul-pycharm:2024.1.4-27',
+                'ref': 'docker.io/ucscgi/azul-pycharm:2024.1.4-29',
                 'url': 'https://hub.docker.com/repository/docker/ucscgi/azul-pycharm',
                 'is_custom': True
             },
diff --git a/image_manifests.json b/image_manifests.json
index 5cb8d702c..9f4e4e567 100644
--- a/image_manifests.json
+++ b/image_manifests.json
@@ -29,17 +29,17 @@
             }
         }
     },
-    "docker.io/ucscgi/azul-pycharm:2024.1.4-27": {
-        "digest": "sha256:9d7673b74e23b2d1b85b677cad8aaf3afec8dd9dae1e4062df451ca7df98419c",
+    "docker.io/ucscgi/azul-pycharm:2024.1.4-29": {
+        "digest": "sha256:0d64cc3083f225af1a8e8f87532ea39f8679e3d27db9383debe4ddfd3a3971c3",
         "manifests": {
             "linux/amd64": {
-                "digest": "sha256:94cadca4ee4134a54207c444dd8985140e2dc90fff4ddd9fc90f39a60bd79b61",
-                "id": "sha256:5bed946b8e710d30311dfb13e97bc252b32552c0aab661091bae7c233a6f5645",
+                "digest": "sha256:03481106395a2ea9c8c5574a8e31302ada32f096441ac83759969ab666caacd7",
+                "id": "sha256:57294c18ca720658a8a4a64c09463010f82d8929a4e7512f49e98c958c2eb584",
                 "platform": "linux/amd64"
             },
             "linux/arm64": {
-                "digest": "sha256:8e7e55aad6ed7ba066a4d9e4f172a74d09f639fc2466b2823c106b1612229a86",
-                "id": "sha256:bac165e26f2db8619c64f7bedc0f96948c0f51a99b32e853102f6f205cc9261e",
+                "digest": "sha256:cc9fc7231e12730158c2128a8b80e190efea765e33ecc491235d3883bfebbbe1",
+                "id": "sha256:382798ed46630ef3b5b23dc11f8d1a741fb477afcd3cbce2ef34ad76b1c3a7f6",
                 "platform": "linux/arm64"
             }
         }

$ azul_docker_registry="" make format
docker run \
        --rm \
        --volume $(python scripts/resolve_container_path.py /Users/daniel/repo/azul2):/home/developer/azul \
        --workdir /home/developer/azul \
        $(AZUL_DEBUG=0 python -m azul 'docker.resolve_docker_image_for_launch("pycharm")') \
        /opt/pycharm/bin/format.sh -r -settings .pycharm.style.xml -mask '*.py' src scripts test lambdas/layer/app.py lambdas/indexer/app.py lambdas/service/app.py .flake8/azul_flake8.py environment.py deployments/anvilbox/environment.py deployments/anvildev.browser/environment.py deployments/anvildev.gitlab/environment.py deployments/anvildev.shared/environment.py deployments/anvildev/environment.py deployments/anvilprod.browser/environment.py deployments/anvilprod.gitlab/environment.py deployments/anvilprod.shared/environment.py deployments/anvilprod/environment.py deployments/daniel.local/environment.py deployments/dev.gitlab/environment.py deployments/dev.shared/environment.py deployments/dev/environment.py deployments/hammerbox/environment.py deployments/prod.gitlab/environment.py deployments/prod.shared/environment.py deployments/prod/environment.py deployments/sandbox/environment.py deployments/tempdev.browser/environment.py deployments/tempdev.gitlab/environment.py deployments/tempdev.shared/environment.py deployments/tempdev/environment.py .github/workflows/schedule.py terraform/backend.tf.json.template.py terraform/common.tf.json.template.py terraform/step_function.tf.json.template.py terraform/lambda_layer.tf.json.template.py terraform/dynamo.tf.json.template.py terraform/cloudwatch.tf.json.template.py terraform/elasticsearch.tf.json.template.py terraform/api_gateway.tf.json.template.py terraform/providers.tf.json.template.py terraform/authentication.tf.json.template.py terraform/sqs.tf.json.template.py terraform/s3.tf.json.template.py terraform/gitlab/gitlab.tf.json.template.py terraform/shared/shared.tf.json.template.py terraform/browser/browser.tf.json.template.py lambdas/indexer/.chalice/config.json.template.py lambdas/service/.chalice/config.json.template.py .github/pull_request_template.md.template.py
envhook.py: Warning: AZUL_DEBUG is '0' but should be '1', you must run `source environment`
2024-08-02 09:49:18,222    INFO MainThread azul.docker: Resolving image 'pycharm' TagImageRef(registry='docker.io', username='ucscgi', repository=('azul-pycharm',), tag='2024.1.4-29') …
2024-08-02 09:49:18,222    INFO MainThread azul.docker: Pulling image DigestImageRef(registry='docker.io', username='ucscgi', repository=('azul-pycharm',), digest='sha256:0d64cc3083f225af1a8e8f87532ea39f8679e3d27db9383debe4ddfd3a3971c3') …
2024-08-02 09:49:19,005    INFO MainThread azul.docker: Pulled image DigestImageRef(registry='docker.io', username='ucscgi', repository=('azul-pycharm',), digest='sha256:0d64cc3083f225af1a8e8f87532ea39f8679e3d27db9383debe4ddfd3a3971c3')
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true
Aug 02, 2024 4:49:19 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
PyCharm 2024.1.4, build PC-241.18034.82 Formatter
2024-08-02 16:49:19,808 [    333]   WARN - #c.i.s.ComponentManagerImpl - com.intellij.formatting.commandLine.FormatterStarterKt <clinit> requests com.intellij.openapi.application.ApplicationInfo instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
…
Formatting /home/developer/azul/lambdas/indexer/.chalice/config.json.template.py...OK
Formatting /home/developer/azul/lambdas/service/.chalice/config.json.template.py...OK
Formatting /home/developer/azul/.github/pull_request_template.md.template.py...OK

253 file(s) scanned.
253 file(s) formatted.
2024-08-02 16:49:28,538 [   9063] SEVERE - #c.i.o.v.n.RefreshQueue - null
org.jetbrains.concurrency.AsyncPromise$Companion$CANCELED$1
2024-08-02 16:49:28,539 [   9064] SEVERE - #c.i.o.v.n.RefreshQueue - PyCharm 2024.1.4  Build #PC-241.18034.82
2024-08-02 16:49:28,539 [   9064] SEVERE - #c.i.o.v.n.RefreshQueue - JDK: 17.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-08-02 16:49:28,539 [   9064] SEVERE - #c.i.o.v.n.RefreshQueue - OS: Linux
```

2024-08-05 17:36 UTC, achave11-ucsc requested changes
Looks good, just address merge conflicts.

2024-08-05 19:06 UTC, dsotirho-ucsc commented
[6467_IT_2024-08-05.txt](https://github.com/user-attachments/files/16501758/6467_IT_2024-08-05.txt)

2024-08-05 19:44 UTC, achave11-ucsc approved these changes

2024-08-12 22:12 UTC, hannes-ucsc requested changes
https://github.com/DataBiosphere/azul/pull/6405#issuecomment-2284990232

2024-08-13 16:44 UTC, dsotirho-ucsc commented
Closing this PR to combine into PR #6405

2024-08-13 16:44 UTC, closed without merging