HCA replicas lack DRS URI and descriptor (#6299)
DataBiosphere/azul pull request #6485
Opened 2024-08-07 22:32 UTC by nadove-ucsc

Connected issues: #6299 

## Checklist

### Author

- [x] PR is a draft
- [x] Target branch is `develop`
- [x] Name of PR branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [ ] On ZenHub, PR is connected to all issues it (partially) resolves
- [x] PR description links to connected issues
- [x] PR title matches<sup>1</sup> that of a connected issue <sub>or comment in PR explains why they're different</sub>
- [x] PR title references all connected issues
- [ ] For each connected issue, there is at least one commit whose title references that issue

<sup>1</sup> when the issue title describes a problem, the corresponding PR
title is `Fix: ` followed by the issue title

### Author (partiality)

- [x] Added `p` tag to titles of partial commits
- [x] This PR is labeled `partial` <sub>or completely resolves all connected issues</sub>
- [x] This PR partially resolves each of the connected issues <sub>or does not have the `partial` label</sub>

### Author (chains)

- [x] This PR is blocked by previous PR in the chain <sub>or is not chained to another PR</sub>
- [x] The blocking PR is labeled `base` <sub>or this PR is not chained to another PR</sub>
- [x] This PR is labeled `chained` <sub>or is not chained to another PR</sub>

### Author (reindex, API changes)

- [x] Added `r` tag to commit title <sub>or the changes introduced by this PR will not require reindexing of any deployment</sub>
- [x] This PR is labeled `reindex:dev` <sub>or the changes introduced by it will not require reindexing of `dev`</sub>
- [x] This PR is labeled `reindex:anvildev` <sub>or the changes introduced by it will not require reindexing of `anvildev`</sub>
- [x] This PR is labeled `reindex:anvilprod` <sub>or the changes introduced by it will not require reindexing of `anvilprod`</sub>
- [x] This PR is labeled `reindex:prod` <sub>or the changes introduced by it will not require reindexing of `prod`</sub>
- [x] This PR is labeled `reindex:partial` and its description documents the specific reindexing procedure for `dev`, `anvildev`, `anvilprod` and `prod` <sub>or requires a full reindex or carries none of the labels `reindex:dev`, `reindex:anvildev`, `reindex:anvilprod` and `reindex:prod`</sub>
- [x] This PR and its connected issues are labeled `API` <sub>or this PR does not modify a REST API</sub>
- [x] Added `a` (`A`) tag to commit title for backwards (in)compatible changes <sub>or this PR does not modify a REST API</sub>
- [x] Updated REST API version number in `app.py` <sub>or this PR does not modify a REST API</sub>

### Author (upgrading deployments)

- [x] Ran `make image_manifests.json` and committed the resulting changes <sub>or this PR does not modify `azul_docker_images`, or any other variables referenced in the definition of that variable</sub>
- [x] Documented upgrading of deployments in UPGRADING.rst <sub>or this PR does not require upgrading deployments</sub>
- [x] Added `u` tag to commit title <sub>or this PR does not require upgrading deployments</sub>
- [x] This PR is labeled `upgrade` <sub>or does not require upgrading deployments</sub>
- [x] This PR is labeled `deploy:shared` <sub>or does not modify `image_manifests.json`, and does not require deploying the `shared` component for any other reason</sub>
- [x] This PR is labeled `deploy:gitlab` <sub>or does not require deploying the `gitlab` component</sub>
- [x] This PR is labeled `deploy:runner` <sub>or does not require deploying the `runner` image</sub>

### Author (hotfixes)

- [x] Added `F` tag to main commit title <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [x] Reverted the temporary hotfixes for any connected issues <sub>or the none of the stable branches (`anvilprod` and `prod`) have temporary hotfixes for any of the issues connected to this PR</sub>

### Author (before every review)

- [x] Rebased PR branch on `develop`, squashed old fixups
- [x] Ran `make requirements_update` <sub>or this PR does not modify `requirements*.txt`, `common.mk`, `Makefile` and `Dockerfile`</sub>
- [x] Added `R` tag to commit title <sub>or this PR does not modify `requirements*.txt`</sub>
- [x] This PR is labeled `reqs` <sub>or does not modify `requirements*.txt`</sub>
- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not modify functionality that could affect the IT outcome</sub>

### Peer reviewer (after approval)

- [ ] PR is not a draft
- [ ] Ticket is in *Review requested* column
- [ ] PR is awaiting requested review from system administrator
- [ ] PR is assigned to only the system administrator

### System administrator (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issues as `demo` or `no demo`
- [ ] Commented on connected issues about demo expectations <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] A comment to this PR details the completed security design review
- [ ] PR title is appropriate as title of merge commit
- [ ] `N reviews` label is accurate
- [ ] Moved ticket to *Approved* column
- [ ] PR is assigned to only the operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex:…` labels and `r` commit title tag
- [ ] Checked that demo expectations are clear <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Squashed PR branch and rebased onto `develop`
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Ran `_select dev.shared && CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR is not labeled `deploy:shared`</sub>
- [ ] Ran `_select dev.gitlab && CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] Ran `_select anvildev.shared && CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR is not labeled `deploy:shared`</sub>
- [ ] Ran `_select anvildev.gitlab && CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] Checked the items in the next section <sub>or this PR is labeled `deploy:gitlab`</sub>
- [ ] PR is assigned to only the system administrator <sub>or this PR is not labeled `deploy:gitlab`</sub>

### System administrator

- [ ] Background migrations for `dev.gitlab` are complete <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] Background migrations for `anvildev.gitlab` are complete <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] PR is assigned to only the operator

### Operator (before pushing merge the commit)

- [ ] Ran `_select dev.gitlab && make -C terraform/gitlab/runner` <sub>or this PR is not labeled `deploy:runner`</sub>
- [ ] Ran `_select anvildev.gitlab && make -C terraform/gitlab/runner` <sub>or this PR is not labeled `deploy:runner`</sub>
- [ ] Added `sandbox` label <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `dev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted unreferenced indices in `sandbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices in `dev`</sub>
- [ ] Deleted unreferenced indices in `anvilbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices in `anvildev`</sub>
- [ ] Started reindex in `sandbox` <sub>or this PR is not labeled `reindex:dev`</sub>
- [ ] Started reindex in `anvilbox` <sub>or this PR is not labeled `reindex:anvildev`</sub>
- [ ] Checked for failures in `sandbox` <sub>or this PR is not [...]

2024-08-10 05:41 UTC, nadove-ucsc commented
Most recent IT success in on `885f61fd1`

2024-08-24 04:42 UTC, nadove-ucsc commented
Integration tests were run for multiple commits on this branch. All tested commits passed IT. Commits tested:
 - d97432e10d2228c04ba3f564ff5c42d3e806ab33
 - 3f41ea4141e95ee543afccaa68517e4771b9e4f3
 - 25aeb676a2dd83094e4ad191194bd261bbae3636
 - e0ac6e395683cefe661dad478f8e16d66e282cff
 - 7cb94315f31b3f80786d5ed0f92cbe6005af9bc4
 - f10c22ef075c6e0533319b4425f010488a8d91f1
 - eac60f092f8963fb2121987ae5dd96d1eb50425c

2024-08-24 04:55 UTC, nadove-ucsc commented
As of HEAD eac60f092f8963fb2121987ae5dd96d1eb50425c, the following work remains outstanding for issue https://github.com/DataBiosphere/azul/issues/6299:

Eliminate the notion of a "manifest" from HCA bundles. Replace the manifest entries with verbatim copies of file descriptors, and add a level of nesting to the "metadata" attribute so that the existing values are moved to a property called "content". For some entities, this will be the only property, but files will have two additional properties: "descriptor" and "file_id". The intent is for the properties of each value to correspond to BigQuery columns.

Once this restructuring is complete, we can include these additional properties in the replicas. The verbatim manifest generator will then partially flatten the replicas as explained [here](https://github.com/DataBiosphere/azul/issues/6299#issuecomment-2225974816), using `__` (two underscores) as a path separator.

2024-08-24 05:02 UTC, nadove-ucsc commented
Addendum: the `stitched` attribute added in this PR could also be folded into the properties of the metadata values, acting like a pseudo-column. If this is done, then the new, refactored structure of HCA bundles will very closely resemble the current structure of AnVIL bundles. It may be then be relatively low hanging fruit to eliminate the remaining inconsistencies' in `HCABundle` and `AnvilBundle`'s interfaces, which could help streamline a lot of our testing code.

2024-08-26 18:01 UTC, achave11-ucsc reviewed
Nicely done, very clean.
Consider that there are some additions/modifications introduced in the initial commits which qualify for `L`, but are addressed later in the commit history. If the line length is addressed in the initial modification/addition, the changes introduced in latter commits might be more obvious, just a nit pick.

2024-08-26 18:01 UTC, achave11-ucsc commented on test/hca_metadata_api/test.py
> +        return os.path.join(os.path.dirname(__file__), 'cans', directory, f'{uuid}.{version}.json')
L

2024-08-26 18:01 UTC, achave11-ucsc commented on src/humancellatlas/data/metadata/api.py
> +            raise
Is there an added benefit to this, or are other types of exceptions OK?
It seems a bit unusual, but I may be missing something.

2024-08-26 18:01 UTC, achave11-ucsc commented on src/humancellatlas/data/metadata/helpers/staging_area.py
> +    def get_bundle_parts(self, subgraph_id: str) -> tuple[str, MutableJSONs, MutableJSON, MutableJSON]:
L

2024-08-26 21:14 UTC, nadove-ucsc commented on src/humancellatlas/data/metadata/api.py
> +            raise
This is a pattern I use while debugging (by putting a breakpoint on the `raise` statement). It should not have been added to the commit.

2024-08-27 05:49 UTC, nadove-ucsc commented
> Consider that there are some additions/modifications introduced in the initial commits which qualify for L, but are addressed later in the commit history. If the line length is addressed in the initial modification/addition, the changes introduced in latter commits might be more obvious, just a nit pick.

Can you provide any examples? I'm not sure I understand what you mean.

2024-08-29 00:17 UTC, dsotirho-ucsc requested changes
Nicely done. Just a few nits to consider.

2024-08-29 00:17 UTC, dsotirho-ucsc commented on src/humancellatlas/data/metadata/helpers/schema_validation.py
>      JSON,
This should import `JSON` from `azul.types` like you did in `staging_area.py`.

2024-08-29 00:17 UTC, dsotirho-ucsc commented on src/humancellatlas/data/metadata/api.py
>      Union,
`Union` could also be replaced with `x | y` notation as part of the `Eliminate old-style type annotations in src/humancellatlas` commit.

2024-08-29 00:17 UTC, dsotirho-ucsc commented on src/azul/plugins/repository/tdr_hca/__init__.py
> +
```suggestion
```

2024-08-29 00:17 UTC, dsotirho-ucsc commented on attic/scripts/recan_bundle_tdr.py
> -        entry['is_stitched'] = False
We generally don't modify files once they've been moved to the attic.

2024-08-29 00:17 UTC, dsotirho-ucsc commented on test/hca_metadata_api/test.py
> +    def _assert_bundle(self, uuid, version, manifest, metadata_files, links,
```suggestion
    def _assert_bundle(self, uuid, version, manifest, metadata, links,
```
To match the changes in commit `Rename attribute and derived variables`

2024-08-29 02:27 UTC, dsotirho-ucsc submitted a review, later dismissed
Approved.

2024-08-29 22:37 UTC, hannes-ucsc requested changes
The commit 0143d57d (Fix mismatched entity IDs in canned TDR table) would benefit from a commit message body explaining the problem that it fixes. Similarly with b7d6c734 (Remove dangling manifest entries in canned bundles). It feels like these commits are anticipating a later code change and would break the build if built separately. If that's not the case, the commit message should briefly explain why. Otherwise, a split commit might be a better vehicle for communicating the codependency between commits. Happy to discuss in huddle or PL.

2024-08-29 22:37 UTC, hannes-ucsc commented on src/humancellatlas/data/metadata/api.py
> +        self.stitched = stitched_entity_ids
The spirit of this class is to track all UUIDs as instances of the `UUID4` class. That's actually a good thing since the string representation of UUIDs is ambiguous with respect to the case of hexadecimal digits. We probably have numerous places where we are vulnerable to that bug and I don't expect to fix all of them now but unless it's prohibitively difficult (more than a couple of hours of work), I'd prefer `self.stitched` to be a set of `UUID4` instances.

2024-08-30 00:29 UTC, hannes-ucsc requested changes
Also, please move your comments regarding the outstanding work from this PR to the issue.

2024-08-30 23:59 UTC, hannes-ucsc approved these changes

2024-08-31 00:00 UTC, hannes-ucsc commented
### Security design review

- [x] Security design review completed; this PR does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with Terra 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

2024-09-03 23:24 UTC, merged