Eliminate RepositoryPlugin.list_partitions (#6531)
DataBiosphere/azul pull request #6554
Opened 2024-09-10 04:17 UTC by nadove-ucsc

Connected issues: #6531

## Checklist

### Author

- [x] PR is a draft
- [x] Target branch is `develop`
- [x] Name of PR branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [ ] On ZenHub, PR is connected to all issues it (partially) resolves
- [x] PR description links to connected issues
- [x] PR title matches<sup>1</sup> that of a connected issue <sub>or comment in PR explains why they're different</sub>
- [x] PR title references all connected issues
- [ ] For each connected issue, there is at least one commit whose title references that issue

<sup>1</sup> when the issue title describes a problem, the corresponding PR
title is `Fix: ` followed by the issue title

### Author (partiality)

- [x] Added `p` tag to titles of partial commits
- [x] This PR is labeled `partial` <sub>or completely resolves all connected issues</sub>
- [x] This PR partially resolves each of the connected issues <sub>or does not have the `partial` label</sub>

### Author (chains)

- [x] This PR is blocked by previous PR in the chain <sub>or is not chained to another PR</sub>
- [x] The blocking PR is labeled `base` <sub>or this PR is not chained to another PR</sub>
- [x] This PR is labeled `chained` <sub>or is not chained to another PR</sub>

### Author (reindex, API changes)

- [x] Added `r` tag to commit title <sub>or the changes introduced by this PR will not require reindexing of any deployment</sub>
- [x] This PR is labeled `reindex:dev` <sub>or the changes introduced by it will not require reindexing of `dev`</sub>
- [x] This PR is labeled `reindex:anvildev` <sub>or the changes introduced by it will not require reindexing of `anvildev`</sub>
- [x] This PR is labeled `reindex:anvilprod` <sub>or the changes introduced by it will not require reindexing of `anvilprod`</sub>
- [x] This PR is labeled `reindex:prod` <sub>or the changes introduced by it will not require reindexing of `prod`</sub>
- [x] This PR is labeled `reindex:partial` and its description documents the specific reindexing procedure for `dev`, `anvildev`, `anvilprod` and `prod` <sub>or requires a full reindex or carries none of the labels `reindex:dev`, `reindex:anvildev`, `reindex:anvilprod` and `reindex:prod`</sub>
- [x] This PR and its connected issues are labeled `API` <sub>or this PR does not modify a REST API</sub>
- [x] Added `a` (`A`) tag to commit title for backwards (in)compatible changes <sub>or this PR does not modify a REST API</sub>
- [x] Updated REST API version number in `app.py` <sub>or this PR does not modify a REST API</sub>

### Author (upgrading deployments)

- [x] Ran `make docker_images.json` and committed the resulting changes <sub>or this PR does not modify `azul_docker_images`, or any other variables referenced in the definition of that variable</sub>
- [ ] Documented upgrading of deployments in UPGRADING.rst <sub>or this PR does not require upgrading deployments</sub>
- [ ] Added `u` tag to commit title <sub>or this PR does not require upgrading deployments</sub>
- [x] This PR is labeled `upgrade` <sub>or does not require upgrading deployments</sub>
- [x] This PR is labeled `deploy:shared` <sub>or does not modify `docker_images.json`, and does not require deploying the `shared` component for any other reason</sub>
- [x] This PR is labeled `deploy:gitlab` <sub>or does not require deploying the `gitlab` component</sub>
- [x] This PR is labeled `deploy:runner` <sub>or does not require deploying the `runner` image</sub>

### Author (hotfixes)

- [x] Added `F` tag to main commit title <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [x] Reverted the temporary hotfixes for any connected issues <sub>or the none of the stable branches (`anvilprod` and `prod`) have temporary hotfixes for any of the issues connected to this PR</sub>

### Author (before every review)

- [ ] Rebased PR branch on `develop`, squashed old fixups
- [x] Ran `make requirements_update` <sub>or this PR does not modify `requirements*.txt`, `common.mk`, `Makefile` and `Dockerfile`</sub>
- [x] Added `R` tag to commit title <sub>or this PR does not modify `requirements*.txt`</sub>
- [x] This PR is labeled `reqs` <sub>or does not modify `requirements*.txt`</sub>
- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not modify functionality that could affect the IT outcome</sub>

### Peer reviewer (after approval)

- [ ] PR is not a draft
- [ ] Ticket is in *Review requested* column
- [ ] PR is awaiting requested review from system administrator
- [ ] PR is assigned to only the system administrator

### System administrator (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issues as `demo` or `no demo`
- [ ] Commented on connected issues about demo expectations <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] A comment to this PR details the completed security design review
- [ ] PR title is appropriate as title of merge commit
- [ ] `N reviews` label is accurate
- [ ] Moved connected issues to *Approved* column
- [ ] PR is assigned to only the operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex:…` labels and `r` commit title tag
- [ ] Checked that demo expectations are clear <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Squashed PR branch and rebased onto `develop`
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Ran `_select dev.shared && CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR is not labeled `deploy:shared`</sub>
- [ ] Ran `_select dev.gitlab && CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] Ran `_select anvildev.shared && CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR is not labeled `deploy:shared`</sub>
- [ ] Ran `_select anvildev.gitlab && CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] Checked the items in the next section <sub>or this PR is labeled `deploy:gitlab`</sub>
- [ ] PR is assigned to only the system administrator <sub>or this PR is not labeled `deploy:gitlab`</sub>

### System administrator

- [ ] Background migrations for `dev.gitlab` are complete <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] Background migrations for `anvildev.gitlab` are complete <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] PR is assigned to only the operator

### Operator (before pushing merge the commit)

- [ ] Ran `_select dev.gitlab && make -C terraform/gitlab/runner` <sub>or this PR is not labeled `deploy:runner`</sub>
- [ ] Ran `_select anvildev.gitlab && make -C terraform/gitlab/runner` <sub>or this PR is not labeled `deploy:runner`</sub>
- [ ] Added `sandbox` label <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `dev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted unreferenced indices in `sandbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices in `dev`</sub>
- [ ] Deleted unreferenced indices in `anvilbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices in `anvildev`</sub>
- [ ] Started reindex in `sandbox` <sub>or this PR is not labeled `reindex:dev`</sub>
- [ ] Started reindex in `anvilbox` <sub>or this PR is not labeled `reindex:anvildev`</sub>
- [ ] Checked for failures in `sandbox` <sub>or this PR i [...]

2024-09-13 17:52 UTC, dsotirho-ucsc requested changes

2024-09-13 17:52 UTC, dsotirho-ucsc commented on src/azul/plugins/metadata/hca/indexer/transform.py
> +    def for_id(cls, submitter_id: str) -> 'Submitter | None':
```suggestion
    def for_id(cls, submitter_id: str) -> Self | None:
```

2024-09-13 17:52 UTC, dsotirho-ucsc commented on src/azul/plugins/metadata/hca/indexer/transform.py
> +    def for_file(cls, file: api.File) -> 'Submitter | None':
```suggestion
    def for_file(cls, file: api.File) -> Self | None:
```

2024-09-13 17:52 UTC, dsotirho-ucsc commented on deployments/dev/environment.py
>  lungmap_sources = mkdict({}, 2, mkdelta([
The old `subgraphs` argument `1` needs to be removed from these sources

2024-09-18 20:50 UTC, dsotirho-ucsc requested changes

2024-09-18 20:50 UTC, dsotirho-ucsc commented on test/integration_test.py
> -    def _list_bundles(self,
A comment in `_prepare_notifications()` that references `_list_bundles()` needs to be updated.

2024-09-18 23:49 UTC, dsotirho-ucsc approved these changes, later dismissed
Approved.

2024-09-23 22:38 UTC, hannes-ucsc requested changes
Please separate the annotation commits, one for Optional, one for Set/AbstractSet, one for Type and so on as needed.

```diff
Index: src/azul/plugins/__init__.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/plugins/__init__.py b/src/azul/plugins/__init__.py
--- a/src/azul/plugins/__init__.py	(revision 10d286acf57927b4757171cd66b4055bd11743aa)
+++ b/src/azul/plugins/__init__.py	(date 1727114349843)
@@ -613,8 +613,9 @@
     @abstractmethod
     def _count_subgraphs(self, source: SOURCE_SPEC) -> int:
         """
-        Count the total number of subgraphs stored in the given source, ignoring
-        its prefix.
+        The total number of subgraphs in the given source, ignoring its prefix.
+
+        REVIEW: Zero seems to have special meaning, which should be documented.
         """
         raise NotImplementedError
 
@@ -634,9 +635,9 @@
             # We use the "other" heuristic during IT to avoid indexing an
             # excessive number of bundles
             if is_main and not is_it:
-                prefix = Prefix.for_main_source(count)
+                prefix = Prefix.for_main_deployment(count)
             else:
-                prefix = Prefix.for_other_source(count)
+                prefix = Prefix.for_lesser_deployment(count)
             source = attr.evolve(source, spec=attr.evolve(source.spec, prefix=prefix))
         return source
 
Index: src/azul/plugins/repository/canned/__init__.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/plugins/repository/canned/__init__.py b/src/azul/plugins/repository/canned/__init__.py
--- a/src/azul/plugins/repository/canned/__init__.py	(revision 10d286acf57927b4757171cd66b4055bd11743aa)
+++ b/src/azul/plugins/repository/canned/__init__.py	(date 1727114148447)
@@ -164,6 +164,7 @@
             return factory.load_staging_area(path)
 
     def _count_subgraphs(self, source: SOURCE_SPEC) -> int:
+        # REVIEW: A comment should explain why 0 is a suitable value
         return 0
 
     def list_bundles(self,
Index: scripts/post_deploy_tdr.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/scripts/post_deploy_tdr.py b/scripts/post_deploy_tdr.py
--- a/scripts/post_deploy_tdr.py	(revision 10d286acf57927b4757171cd66b4055bd11743aa)
+++ b/scripts/post_deploy_tdr.py	(date 1726853400195)
@@ -58,8 +58,10 @@
         result = [
             catalog.name
             for catalog in config.catalogs.values()
-            if (config.is_tdr_enabled(catalog.name)
-                and catalog.name not in config.integration_test_catalogs)
+            if (
+                config.is_tdr_enabled(catalog.name)
+                and catalog.name not in config.integration_test_catalogs
+            )
         ]
         assert result, config.catalogs
         return result
Index: src/azul/plugins/repository/dss/__init__.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/plugins/repository/dss/__init__.py b/src/azul/plugins/repository/dss/__init__.py
--- a/src/azul/plugins/repository/dss/__init__.py	(revision 10d286acf57927b4757171cd66b4055bd11743aa)
+++ b/src/azul/plugins/repository/dss/__init__.py	(date 1727114349847)
@@ -118,6 +118,7 @@
         return DSSSourceRef.id_from_spec(spec)
 
     def _count_subgraphs(self, source: SimpleSourceSpec) -> int:
+        # REVIEW: A comment should explain why 0 is a suitable value
         return 0
 
     def list_sources(self,
Index: src/azul/terra.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/terra.py b/src/azul/terra.py
--- a/src/azul/terra.py	(revision 10d286acf57927b4757171cd66b4055bd11743aa)
+++ b/src/azul/terra.py	(date 1726852810880)
@@ -139,7 +139,8 @@
         ...
         ValueError: 'eggs' is not a valid TDRSourceSpec.Domain
 
-        >>> # If any :'s are missing, the last part will be interpreted as the prefix
+        If any :'s are missing, the last part will be interpreted as the prefix
+
         >>> TDRSourceSpec.parse('tdr:bigquery:gcp:foo:bar')
         Traceback (most recent call last):
         ...
Index: src/azul/indexer/__init__.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/indexer/__init__.py b/src/azul/indexer/__init__.py
--- a/src/azul/indexer/__init__.py	(revision 10d286acf57927b4757171cd66b4055bd11743aa)
+++ b/src/azul/indexer/__init__.py	(date 1727130748825)
@@ -21,7 +21,8 @@
     TypedDict,
 )
 
-import attr
+# REVIEW: We shouldn't mix the old and the new API, converting a module to the
+#         new API should happen in a separate commit
 import attrs
 
 from azul import (
@@ -144,34 +145,36 @@
         return cls(common=entry, partition=partition)
 
     @classmethod
-    def for_main_source(cls, subgraphs: int) -> Self:
+    def for_main_deployment(cls, num_subgraphs: int) -> Self:
         """
         A prefix that is expected to rarely exceed 8192 subgraphs per partition
 
-        >>> str(Prefix.for_main_source(0))
+        >>> str(Prefix.for_main_deployment(0))
         Traceback (most recent call last):
         ...
         ValueError: math domain error
 
-        >>> str(Prefix.for_main_source(1))
+        >>> str(Prefix.for_main_deployment(1))
         '/0'
 
-        >>> n = 8192
         >>> cases = [-1, 0, 1, 2]
-        >>> [str(Prefix.for_main_source(n + i)) for i in cases]
+
+        >>> n = 8192
+        >>> [str(Prefix.for_main_deployment(n + i)) for i in cases]
         ['/0', '/0', '/1', '/1']
 
-        >>> # Sources with this many bundles are very rare, so we have a
-        >>> # generous margin of error surrounding this cutoff point
-        >>> n *= 16  # 131072
-        >>> [str(Prefix.for_main_source(n + i)) for i in cases]
+        Sources with this many bundles are very rare, so we have a generous
+        margin of error surrounding this cutoff point
+
+        >>> n = 8192 * 16
+        >>> [str(Prefix.for_main_deployment(n + i)) for i in cases]
         ['/1', '/1', '/2', '/2']
         """
-        partition = cls._prefix_length(subgraphs, 8192)
+        partition = cls._prefix_length(num_subgraphs, 8192)
         return cls(common='', partition=partition)
 
     @classmethod
-    def for_other_source(cls, subgraphs: int) -> Self:
+    def for_lesser_deployment(cls, num_subgraphs: int) -> Self:
         """
         A prefix that yields an average of approximately 24 subgraphs per
         source, using an experimentally derived heuristic formula designed to
@@ -179,26 +182,27 @@
         partition prefix length is always 1, even though some partitions may be
         empty, to provide test coverage for handling multiple partitions.
 
-        >>> str(Prefix.for_other_source(0))
+        >>> str(Prefix.for_lesser_deployment(0))
         Traceback (most recent call last):
         ...
         ValueError: math domain error
 
-        >>> str(Prefix.for_other_source(1))
+        >>> str(Prefix.for_lesser_deployment(1))
         '/1'
 
-        >>> n = 64
         >>> cases = [-1, 0, 1, 2]
-        >>> [str(Prefix.for_other_source(n + i)) for i in cases]
+
+        >>> n = 64
+        >>> [str(Prefix.for_lesser_deployment(n + i)) for i in cases]
         ['/1', '/1', '0/1', '1/1']
 
-        >>> n *= 16  # 1024
-        >>> [str(Prefix.for_other_source(n + i)) for i in cases]
+        >>> n = 64 * 16
+        >>> [str(Prefix.for_lesser_d [...]

2024-09-24 01:34 UTC, nadove-ucsc commented
> REVIEW: Zero seems to have special meaning, which should be documented.
> REVIEW: A comment should explain why 0 is a suitable value

I was just using zero as a placeholder with the expectation that those overrides would never actually be called. It has no special meaning at the call site and would raise if actually encountered there. I've replaced it with an actual implementation for the Canned plugin (untested as its never called) and an assertion for the DSS plugin.

2024-09-24 01:49 UTC, nadove-ucsc commented
> REVIEW: A comment should explain what the significance of None is and
              how that differs from '', assuming we need the distinction. If we
              don't, I would prefer to represent that case with '' instead of
              None.

This makes no sense to me. The `prefix` field can never be equal to `''` because the type annotation `Prefix | None` does not permit instances of `str`. Furthermore, [the empty string cannot be parsed as a Prefix](https://github.com/DataBiosphere/azul/blob/e8c2280039206d42dbd3623611f32c02fa16708b/src/azul/indexer/__init__.py#L126), and there is no instance of `Prefix` whose string representation is `''`. The "distinction" is therefore that `None` is a valid possible value for this field and the empty string is not.

2024-09-24 01:52 UTC, nadove-ucsc commented
> REVIEW: We shouldn't mix the old and the new API, converting a module to the
         new API should happen in a separate commit

The module already consistently uses the new API. I just mistakenly added an import from old one.

2024-09-25 02:05 UTC, hannes-ucsc submitted a review, later dismissed
One nit: 

```diff

Index: src/azul/terra.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/terra.py b/src/azul/terra.py
--- a/src/azul/terra.py	(revision fa3db5c97b3ca226862c3b844244581b75381d5d)
+++ b/src/azul/terra.py	(date 1727228818605)
@@ -202,7 +202,7 @@
             self.domain.value,
             self.subdomain,
             self.name,
-            self._prefix_str()
+            self._prefix_str
         ])
 
     def qualify_table(self, table_name: str) -> str:
Index: src/azul/indexer/__init__.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/indexer/__init__.py b/src/azul/indexer/__init__.py
--- a/src/azul/indexer/__init__.py	(revision fa3db5c97b3ca226862c3b844244581b75381d5d)
+++ b/src/azul/indexer/__init__.py	(date 1727228818618)
@@ -283,6 +283,7 @@
         prefix = Prefix.parse(prefix) if prefix else None
         return rest, prefix
 
+    @property
     def _prefix_str(self) -> str:
         return '' if self.prefix is None else str(self.prefix)
 
@@ -352,7 +353,7 @@
         >>> s == str(SimpleSourceSpec.parse(s))
         True
         """
-        return f'{self.name}:{self._prefix_str()}'
+        return f'{self.name}:{self._prefix_str}'
 
 
 class SourceJSON(TypedDict):
```

The rest looks good. When you merge this please closely monitor the reindex in `dev` and `anvildev`. As a baseline, please perform the equivalent reindex on `develop` prior to merging this. We should wait with promoting it until I can weigh in during stand-up next week, and if we promote it, it should be promoted separately which implies first promoting the parent commit and following that up with another promotion of the merge commit. The first of these two promotions should be ad-hoc (as opposed to scheduled), happen midweek, and wouldn't involve a reindex. The second would happen on a Friday so that the reindex falls on the weekend.

2024-09-26 20:50 UTC, achave11-ucsc reviewed
Looks good 🦭✅

🔎👁️ Integration Test CL item is unchecked, maybe it didn't stick?

Feel free to incorporate the fixup commits for the next round.

2024-09-27 02:17 UTC, achave11-ucsc approved these changes
Approved ✅

2024-09-27 02:19 UTC, achave11-ucsc commented
Assigned @dsotirho-ucsc for a second review on this PR, [as prescribed in Slack](https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1727378403924689).

2024-09-27 18:28 UTC, dsotirho-ucsc requested changes
Nit:
- `typing.Self` could be applied in other locations inside `/src/azul/indexer/__init__.py` such as `SimpleSourceSpec.parse`, `SourceRef.from_json`, `SourcedBundleFQID.from_json`, and `Bundle.from_json`.

2024-09-27 19:37 UTC, nadove-ucsc commented
As discussed at PL, I'm choosing not to incorporate every potential use of `typing.Self` in this PR to avoid modifying a large number of unrelated files.

2024-09-27 23:14 UTC, dsotirho-ucsc approved these changes
Approved.

2024-09-27 23:31 UTC, nadove-ucsc commented
### Security design review

- [x] Security design review completed; this PR does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with Terra 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

2024-09-28 15:22 UTC, merged

2024-10-02 22:22 UTC, achave11-ucsc commented
Removing `do not promote` label, since it's no longer appropriate.