Fix: No replicas for donors in HCA (#6582)
DataBiosphere/azul pull request #6584
Opened 2024-09-20 02:52 UTC by nadove-ucsc

Connected issues: #6582

## Checklist

### Author

- [x] PR is a draft
- [x] Target branch is `develop`
- [x] Name of PR branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [ ] On ZenHub, PR is connected to all issues it (partially) resolves
- x ] PR description links to connected issues
- [x] PR title matches<sup>1</sup> that of a connected issue <sub>or comment in PR explains why they're different</sub>
- [x] PR title references all connected issues
- [x] For each connected issue, there is at least one commit whose title references that issue

<sup>1</sup> when the issue title describes a problem, the corresponding PR
title is `Fix: ` followed by the issue title

### Author (partiality)

- [x] Added `p` tag to titles of partial commits
- [x] This PR is labeled `partial` <sub>or completely resolves all connected issues</sub>
- [x] This PR partially resolves each of the connected issues <sub>or does not have the `partial` label</sub>

### Author (chains)

- [x] This PR is blocked by previous PR in the chain <sub>or is not chained to another PR</sub>
- [x] The blocking PR is labeled `base` <sub>or this PR is not chained to another PR</sub>
- [x] This PR is labeled `chained` <sub>or is not chained to another PR</sub>

### Author (reindex, API changes)

- [x] Added `r` tag to commit title <sub>or the changes introduced by this PR will not require reindexing of any deployment</sub>
- [ ] This PR is labeled `reindex:dev` <sub>or the changes introduced by it will not require reindexing of `dev`</sub>
- [x] This PR is labeled `reindex:anvildev` <sub>or the changes introduced by it will not require reindexing of `anvildev`</sub>
- [x] This PR is labeled `reindex:anvilprod` <sub>or the changes introduced by it will not require reindexing of `anvilprod`</sub>
- [ ] This PR is labeled `reindex:prod` <sub>or the changes introduced by it will not require reindexing of `prod`</sub>
- [x] This PR is labeled `reindex:partial` and its description documents the specific reindexing procedure for `dev`, `anvildev`, `anvilprod` and `prod` <sub>or requires a full reindex or carries none of the labels `reindex:dev`, `reindex:anvildev`, `reindex:anvilprod` and `reindex:prod`</sub>
- [x] This PR and its connected issues are labeled `API` <sub>or this PR does not modify a REST API</sub>
- [x] Added `a` (`A`) tag to commit title for backwards (in)compatible changes <sub>or this PR does not modify a REST API</sub>
- [x] Updated REST API version number in `app.py` <sub>or this PR does not modify a REST API</sub>

### Author (upgrading deployments)

- [x] Ran `make docker_images.json` and committed the resulting changes <sub>or this PR does not modify `azul_docker_images`, or any other variables referenced in the definition of that variable</sub>
- [x] Documented upgrading of deployments in UPGRADING.rst <sub>or this PR does not require upgrading deployments</sub>
- [x] Added `u` tag to commit title <sub>or this PR does not require upgrading deployments</sub>
- [x] This PR is labeled `upgrade` <sub>or does not require upgrading deployments</sub>
- [x] This PR is labeled `deploy:shared` <sub>or does not modify `docker_images.json`, and does not require deploying the `shared` component for any other reason</sub>
- [x] This PR is labeled `deploy:gitlab` <sub>or does not require deploying the `gitlab` component</sub>
- [x] This PR is labeled `deploy:runner` <sub>or does not require deploying the `runner` image</sub>

### Author (hotfixes)

- [x] Added `F` tag to main commit title <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [x] Reverted the temporary hotfixes for any connected issues <sub>or the none of the stable branches (`anvilprod` and `prod`) have temporary hotfixes for any of the issues connected to this PR</sub>

### Author (before every review)

- [x] Rebased PR branch on `develop`, squashed old fixups
- [x] Ran `make requirements_update` <sub>or this PR does not modify `requirements*.txt`, `common.mk`, `Makefile` and `Dockerfile`</sub>
- [x] Added `R` tag to commit title <sub>or this PR does not modify `requirements*.txt`</sub>
- [x] This PR is labeled `reqs` <sub>or does not modify `requirements*.txt`</sub>
- [ ] `make integration_test` passes in personal deployment <sub>or this PR does not modify functionality that could affect the IT outcome</sub>

### Peer reviewer (after approval)

- [ ] PR is not a draft
- [ ] Ticket is in *Review requested* column
- [ ] PR is awaiting requested review from system administrator
- [ ] PR is assigned to only the system administrator

### System administrator (after approval)

- [ ] Actually approved the PR
- [ ] Labeled connected issues as `demo` or `no demo`
- [ ] Commented on connected issues about demo expectations <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Decided if PR can be labeled `no sandbox`
- [ ] A comment to this PR details the completed security design review
- [ ] PR title is appropriate as title of merge commit
- [ ] `N reviews` label is accurate
- [ ] Moved connected issues to *Approved* column
- [ ] PR is assigned to only the operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex:…` labels and `r` commit title tag
- [ ] Checked that demo expectations are clear <sub>or all connected issues are labeled `no demo`</sub>
- [ ] Squashed PR branch and rebased onto `develop`
- [ ] Sanity-checked history
- [ ] Pushed PR branch to GitHub
- [ ] Ran `_select dev.shared && CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR is not labeled `deploy:shared`</sub>
- [ ] Ran `_select dev.gitlab && CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] Ran `_select anvildev.shared && CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR is not labeled `deploy:shared`</sub>
- [ ] Ran `_select anvildev.gitlab && CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] Checked the items in the next section <sub>or this PR is labeled `deploy:gitlab`</sub>
- [ ] PR is assigned to only the system administrator <sub>or this PR is not labeled `deploy:gitlab`</sub>

### System administrator

- [ ] Background migrations for `dev.gitlab` are complete <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] Background migrations for `anvildev.gitlab` are complete <sub>or this PR is not labeled `deploy:gitlab`</sub>
- [ ] PR is assigned to only the operator

### Operator (before pushing merge the commit)

- [ ] Ran `_select dev.gitlab && make -C terraform/gitlab/runner` <sub>or this PR is not labeled `deploy:runner`</sub>
- [ ] Ran `_select anvildev.gitlab && make -C terraform/gitlab/runner` <sub>or this PR is not labeled `deploy:runner`</sub>
- [ ] Added `sandbox` label <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `dev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Pushed PR branch to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passes in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Reviewed build logs for anomalies in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted unreferenced indices in `sandbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices in `dev`</sub>
- [ ] Deleted unreferenced indices in `anvilbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices in `anvildev`</sub>
- [ ] Started reindex in `sandbox` <sub>or this PR is not labeled `reindex:dev`</sub>
- [ ] Started reindex in `anvilbox` <sub>or this PR is not labeled `reindex:anvildev`</sub>
- [ ] Checked for failures in `sandbox` <sub>or this PR i [...]

2024-09-27 18:00 UTC, achave11-ucsc requested changes
Looks good.

Just spotted some minor nits to fix.

2024-09-27 18:00 UTC, achave11-ucsc commented on src/humancellatlas/data/metadata/api.py
> +        super().__init__(f'{entity.ref} cannot {"reference" if forward else "be referenced by"} '
L

2024-09-27 18:00 UTC, achave11-ucsc commented on src/azul/indexer/transform.py
> +    def transform(self, partition: BundlePartition) -> Iterable[Contribution | Replica]:
L

2024-09-27 18:00 UTC, achave11-ucsc commented on src/azul/plugins/metadata/anvil/indexer/transform.py
> +    def transform(self, partition: BundlePartition) -> Iterable[Contribution | Replica]:
L

2024-09-27 18:00 UTC, achave11-ucsc commented on src/azul/plugins/metadata/hca/indexer/transform.py
> +    def transform(self, partition: BundlePartition) -> Iterable[Contribution | Replica]:
L

2024-09-27 18:00 UTC, achave11-ucsc commented on src/azul/plugins/metadata/anvil/indexer/transform.py
> +    def _transform(self, entity: EntityReference) -> Iterable[Contribution | Replica]:
L

2024-09-27 18:00 UTC, achave11-ucsc commented on src/azul/plugins/metadata/anvil/indexer/transform.py
> +    def _transform(self, entity: EntityReference) -> Iterable[Contribution | Replica]:
L

2024-09-27 18:00 UTC, achave11-ucsc commented on src/azul/plugins/metadata/anvil/indexer/transform.py
> +    def _transform(self, entity: EntityReference) -> Iterable[Contribution | Replica]:
L

2024-09-27 18:00 UTC, achave11-ucsc commented on src/azul/plugins/metadata/anvil/indexer/transform.py
> +    def _transform(self, entity: EntityReference) -> Iterable[Contribution | Replica]:
def _transform(self, entity: EntityReference) -> Iterable[Contribution | Replica]:

2024-09-27 18:00 UTC, achave11-ucsc commented on src/azul/plugins/metadata/anvil/indexer/transform.py
> +    def _transform(self, entity: EntityReference) -> Iterable[Contribution | Replica]:
L

2024-09-27 18:00 UTC, achave11-ucsc commented on src/azul/plugins/metadata/hca/indexer/transform.py
> +    def _transform(self, files: Iterable[api.File]) -> Iterable[Contribution | Replica]:
L

2024-09-27 18:00 UTC, achave11-ucsc commented on src/azul/plugins/metadata/hca/indexer/transform.py
> +    def transform(self, partition: BundlePartition) -> Iterable[Contribution | Replica]:
L

2024-09-27 18:00 UTC, achave11-ucsc commented on src/azul/plugins/metadata/hca/indexer/transform.py
> +                                        # file is an implicit hub of its parent project.
L, https://github.com/DataBiosphere/azul/blob/develop/CONTRIBUTING.rst#12line-length
```diff
diff --git a/src/azul/plugins/metadata/hca/indexer/transform.py b/src/azul/plugins/metadata/hca/indexer/transform.py
index d263e7c2..f1942292 100644
--- a/src/azul/plugins/metadata/hca/indexer/transform.py
+++ b/src/azul/plugins/metadata/hca/indexer/transform.py
@@ -1469,13 +1469,19 @@ class FileTransformer(PartitionedTransformer[api.File]):
                 yield self._contribution(contents, file_id)
                 if config.enable_replicas:
                     yield self._replica(self.api_bundle.ref,
-                                        # The other hubs will be added when the indexer consolidates duplicate replicas.
+                                        # The other hubs will be added when the
+                                        # indexer consolidates duplicate
+                                        # replicas.
                                         [file_id])
                     yield self._replica(one(self.api_bundle.projects.values()).ref,
-                                        # Projects are linked to every file in their snapshot, making an explicit list
-                                        # of hub IDs for the project both redundant and impractically large. Therefore,
-                                        # we leave the hub IDs field empty for projects and rely on the tenet that every
-                                        # file is an implicit hub of its parent project.
+                                        # Projects are linked to every file in
+                                        # their snapshot, making an explicit
+                                        # list of hub IDs for the project both
+                                        # redundant and impractically large.
+                                        # Therefore, we leave the hub IDs field
+                                        # empty for projects and rely on the
+                                        # tenet that every file is an implicit
+                                        # hub of its parent project.
                                         [])
                     for linked_entity in visitor.entities:
                         yield self._replica(linked_entity, [file_id])
```

2024-09-27 18:00 UTC, achave11-ucsc commented on src/azul/plugins/metadata/anvil/indexer/transform.py
> +                # file is an implicit hub of its parent dataset.
L
```diff
diff --git a/src/azul/plugins/metadata/anvil/indexer/transform.py b/src/azul/plugins/metadata/anvil/indexer/transform.py
index 06464c9a..5e004beb 100644
--- a/src/azul/plugins/metadata/anvil/indexer/transform.py
+++ b/src/azul/plugins/metadata/anvil/indexer/transform.py
@@ -610,12 +610,14 @@ class FileTransformer(BaseTransformer):
         )
         yield self._contribution(contents, entity.entity_id)
         if config.enable_replicas:
-            # The other hubs will be added when the indexer consolidates duplicate replicas.
+            # The other hubs will be added when the indexer consolidates
+            # duplicate replicas.
             yield self._replica(entity, [entity.entity_id])
             for linked_entity in linked:
-                # Datasets are linked to every file in their snapshot, making an explicit list
-                # of hub IDs for the dataset both redundant and impractically large. Therefore,
-                # we leave the hub IDs field empty for datasets and rely on the tenet that every
-                # file is an implicit hub of its parent dataset.
+                # Datasets are linked to every file in their snapshot, making an
+                # explicit list of hub IDs for the dataset both redundant and
+                # impractically large. Therefore, we leave the hub IDs field
+                # empty for datasets and rely on the tenet that every file is an
+                # implicit hub of its parent dataset.
                 yield self._replica(linked_entity,
                                     hub_ids=[] if linked_entity.entity_type == 'dataset' else [entity.entity_id])

```

2024-09-27 18:00 UTC, achave11-ucsc commented on src/azul/plugins/metadata/hca/indexer/transform.py
> +    def _transform(self, entities: Iterable[ENTITY]) -> Iterable[Contribution | Replica]:
L

2024-09-28 19:07 UTC, nadove-ucsc commented
Rebasing to address conflicts.

2024-09-30 23:57 UTC, achave11-ucsc approved these changes, later dismissed
Approved ✅

2024-10-01 17:15 UTC, dsotirho-ucsc requested changes
Nicely done. Just one documentation nit.

2024-10-01 17:15 UTC, dsotirho-ucsc commented on test/indexer/test_indexer.py
> +        :param num_replicas: Expected number of replicas, assuming replicas are
Should be moved above `num_aggs`

2024-10-01 18:57 UTC, dsotirho-ucsc approved these changes, later dismissed
Approved.

2024-10-02 18:57 UTC, hannes-ucsc requested changes
A few nits.

2024-10-03 16:06 UTC, dsotirho-ucsc approved these changes

2024-10-04 19:12 UTC, hannes-ucsc approved these changes

2024-10-04 19:16 UTC, hannes-ucsc commented
I added the `reindex:anvildev` and `reindex:anvilprod` labels because I would like to verify the impact of these changes for both AnVIL and HCA. As in the previous PR on this track, I would like to run a reindex immediately before and after merging the PR, and compare the runs via the CW dashboard.

2024-10-04 20:00 UTC, hannes-ucsc commented
### Security design review

- [x] Security design review completed; this PR does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with Terra 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

2024-10-06 16:50 UTC, merged

2024-10-07 21:18 UTC, achave11-ucsc commented
`dev`:
Prior reindex: https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/101494
Posterior reindex: https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/101674

`anvildev`:
Prior reindex: https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/49234
Posterior reindex: https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/49426